import { db } from "../db";
import { videoTopics } from "../../shared/schema";

const topics = [
  {
    title: "Identity",
    description: "Exploring who you are in God's eyes and finding your true identity in Christ.",
    category: "Identity",
    scriptureAnchor: "Jeremiah 1:5",
    targetAgeGroup: "young disciples",
    status: "pending",
    priority: 1,
    language: "en",
  },
  {
    title: "Anxiety",
    description: "Understanding how to overcome anxiety through prayer and trust in God.",
    category: "Mental Health",
    scriptureAnchor: "Philippians 4:6-7",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 2,
    language: "en",
  },
  {
    title: "Depression",
    description: "Finding comfort and hope in God's presence during seasons of depression.",
    category: "Mental Health",
    scriptureAnchor: "Psalm 34:18",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 3,
    language: "en",
  },
  {
    title: "Loneliness",
    description: "Discovering that God is always with you even in the loneliest moments.",
    category: "Relationships",
    scriptureAnchor: "Deuteronomy 31:6",
    targetAgeGroup: "young disciples",
    status: "pending",
    priority: 4,
    language: "en",
  },
  {
    title: "Purpose",
    description: "Understanding God's plans and purpose for your life.",
    category: "Identity",
    scriptureAnchor: "Jeremiah 29:11",
    targetAgeGroup: "young disciples",
    status: "pending",
    priority: 5,
    language: "en",
  },
  {
    title: "Love",
    description: "Learning about the depth of God's love and how to love others.",
    category: "Relationships",
    scriptureAnchor: "1 John 4:19",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 6,
    language: "en",
  },
  {
    title: "Forgiveness",
    description: "Understanding the power of forgiveness and how to extend it to others.",
    category: "Character",
    scriptureAnchor: "Ephesians 4:32",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 7,
    language: "en",
  },
  {
    title: "Fear",
    description: "Overcoming fear by trusting in God's strength and presence.",
    category: "Mental Health",
    scriptureAnchor: "Isaiah 41:10",
    targetAgeGroup: "young disciples",
    status: "pending",
    priority: 8,
    language: "en",
  },
  {
    title: "Belonging",
    description: "Knowing that nothing can separate you from God's love and community.",
    category: "Relationships",
    scriptureAnchor: "Romans 8:38-39",
    targetAgeGroup: "young disciples",
    status: "pending",
    priority: 9,
    language: "en",
  },
  {
    title: "Self Worth",
    description: "Recognizing your value as someone fearfully and wonderfully made by God.",
    category: "Identity",
    scriptureAnchor: "Psalm 139:14",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 10,
    language: "en",
  },
  {
    title: "Grief",
    description: "Finding hope and healing in God's promise to wipe away every tear.",
    category: "Mental Health",
    scriptureAnchor: "Revelation 21:4",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 11,
    language: "en",
  },
  {
    title: "Peer Pressure",
    description: "Standing firm in your faith and not conforming to the patterns of this world.",
    category: "Character",
    scriptureAnchor: "Romans 12:2",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 12,
    language: "en",
  },
  {
    title: "Family",
    description: "Honoring your family relationships and growing in love at home.",
    category: "Relationships",
    scriptureAnchor: "Ephesians 6:1-3",
    targetAgeGroup: "young disciples",
    status: "pending",
    priority: 13,
    language: "en",
  },
  {
    title: "Faith Doubts",
    description: "Navigating seasons of doubt and learning to trust God through uncertainty.",
    category: "Faith",
    scriptureAnchor: "Mark 9:24",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 14,
    language: "en",
  },
  {
    title: "Addiction",
    description: "Finding freedom from addiction through God's faithfulness and provision.",
    category: "Mental Health",
    scriptureAnchor: "1 Corinthians 10:13",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 15,
    language: "en",
  },
  {
    title: "Anger",
    description: "Learning to be slow to anger and quick to listen through God's wisdom.",
    category: "Character",
    scriptureAnchor: "James 1:19-20",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 16,
    language: "en",
  },
  {
    title: "Rejection",
    description: "Overcoming rejection by knowing your identity as a child of God.",
    category: "Identity",
    scriptureAnchor: "John 1:12",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 17,
    language: "en",
  },
  {
    title: "Hope",
    description: "Being filled with joy, peace, and hope through the power of the Holy Spirit.",
    category: "Faith",
    scriptureAnchor: "Romans 15:13",
    targetAgeGroup: "young disciples",
    status: "pending",
    priority: 18,
    language: "en",
  },
  {
    title: "Trust",
    description: "Learning to trust in the Lord with all your heart and lean not on your own understanding.",
    category: "Faith",
    scriptureAnchor: "Proverbs 3:5-6",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 19,
    language: "en",
  },
  {
    title: "Gratitude",
    description: "Cultivating a heart of thankfulness in all circumstances.",
    category: "Character",
    scriptureAnchor: "1 Thessalonians 5:18",
    targetAgeGroup: "young disciples",
    status: "pending",
    priority: 20,
    language: "en",
  },
  {
    title: "Do Not Conform to This World",
    description: "Standing firm in faith when the world pressures you to compromise.",
    category: "Digital World",
    scriptureAnchor: "Romans 12:2",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 21,
    language: "en",
  },
  {
    title: "Disinformation and Truth",
    description: "Finding truth in a world of fake news and digital deception.",
    category: "Digital World",
    scriptureAnchor: "John 8:32",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 22,
    language: "en",
  },
  {
    title: "Social Media and Your Identity",
    description: "Who are you when the likes stop.",
    category: "Digital World",
    scriptureAnchor: "Galatians 1:10",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 23,
    language: "en",
  },
  {
    title: "AI and What Makes Us Human",
    description: "What artificial intelligence reveals about what God created in you.",
    category: "Digital World",
    scriptureAnchor: "Genesis 1:27",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 24,
    language: "en",
  },
  {
    title: "Cancel Culture and Grace",
    description: "How to respond with grace when the world demands judgment.",
    category: "Digital World",
    scriptureAnchor: "Ephesians 4:32",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 25,
    language: "en",
  },
  {
    title: "Pornography and Purity",
    description: "Honest conversation about purity in a hypersexualised world.",
    category: "Digital World",
    scriptureAnchor: "1 Corinthians 6:18-20",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 26,
    language: "en",
  },
  {
    title: "Gaming Addiction",
    description: "When entertainment becomes an escape from real life.",
    category: "Digital World",
    scriptureAnchor: "1 Corinthians 10:23",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 27,
    language: "en",
  },
  {
    title: "FOMO",
    description: "Learning contentment in a world designed to make you feel behind.",
    category: "Digital World",
    scriptureAnchor: "Philippians 4:11",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 28,
    language: "en",
  },
  {
    title: "Comparison Culture",
    description: "Scrolling through everyone else's highlight reel and feeling less than.",
    category: "Identity and Self Worth",
    scriptureAnchor: "Galatians 6:4",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 29,
    language: "en",
  },
  {
    title: "Body Image",
    description: "What God says about the body you live in.",
    category: "Identity and Self Worth",
    scriptureAnchor: "Psalm 139:14",
    targetAgeGroup: "young disciples",
    status: "pending",
    priority: 30,
    language: "en",
  },
  {
    title: "Am I Enough",
    description: "The question every teenager asks and the answer that changes everything.",
    category: "Identity and Self Worth",
    scriptureAnchor: "2 Corinthians 12:9",
    targetAgeGroup: "young disciples",
    status: "pending",
    priority: 31,
    language: "en",
  },
  {
    title: "Burnout",
    description: "When you are exhausted from trying to keep up with everything.",
    category: "Mental and Emotional Health",
    scriptureAnchor: "Matthew 11:28-30",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 32,
    language: "en",
  },
  {
    title: "Shame",
    description: "The difference between guilt that heals and shame that destroys.",
    category: "Mental and Emotional Health",
    scriptureAnchor: "Romans 8:1",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 33,
    language: "en",
  },
  {
    title: "Is God Real",
    description: "Honest questions deserve honest answers.",
    category: "Faith and Doubt",
    scriptureAnchor: "Hebrews 11:1",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 34,
    language: "en",
  },
  {
    title: "Why Does God Allow Suffering",
    description: "The question nobody wants to ask out loud.",
    category: "Faith and Doubt",
    scriptureAnchor: "Romans 8:28",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 35,
    language: "en",
  },
  {
    title: "Prayer Feels Empty",
    description: "What to do when you pray and hear nothing back.",
    category: "Faith and Doubt",
    scriptureAnchor: "Romans 8:26",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 36,
    language: "en",
  },
  {
    title: "I Don't Feel God",
    description: "Faith when the feeling is completely gone.",
    category: "Faith and Doubt",
    scriptureAnchor: "Deuteronomy 31:8",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 37,
    language: "en",
  },
  {
    title: "Toxic Friendships",
    description: "How to recognise and walk away from relationships that destroy you.",
    category: "Relationships",
    scriptureAnchor: "1 Corinthians 15:33",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 38,
    language: "en",
  },
  {
    title: "Family Conflict",
    description: "Honouring your family when it is really hard.",
    category: "Relationships",
    scriptureAnchor: "Colossians 3:13",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 39,
    language: "en",
  },
  {
    title: "Romantic Relationships",
    description: "What love actually looks like versus what culture sells you.",
    category: "Relationships",
    scriptureAnchor: "1 Corinthians 13:4-7",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 40,
    language: "en",
  },
  {
    title: "Boundaries",
    description: "Learning to say no as an act of faith.",
    category: "Relationships",
    scriptureAnchor: "Matthew 5:37",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 41,
    language: "en",
  },
  {
    title: "Calling",
    description: "You were made for something specific.",
    category: "Purpose and Future",
    scriptureAnchor: "Ephesians 2:10",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 42,
    language: "en",
  },
  {
    title: "What Do I Do With My Life",
    description: "When everyone expects you to have it figured out.",
    category: "Purpose and Future",
    scriptureAnchor: "Proverbs 3:5-6",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 43,
    language: "en",
  },
  {
    title: "Failure",
    description: "What to do when you fall down and cannot see the point.",
    category: "Purpose and Future",
    scriptureAnchor: "Micah 7:8",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 44,
    language: "en",
  },
  {
    title: "Ambition vs Surrender",
    description: "The tension between dreaming big and trusting God.",
    category: "Purpose and Future",
    scriptureAnchor: "Matthew 6:33",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 45,
    language: "en",
  },
  {
    title: "Your Body is a Temple",
    description: "God designed your body with purpose — what does that mean for how we treat it",
    category: "Biblical Health",
    scriptureAnchor: "1 Corinthians 6:19-20",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 46,
    language: "en",
  },
  {
    title: "What Does God Say About What We Eat",
    description: "The biblical case for clean eating and why it still matters today",
    category: "Biblical Health",
    scriptureAnchor: "Leviticus 11 and Daniel 1",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 47,
    language: "en",
  },
  {
    title: "Daniel's Diet",
    description: "A teenage boy who refused the kings food and came out stronger than everyone else",
    category: "Biblical Health",
    scriptureAnchor: "Daniel 1:8-16",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 48,
    language: "en",
  },
  {
    title: "Rest and the Sabbath",
    description: "God built rest into creation — what does that mean for our always-on culture",
    category: "Biblical Health",
    scriptureAnchor: "Exodus 20:8-11",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 49,
    language: "en",
  },
  {
    title: "Mental Health and Faith",
    description: "Are mental and spiritual health connected — what does God say about our whole wellbeing",
    category: "Biblical Health",
    scriptureAnchor: "3 John 1:2",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 50,
    language: "en",
  },
  {
    title: "Fasting and Faith",
    description: "What fasting actually is and why teenagers might want to try it",
    category: "Biblical Health",
    scriptureAnchor: "Matthew 6:16-18",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 51,
    language: "en",
  },
  {
    title: "Sleep and Trust",
    description: "Why rest is an act of faith not laziness",
    category: "Biblical Health",
    scriptureAnchor: "Psalm 127:2",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 52,
    language: "en",
  },
  {
    title: "Exercise and Stewardship",
    description: "Taking care of your body as an act of worship not vanity",
    category: "Biblical Health",
    scriptureAnchor: "1 Timothy 4:8",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 53,
    language: "en",
  },
  {
    title: "The Weekly Sabbath",
    description: "God rested on the seventh day and set it apart — what that means for us today and why it still matters.",
    category: "Biblical Sabbaths",
    scriptureAnchor: "Genesis 2:2-3",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 54,
    language: "en",
  },
  {
    title: "The Sabbath of Sabbaths — Yom Kippur",
    description: "The holiest day in the biblical calendar — a day of atonement, rest, and drawing near to God.",
    category: "Biblical Sabbaths",
    scriptureAnchor: "Leviticus 23:27-28",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 55,
    language: "en",
  },
  {
    title: "The Sabbatical Year — Shemitah",
    description: "Every seventh year the land rests. What God's rhythm of release and renewal reveals about trust, provision, and letting go.",
    category: "Biblical Sabbaths",
    scriptureAnchor: "Leviticus 25:1-7",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 56,
    language: "en",
  },
  {
    title: "The Jubilee Year",
    description: "Every fifty years debts cancelled, slaves freed, land returned. The most radical economic reset in human history — and what it points to in Christ.",
    category: "Biblical Sabbaths",
    scriptureAnchor: "Leviticus 25:8-12",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 57,
    language: "en",
  },
  {
    title: "The Appointed Times — God's Calendar",
    description: "God's seven annual Sabbaths — Passover, Firstfruits, Pentecost, Trumpets, Atonement, Tabernacles — each one a signpost pointing to Christ.",
    category: "Biblical Sabbaths",
    scriptureAnchor: "Leviticus 23:1-4",
    targetAgeGroup: "teens and young adults",
    status: "pending",
    priority: 58,
    language: "en",
  },
];

const COMPLETED_VIDEOS: Record<string, { status: string; avatarVideoUrl: string }> = {
  "Anxiety": {
    status: "avatar-ready",
    avatarVideoUrl: "https://res.cloudinary.com/dy77gwpzu/video/upload/v1774533334/grace-through-faith/videos/anxiety-sienna-final.mp4",
  },
  "Depression": {
    status: "avatar-ready",
    avatarVideoUrl: "https://res.cloudinary.com/dy77gwpzu/video/upload/v1774538750/grace-through-faith/videos/topic-23d17332-2fc4-41bc-898d-74e5807d0f7b-90de2a6d1aea48eba43212faf9697831.mp4",
  },
};

async function seed() {
  console.log("Seeding video topics...");
  const { sql } = await import("drizzle-orm");

  const enriched = topics.map((t) => {
    const completed = COMPLETED_VIDEOS[t.title];
    if (completed) {
      return { ...t, ...completed };
    }
    return t;
  });

  await db.insert(videoTopics).values(enriched).onConflictDoNothing();
  console.log(`[seed] Upserted ${enriched.length} video topics (duplicates skipped).`);

  for (const [title, data] of Object.entries(COMPLETED_VIDEOS)) {
    await db.execute(sql`
      UPDATE video_topics
      SET status = ${data.status}, avatar_video_url = ${data.avatarVideoUrl}
      WHERE title = ${title} AND status != 'avatar-ready'
    `);
    console.log(`[seed] Ensured ${title} is avatar-ready with video URL.`);
  }

  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
