export const belief17Lessons = [
  {
    id: "w3l-17-1",
    moduleId: "bmod-017",
    title: "Biblical Foundations: Gifted for Service",
    description: "Tracing the biblical teaching on spiritual gifts from the Old Testament through the apostolic church, and understanding why God distributes gifts to every believer.",
    lessonOrder: 1,
    anchorText: "1 Corinthians 12:4-11; Romans 12:4-8; 1 Peter 4:10-11",
    anchorBookId: 46,
    anchorChapter: 12,
    anchorVerseStart: 4,
    anchorVerseEnd: 11,
    estimatedMinutes: 35,
  },
  {
    id: "w3l-17-2",
    moduleId: "bmod-017",
    title: "Doctrinal Formulation: Gifts for the Body",
    description: "Understanding the Adventist position on the diversity, purpose, and distribution of spiritual gifts within the church.",
    lessonOrder: 2,
    anchorText: "Ephesians 4:8,11-16; 1 Corinthians 12:27-28; Joel 2:28-29",
    anchorBookId: 49,
    anchorChapter: 4,
    anchorVerseStart: 8,
    anchorVerseEnd: 16,
    estimatedMinutes: 30,
  },
  {
    id: "w3l-17-3",
    moduleId: "bmod-017",
    title: "Practical Implications: Discovering and Using Your Gifts",
    description: "Moving from theory to practice in identifying, developing, and deploying spiritual gifts for the building up of the church and the service of the community.",
    lessonOrder: 3,
    anchorText: "Acts 6:1-7; 1 Timothy 3:1-13; Romans 12:6-8",
    anchorBookId: 44,
    anchorChapter: 6,
    anchorVerseStart: 1,
    anchorVerseEnd: 7,
    estimatedMinutes: 30,
  },
  {
    id: "w3l-17-4",
    moduleId: "bmod-017",
    title: "Misunderstandings & Challenges",
    description: "Addressing common misconceptions about spiritual gifts, including hierarchies of importance, cessationist claims, and the relationship between gifts and love.",
    lessonOrder: 4,
    anchorText: "1 Corinthians 13:1-3; 1 Corinthians 14:1-5,39-40; Matthew 7:21-23",
    anchorBookId: 46,
    anchorChapter: 13,
    anchorVerseStart: 1,
    anchorVerseEnd: 3,
    estimatedMinutes: 30,
  },
];

export const belief17Sections = [
  {
    id: "w3s-17-1-1",
    lessonId: "w3l-17-1",
    sectionType: "anchor",
    title: "Anchor Passages",
    content: "Read the following passages carefully, paying attention to who distributes spiritual gifts, why they are given, and how many believers receive them.\n\n1. **1 Corinthians 12:4-11** — Paul's foundational teaching on the variety and source of spiritual gifts. Notice how many times the Spirit is named as the giver.\n2. **Romans 12:4-8** — The body metaphor applied to gift diversity. Look for the connection between grace and gifting.\n3. **1 Peter 4:10-11** — Peter's summary command. Notice the stewardship language: gifts are received in order to be given away.\n4. **Exodus 31:1-6** — Bezalel and Oholiab. Look for how the Spirit empowered specific skills for the building of the tabernacle.\n5. **Numbers 11:16-17,25** — The Spirit distributed to the seventy elders. Note the connection between the Spirit's presence and empowerment for leadership.",
    sortOrder: 1,
  },
  {
    id: "w3s-17-1-2",
    lessonId: "w3l-17-1",
    sectionType: "explain",
    title: "Understanding Spiritual Gifts",
    content: "The Bible teaches that God gives spiritual gifts to every believer, not as rewards for spiritual maturity but as tools for service. Paul writes that \"there are diversities of gifts, but the same Spirit\" (1 Corinthians 12:4). The word for gifts here is charismata, rooted in charis (grace). Spiritual gifts are grace-gifts: unearned capacities given by the Holy Spirit for the benefit of the community. Peter reinforces this: \"As each one has received a gift, minister it to one another\" (1 Peter 4:10). No believer is ungifted. No gift is given for private enrichment.\n\nThe Old Testament already witnesses to this pattern. When the tabernacle needed builders, God filled Bezalel \"with the Spirit of God, in wisdom, in understanding, in knowledge, and in all manner of workmanship\" (Exodus 31:3). Craftsmanship became a spiritual gift because the Spirit directed it toward God's purpose. When Moses needed help governing Israel, God took the Spirit that was upon Moses and distributed it to seventy elders (Numbers 11:25). The New Testament extends this principle universally: at Pentecost, the Spirit was poured out on all flesh (Acts 2:17), and Paul teaches that to \"each one\" the manifestation of the Spirit is given \"for the profit of all\" (1 Corinthians 12:7). The gifts are as diverse as the needs of the church, and the Spirit distributes them \"to each one individually as He wills\" (1 Corinthians 12:11).",
    sortOrder: 2,
  },
  {
    id: "w3s-17-1-3",
    lessonId: "w3l-17-1",
    sectionType: "integrate",
    title: "Adventist Theological Integration",
    content: "Adventists understand spiritual gifts as the Holy Spirit's provision for the church's mission during the Great Controversy. The church is not a human organization sustained by talent alone; it is a Spirit-empowered body entrusted with the proclamation of the three angels' messages (Revelation 14:6-12). Every gift, whether teaching, hospitality, administration, or mercy, serves this larger mission.\n\nThe Adventist position affirms several key points:\n\n1. **Every believer is gifted** — There is no class of \"ordinary\" members who merely receive ministry. The priesthood of all believers (1 Peter 2:9) means every member has both the privilege and responsibility of Spirit-empowered service.\n2. **Gifts are for the body, not the individual** — Gifts are given for \"the profit of all\" (1 Corinthians 12:7), not for personal prestige or spiritual competition.\n3. **Gifts continue throughout church history** — Adventists reject cessationism (the view that certain gifts ended with the apostolic age). Joel 2:28-29 promises the Spirit's gifts in the \"last days,\" and the church's mission demands ongoing empowerment.\n4. **The Spirit distributes sovereignly** — No one earns or chooses their gift. The Spirit gives \"to each one individually as He wills\" (1 Corinthians 12:11).\n\n**Corrective boundary:** This belief guards against both clericalism (the idea that ministry belongs only to ordained professionals) and spiritual elitism (the elevation of certain gifts over others). Every member is a minister; every gift matters.\n\nFor further reading on the Adventist understanding of spiritual gifts, visit adventist.org/spiritual-gifts-and-ministries.",
    sortOrder: 3,
  },
  {
    id: "w3s-17-1-4",
    lessonId: "w3l-17-1",
    sectionType: "practice",
    title: "Putting It Into Practice",
    content: "1. **Articulation exercise:** Write a four-sentence explanation of what spiritual gifts are, who receives them, and what they are for, using only Scripture (no jargon). Share it with a friend or family member and ask if it was clear.\n2. **Gift inventory:** Read 1 Corinthians 12:4-11 and Romans 12:4-8 side by side. List every gift mentioned. Circle any that you think might describe something God has given you. Bring this list to prayer.\n3. **Service step:** Identify one practical need in your local church this week (greeting visitors, helping with technology, preparing food for a potluck, visiting a homebound member). Volunteer to fill it as an act of Spirit-directed service.",
    sortOrder: 4,
  },
  {
    id: "w3s-17-1-5",
    lessonId: "w3l-17-1",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Do you think of yourself as spiritually gifted? Why or why not? How does 1 Corinthians 12:7 (\"to each one\") challenge or confirm your self-perception?\n2. In what moments of service have you felt most alive and effective? Could those moments be indicators of a spiritual gift the Spirit has given you?\n3. How would your local church change if every member actively exercised their spiritual gift each week?",
    sortOrder: 5,
  },
  {
    id: "w3s-17-1-6",
    lessonId: "w3l-17-1",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },
  {
    id: "w3s-17-2-1",
    lessonId: "w3l-17-2",
    sectionType: "anchor",
    title: "Anchor Passages",
    content: "Read these passages with attention to how the gifts relate to Christ's ascension, the structure of the church, and the promise of the Spirit in the last days.\n\n1. **Ephesians 4:8,11-16** — Christ's ascension gifts to the church. Notice the purpose: equipping the saints for the work of ministry.\n2. **1 Corinthians 12:27-28** — God has appointed various roles in the church. Observe the order and diversity.\n3. **Joel 2:28-29** — The promise of the Spirit poured out on all flesh. Note the inclusiveness: sons, daughters, old, young, servants.\n4. **Acts 2:1-4,17-18** — Pentecost as the fulfillment of Joel's prophecy.\n5. **1 Corinthians 14:26** — The principle governing gathered worship: \"Let all things be done for edification.\"",
    sortOrder: 1,
  },
  {
    id: "w3s-17-2-2",
    lessonId: "w3l-17-2",
    sectionType: "explain",
    title: "What Adventists Affirm",
    content: "Paul teaches that when Christ ascended, He gave gifts to the church: \"He Himself gave some to be apostles, some prophets, some evangelists, and some pastors and teachers\" (Ephesians 4:11). These are not bureaucratic offices but functional gifts for the equipping of all believers. The purpose clause is critical: \"for the equipping of the saints for the work of ministry, for the edifying of the body of Christ\" (4:12). Ministry is not delegated to a professional class; rather, gifted leaders exist to train the entire body to serve. The goal is maturity — \"the measure of the stature of the fullness of Christ\" (4:13).\n\nAdventists affirm that this gift structure continues today. Joel prophesied that God would pour out His Spirit \"on all flesh\" — crossing lines of age, gender, and social status (Joel 2:28-29). Peter declared at Pentecost that this prophecy was being fulfilled (Acts 2:16-17), and the New Testament everywhere assumes that the Spirit's gifts are active in the church. Adventists specifically reject the cessationist claim that miraculous or revelatory gifts ended with the apostles. The same Spirit who empowered the early church empowers the remnant church, and the last days demand even greater manifestations of the Spirit's power for the completion of the gospel commission.",
    sortOrder: 2,
  },
  {
    id: "w3s-17-2-3",
    lessonId: "w3l-17-2",
    sectionType: "integrate",
    title: "Adventist Theological Integration",
    content: "Within the Great Controversy framework, spiritual gifts are God's provision for the church's mission in every era. The gifts are not optional extras or signs of special spiritual status; they are the means by which the body of Christ carries out its mandate to proclaim the everlasting gospel (Revelation 14:6).\n\nAdventist doctrine distinguishes between:\n\n1. **Gift and office** — A gift is a Spirit-given capacity; an office is a recognized function within church structure. A person may have the gift of teaching without holding the office of pastor. Both are valuable; neither replaces the other.\n2. **Natural talent and spiritual gift** — Natural abilities become spiritual gifts when the Spirit directs them toward the building up of the church and the advancement of its mission. Bezalel's craftsmanship (Exodus 31:3-5) illustrates this transformation.\n3. **Equipping gifts and serving gifts** — Ephesians 4:11-12 identifies certain gifts (apostles, prophets, evangelists, pastors, teachers) as equipping gifts whose purpose is to train the rest of the body for ministry. Every member ministers; some are specifically gifted to train others.\n\nThe Adventist Church recognizes the full range of New Testament gifts as operative today, including prophecy (see Belief 18). The church's organizational structure — with pastors, elders, deacons, teachers, and departmental leaders — reflects a practical expression of this theology.\n\n**Corrective boundary:** This belief guards against two errors: (a) the concentration of all ministry in clergy (clericalism), and (b) the elevation of spectacular gifts over quiet service (spiritual elitism). Paul's body metaphor in 1 Corinthians 12 insists that \"the eye cannot say to the hand, 'I have no need of you'\" (12:21).",
    sortOrder: 3,
  },
  {
    id: "w3s-17-2-4",
    lessonId: "w3l-17-2",
    sectionType: "practice",
    title: "Putting It Into Practice",
    content: "1. **Articulation exercise:** Write a brief paragraph distinguishing between a natural talent and a spiritual gift. Use at least one biblical example (e.g., Bezalel, the seventy elders, Philip the evangelist). Share your paragraph with a study partner or small group.\n2. **Conversation starter:** This week, ask two church members what they believe their spiritual gift is. Listen carefully. If they are unsure, share what you have observed about their service and encourage them.\n3. **Prayer of availability:** Set aside fifteen minutes this week to pray specifically: \"Lord, show me my gift and show me where You want me to use it.\" Journal whatever impressions come.",
    sortOrder: 4,
  },
  {
    id: "w3s-17-2-5",
    lessonId: "w3l-17-2",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Ephesians 4:12 says that equipping gifts exist so that all believers can do the work of ministry. In your experience, does your church function this way? What would need to change?\n2. Do you tend to think of some gifts as more important than others? How does Paul's body metaphor challenge that tendency?\n3. If the Spirit distributes gifts sovereignly (1 Corinthians 12:11), what does that mean for envy and comparison within the church?",
    sortOrder: 5,
  },
  {
    id: "w3s-17-2-6",
    lessonId: "w3l-17-2",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },
  {
    id: "w3s-17-3-1",
    lessonId: "w3l-17-3",
    sectionType: "anchor",
    title: "Anchor Passages",
    content: "Read these passages looking for how early believers identified needs, selected servants, and deployed gifts within their communities.\n\n1. **Acts 6:1-7** — The appointment of the seven to serve tables. Notice how the church identified a need, recognized gifted individuals, and the result: \"the word of God spread.\"\n2. **1 Timothy 3:1-13** — Qualifications for overseers and deacons. Note that these are character requirements, not merely skill requirements.\n3. **Romans 12:6-8** — Practical instructions for exercising gifts. Paul says to do each \"with\" something: prophecy with faith, service with diligence, giving with generosity, leadership with zeal, mercy with cheerfulness.",
    sortOrder: 1,
  },
  {
    id: "w3s-17-3-2",
    lessonId: "w3l-17-3",
    sectionType: "explain",
    title: "Discovering and Deploying Gifts",
    content: "The early church provides a compelling model for gift discovery and deployment. In Acts 6, the Hellenist widows were being overlooked in the daily distribution. The apostles did not try to do everything themselves. Instead, they instructed the congregation: \"seek out from among you seven men of good reputation, full of the Holy Spirit and wisdom\" (Acts 6:3). The community identified gifted individuals, the apostles confirmed them, and the result was explosive growth: \"the word of God spread, and the number of the disciples multiplied greatly\" (Acts 6:7). Gifts are discovered not in isolation but in community, through service, and by the confirmation of other believers.\n\nPaul gives practical counsel for exercising gifts in Romans 12:6-8. Each gift comes with its own posture: prophecy is to be exercised \"in proportion to our faith,\" service \"in serving,\" teaching \"in teaching,\" exhortation \"with encouragement,\" giving \"with liberality,\" leadership \"with diligence,\" and mercy \"with cheerfulness.\" The common thread is wholehearted engagement. Gifts are not decorations on a spiritual resume; they are tools to be picked up and used with full energy and genuine love. Paul's opening instruction frames everything: \"Let love be without hypocrisy\" (Romans 12:9).",
    sortOrder: 2,
  },
  {
    id: "w3s-17-3-3",
    lessonId: "w3l-17-3",
    sectionType: "integrate",
    title: "Adventist Theological Integration",
    content: "The Adventist Church has historically emphasized that every member is a minister. This conviction flows directly from the theology of spiritual gifts. The church's organizational structure — local church boards, Sabbath School classes, Pathfinder clubs, community services centers, health ministries — reflects a conscious effort to create spaces where diverse gifts can be exercised.\n\nPractical gift discovery in an Adventist context involves several steps:\n\n1. **Prayer and study** — Ask the Spirit to reveal your gifts. Study the gift lists in Romans 12, 1 Corinthians 12, and Ephesians 4.\n2. **Experimentation** — Try different areas of service. Gifts often surface through action, not through contemplation alone.\n3. **Community confirmation** — Pay attention to what others affirm in you. The church in Acts 6 selected servants based on observed character and capacity.\n4. **Ongoing development** — Gifts grow through faithful use. The parable of the talents (Matthew 25:14-30) teaches that what we exercise increases, and what we neglect atrophies.\n\nThe Adventist emphasis on holistic ministry (health, education, publishing, community development) reflects a broad understanding of spiritual gifts. Administration, hospitality, craftsmanship, teaching, and mercy are all valued alongside preaching and evangelism.\n\n**Corrective boundary:** This belief guards against passivity — the idea that only pastors or \"gifted\" people should be involved in ministry. If every believer has a gift, then every believer has a ministry. The pew is not a spectator seat; it is a launching pad.",
    sortOrder: 3,
  },
  {
    id: "w3s-17-3-4",
    lessonId: "w3l-17-3",
    sectionType: "practice",
    title: "Putting It Into Practice",
    content: "1. **Articulation exercise:** Write a one-paragraph description of a gift you believe God has given you. Include: what the gift is, how you have seen it in action, and one way you could use it more intentionally this month. Share it with a trusted friend for feedback.\n2. **Serve outside your comfort zone:** This week, volunteer for a ministry area you have never tried before. It could be children's ministry, greeting, sound and media, or visiting the sick. Pay attention to whether the Spirit energizes you in this new role.\n3. **Encourage a fellow member:** Identify one person in your church who serves faithfully but may not realize they are exercising a spiritual gift. Tell them specifically what you see God doing through them.",
    sortOrder: 4,
  },
  {
    id: "w3s-17-3-5",
    lessonId: "w3l-17-3",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. What areas of church service bring you the most energy and fulfillment? Could these be indicators of your spiritual gift?\n2. Have others ever affirmed a particular strength in you that you had not recognized yourself? What was it, and how did it make you feel?\n3. The parable of the talents teaches that unused gifts diminish. Is there a gift you sense the Spirit has given you that you have been neglecting? What would it take to begin exercising it again?",
    sortOrder: 5,
  },
  {
    id: "w3s-17-3-6",
    lessonId: "w3l-17-3",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },
  {
    id: "w3s-17-4-1",
    lessonId: "w3l-17-4",
    sectionType: "anchor",
    title: "Anchor Passages",
    content: "Read these passages with attention to the relationship between gifts and love, the need for order in worship, and the warning against counterfeit spirituality.\n\n1. **1 Corinthians 13:1-3** — Paul's famous love chapter in context. Notice: it sits between chapters 12 (gift diversity) and 14 (gift regulation). Love is not an alternative to gifts; it is their necessary context.\n2. **1 Corinthians 14:1-5,39-40** — Guidelines for the exercise of gifts in corporate worship. Note Paul's emphasis on intelligibility and edification.\n3. **Matthew 7:21-23** — A sobering warning from Jesus about those who perform mighty works in His name but are not known by Him.",
    sortOrder: 1,
  },
  {
    id: "w3s-17-4-2",
    lessonId: "w3l-17-4",
    sectionType: "explain",
    title: "Common Misunderstandings Addressed",
    content: "Several persistent misunderstandings surround the doctrine of spiritual gifts. The first is the hierarchy error: the belief that some gifts are inherently superior to others. Paul confronts this directly in 1 Corinthians 12:21-25 with the body metaphor. The eye cannot dismiss the hand; the head cannot ignore the feet. Every gift is necessary, and God has arranged them precisely as He intended. The Corinthian church was infatuated with spectacular manifestations; Paul redirected them toward love and edification as the true measures of spiritual maturity.\n\nA second misunderstanding is cessationism — the claim that certain gifts (particularly prophecy, healing, and tongues) ceased with the death of the last apostle. Scripture offers no such cutoff. Paul writes that gifts will cease \"when that which is perfect has come\" (1 Corinthians 13:10), which in context refers to the second coming, not the closing of the canon. A third error is the equation of gifts with spiritual status. Jesus warned that people would say, \"Lord, Lord, did we not prophesy in Your name?\" and He would respond, \"I never knew you\" (Matthew 7:22-23). Gifts are tools, not trophies. Their exercise means nothing apart from a genuine relationship with Christ and the fruit of the Spirit.",
    sortOrder: 2,
  },
  {
    id: "w3s-17-4-3",
    lessonId: "w3l-17-4",
    sectionType: "integrate",
    title: "Adventist Theological Integration",
    content: "Adventists navigate these challenges by holding together several biblical principles:\n\n1. **Love is the environment for gifts** — 1 Corinthians 13 is not a poetic interlude; it is the criterion by which all gift exercise is evaluated. A gift exercised without love is \"sounding brass\" (13:1).\n2. **Order reflects God's character** — Paul insists that \"all things be done decently and in order\" (1 Corinthians 14:40). Adventist worship values reverence, intelligibility, and edification. This does not quench the Spirit; it honors the Spirit, who is a God of order, not confusion (14:33).\n3. **Gifts are tested, not assumed** — The instruction to \"test all things; hold fast what is good\" (1 Thessalonians 5:21) applies to claimed spiritual manifestations. Adventists test all gifts by Scripture (Isaiah 8:20), by their fruit (Matthew 7:16-20), and by their confession of Christ (1 John 4:1-3).\n4. **The fruit of the Spirit outranks the gifts of the Spirit** — Galatians 5:22-23 describes the character that should accompany and validate all gift exercise. A person with great gifts but poor character is a danger, not a blessing.\n\n**Corrective boundary:** This belief guards against both the suppression of gifts (quenching the Spirit) and the uncritical acceptance of claimed spiritual experiences (gullibility). The biblical standard is discernment: \"Do not quench the Spirit. Do not despise prophecies. Test all things; hold fast what is good\" (1 Thessalonians 5:19-21).",
    sortOrder: 3,
  },
  {
    id: "w3s-17-4-4",
    lessonId: "w3l-17-4",
    sectionType: "practice",
    title: "Putting It Into Practice",
    content: "1. **Articulation exercise:** Write a four-sentence response to someone who says, \"Speaking in tongues is the most important spiritual gift.\" Use Scripture (especially 1 Corinthians 12:21-25 and 13:1-3) to explain why no gift is inherently superior.\n2. **Self-examination:** Spend time in prayer asking: \"Am I exercising whatever gift I have in love? Is my motivation the building up of others, or my own recognition?\" Journal your honest response.\n3. **Community conversation:** Initiate a conversation in your small group or Sabbath School class about the difference between the gifts of the Spirit and the fruit of the Spirit. Ask: \"Which does our church tend to emphasize more? What would balance look like?\"",
    sortOrder: 4,
  },
  {
    id: "w3s-17-4-5",
    lessonId: "w3l-17-4",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Have you ever seen a spiritual gift exercised in a way that caused harm rather than edification? What went wrong, and what would Paul say about it?\n2. Paul places 1 Corinthians 13 (love) between chapters 12 (gifts) and 14 (gift regulation). What does this literary placement teach about the relationship between gifts and character?\n3. Jesus said some will perform mighty works in His name yet not know Him (Matthew 7:22-23). How does this warning shape your understanding of what matters most in the Christian life?",
    sortOrder: 5,
  },
  {
    id: "w3s-17-4-6",
    lessonId: "w3l-17-4",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },
];

export const belief17Assessments = [
  { id: "w3a-17-1", lessonId: "w3l-17-1", title: "Spiritual Gifts Foundations Assessment", passingScore: 70 },
  { id: "w3a-17-2", lessonId: "w3l-17-2", title: "Gifts for the Body Assessment", passingScore: 70 },
  { id: "w3a-17-3", lessonId: "w3l-17-3", title: "Discovering Your Gifts Assessment", passingScore: 70 },
  { id: "w3a-17-4", lessonId: "w3l-17-4", title: "Gifts Misunderstandings Assessment", passingScore: 70 },
];

export const belief17Items = [
  {
    id: "w3i-17-1-1",
    assessmentId: "w3a-17-1",
    question: "What is the Greek root word from which 'charismata' (spiritual gifts) is derived?",
    options: ["Pneuma (spirit)", "Charis (grace)", "Dunamis (power)", "Agape (love)"],
    correctIndex: 1,
    explanation: "Charismata comes from charis, meaning grace. Spiritual gifts are grace-gifts — unearned capacities given by God for the benefit of the community.",
  },
  {
    id: "w3i-17-1-2",
    assessmentId: "w3a-17-1",
    question: "According to 1 Corinthians 12:7, who receives a manifestation of the Spirit?",
    options: ["Only apostles and prophets", "Only those who ask for it", "Each one — every believer", "Only church leaders"],
    correctIndex: 2,
    explanation: "Paul states that 'the manifestation of the Spirit is given to each one for the profit of all.' No believer is ungifted.",
  },
  {
    id: "w3i-17-1-3",
    assessmentId: "w3a-17-1",
    question: "In Exodus 31:1-6, what Old Testament figure was filled with the Spirit for craftsmanship in building the tabernacle?",
    options: ["Moses", "Aaron", "Bezalel", "Joshua"],
    correctIndex: 2,
    explanation: "God filled Bezalel 'with the Spirit of God, in wisdom, in understanding, in knowledge, and in all manner of workmanship' for the construction of the tabernacle.",
  },
  {
    id: "w3i-17-1-4",
    assessmentId: "w3a-17-1",
    question: "Why does the example of Bezalel matter for our understanding of spiritual gifts?",
    options: ["It proves that only artistic people receive spiritual gifts", "It shows that practical skills like craftsmanship can be Spirit-directed gifts when used for God's purposes", "It demonstrates that Old Testament figures did not have the Spirit", "It means every Christian should be an artist"],
    correctIndex: 1,
    explanation: "Bezalel's example broadens the category of spiritual gifts beyond preaching and prophecy. When the Spirit directs a natural ability toward God's purpose, it becomes a spiritual gift.",
  },
  {
    id: "w3i-17-1-5",
    assessmentId: "w3a-17-1",
    question: "A church member says, 'I don't have any spiritual gifts — I'm just ordinary.' Based on 1 Peter 4:10, how would you respond?",
    options: ["Agree that some people are not gifted", "Suggest they pray harder until they receive a gift", "Explain that Peter says 'each one has received a gift' and help them explore what form their gift might take", "Tell them to seek a more spectacular gift"],
    correctIndex: 2,
    explanation: "Peter's language is universal: 'As each one has received a gift, minister it to one another.' The task is not to obtain a gift but to discover and deploy the one already given.",
  },
  {
    id: "w3i-17-2-1",
    assessmentId: "w3a-17-2",
    question: "According to Ephesians 4:12, what is the purpose of the equipping gifts (apostles, prophets, evangelists, pastors, teachers)?",
    options: ["To perform all ministry on behalf of the congregation", "To equip the saints for the work of ministry and the edifying of the body", "To establish a hierarchy of authority in the church", "To replace the gifts listed in 1 Corinthians 12"],
    correctIndex: 1,
    explanation: "Paul says equipping gifts exist 'for the equipping of the saints for the work of ministry, for the edifying of the body of Christ.' Leaders train all members to serve.",
  },
  {
    id: "w3i-17-2-2",
    assessmentId: "w3a-17-2",
    question: "Joel 2:28-29 prophesies that the Spirit would be poured out on whom?",
    options: ["Only the priests and Levites", "Only male leaders of Israel", "All flesh — sons, daughters, old men, young men, servants", "Only those in Jerusalem"],
    correctIndex: 2,
    explanation: "Joel's prophecy is radically inclusive: 'your sons and your daughters... your old men... your young men... My menservants and on My maidservants.' The Spirit crosses every social boundary.",
  },
  {
    id: "w3i-17-2-3",
    assessmentId: "w3a-17-2",
    question: "What is the Adventist position on whether spiritual gifts continue today or ceased with the apostles?",
    options: ["Gifts ceased when the last apostle died", "Only some gifts continue; miraculous ones have ended", "All gifts continue; the Spirit empowers the church in every era until Christ returns", "Gifts restarted in 1844 after a long cessation"],
    correctIndex: 2,
    explanation: "Adventists reject cessationism. Joel 2:28-29 promises the Spirit's gifts in the 'last days,' and Paul says gifts will cease only 'when that which is perfect has come' (1 Corinthians 13:10) — the second coming.",
  },
  {
    id: "w3i-17-2-4",
    assessmentId: "w3a-17-2",
    question: "What is the difference between a spiritual gift and a church office?",
    options: ["There is no difference; they are the same thing", "A gift is a Spirit-given capacity; an office is a recognized function within church structure", "An office is always more important than a gift", "Gifts are temporary; offices are permanent"],
    correctIndex: 1,
    explanation: "A person may have the gift of teaching without holding the office of pastor. Both are valuable; neither replaces the other. The gift is the Spirit's empowerment; the office is the community's recognition.",
  },
  {
    id: "w3i-17-2-5",
    assessmentId: "w3a-17-2",
    question: "A new believer asks why the church has so many departments and ministries instead of just focusing on preaching. Using Ephesians 4:11-16, how would you explain this?",
    options: ["It's just tradition — preaching is all that matters", "Christ gave diverse gifts so that every member can be equipped for their own ministry, building up the whole body toward maturity", "Departments exist to give people positions of authority", "Preaching is the only real spiritual gift; everything else is secondary"],
    correctIndex: 1,
    explanation: "Paul's vision is a body where every part functions. Diverse ministries reflect the diversity of gifts Christ distributes. The goal is 'the edifying of the body of Christ' until all reach 'the measure of the stature of the fullness of Christ' (Ephesians 4:12-13).",
  },
  {
    id: "w3i-17-3-1",
    assessmentId: "w3a-17-3",
    question: "In Acts 6:1-7, what was the result when the church identified gifted servants to handle the daily distribution?",
    options: ["The church split over the decision", "The word of God spread, and the number of disciples multiplied greatly", "The apostles were criticized for delegating", "The seven servants became the new leaders of the church"],
    correctIndex: 1,
    explanation: "When practical needs were met by gifted servants, the apostles could focus on prayer and the word, and 'the word of God spread, and the number of the disciples multiplied greatly' (Acts 6:7).",
  },
  {
    id: "w3i-17-3-2",
    assessmentId: "w3a-17-3",
    question: "In Romans 12:6-8, Paul says each gift should be exercised with a particular posture. Which of the following pairings is correct?",
    options: ["Giving — with reluctance", "Mercy — with cheerfulness", "Leadership — with caution", "Teaching — with speed"],
    correctIndex: 1,
    explanation: "Paul says the one who shows mercy should do so 'with cheerfulness.' Each gift has its own appropriate attitude: generosity for giving, diligence for leadership, and cheerfulness for mercy.",
  },
  {
    id: "w3i-17-3-3",
    assessmentId: "w3a-17-3",
    question: "According to the lesson, how are spiritual gifts typically discovered?",
    options: ["Through a standardized test administered by the pastor", "Through prayer, experimentation in service, and community confirmation", "By waiting passively until the Spirit reveals it dramatically", "By choosing the gift you find most appealing"],
    correctIndex: 1,
    explanation: "The lesson outlines a threefold process: prayer and study, experimentation through service, and confirmation by the community — reflecting the Acts 6 model where the congregation identified gifted individuals.",
  },
  {
    id: "w3i-17-3-4",
    assessmentId: "w3a-17-3",
    question: "The parable of the talents (Matthew 25:14-30) teaches that gifts which are not exercised will:",
    options: ["Remain the same indefinitely", "Be transferred to another believer automatically", "Diminish — what we neglect atrophies", "Increase on their own over time"],
    correctIndex: 2,
    explanation: "The servant who buried his talent had even that one taken away. The principle is clear: faithful use of gifts leads to increase; neglect leads to loss.",
  },
  {
    id: "w3i-17-3-5",
    assessmentId: "w3a-17-3",
    question: "A long-time church member says, 'Ministry is the pastor's job — that's what we pay them for.' How would you respond using the theology of spiritual gifts?",
    options: ["Agree — pastors are the professionals and should handle all ministry", "Explain that Ephesians 4:12 says pastors exist to equip all members for ministry, not to do it alone, because every believer has received a gift (1 Peter 4:10)", "Suggest the member is right but could help occasionally", "Say that only ordained people have spiritual gifts"],
    correctIndex: 1,
    explanation: "The theology of spiritual gifts overturns the clergy-laity divide as a ministry boundary. Pastors equip; all members minister. The pew is not a spectator seat.",
  },
  {
    id: "w3i-17-4-1",
    assessmentId: "w3a-17-4",
    question: "In 1 Corinthians 13:1, Paul says that speaking in tongues without love makes one like what?",
    options: ["A still, small voice", "Sounding brass or a clanging cymbal", "A gentle rain", "A trumpet call"],
    correctIndex: 1,
    explanation: "Paul uses the image of 'sounding brass or a clanging cymbal' — impressive noise but empty content — to show that gifts without love are meaningless.",
  },
  {
    id: "w3i-17-4-2",
    assessmentId: "w3a-17-4",
    question: "According to 1 Corinthians 14:40, what principle should govern the exercise of spiritual gifts in corporate worship?",
    options: ["Spontaneity above all else", "The louder the better", "All things should be done decently and in order", "Only the pastor should exercise gifts publicly"],
    correctIndex: 2,
    explanation: "Paul insists that 'all things be done decently and in order.' Order in worship reflects the character of God, who is 'not the author of confusion but of peace' (14:33).",
  },
  {
    id: "w3i-17-4-3",
    assessmentId: "w3a-17-4",
    question: "In Matthew 7:22-23, Jesus warns that some who performed mighty works in His name will hear Him say, 'I never knew you.' What does this teach about the relationship between gifts and salvation?",
    options: ["Spiritual gifts guarantee salvation", "Gifts are proof of a genuine relationship with Christ", "Gifts can be exercised without a genuine relationship with Christ — gifts are tools, not evidence of salvation", "Only those without gifts need to worry about their relationship with Christ"],
    correctIndex: 2,
    explanation: "Jesus' warning makes clear that gifts are not proof of relationship. People can prophesy, cast out demons, and do mighty works and still not know Christ. Character and relationship matter more than performance.",
  },
  {
    id: "w3i-17-4-4",
    assessmentId: "w3a-17-4",
    question: "Why does Paul's placement of the love chapter (1 Corinthians 13) between chapters 12 and 14 matter theologically?",
    options: ["It was an accident of ancient manuscript arrangement", "It shows that love is the necessary context for all gift exercise — gifts without love are empty, and gift regulation must be guided by love", "It means love replaces gifts entirely", "It suggests Paul was unsure about the value of gifts"],
    correctIndex: 1,
    explanation: "The placement is deliberate: chapter 12 establishes gift diversity, chapter 13 establishes love as their indispensable context, and chapter 14 regulates their exercise. Love is not a substitute for gifts; it is their lifeblood.",
  },
  {
    id: "w3i-17-4-5",
    assessmentId: "w3a-17-4",
    question: "During a church business meeting, a member stands up and claims to have received a direct revelation from God that the church should make a major financial decision immediately, without further discussion. How should the church respond?",
    options: ["Accept the claim immediately because all prophecy is from God", "Reject the claim outright because God no longer speaks through individuals", "Test the claim by Scripture (Isaiah 8:20), by its fruit (Matthew 7:16-20), and by the counsel of the body — while maintaining order and love", "Table the discussion indefinitely to avoid conflict"],
    correctIndex: 2,
    explanation: "Paul instructs: 'Do not despise prophecies. Test all things; hold fast what is good' (1 Thessalonians 5:20-21). The church neither dismisses nor blindly accepts claimed revelations. It tests them by Scripture, fruit, and corporate discernment.",
  },
];
