export const belief1Lessons = [
  {
    id: "w1l-1-2",
    moduleId: "bmod-001",
    title: "Doctrinal Formulation: What Adventists Affirm About Scripture",
    description: "Understanding the Adventist position on biblical inspiration, the role of the Holy Spirit in interpretation, and the principle of testing all teaching by Scripture.",
    lessonOrder: 2,
    anchorText: "2 Peter 1:20-21; Isaiah 8:20; 1 Thessalonians 2:13",
    anchorBookId: 61,
    anchorChapter: 1,
    anchorVerseStart: 20,
    anchorVerseEnd: 21,
    estimatedMinutes: 30,
  },
  {
    id: "w1l-1-3",
    moduleId: "bmod-001",
    title: "Practical Implications: Living by the Word",
    description: "Moving from intellectual assent to daily dependence on Scripture — how the Word shapes decisions, relationships, and spiritual growth.",
    lessonOrder: 3,
    anchorText: "Psalm 119:105; Hebrews 4:12; James 1:22-25",
    anchorBookId: 19,
    anchorChapter: 119,
    anchorVerseStart: 105,
    anchorVerseEnd: 105,
    estimatedMinutes: 30,
  },
  {
    id: "w1l-1-4",
    moduleId: "bmod-001",
    title: "Misunderstandings & Challenges",
    description: "Addressing common misconceptions about the Bible — from claims of contradiction to the misuse of proof-texting — and learning how to handle Scripture with integrity.",
    lessonOrder: 4,
    anchorText: "Matthew 4:4; John 5:39; 2 Timothy 2:15",
    anchorBookId: 40,
    anchorChapter: 4,
    anchorVerseStart: 4,
    anchorVerseEnd: 4,
    estimatedMinutes: 30,
  },
];

export const belief1Sections = [
  {
    id: "w1s-1-2-1",
    lessonId: "w1l-1-2",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"Knowing this first, that no prophecy of Scripture is of any private interpretation, for prophecy never came by the will of man, but holy men of God spoke as they were moved by the Holy Spirit.\" — 2 Peter 1:20-21 (NKJV)\n\n\"To the law and to the testimony! If they do not speak according to this word, it is because there is no light in them.\" — Isaiah 8:20 (NKJV)\n\n\"For this reason we also thank God without ceasing, because when you received the word of God which you heard from us, you welcomed it not as the word of men, but as it is in truth, the word of God, which also effectively works in you who believe.\" — 1 Thessalonians 2:13 (NKJV)",
    sortOrder: 1,
  },
  {
    id: "w1s-1-2-2",
    lessonId: "w1l-1-2",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Peter's declaration in 2 Peter 1:20-21 establishes a critical truth: the origin of Scripture lies not in human initiative but in the sovereign movement of God's Spirit. The Greek word pheromenoi (\"moved\" or \"carried along\") pictures a sail filled by wind — the writers were borne forward by the Spirit while remaining conscious participants in the process. This is the heart of what Adventists mean by \"thought inspiration.\"\n\nIsaiah 8:20 provides the testing standard. Every claim to truth — whether from tradition, personal experience, or alleged new revelation — must pass through the filter of Scripture. The phrase \"to the law and to the testimony\" binds together God's moral will (the law) and His prophetic word (the testimony). If a teaching cannot withstand this examination, Isaiah says plainly, \"there is no light in them.\"\n\nPaul's gratitude in 1 Thessalonians 2:13 adds a third dimension: the reception of Scripture as God's own word, not merely a human product. The Thessalonians did not simply hear good advice; they recognized the divine voice behind the human messenger. Paul notes that this word \"effectively works\" in those who believe — Scripture is not passive information but an active, transforming force.\n\nTaken together, these passages outline the Adventist doctrine of Scripture: divinely originated, self-authenticating, and dynamically powerful in the life of the believer.",
    sortOrder: 2,
  },
  {
    id: "w1s-1-2-3",
    lessonId: "w1l-1-2",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "Seventh-day Adventists affirm several distinctive positions about the nature of Scripture that flow from these passages:\n\n**Thought inspiration, not verbal dictation.** God communicated His thoughts to the biblical writers, who then expressed those truths in their own words and styles. This explains why the four Gospels record the same events with different vocabulary and arrangement — the divine message is consistent, but the human vessel is visible. The unity of thought across diverse human authors testifies to the Spirit's guiding hand.\n\n**Scripture as the final court of appeal.** The Adventist commitment to sola scriptura means that creeds, councils, and traditions — however valuable — remain subordinate to the Bible. When the early Adventist pioneers studied the Sabbath, the state of the dead, and the sanctuary doctrine, they returned again and again to the biblical text rather than deferring to inherited theological systems.\n\n**The prophetic gift and biblical authority.** Adventists recognize the prophetic ministry of Ellen G. White as a manifestation of the spiritual gift described in 1 Corinthians 12. Her writings serve as a \"lesser light\" pointing to the \"greater light\" of Scripture (see her own description at egwwritings.org). This means her counsel is tested by — and never elevated above — the Bible itself. Isaiah 8:20 applies to every prophetic claim, including those within the Adventist movement.\n\n**Present truth and progressive understanding.** Adventists believe the Holy Spirit continues to unfold deeper insight from Scripture as history moves toward its climax. This is not new revelation that contradicts the Bible but clearer understanding of what Scripture already teaches — consistent with Peter's observation that the Spirit who inspired the Word also illuminates the reader.",
    sortOrder: 3,
  },
  {
    id: "w1s-1-2-4",
    lessonId: "w1l-1-2",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Apply what you have learned this week through these specific actions:\n\n1. **Test a belief by Scripture.** Choose one doctrine or conviction you hold — perhaps one you adopted from family or church culture — and trace it back to specific Bible passages. Can you defend it from Scripture alone, without appealing to tradition? Write down the texts that support it.\n\n2. **Practice the Isaiah 8:20 filter.** The next time you encounter a spiritual claim — in a sermon, a book, or a conversation — pause and ask: \"Does this align with the law and the testimony?\" Note what you discover in your journal.\n\n3. **Read Scripture expecting transformation.** Before opening your Bible this week, pray: \"Lord, let Your Word work effectively in me today.\" After reading, identify one specific way the passage challenges or reshapes your thinking.",
    sortOrder: 4,
  },
  {
    id: "w1s-1-2-5",
    lessonId: "w1l-1-2",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. When you read the Bible, do you approach it primarily as information to master or as God's living voice addressing you? What would change if you consistently adopted the second posture?\n\n2. How does the principle of sola scriptura affect your response when a respected teacher or tradition disagrees with a plain biblical teaching?\n\n3. Can you identify a time when the Holy Spirit illuminated a passage for you in a fresh way — not contradicting its original meaning, but deepening your understanding?",
    sortOrder: 5,
  },
  {
    id: "w1s-1-2-6",
    lessonId: "w1l-1-2",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of the Adventist doctrinal formulation regarding Scripture.",
    sortOrder: 6,
  },

  {
    id: "w1s-1-3-1",
    lessonId: "w1l-1-3",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"Your word is a lamp to my feet and a light to my path.\" — Psalm 119:105 (NKJV)\n\n\"For the word of God is living and powerful, and sharper than any two-edged sword, piercing even to the division of soul and spirit, and of joints and marrow, and is a discerner of the thoughts and intents of the heart.\" — Hebrews 4:12 (NKJV)\n\n\"But be doers of the word, and not hearers only, deceiving yourselves. For if anyone is a hearer of the word and not a doer, he is like a man observing his natural face in a mirror; for he observes himself, goes away, and immediately forgets what kind of man he was. But he who looks into the perfect law of liberty and continues in it, and is not a forgetful hearer but a doer of the work, this one will be blessed in his doing.\" — James 1:22-25 (NKJV)",
    sortOrder: 1,
  },
  {
    id: "w1s-1-3-2",
    lessonId: "w1l-1-3",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "The psalmist's metaphor of lamp and light reveals Scripture's most immediate practical purpose: guidance for the next step. In ancient Palestine, a clay oil lamp illuminated only a few feet ahead on a dark trail. The Word does not promise a floodlight over the entire future; it promises enough light for the step you are taking right now. This is an invitation to daily dependence rather than anxious planning.\n\nHebrews 4:12 presses deeper. The Word is not a passive document waiting to be analyzed — it analyzes the reader. The image of a surgical blade dividing soul from spirit and joint from marrow suggests a precision that reaches the places we hide even from ourselves. Scripture exposes motives, reveals self-deception, and confronts rationalizations. It discerns what we think and why we think it.\n\nJames completes the picture with a stark warning: hearing without doing is self-deception. His mirror analogy is deliberately unflattering — the person who reads Scripture but refuses to act on it walks away and forgets the truth about themselves. The blessing, James insists, belongs not to the one who studies the Word most thoroughly, but to the one who does what it says.\n\nThese three passages together form a practical theology of Scripture engagement: the Word guides (Psalm 119), the Word exposes (Hebrews 4), and the Word demands response (James 1).",
    sortOrder: 2,
  },
  {
    id: "w1s-1-3-3",
    lessonId: "w1l-1-3",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "The Adventist tradition has consistently emphasized that Bible study is not an academic exercise but a life-shaping encounter with the living God. Several distinctives flow from this conviction:\n\n**Scripture shapes the whole person.** Because Adventists understand human beings as an indivisible unity of body, mind, and spirit, the Word's transforming power touches every dimension of life — not just \"spiritual\" matters. Dietary choices, Sabbath observance, stewardship, and interpersonal ethics are all areas where \"doing the Word\" takes concrete form. The Adventist health message, for example, is not a cultural add-on but a response to the biblical call for whole-person faithfulness.\n\n**The Great Controversy as interpretive lens.** When Scripture functions as a lamp (Psalm 119:105), it illuminates the cosmic conflict between Christ and Satan. Adventists read the Bible with an awareness that every command, every promise, and every warning exists within a universe-wide drama over God's character. Obedience is not arbitrary rule-keeping; it is alignment with the God whose character is love and whose law reflects that love.\n\n**Present truth and the call to action.** The Adventist concept of \"present truth\" (2 Peter 1:12) means that certain biblical teachings carry particular urgency for this generation. The three angels' messages of Revelation 14 call for decisive action — worship the Creator, reject false systems, keep the commandments and the faith of Jesus. James's warning against passive hearing resonates powerfully with the Adventist conviction that the final generation must be a people who live what they believe.\n\n**Personal devotional life.** Adventists have historically prioritized daily Bible reading, family worship, and Sabbath School study as disciplines that keep the Word active in daily experience. These are not rituals for their own sake but structured opportunities to let the Word do its diagnostic and guiding work.",
    sortOrder: 3,
  },
  {
    id: "w1s-1-3-4",
    lessonId: "w1l-1-3",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Move from hearing to doing this week:\n\n1. **The one-verse obedience challenge.** Each morning, read one verse slowly. Before closing your Bible, identify one concrete action that verse calls for — and do it before the day ends. Keep a brief record of what you chose and what happened.\n\n2. **Allow the Word to search you.** Read Hebrews 4:12-13 aloud at the start of your prayer time. Then sit quietly and ask: \"Lord, what thought or motive are You bringing to light today?\" Write down whatever comes to mind without defending yourself.\n\n3. **Share what you are learning.** Tell one person this week about a passage that challenged or changed your behavior. Accountability transforms private conviction into lived reality.",
    sortOrder: 4,
  },
  {
    id: "w1s-1-3-5",
    lessonId: "w1l-1-3",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. When was the last time a Bible passage genuinely changed how you acted — not just how you felt? What made that experience different from ordinary reading?\n\n2. James warns that hearing without doing is self-deception. Are there areas of your life where you know what Scripture teaches but have not yet followed through? What holds you back?\n\n3. How does the image of Scripture as a surgical instrument (Hebrews 4:12) affect your willingness to approach difficult or uncomfortable passages?",
    sortOrder: 5,
  },
  {
    id: "w1s-1-3-6",
    lessonId: "w1l-1-3",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of the practical implications of living by Scripture.",
    sortOrder: 6,
  },

  {
    id: "w1s-1-4-1",
    lessonId: "w1l-1-4",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"But He answered and said, 'It is written, \"Man shall not live by bread alone, but by every word that proceeds from the mouth of God.\"'\" — Matthew 4:4 (NKJV)\n\n\"You search the Scriptures, for in them you think you have eternal life; and these are they which testify of Me.\" — John 5:39 (NKJV)\n\n\"Be diligent to present yourself approved to God, a worker who does not need to be ashamed, rightly dividing the word of truth.\" — 2 Timothy 2:15 (NKJV)",
    sortOrder: 1,
  },
  {
    id: "w1s-1-4-2",
    lessonId: "w1l-1-4",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Jesus' response to Satan in Matthew 4:4 is itself a model of proper Scripture use. Facing temptation in the wilderness, Jesus did not rely on personal authority or miraculous power; He quoted Deuteronomy 8:3 and stood on the written Word. Yet Satan also quoted Scripture in the same encounter (Matthew 4:6), twisting Psalm 91 to serve a destructive purpose. The difference between faithful use and misuse of Scripture is not whether you can cite a verse, but whether your citation honors the full testimony of God's Word.\n\nJohn 5:39 exposes a subtler danger. The religious leaders of Jesus' day were devoted students of the Torah. They memorized, debated, and reverenced the text — yet missed the Person to whom every page pointed. It is possible to master the letter of Scripture while remaining blind to its living center. Jesus insists that the Scriptures \"testify of Me.\" Any method of Bible study that produces knowledge without encounter, or doctrine without devotion to Christ, has gone wrong somewhere.\n\nPaul's charge to Timothy in 2 Timothy 2:15 introduces the concept of \"rightly dividing\" (orthotomeo — literally, \"cutting straight\") the word of truth. The metaphor suggests a craftsman cutting a straight line or a farmer plowing a straight furrow. Careless handling of Scripture — yanking verses from context, building doctrines on obscure passages while ignoring clear ones, or forcing texts to say what they never meant — dishonors both the Author and the reader.\n\nThree common misunderstandings emerge from these passages: (1) that quoting Scripture is always the same as using it faithfully, (2) that rigorous study guarantees spiritual insight, and (3) that all interpretations are equally valid regardless of method.",
    sortOrder: 2,
  },
  {
    id: "w1s-1-4-3",
    lessonId: "w1l-1-4",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "The Adventist community has navigated several persistent challenges regarding Scripture that these passages illuminate:\n\n**Proof-texting versus contextual reading.** Adventists have sometimes been accused — and have sometimes been guilty — of stringing together isolated verses to support a conclusion without attending to each text's literary and historical context. The commitment to \"rightly dividing\" (2 Timothy 2:15) calls for careful, honest exegesis. The Adventist hermeneutical principle that Scripture interprets Scripture does not mean any verse can be forced to connect with any other; it means the Bible's own theological framework, not an external system, governs interpretation.\n\n**Christ-centered reading.** Jesus' rebuke in John 5:39 is a standing challenge to any tradition that prizes doctrinal precision above a living relationship with the Savior. Adventist theology at its best is deeply Christocentric — the sanctuary doctrine traces Christ's ministry, the Sabbath celebrates His creatorship and redemption, and the three angels' messages culminate in \"the faith of Jesus\" (Revelation 14:12). When doctrine becomes an end in itself rather than a window into the character of Christ, something essential has been lost.\n\n**Handling alleged contradictions.** Critics frequently point to apparent discrepancies in the biblical text. The Adventist position, grounded in thought inspiration, acknowledges that human writers expressed divine truth in imperfect language and from limited vantage points. Apparent contradictions often dissolve when context, genre, and the writer's purpose are taken into account. The honest student neither ignores difficulties nor allows them to undermine confidence in Scripture's reliability.\n\n**The danger of selective reading.** Satan's use of Scripture in the wilderness temptation (Matthew 4:6) warns against cherry-picking texts that support a desired conclusion while ignoring those that challenge it. The Adventist commitment to the whole counsel of God (Acts 20:27) is a safeguard against this tendency.",
    sortOrder: 3,
  },
  {
    id: "w1s-1-4-4",
    lessonId: "w1l-1-4",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Strengthen your ability to handle Scripture faithfully this week:\n\n1. **Context check.** Choose a favorite verse you quote often. Read the entire chapter surrounding it. Ask: Does my usual application of this verse align with the author's original point? If you discover a gap, adjust your understanding and share what you learned with a friend.\n\n2. **Read for Christ.** Select one Old Testament chapter — perhaps from Leviticus or Numbers, a section you might normally skip — and look for ways it points to Jesus. Record at least one connection you find.\n\n3. **Engage a difficult text.** Identify one passage you have always found confusing or troubling. Read it in two or three translations, consult a cross-reference, and write a brief paragraph summarizing what you now understand. If questions remain, bring them to your Sabbath School class or study group.",
    sortOrder: 4,
  },
  {
    id: "w1s-1-4-5",
    lessonId: "w1l-1-4",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Have you ever used a Bible verse to justify a position that, on deeper study, the verse did not actually support? What did you learn from that experience?\n\n2. Jesus told the Pharisees they searched the Scriptures but missed Him. In your own study habits, how do you guard against accumulating knowledge without deepening your relationship with Christ?\n\n3. When you encounter a passage that seems to contradict another, what is your first instinct — to dismiss the difficulty, to doubt the Bible, or to dig deeper? How might the principle of thought inspiration guide your response?",
    sortOrder: 5,
  },
  {
    id: "w1s-1-4-6",
    lessonId: "w1l-1-4",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of common misunderstandings and challenges regarding Scripture.",
    sortOrder: 6,
  },
];

export const belief1Assessments = [
  {
    id: "w1a-1-2",
    lessonId: "w1l-1-2",
    title: "Doctrinal Formulation Assessment — Scripture",
    passingScore: 70,
  },
  {
    id: "w1a-1-3",
    lessonId: "w1l-1-3",
    title: "Practical Implications Assessment — Scripture",
    passingScore: 70,
  },
  {
    id: "w1a-1-4",
    lessonId: "w1l-1-4",
    title: "Misunderstandings & Challenges Assessment — Scripture",
    passingScore: 70,
  },
];

export const belief1Items = [
  {
    id: "w1i-1-2-1",
    assessmentId: "w1a-1-2",
    question: "In 2 Peter 1:21, what does the Greek word 'pheromenoi' describe about how the biblical writers received their messages?",
    options: ["They were put into a trance state", "They were carried along by the Holy Spirit", "They copied directly from heavenly tablets", "They relied on their own research alone"],
    correctIndex: 1,
    explanation: "Pheromenoi means 'carried along' or 'borne forward,' like a sail filled by wind. The writers were consciously active but divinely directed — the foundation of thought inspiration.",
  },
  {
    id: "w1i-1-2-2",
    assessmentId: "w1a-1-2",
    question: "According to Isaiah 8:20, what standard must all spiritual claims be measured against?",
    options: ["Church tradition and councils", "The law and the testimony", "Personal spiritual experience", "The consensus of scholars"],
    correctIndex: 1,
    explanation: "Isaiah declares 'To the law and to the testimony!' — God's moral will and prophetic word form the non-negotiable standard. Claims that fail this test have 'no light in them.'",
  },
  {
    id: "w1i-1-2-3",
    assessmentId: "w1a-1-2",
    question: "What does Paul say the word of God does in those who believe, according to 1 Thessalonians 2:13?",
    options: ["It provides intellectual entertainment", "It effectively works in them", "It guarantees material prosperity", "It removes the need for community"],
    correctIndex: 1,
    explanation: "Paul celebrates that the Thessalonians received the message as God's word, which 'effectively works' (energeitai) in believers — Scripture is an active, transforming force, not merely information.",
  },
  {
    id: "w1i-1-2-4",
    assessmentId: "w1a-1-2",
    question: "A church member argues that a popular teacher's vision should be accepted as equal to Scripture because the teacher is sincere. How would the Adventist principle of sola scriptura respond?",
    options: ["Sincerity validates the vision as trustworthy", "The vision must be tested by Scripture and held subordinate to it", "Visions ceased after the apostolic era and should all be rejected", "The congregation should vote on whether to accept it"],
    correctIndex: 1,
    explanation: "Sola scriptura means the Bible is the supreme authority. All prophetic claims — including sincere ones — must be evaluated against the written Word (Isaiah 8:20). Sincerity alone does not establish authority.",
  },
  {
    id: "w1i-1-2-5",
    assessmentId: "w1a-1-2",
    question: "Why do Adventists describe Ellen G. White's writings as a 'lesser light' pointing to a 'greater light'?",
    options: ["Because her writings contain errors that Scripture does not", "Because her prophetic gift is tested by and subordinate to biblical authority", "Because she wrote before the Bible was completed", "Because her writings are only relevant to the nineteenth century"],
    correctIndex: 1,
    explanation: "Ellen White herself used this language to describe the relationship between her writings and the Bible. Her prophetic ministry is a gift of the Spirit tested by Scripture, not a replacement for it.",
  },

  {
    id: "w1i-1-3-1",
    assessmentId: "w1a-1-3",
    question: "In Psalm 119:105, the Word is compared to a lamp for the feet. What does this metaphor primarily emphasize?",
    options: ["Scripture reveals the entire future at once", "Scripture provides enough light for the immediate next step", "Scripture is only useful in moments of crisis", "Scripture replaces the need for prayer"],
    correctIndex: 1,
    explanation: "An ancient oil lamp illuminated only a few feet ahead. The metaphor emphasizes daily dependence — God gives enough guidance for the step you are taking right now, not a floodlight over the distant future.",
  },
  {
    id: "w1i-1-3-2",
    assessmentId: "w1a-1-3",
    question: "According to Hebrews 4:12, what is the Word of God able to discern?",
    options: ["The financial worth of a person", "The thoughts and intents of the heart", "The political loyalties of nations", "The genetic heritage of individuals"],
    correctIndex: 1,
    explanation: "Hebrews 4:12 describes Scripture as a two-edged sword that pierces to the division of soul and spirit, discerning 'the thoughts and intents of the heart' — it reaches motives and hidden attitudes.",
  },
  {
    id: "w1i-1-3-3",
    assessmentId: "w1a-1-3",
    question: "What does James compare a person to who hears the Word but does not act on it?",
    options: ["A tree with deep roots", "A man who looks in a mirror and forgets his face", "A soldier standing guard", "A builder on solid rock"],
    correctIndex: 1,
    explanation: "James 1:23-24 uses the mirror analogy: the person looks at their reflection (reads Scripture), walks away, and immediately forgets what they saw. Hearing without doing is self-deception.",
  },
  {
    id: "w1i-1-3-4",
    assessmentId: "w1a-1-3",
    question: "A believer reads about forgiveness in Scripture and feels convicted but postpones reconciling with a family member indefinitely. According to James 1:22-25, what is happening?",
    options: ["They are wisely waiting for the right timing", "They are deceiving themselves by hearing without doing", "They are practicing healthy boundaries", "They are demonstrating mature patience"],
    correctIndex: 1,
    explanation: "James explicitly warns that hearing without corresponding action is self-deception. Conviction without obedience leads to spiritual numbness, not growth. The blessing belongs to the doer, not merely the hearer.",
  },
  {
    id: "w1i-1-3-5",
    assessmentId: "w1a-1-3",
    question: "How does the Adventist understanding of holistic anthropology (body-mind-spirit unity) affect how 'doing the Word' is practiced?",
    options: ["It limits Scripture's relevance to spiritual matters only", "It means obedience touches every dimension of life — diet, relationships, Sabbath, stewardship", "It suggests the body is unimportant compared to the soul", "It restricts Bible application to worship services"],
    correctIndex: 1,
    explanation: "Because Adventists view humans as an indivisible unity, the Word's call to obedience extends to physical health, financial stewardship, interpersonal ethics, and Sabbath keeping — not just 'spiritual' matters.",
  },

  {
    id: "w1i-1-4-1",
    assessmentId: "w1a-1-4",
    question: "In Matthew 4, both Jesus and Satan quote Scripture during the wilderness temptation. What distinguishes faithful use of the Bible from its misuse?",
    options: ["Only ordained ministers can quote Scripture faithfully", "Faithful use honors the full testimony of God's Word rather than isolating texts", "It depends on who speaks louder", "The difference is determined by majority opinion"],
    correctIndex: 1,
    explanation: "Satan quoted Psalm 91 accurately but twisted its application. Jesus responded with the full counsel of Scripture (Deuteronomy 6:16). Faithful use considers context, intent, and harmony with the whole biblical message.",
  },
  {
    id: "w1i-1-4-2",
    assessmentId: "w1a-1-4",
    question: "In John 5:39, Jesus told the religious leaders they searched the Scriptures but missed something essential. What did they miss?",
    options: ["The correct Hebrew pronunciation", "That the Scriptures testify of Him — the living Christ", "The proper ritual calendar", "The hidden numerical codes"],
    correctIndex: 1,
    explanation: "Jesus declared that the Scriptures 'testify of Me.' The Pharisees were rigorous students of the text but failed to recognize the Person to whom every page pointed. Knowledge without encounter with Christ is incomplete.",
  },
  {
    id: "w1i-1-4-3",
    assessmentId: "w1a-1-4",
    question: "What does Paul mean by 'rightly dividing the word of truth' in 2 Timothy 2:15?",
    options: ["Separating the Old Testament from the New Testament", "Handling Scripture with accuracy, honoring its context and meaning", "Dividing verses into equal-length portions for memorization", "Reading only the passages that apply to your situation"],
    correctIndex: 1,
    explanation: "The Greek orthotomeo means 'cutting straight' — handling the text with precision and honesty. It calls for contextual, careful interpretation rather than careless or manipulative use of Scripture.",
  },
  {
    id: "w1i-1-4-4",
    assessmentId: "w1a-1-4",
    question: "A skeptic points out that Matthew and Luke record different details about the same event and claims this proves the Bible is unreliable. How does the Adventist understanding of thought inspiration address this?",
    options: ["It admits the Bible is full of errors", "It recognizes that different writers expressed the same divine truths from their own perspectives without compromising reliability", "It insists every detail must match word-for-word", "It dismisses one Gospel as less inspired than the other"],
    correctIndex: 1,
    explanation: "Thought inspiration means God guided the writers' thoughts while allowing their individuality. Differences in detail reflect human perspective, not error — the core divine message remains consistent and trustworthy.",
  },
  {
    id: "w1i-1-4-5",
    assessmentId: "w1a-1-4",
    question: "Why is proof-texting — pulling individual verses out of context to support a predetermined conclusion — a misuse of Scripture according to Adventist hermeneutics?",
    options: ["Because only long passages are inspired, not individual verses", "Because it violates the principle that Scripture interprets Scripture within its literary and historical context", "Because proof-texting was invented by non-Adventists", "Because the Bible should never be quoted directly"],
    correctIndex: 1,
    explanation: "The Adventist principle that Scripture interprets Scripture requires attention to context, genre, and the author's intent. Proof-texting ignores these safeguards and risks making the Bible say what the reader wants rather than what God intended.",
  },
];

export const belief2Lessons = [
  {
    id: "w1l-2-2",
    moduleId: "bmod-002",
    title: "Doctrinal Formulation: One God in Three Persons",
    description: "Examining the precise Adventist affirmation of the Trinity — one God existing as three co-eternal, co-equal Persons — and how this doctrine developed through careful biblical study.",
    lessonOrder: 2,
    anchorText: "2 Corinthians 13:14; Ephesians 4:4-6; 1 Peter 1:2",
    anchorBookId: 47,
    anchorChapter: 13,
    anchorVerseStart: 14,
    anchorVerseEnd: 14,
    estimatedMinutes: 30,
  },
  {
    id: "w1l-2-3",
    moduleId: "bmod-002",
    title: "Practical Implications: Living in Trinitarian Community",
    description: "Discovering how the relational nature of the Triune God shapes Christian community, worship, and mission.",
    lessonOrder: 3,
    anchorText: "John 17:20-23; 1 John 1:3; Romans 8:14-17",
    anchorBookId: 43,
    anchorChapter: 17,
    anchorVerseStart: 20,
    anchorVerseEnd: 23,
    estimatedMinutes: 30,
  },
  {
    id: "w1l-2-4",
    moduleId: "bmod-002",
    title: "Misunderstandings & Challenges",
    description: "Addressing common errors about the Trinity — from modalism to tritheism — and responding to objections with Scripture and clarity.",
    lessonOrder: 4,
    anchorText: "Isaiah 44:6; John 10:30; Acts 5:3-4",
    anchorBookId: 23,
    anchorChapter: 44,
    anchorVerseStart: 6,
    anchorVerseEnd: 6,
    estimatedMinutes: 30,
  },
];

export const belief2Sections = [
  {
    id: "w1s-2-2-1",
    lessonId: "w1l-2-2",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"The grace of the Lord Jesus Christ, and the love of God, and the communion of the Holy Spirit be with you all.\" — 2 Corinthians 13:14 (NKJV)\n\n\"There is one body and one Spirit, just as you were called in one hope of your calling; one Lord, one faith, one baptism; one God and Father of all, who is above all, and through all, and in you all.\" — Ephesians 4:4-6 (NKJV)\n\n\"Elect according to the foreknowledge of God the Father, in sanctification of the Spirit, for obedience and sprinkling of the blood of Jesus Christ.\" — 1 Peter 1:2 (NKJV)",
    sortOrder: 1,
  },
  {
    id: "w1s-2-2-2",
    lessonId: "w1l-2-2",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Paul's benediction in 2 Corinthians 13:14 is one of the clearest trinitarian statements in the New Testament. Three distinct Persons are named — the Lord Jesus Christ, God (the Father), and the Holy Spirit — each contributing something essential to the believer's experience: grace, love, and communion. The structure is not accidental. Paul places three divine Persons side by side as equal sources of blessing, implying a shared divine nature.\n\nEphesians 4:4-6 reinforces this by weaving the three Persons into the fabric of Christian unity. Paul identifies one Spirit, one Lord (Jesus), and one God and Father — each with a distinct relational role, yet bound together by the repeated word \"one.\" The passage does not describe three Gods cooperating; it describes one God whose unity is expressed through three Persons working in harmony for the salvation and sanctification of believers.\n\nPeter's greeting in 1 Peter 1:2 assigns a specific role to each Person in the plan of salvation: the Father's foreknowledge (initiating), the Spirit's sanctification (transforming), and Christ's blood (atoning). This trinitarian division of labor runs throughout the New Testament and reflects not three separate projects but one unified redemptive purpose carried out by one God in three Persons.\n\nThe word \"Trinity\" does not appear in Scripture, but the reality it describes saturates the biblical witness. The doctrine is not a philosophical invention imposed on the text; it is the conclusion that honest readers reach when they take the full biblical testimony seriously.",
    sortOrder: 2,
  },
  {
    id: "w1s-2-2-3",
    lessonId: "w1l-2-2",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "The Adventist affirmation of the Trinity rests on biblical evidence rather than creedal inheritance. Several key distinctives mark the Adventist position:\n\n**A doctrine arrived at, not inherited.** Early Adventist pioneers included individuals from various theological backgrounds, some of whom questioned the Trinity. Through decades of sustained Bible study — particularly concerning the full divinity of Christ and the personhood of the Holy Spirit — the movement arrived at a trinitarian conviction on its own terms. This history reminds Adventists that doctrinal integrity requires following Scripture wherever it leads, even beyond inherited assumptions.\n\n**Three Persons, not three roles.** Adventists reject modalism — the idea that God is one Person who appears in three different \"modes\" (like an actor wearing three masks). The baptism of Jesus (Matthew 3:16-17) demonstrates three simultaneous, distinct Persons: the Son in the water, the Spirit descending, and the Father speaking from heaven. Each Person is conscious, relational, and fully divine.\n\n**The Great Controversy and trinitarian cooperation.** The cosmic conflict between Christ and Satan is resolved through the cooperative work of all three Persons. The Father initiates the plan of redemption, the Son executes it through incarnation and atonement, and the Spirit applies it through conviction, regeneration, and empowerment. Satan's rebellion was ultimately a rejection of the relational order within the Godhead — he sought to displace the Son (Isaiah 14:13-14) and fracture the unity of heaven.\n\n**One divine essence, three Persons.** Adventists affirm that the Father, Son, and Holy Spirit share the same divine nature and attributes — omniscience, omnipotence, omnipresence, eternality. There is no hierarchy of essence, though there is a voluntary order of function within the plan of salvation.",
    sortOrder: 3,
  },
  {
    id: "w1s-2-2-4",
    lessonId: "w1l-2-2",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Deepen your understanding of the Triune God this week:\n\n1. **Trinitarian prayer pattern.** Each day, structure your prayer to address all three Persons: thank the Father for His sovereign love, praise the Son for His saving work, and invite the Spirit's guidance for the day ahead. Notice how this changes the texture of your prayer life.\n\n2. **Trace the three Persons through one chapter.** Choose a chapter from the Gospel of John (chapters 14-16 are especially rich). As you read, underline every reference to the Father, the Son, and the Spirit. Map the relationships between them in a brief written summary.",
    sortOrder: 4,
  },
  {
    id: "w1s-2-2-5",
    lessonId: "w1l-2-2",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. The early Adventist pioneers changed their minds about the Trinity as they studied Scripture more deeply. What does this teach you about intellectual humility in doctrinal study?\n\n2. If someone asked you, \"Where does the Bible teach the Trinity?\" which two or three passages would you point to first, and why?\n\n3. How does understanding God as three Persons in one essence differ from believing in three separate Gods? Why does the distinction matter for worship and trust?",
    sortOrder: 5,
  },
  {
    id: "w1s-2-2-6",
    lessonId: "w1l-2-2",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of the Adventist doctrinal formulation of the Trinity.",
    sortOrder: 6,
  },

  {
    id: "w1s-2-3-1",
    lessonId: "w1l-2-3",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"I do not pray for these alone, but also for those who will believe in Me through their word; that they all may be one, as You, Father, are in Me, and I in You; that they also may be one in Us, that the world may believe that You sent Me. And the glory which You gave Me I have given them, that they may be one just as We are one: I in them, and You in Me; that they may be made perfect in one, and that the world may know that You have sent Me, and have loved them as You have loved Me.\" — John 17:20-23 (NKJV)\n\n\"That which we have seen and heard we declare to you, that you also may have fellowship with us; and truly our fellowship is with the Father and with His Son Jesus Christ.\" — 1 John 1:3 (NKJV)\n\n\"For as many as are led by the Spirit of God, these are sons of God. For you did not receive the spirit of bondage again to fear, but you received the Spirit of adoption by whom we cry out, 'Abba, Father.' The Spirit Himself bears witness with our spirit that we are children of God, and if children, then heirs — heirs of God and joint heirs with Christ.\" — Romans 8:14-17 (NKJV)",
    sortOrder: 1,
  },
  {
    id: "w1s-2-3-2",
    lessonId: "w1l-2-3",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Jesus' prayer in John 17 is breathtaking in its scope. He prays not only for His immediate disciples but for every future believer — and the standard He sets for their unity is nothing less than the unity within the Godhead itself: \"as You, Father, are in Me, and I in You.\" This is not mere organizational cooperation or doctrinal agreement. It is a relational oneness that mirrors the intimate, self-giving love shared among the Father, Son, and Spirit.\n\nJohn's declaration in 1 John 1:3 reveals that Christian fellowship is not a social club but a participation in the divine community. Believers have fellowship \"with the Father and with His Son Jesus Christ\" — and through that vertical relationship, they are drawn into genuine horizontal fellowship with one another. The quality of human community is shaped by the quality of divine communion.\n\nPaul's argument in Romans 8:14-17 introduces a stunning truth: through the Spirit, believers are adopted into God's own family. The Spirit does not make us servants awaiting orders; He makes us children crying \"Abba, Father\" — the intimate Aramaic term a child would use. All three Persons are active in this adoption: the Spirit leads and testifies, the Father receives, and believers become \"joint heirs with Christ.\" The relational life within the Trinity overflows to include redeemed humanity.\n\nThe practical implication is clear: if God exists in eternal self-giving relationship, then isolation, self-sufficiency, and relational indifference are fundamentally contrary to the character of the God we worship. Community is not optional for Christians — it is a reflection of God's own nature.",
    sortOrder: 2,
  },
  {
    id: "w1s-2-3-3",
    lessonId: "w1l-2-3",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "The trinitarian foundation of Christian community carries specific implications for Adventist life and mission:\n\n**Church unity reflects divine unity.** When Adventist congregations fragment over cultural preferences, personality conflicts, or institutional politics, they contradict the prayer of Jesus in John 17. Unity does not mean uniformity — the three Persons of the Godhead are distinct yet perfectly one. Likewise, the body of Christ embraces diverse languages, cultures, and temperaments while maintaining oneness in faith and mission.\n\n**Worship as trinitarian encounter.** Adventist worship at its richest engages all three Persons: praise directed to the Father, gratitude for the Son's sacrifice, and openness to the Spirit's presence. Sabbath worship is not merely a duty performed before an abstract deity; it is a relational encounter with the God who is, in His very being, communal. The Sabbath itself was given in the context of creation — an act of the Triune God (Genesis 1:1-2, John 1:1-3, Genesis 1:2).\n\n**Mission as participation in trinitarian sending.** The Great Commission (Matthew 28:18-20) is explicitly trinitarian: \"baptizing them in the name of the Father and of the Son and of the Holy Spirit.\" Adventist mission — whether global evangelism, health ministry, or education — is participation in the sending movement that begins within the Godhead. The Father sends the Son, the Father and Son send the Spirit, and the Triune God sends the church.\n\n**Spiritual gifts and trinitarian diversity.** Paul's teaching on spiritual gifts in 1 Corinthians 12 has a trinitarian structure: \"diversities of gifts, but the same Spirit ... differences of ministries, but the same Lord ... diversities of activities, but it is the same God\" (vv. 4-6). The diversity of gifts within the church mirrors the diversity of Persons within the Godhead — varied roles serving one unified purpose.",
    sortOrder: 3,
  },
  {
    id: "w1s-2-3-4",
    lessonId: "w1l-2-3",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Live out the communal nature of the Triune God this week:\n\n1. **Pursue reconciliation.** Is there a broken or strained relationship in your church community? Take one concrete step toward healing it this week — a conversation, an apology, or an act of service. Let the unity of the Godhead challenge your comfort with relational distance.\n\n2. **Practice trinitarian hospitality.** Invite someone to share a meal or a Sabbath afternoon who is outside your usual circle — a visitor, a new member, someone from a different cultural background. Reflect afterward on how this experience mirrors the self-giving love within the Trinity.\n\n3. **Serve through your gifts.** Identify one spiritual gift you believe God has given you and use it intentionally this week for the benefit of another person or your local congregation. The Spirit distributes gifts not for personal prestige but for communal edification.",
    sortOrder: 4,
  },
  {
    id: "w1s-2-3-5",
    lessonId: "w1l-2-3",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Jesus prayed that His followers would be one \"as\" the Father and Son are one. What would your local church look like if that prayer were being answered more fully?\n\n2. Romans 8:15 says the Spirit enables us to cry \"Abba, Father.\" How does your sense of intimacy with God affect your willingness to be vulnerable and authentic with other believers?\n\n3. If community reflects the nature of the Triune God, what does your current level of engagement in Christian fellowship say about your understanding of who God is?",
    sortOrder: 5,
  },
  {
    id: "w1s-2-3-6",
    lessonId: "w1l-2-3",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of the practical implications of trinitarian theology.",
    sortOrder: 6,
  },

  {
    id: "w1s-2-4-1",
    lessonId: "w1l-2-4",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"Thus says the LORD, the King of Israel, and his Redeemer, the LORD of hosts: 'I am the First and I am the Last; besides Me there is no God.'\" — Isaiah 44:6 (NKJV)\n\n\"I and My Father are one.\" — John 10:30 (NKJV)\n\n\"But Peter said, 'Ananias, why has Satan filled your heart to lie to the Holy Spirit and keep back part of the price of the land for yourself? While it remained, was it not your own? And after it was sold, was it not in your own control? Why have you conceived this thing in your heart? You have not lied to men but to God.'\" — Acts 5:3-4 (NKJV)",
    sortOrder: 1,
  },
  {
    id: "w1s-2-4-2",
    lessonId: "w1l-2-4",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Isaiah 44:6 declares in the strongest possible terms that there is only one God. The LORD (Yahweh) identifies Himself as \"the First and the Last\" — a title later applied to Jesus in Revelation 1:17 and 22:13. This creates a theological tension that the doctrine of the Trinity resolves: if the Father is the only God and Jesus also bears the title that belongs to God alone, then they must share the same divine nature.\n\nJesus' statement in John 10:30 — \"I and My Father are one\" — was understood by His hearers as a claim to deity. They immediately took up stones to execute Him for blasphemy, saying, \"You, being a Man, make Yourself God\" (v. 33). Jesus did not correct their understanding of His claim; He defended it. The Greek word hen (\"one\") is neuter, suggesting not \"one Person\" but \"one thing\" — one in essence, nature, and purpose.\n\nPeter's confrontation with Ananias in Acts 5:3-4 provides decisive evidence for the deity of the Holy Spirit. In verse 3, Peter says Ananias lied \"to the Holy Spirit.\" In verse 4, he says Ananias lied \"to God.\" The equation is direct: the Holy Spirit is God. This is not a figure of speech or a loose identification; Peter treats lying to the Spirit and lying to God as the same act.\n\nThree common errors arise from misreading these texts. Modalism collapses the three Persons into one Person wearing three masks — but John 10:30 distinguishes \"I\" and \"My Father\" as two while affirming their oneness. Tritheism splits the Godhead into three separate Gods — but Isaiah 44:6 insists there is only one. Subordinationism denies the full deity of the Son or Spirit — but Acts 5:3-4 identifies the Spirit as God, and Revelation applies the Father's own title to the Son.",
    sortOrder: 2,
  },
  {
    id: "w1s-2-4-3",
    lessonId: "w1l-2-4",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "Several persistent challenges and misunderstandings about the Trinity deserve careful Adventist engagement:\n\n**\"The Trinity is a pagan invention.\"** Some critics claim that the doctrine was borrowed from pagan triads or imposed by the Council of Nicaea in AD 325. Adventists respond by pointing to the biblical evidence itself — the trinitarian patterns in Matthew 28:19, 2 Corinthians 13:14, and 1 Peter 1:2 predate any council. Nicaea did not invent the Trinity; it formalized language to protect a truth already present in Scripture. Adventists arrive at the doctrine through independent Bible study, not creedal loyalty.\n\n**\"Early Adventists were anti-trinitarian.\"** It is true that some pioneers, including James White and Uriah Smith, questioned aspects of traditional trinitarianism. However, their concerns were often directed at specific creedal formulations they viewed as unbiblical rather than at the reality of three divine Persons. As the movement matured in its study of Scripture — particularly through the writings of Ellen G. White, who affirmed \"three living persons of the heavenly trio\" — the church arrived at a robust trinitarian position anchored in the Bible rather than in philosophical categories.\n\n**\"The Holy Spirit is a force, not a Person.\"** This claim is refuted by the consistent New Testament portrayal of the Spirit as a Person who speaks (Acts 13:2), teaches (John 14:26), can be grieved (Ephesians 4:30), and can be lied to (Acts 5:3). Forces do not grieve, teach, or hold conversations. The Spirit possesses intellect, will, and emotion — the marks of personhood.\n\n**\"If there are three Persons, there must be three Gods.\"** The biblical witness holds two truths simultaneously: there is one God (Deuteronomy 6:4; Isaiah 44:6), and three Persons share that one divine nature. Adventists do not claim to resolve this mystery exhaustively — they affirm it because Scripture teaches both truths, and they trust the self-revelation of a God who transcends human categories.",
    sortOrder: 3,
  },
  {
    id: "w1s-2-4-4",
    lessonId: "w1l-2-4",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Sharpen your ability to think and speak clearly about the Trinity this week:\n\n1. **Prepare a simple explanation.** Write a two-minute response to the question: \"How can God be one and three at the same time?\" Use only Scripture references — no philosophical jargon. Practice saying it aloud until it feels natural. This is not about memorizing a formula but about being ready to give an answer (1 Peter 3:15).\n\n2. **Study the Spirit's personhood.** Read John 14-16 and list every action attributed to the Holy Spirit. Note which of these actions require personhood (speaking, teaching, guiding, testifying, convicting). Reflect on how this changes your relationship with the Spirit.\n\n3. **Engage a skeptic's question honestly.** If you have a friend or family member who struggles with the Trinity, listen to their specific objection before responding. Often the real barrier is not intellectual but relational — they may fear that accepting the doctrine means abandoning careful thinking. Meet them with patience and Scripture.",
    sortOrder: 4,
  },
  {
    id: "w1s-2-4-5",
    lessonId: "w1l-2-4",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Which of the common misunderstandings about the Trinity (modalism, tritheism, subordinationism) do you find most tempting or confusing? What biblical text helps you correct that tendency?\n\n2. The fact that early Adventist pioneers wrestled with the Trinity and eventually embraced it through deeper study is part of the church's story. What does this process teach you about doctrinal growth and honesty?\n\n3. How does recognizing the Holy Spirit as a divine Person — not an impersonal force — change the way you pray, worship, and seek guidance?",
    sortOrder: 5,
  },
  {
    id: "w1s-2-4-6",
    lessonId: "w1l-2-4",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of common misunderstandings and challenges regarding the Trinity.",
    sortOrder: 6,
  },
];

export const belief2Assessments = [
  {
    id: "w1a-2-2",
    lessonId: "w1l-2-2",
    title: "Doctrinal Formulation Assessment — Trinity",
    passingScore: 70,
  },
  {
    id: "w1a-2-3",
    lessonId: "w1l-2-3",
    title: "Practical Implications Assessment — Trinity",
    passingScore: 70,
  },
  {
    id: "w1a-2-4",
    lessonId: "w1l-2-4",
    title: "Misunderstandings & Challenges Assessment — Trinity",
    passingScore: 70,
  },
];

export const belief2Items = [
  {
    id: "w1i-2-2-1",
    assessmentId: "w1a-2-2",
    question: "In 2 Corinthians 13:14, Paul names three divine Persons. What does each contribute to the believer's experience?",
    options: ["Power, wisdom, and beauty", "Grace (Christ), love (God/Father), and communion (Holy Spirit)", "Creation, judgment, and destruction", "Knowledge, faith, and hope"],
    correctIndex: 1,
    explanation: "Paul's benediction assigns grace to the Lord Jesus Christ, love to God (the Father), and communion (fellowship) to the Holy Spirit — three distinct Persons contributing uniquely to the believer's life.",
  },
  {
    id: "w1i-2-2-2",
    assessmentId: "w1a-2-2",
    question: "According to 1 Peter 1:2, what role does each Person of the Trinity play in salvation?",
    options: ["The Father creates, the Son destroys, the Spirit rebuilds", "The Father foreknows, the Spirit sanctifies, and Christ atones through His blood", "The Father judges, the Son intercedes, the Spirit observes", "All three perform identical functions without distinction"],
    correctIndex: 1,
    explanation: "Peter identifies the Father's foreknowledge (initiating), the Spirit's sanctification (transforming), and the sprinkling of Christ's blood (atoning) — three distinct roles within one unified plan of redemption.",
  },
  {
    id: "w1i-2-2-3",
    assessmentId: "w1a-2-2",
    question: "How did early Adventists arrive at their trinitarian position?",
    options: ["They adopted the Nicene Creed without examination", "They inherited it directly from the Protestant Reformation", "They arrived at it through decades of independent Bible study", "They were pressured by other denominations to conform"],
    correctIndex: 2,
    explanation: "Early Adventist pioneers included non-trinitarians. Through sustained Scripture study and the influence of Ellen G. White's writings, the movement arrived at a trinitarian conviction based on biblical evidence rather than creedal inheritance.",
  },
  {
    id: "w1i-2-2-4",
    assessmentId: "w1a-2-2",
    question: "A new Bible study group member says, 'The Trinity is just a human invention — the word doesn't even appear in the Bible.' How would you respond based on the Adventist approach?",
    options: ["Agree that the doctrine is unbiblical since the word is absent", "Explain that while the word is absent, the reality of three divine Persons is woven throughout the New Testament witness", "Admit it was invented at the Council of Nicaea", "Suggest the doctrine is unimportant"],
    correctIndex: 1,
    explanation: "Many biblical concepts are described without a single-word label (e.g., 'incarnation'). The trinitarian pattern — three Persons, one God — appears in baptismal formulas, apostolic benedictions, and salvation descriptions throughout the New Testament.",
  },
  {
    id: "w1i-2-2-5",
    assessmentId: "w1a-2-2",
    question: "Ephesians 4:4-6 names one Spirit, one Lord, and one God and Father. What does the repetition of 'one' in this passage emphasize?",
    options: ["That only the Father is truly God", "That the three Persons are united in one divine reality, not three separate deities", "That Christians should have only one spiritual gift", "That denominations should merge into a single organization"],
    correctIndex: 1,
    explanation: "Paul's sevenfold use of 'one' in Ephesians 4:4-6 stresses the unity of the Godhead. Three Persons are named — Spirit, Lord (Jesus), and Father — yet the overall emphasis is on the single divine reality they share.",
  },

  {
    id: "w1i-2-3-1",
    assessmentId: "w1a-2-3",
    question: "In John 17:20-23, what standard does Jesus set for the unity of His followers?",
    options: ["Organizational uniformity", "The unity shared between the Father and the Son", "Agreement on every doctrinal detail", "Political solidarity"],
    correctIndex: 1,
    explanation: "Jesus prays that believers 'may be one, as You, Father, are in Me, and I in You.' The model for Christian unity is the intimate, self-giving relationship within the Godhead — relational oneness, not mere organizational uniformity.",
  },
  {
    id: "w1i-2-3-2",
    assessmentId: "w1a-2-3",
    question: "According to 1 John 1:3, what is the foundation of genuine Christian fellowship?",
    options: ["Shared hobbies and cultural background", "Fellowship with the Father and His Son Jesus Christ", "Membership in the same local church", "Agreement on political issues"],
    correctIndex: 1,
    explanation: "John declares that human fellowship flows from divine fellowship — 'our fellowship is with the Father and with His Son Jesus Christ.' Vertical communion with God produces authentic horizontal community among believers.",
  },
  {
    id: "w1i-2-3-3",
    assessmentId: "w1a-2-3",
    question: "In Romans 8:14-17, what does the Spirit enable believers to call God?",
    options: ["Master", "Judge", "Abba, Father", "The Almighty"],
    correctIndex: 2,
    explanation: "The Spirit of adoption enables believers to cry 'Abba, Father' — the intimate Aramaic term a child would use. This reflects the relational nature of the Triune God, who draws redeemed humanity into His own family.",
  },
  {
    id: "w1i-2-3-4",
    assessmentId: "w1a-2-3",
    question: "A church is divided along cultural lines, with different language groups refusing to collaborate on ministry projects. How does John 17:20-23 speak to this situation?",
    options: ["Cultural separation is acceptable as long as each group worships sincerely", "Jesus' prayer for oneness 'as We are one' challenges every barrier that fragments the body of Christ", "Unity is a future hope, not a present expectation", "Each group should form its own denomination"],
    correctIndex: 1,
    explanation: "Jesus' prayer envisions a unity that mirrors the Godhead's own oneness — diverse Persons in perfect harmony. Cultural diversity is a gift, but division that prevents collaboration contradicts the trinitarian model of community.",
  },
  {
    id: "w1i-2-3-5",
    assessmentId: "w1a-2-3",
    question: "Why does Paul describe spiritual gifts in 1 Corinthians 12:4-6 using trinitarian language (same Spirit, same Lord, same God)?",
    options: ["To show that only specially gifted people matter", "To demonstrate that the diversity of gifts mirrors the diversity of Persons within the one Godhead", "To limit spiritual gifts to three categories", "To argue that gifts have replaced the Trinity"],
    correctIndex: 1,
    explanation: "Paul structures his teaching on gifts around the three Persons — diversities of gifts (Spirit), ministries (Lord/Son), and activities (God/Father). The diversity within the church reflects the diverse-yet-unified nature of the Triune God.",
  },

  {
    id: "w1i-2-4-1",
    assessmentId: "w1a-2-4",
    question: "What error does modalism commit regarding the Trinity?",
    options: ["It denies that God exists", "It collapses three distinct Persons into one Person who appears in three different modes", "It adds a fourth Person to the Godhead", "It claims the Trinity is a mathematical equation"],
    correctIndex: 1,
    explanation: "Modalism teaches that God is one Person who shows up as Father, then Son, then Spirit — like an actor changing masks. This contradicts passages like Jesus' baptism (Matthew 3:16-17), where all three Persons appear simultaneously.",
  },
  {
    id: "w1i-2-4-2",
    assessmentId: "w1a-2-4",
    question: "In Acts 5:3-4, Peter equates lying to the Holy Spirit with lying to whom?",
    options: ["The apostles", "The church", "God", "Satan"],
    correctIndex: 2,
    explanation: "Peter tells Ananias he lied 'to the Holy Spirit' (v. 3) and then states 'You have not lied to men but to God' (v. 4). The direct equation confirms the full deity of the Holy Spirit.",
  },
  {
    id: "w1i-2-4-3",
    assessmentId: "w1a-2-4",
    question: "Which title does Isaiah 44:6 apply to the LORD that Revelation later applies to Jesus, supporting the shared divine nature of Father and Son?",
    options: ["King of Kings", "The First and the Last", "Lion of Judah", "Prince of Peace"],
    correctIndex: 1,
    explanation: "Isaiah 44:6 declares the LORD is 'the First and the Last.' Revelation 1:17 and 22:13 apply this same title to Jesus Christ — demonstrating that Father and Son share the same unique divine identity.",
  },
  {
    id: "w1i-2-4-4",
    assessmentId: "w1a-2-4",
    question: "Someone argues that the Holy Spirit cannot be a Person because the Spirit is described as being 'poured out' (Acts 2:17). How would you respond?",
    options: ["Agree that the Spirit is merely a force like electricity", "Point out that the Bible also describes the Spirit speaking, teaching, grieving, and making decisions — actions that require personhood", "Concede that metaphorical language cancels the Spirit's personhood", "Suggest the passage is not reliable"],
    correctIndex: 1,
    explanation: "Metaphorical language ('poured out') does not cancel the Spirit's personhood any more than Jesus being called the 'Lamb' cancels His humanity. The Spirit speaks (Acts 13:2), teaches (John 14:26), grieves (Ephesians 4:30), and is lied to (Acts 5:3) — all marks of personhood.",
  },
  {
    id: "w1i-2-4-5",
    assessmentId: "w1a-2-4",
    question: "In John 10:30, Jesus says 'I and My Father are one.' What does the Greek neuter form of 'one' (hen) indicate?",
    options: ["That Jesus and the Father are the same Person", "That they are one in essence and nature, not one Person", "That their agreement is temporary", "That 'one' is a mistranslation"],
    correctIndex: 1,
    explanation: "The neuter hen means 'one thing' — one in essence, nature, and purpose — rather than the masculine heis, which would mean 'one person.' Jesus and the Father are distinct Persons who share one divine nature.",
  },
];
