export const belief9Lessons = [
  {
    id: "w2l-9-1",
    moduleId: "bmod-009",
    title: "Biblical Foundations: The Life and Death of Christ",
    description: "Tracing the prophetic portrait of the Suffering Servant through Isaiah, John, and Peter — and discovering why the cross was not an accident but the eternal plan of God.",
    lessonOrder: 1,
    anchorText: "Isaiah 53:3-7; John 3:16; 1 Peter 2:21-22",
    anchorBookId: 23,
    anchorChapter: 53,
    anchorVerseStart: 3,
    anchorVerseEnd: 7,
    estimatedMinutes: 35,
  },
  {
    id: "w2l-9-2",
    moduleId: "bmod-009",
    title: "Doctrinal Formulation: Atonement and Resurrection",
    description: "Understanding the Adventist affirmation of substitutionary atonement, the bodily resurrection, and Christ's ongoing priestly ministry as inseparable dimensions of salvation.",
    lessonOrder: 2,
    anchorText: "Romans 3:25-26; 1 Corinthians 15:3-4,20-22; 2 Corinthians 5:19-21",
    anchorBookId: 45,
    anchorChapter: 3,
    anchorVerseStart: 25,
    anchorVerseEnd: 26,
    estimatedMinutes: 30,
  },
  {
    id: "w2l-9-3",
    moduleId: "bmod-009",
    title: "Practical Implications: Living in the Shadow of the Cross",
    description: "Moving from doctrinal conviction to transformed living — how the cross reshapes identity, motivation, and daily conduct for the believer.",
    lessonOrder: 3,
    anchorText: "Galatians 2:20; 2 Corinthians 5:14-15; Philippians 3:10-11",
    anchorBookId: 48,
    anchorChapter: 2,
    anchorVerseStart: 20,
    anchorVerseEnd: 20,
    estimatedMinutes: 30,
  },
  {
    id: "w2l-9-4",
    moduleId: "bmod-009",
    title: "Misunderstandings & Challenges",
    description: "Addressing common distortions of the atonement — from purely legal models that ignore love, to universalism that ignores justice — and recovering a balanced, biblical view.",
    lessonOrder: 4,
    anchorText: "Hebrews 2:9; 1 John 2:2; Colossians 2:15",
    anchorBookId: 58,
    anchorChapter: 2,
    anchorVerseStart: 9,
    anchorVerseEnd: 9,
    estimatedMinutes: 30,
  },
];

export const belief9Sections = [
  {
    id: "w2s-9-1-1",
    lessonId: "w2l-9-1",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"He is despised and rejected by men, a Man of sorrows and acquainted with grief. And we hid, as it were, our faces from Him; He was despised, and we did not esteem Him. Surely He has borne our griefs and carried our sorrows; yet we esteemed Him stricken, smitten by God, and afflicted. But He was wounded for our transgressions, He was bruised for our iniquities; the chastisement for our peace was upon Him, and by His stripes we are healed. All we like sheep have gone astray; we have turned, every one, to his own way; and the LORD has laid on Him the iniquity of us all. He was oppressed and He was afflicted, yet He opened not His mouth; He was led as a lamb to the slaughter, and as a sheep before its shearers is silent, so He opened not His mouth.\" — Isaiah 53:3-7 (NKJV)\n\n\"For God so loved the world that He gave His only begotten Son, that whoever believes in Him should not perish but have everlasting life.\" — John 3:16 (NKJV)\n\n\"For to this you were called, because Christ also suffered for us, leaving us an example, that you should follow His steps: 'Who committed no sin, nor was deceit found in His mouth.'\" — 1 Peter 2:21-22 (NKJV)",
    sortOrder: 1,
  },
  {
    id: "w2s-9-1-2",
    lessonId: "w2l-9-1",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Isaiah 53 stands as the most detailed messianic prophecy in the Hebrew Scriptures, written roughly seven centuries before the events it describes. The passage introduces a figure who defies every expectation of power and triumph — a Man of sorrows, despised, rejected, and silent before His accusers. The language is deliberately shocking: the Servant does not suffer for His own failures but bears the griefs, sorrows, and iniquities of others. The Hebrew verb nasa (\"borne\") and sabal (\"carried\") convey the image of someone lifting a crushing weight onto His own shoulders. Isaiah insists that the suffering is substitutionary — \"wounded for our transgressions, bruised for our iniquities\" — and that the result is healing and peace for those whose sins He carries.\n\nJohn 3:16 compresses the entire gospel into a single sentence. Four elements define its structure: the motive (God's love), the cost (His only Son), the condition (belief), and the result (everlasting life rather than perishing). The verb \"gave\" (edoken) does not merely mean \"sent\" — it carries the weight of sacrifice, anticipating the cross. God did not dispatch an ambassador; He surrendered what was most precious to Him. The scope is universal — \"the world\" — while the appropriation is personal — \"whoever believes.\"\n\nPeter's testimony in 1 Peter 2:21-22 adds a dimension often overlooked: Christ's sinless life is not merely a theological prerequisite for a valid sacrifice but a lived example for His followers. The word hypogrammon (\"example\") literally refers to a writing template placed under a sheet so a student can trace the letters. Christ's obedience under pressure — suffering without retaliation, enduring injustice without deceit — becomes the pattern believers are called to follow. His life and His death belong together; you cannot separate the sacrifice from the character of the One who made it.\n\nThese three passages converge on a single reality: the life and death of Jesus Christ constitute God's definitive answer to the problem of human sin. The cross was not an emergency measure or a tragic accident — it was the unfolding of a plan rooted in the eternal love of God.",
    sortOrder: 2,
  },
  {
    id: "w2s-9-1-3",
    lessonId: "w2l-9-1",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "The Adventist understanding of Christ's life and death is shaped by the Great Controversy framework, which places Calvary at the center of a cosmic drama far larger than individual forgiveness alone.\n\n**The cross as vindication of God's character.** In the Great Controversy, Satan's primary accusation is that God's law is arbitrary and His government unjust. The cross answers both charges simultaneously. By bearing the penalty of a broken law in the sinner's place, God demonstrated that His law is so sacred it cannot simply be set aside — yet His love is so deep that He would rather absorb the penalty Himself than abandon the lawbreaker. Calvary reveals a God who is both just and the justifier of the one who has faith in Jesus (Romans 3:26).\n\n**Christ's sinless life as essential to atonement.** Adventists emphasize that Christ's perfect obedience throughout His earthly life was not incidental to His saving work. His righteous character is the positive righteousness credited to the believer — what theologians call \"active obedience.\" The sacrifice on the cross would have had no atoning value if the Lamb had been blemished. Peter's insistence that Christ \"committed no sin\" (1 Peter 2:22) echoes the Old Testament requirement of an unblemished sacrificial animal, fulfilled now in the person of the Son of God.\n\n**Isaiah 53 and the sanctuary.** The Adventist sanctuary doctrine connects Isaiah's Suffering Servant directly to the Day of Atonement imagery in Leviticus 16. The Servant who bears the iniquity of many (Isaiah 53:12) parallels the scapegoat ritual in which sin is symbolically transferred and removed. This linkage allows Adventists to see a continuous arc from Calvary to Christ's high-priestly ministry in the heavenly sanctuary — the cross initiates what the priestly intercession applies and the final judgment vindicates.\n\n**John 3:16 and the universal scope of the offer.** Adventists affirm that Christ's death was sufficient for every human being, rejecting any notion of limited atonement. The invitation is genuinely universal, though its benefits are appropriated by faith. This conviction fuels Adventist global mission — if God loved the world, the message of the cross must reach every people group.",
    sortOrder: 3,
  },
  {
    id: "w2s-9-1-4",
    lessonId: "w2l-9-1",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Engage with the reality of Christ's life and death this week through these actions:\n\n1. **Read Isaiah 53 aloud each day this week.** Read it slowly, pausing at each verse. On each reading, underline or note the word or phrase that strikes you most forcefully. By the end of the week, review your notes and write a brief paragraph about what the Spirit highlighted.\n\n2. **Memorize John 3:16 in its context.** Most believers know this verse in isolation. This week, memorize verses 14-18 together — including the bronze serpent reference and the purpose clause that follows. Share the fuller passage with someone who has only heard verse 16 alone.\n\n3. **Identify one area of suffering where Christ's example speaks.** Peter says Christ left an example for those who suffer unjustly. Reflect on a situation in your life where you face unfair treatment. Write down one specific way Christ's response under pressure could reshape your own.",
    sortOrder: 4,
  },
  {
    id: "w2s-9-1-5",
    lessonId: "w2l-9-1",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Isaiah says \"we esteemed Him stricken, smitten by God.\" The onlookers misread the cross as divine punishment of a failed prophet. In what ways might you misread God's purposes in seasons of suffering — your own or others'?\n\n2. John 3:16 says God \"gave\" His Son. What does it cost you to truly receive a gift you cannot earn or repay? How does the instinct to earn your way with God compete with the posture of receiving?\n\n3. Peter calls Christ's suffering an \"example\" (hypogrammon). Does the idea of tracing Christ's pattern under pressure feel inspiring or intimidating? What would change if you saw hardship as an opportunity to reflect His character rather than merely something to endure?",
    sortOrder: 5,
  },
  {
    id: "w2s-9-1-6",
    lessonId: "w2l-9-1",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },

  {
    id: "w2s-9-2-1",
    lessonId: "w2l-9-2",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"Whom God set forth as a propitiation by His blood, through faith, to demonstrate His righteousness, because in His forbearance God had passed over the sins that were previously committed, to demonstrate at the present time His righteousness, that He might be just and the justifier of the one who has faith in Jesus.\" — Romans 3:25-26 (NKJV)\n\n\"For I delivered to you first of all that which I also received: that Christ died for our sins according to the Scriptures, and that He was buried, and that He rose again the third day according to the Scriptures... But now Christ is risen from the dead, and has become the firstfruits of those who have fallen asleep. For since by man came death, by Man also came the resurrection of the dead. For as in Adam all die, even so in Christ all shall be made alive.\" — 1 Corinthians 15:3-4, 20-22 (NKJV)\n\n\"Now all things are of God, who has reconciled us to Himself through Jesus Christ, and has given us the ministry of reconciliation, that is, that God was in Christ reconciling the world to Himself, not imputing their trespasses to them, and has committed to us the word of reconciliation... For He made Him who knew no sin to be sin for us, that we might become the righteousness of God in Him.\" — 2 Corinthians 5:19-21 (NKJV)",
    sortOrder: 1,
  },
  {
    id: "w2s-9-2-2",
    lessonId: "w2l-9-2",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Romans 3:25-26 addresses a question that sits at the heart of every serious theology: How can God forgive sin without becoming indifferent to evil? Paul's answer is the word hilasterion — translated \"propitiation\" or \"mercy seat.\" The term deliberately echoes the kapporet, the gold cover of the Ark of the Covenant where blood was sprinkled on the Day of Atonement (Leviticus 16:14-15). God did not overlook sin; He publicly demonstrated His justice by dealing with it at the cross. The phrase \"just and the justifier\" captures the paradox: God upholds the moral order (\"just\") while simultaneously declaring guilty sinners righteous (\"justifier\") — because the penalty has been absorbed, not dismissed.\n\nPaul's summary in 1 Corinthians 15:3-4 is among the earliest Christian creeds, likely circulating within a few years of the crucifixion. Four verbs anchor the gospel: Christ died, was buried, rose, and appeared. The burial confirms the reality of His death; the appearances confirm the reality of His resurrection. Paul then extends the argument in verses 20-22 with the concept of \"firstfruits\" — the first sheaf of the harvest presented in the temple as a pledge that the full harvest was coming. Christ's resurrection is not an isolated miracle but the guarantee that all who belong to Him will follow. The Adam-Christ parallel frames the entire human story: death entered through one man's disobedience; resurrection life enters through one Man's obedience.\n\nSecond Corinthians 5:19-21 introduces the staggering exchange at the center of the gospel. God was \"in Christ\" reconciling the world — the initiative belongs entirely to God, not to the sinner. The means is substitution: He who knew no sin was \"made sin\" so that believers might become \"the righteousness of God in Him.\" This is not moral fiction; it is a real transaction grounded in Christ's representative identification with humanity. The one who never sinned bore the full consequence of sin; the ones steeped in sin receive a standing of righteousness they could never produce.\n\nTogether these passages establish three non-negotiable truths: the atonement satisfies divine justice, the resurrection validates the sacrifice, and the resulting reconciliation is God's gift from start to finish.",
    sortOrder: 2,
  },
  {
    id: "w2s-9-2-3",
    lessonId: "w2l-9-2",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "Adventist theology affirms substitutionary atonement while placing it within a broader framework than many Protestant traditions typically employ.\n\n**Propitiation and the sanctuary.** Paul's use of hilasterion in Romans 3:25 directly links the cross to the sanctuary system. Adventists see this connection as foundational: the earthly sanctuary service prefigured what Christ would accomplish in His death and continues to apply in His heavenly priesthood. The cross is the once-for-all sacrifice (Hebrews 9:28), but its benefits are mediated through Christ's ongoing intercession — a distinction that prevents reducing atonement to a single moment in time.\n\n**The resurrection and the state of the dead.** The Adam-Christ typology of 1 Corinthians 15:20-22 carries particular significance for Adventists, who understand death as an unconscious sleep rather than immediate passage to heaven or hell. Christ's resurrection as \"firstfruits\" means that the hope of believers is not a disembodied spiritual existence but a future bodily resurrection at His second coming. The dead in Christ rest until that trumpet sounds — and it is the same power that raised Jesus from the tomb that will raise them.\n\n**The great exchange and investigative judgment.** The declaration that God made Christ \"to be sin for us\" (2 Corinthians 5:21) undergirds the Adventist understanding of the pre-advent judgment. Those who have accepted Christ's substitutionary death are covered by His righteousness — not their own. The judgment reveals not whether believers are perfect but whether they are genuinely trusting in Christ's merit. The investigative judgment vindicates God's decisions about who has genuinely entered into the covenant relationship represented by the cross.\n\n**Reconciliation and mission.** Paul's statement that God has \"committed to us the word of reconciliation\" (2 Corinthians 5:19) is the theological engine behind Adventist world mission. The three angels' messages of Revelation 14 are, at their core, a call to accept God's reconciling work in Christ before the close of probation. Adventists understand themselves as bearers of a message that is both ancient — rooted in the cross — and urgent — addressed to the final generation.",
    sortOrder: 3,
  },
  {
    id: "w2s-9-2-4",
    lessonId: "w2l-9-2",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Deepen your grasp of atonement and resurrection this week:\n\n1. **Study the Day of Atonement.** Read Leviticus 16 alongside Romans 3:25-26. List every parallel you can find between the Old Testament ritual and what Paul describes Christ accomplishing at the cross. Note where the reality exceeds the shadow.\n\n2. **Write your own \"firstfruits\" confession.** Using the structure of 1 Corinthians 15:3-4, write a brief personal statement: \"Christ died for [my specific sins], He was buried, He rose again, and because He lives, I [specific hope or change in your life].\" Share it with a trusted friend or small group.\n\n3. **Practice the ministry of reconciliation.** Identify one relationship in your life marked by distance or unresolved tension. Take one concrete step this week — a conversation, a letter, an act of kindness — that reflects the reconciling initiative God took toward you.",
    sortOrder: 4,
  },
  {
    id: "w2s-9-2-5",
    lessonId: "w2l-9-2",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Paul says God is both \"just and the justifier\" of the one who has faith in Jesus. How does this dual reality shape your confidence before God — knowing that forgiveness does not come at the expense of justice?\n\n2. The resurrection is not merely a historical claim but a promise about your own future. How does the concept of Christ as \"firstfruits\" affect the way you think about death — your own and that of people you have lost?\n\n3. Second Corinthians 5:21 describes a staggering exchange: Christ received your sin; you received His righteousness. When you stand before God in prayer, which identity do you tend to present — your sinfulness or His righteousness? What would shift if you consistently approached God clothed in what Christ has given you?",
    sortOrder: 5,
  },
  {
    id: "w2s-9-2-6",
    lessonId: "w2l-9-2",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },

  {
    id: "w2s-9-3-1",
    lessonId: "w2l-9-3",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"I have been crucified with Christ; it is no longer I who live, but Christ lives in me; and the life which I now live in the flesh I live by faith in the Son of God, who loved me and gave Himself for me.\" — Galatians 2:20 (NKJV)\n\n\"For the love of Christ compels us, because we judge thus: that if One died for all, then all died; and He died for all, that those who live should live no longer for themselves, but for Him who died for them and rose again.\" — 2 Corinthians 5:14-15 (NKJV)\n\n\"That I may know Him and the power of His resurrection, and the fellowship of His sufferings, being conformed to His death, if, by any means, I may attain to the resurrection from the dead.\" — Philippians 3:10-11 (NKJV)",
    sortOrder: 1,
  },
  {
    id: "w2s-9-3-2",
    lessonId: "w2l-9-3",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Galatians 2:20 is Paul's most compressed autobiography. The phrase \"I have been crucified with Christ\" is not metaphor for self-improvement — it describes a real spiritual event with ongoing consequences. The Greek perfect tense (synestaurōmai) indicates a completed action with continuing results: Paul's old identity was put to death at the cross and remains dead. What lives now is not a reformed version of the old Paul but Christ Himself dwelling within. The qualifying phrase \"by faith in the Son of God, who loved me and gave Himself for me\" anchors this mystical-sounding language in historical reality. The cross is personal — \"loved me\" — and costly — \"gave Himself for me.\"\n\nPaul's logic in 2 Corinthians 5:14-15 follows a tight chain: Christ's love compels (synechei — \"grips\" or \"constrains\") the believer. The reasoning runs: if One died for all, then all died representatively in Him. The purpose of that representative death is not merely forgiveness but a total reorientation of life. Those who have been included in Christ's death no longer live \"for themselves\" but \"for Him who died for them and rose again.\" Self-centered existence has been replaced by Christ-centered purpose. The resurrection is essential to this logic — Christ did not simply die; He rose, and His risen life becomes the new center of gravity for the believer.\n\nPhilippians 3:10-11 reveals Paul's deepest aspiration, and it is striking for what it includes: not only the power of Christ's resurrection but the fellowship of His sufferings and conformity to His death. Paul does not separate glory from suffering. He desires an intimate, participatory knowledge of Christ (gnōnai — relational knowing, not abstract information) that embraces the full arc of Christ's experience. The phrase \"if, by any means\" is not doubt but intense longing — Paul is willing to take any path that leads to resurrection life, even if that path runs through suffering.\n\nThese three texts together define the shape of a cross-formed life: death to self (Galatians 2:20), reorientation of purpose (2 Corinthians 5:14-15), and willingness to share in Christ's sufferings (Philippians 3:10-11).",
    sortOrder: 2,
  },
  {
    id: "w2s-9-3-3",
    lessonId: "w2l-9-3",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "The Adventist tradition has always insisted that the gospel is not merely a transaction to be believed but a reality to be lived. These passages illuminate several practical distinctives.\n\n**Sanctification as participation in Christ's death and life.** Adventist theology distinguishes between justification (a declared status) and sanctification (a transforming process), but insists they are inseparable. Paul's \"I have been crucified with Christ\" describes the believer's entry into a new existence where the power of sin is broken. Sanctification is not self-generated moral effort; it is the daily outworking of a death that has already occurred and a life that is already indwelling. This understanding prevents both legalism (trying to earn what Christ freely gives) and cheap grace (accepting pardon while resisting transformation).\n\n**The cross and health reform.** Paul says those who have died with Christ \"no longer live for themselves.\" Adventists apply this principle holistically. If the body is the temple of the Holy Spirit and the believer's life belongs to Christ, then stewardship of health — diet, rest, exercise, temperance — is not legalistic addition to the gospel but a natural consequence of belonging to the One who died and rose. The health message flows from the cross, not from cultural preference.\n\n**Suffering and the Great Controversy.** Paul's desire to share in Christ's sufferings (Philippians 3:10) resonates with the Adventist understanding that the final generation will face intensified opposition. In the Great Controversy framework, suffering is neither meaningless nor punitive — it is the cost of loyalty in a contested universe. Believers who endure faithfully demonstrate before the watching universe that God's character is worth trusting even when the cost is high. This is not masochism; it is the same willingness that took Christ to the cross.\n\n**Mission as living \"for Him.\"** Paul's declaration that the redeemed live \"no longer for themselves but for Him\" (2 Corinthians 5:15) is the heartbeat of Adventist mission. The three angels' messages are not merely doctrines to broadcast but the overflow of lives that have been captured by Christ's love. The compulsion to share is not guilt but gratitude — the same love that constrained Paul constrains those who have genuinely encountered the risen Christ.",
    sortOrder: 3,
  },
  {
    id: "w2s-9-3-4",
    lessonId: "w2l-9-3",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Let the cross reshape your daily rhythms this week:\n\n1. **Morning surrender prayer.** Each morning, before checking your phone or starting your routine, pray Galatians 2:20 back to God in your own words: \"The old me has been crucified. Today, let Christ live through me. I receive this day by faith in the One who loved me and gave Himself for me.\" Note how this posture affects your first decisions of the day.\n\n2. **Audit your \"for whom.\"** At the end of each day this week, review your major decisions and ask: \"Did I make this choice for myself or for Christ?\" This is not about guilt but awareness. Record one decision each day that you would make differently if you were fully living \"for Him who died and rose.\"\n\n3. **Embrace a voluntary discomfort.** Paul sought the fellowship of Christ's sufferings. This week, choose one small act of self-denial or service that costs you something — time, comfort, or reputation. Reflect on what that experience teaches you about the shape of a crucified life.",
    sortOrder: 4,
  },
  {
    id: "w2s-9-3-5",
    lessonId: "w2l-9-3",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Paul says \"it is no longer I who live, but Christ lives in me.\" What parts of your old identity are most resistant to being crucified? Where do you find yourself reclaiming territory that belongs to Christ?\n\n2. The love of Christ \"compels\" — the Greek suggests being pressed in from all sides, like water in a narrow channel. Have you experienced a moment when Christ's love left you no option but to act? What did that feel like, and what resulted?\n\n3. Paul desires to know not only the power of the resurrection but the fellowship of Christ's sufferings. Most believers eagerly pursue power but instinctively avoid suffering. How does Paul's integrated vision challenge your own spiritual aspirations?",
    sortOrder: 5,
  },
  {
    id: "w2s-9-3-6",
    lessonId: "w2l-9-3",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },

  {
    id: "w2s-9-4-1",
    lessonId: "w2l-9-4",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"But we see Jesus, who was made a little lower than the angels, for the suffering of death crowned with glory and honor, that He, by the grace of God, might taste death for everyone.\" — Hebrews 2:9 (NKJV)\n\n\"And He Himself is the propitiation for our sins, and not for ours only but also for the whole world.\" — 1 John 2:2 (NKJV)\n\n\"Having disarmed principalities and powers, He made a public spectacle of them, triumphing over them in it.\" — Colossians 2:15 (NKJV)",
    sortOrder: 1,
  },
  {
    id: "w2s-9-4-2",
    lessonId: "w2l-9-4",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Hebrews 2:9 confronts a scandal that troubled the early church and still unsettles thoughtful readers: the Creator of the universe was \"made a little lower than the angels\" and subjected to death. The author of Hebrews does not soften this — he names the suffering, the death, and the temporary humiliation. But the purpose clause transforms the scandal into gospel: \"that He, by the grace of God, might taste death for everyone.\" The verb \"taste\" (geusetai) does not mean a superficial sip; in Greek usage it means to fully experience. Christ did not merely approach death — He entered it completely, drained its cup, and emerged on the other side \"crowned with glory and honor.\" The scope is universal: \"for everyone.\"\n\nFirst John 2:2 reinforces this universal scope with blunt clarity. Christ is the propitiation — the satisfaction of divine justice — not only for the sins of believers (\"our sins\") but \"for the whole world.\" This verse has been a battleground between those who affirm limited atonement (Christ died only for the elect) and those who affirm unlimited atonement (Christ died sufficiently for all). The plain language of John's statement resists restriction: the provision is genuinely worldwide, even though its application depends on faith.\n\nColossians 2:15 shifts the lens from the legal to the martial. The cross was not only a payment for sin but a decisive military victory. Paul pictures a Roman triumph — a conquering general parading defeated enemies through the streets. At Calvary, the principalities and powers that held humanity captive were \"disarmed\" (apekdysamenos — stripped of weapons and authority) and \"made a public spectacle.\" What appeared to the watching world as the defeat of Christ was, in reality, the defeat of the powers arrayed against Him.\n\nThree misunderstandings commonly arise from these themes: (1) that the atonement is limited in scope, (2) that the cross was primarily about God's anger rather than His love, and (3) that Satan retains real power over those who belong to Christ. Each of these distortions is corrected by careful attention to these texts.",
    sortOrder: 2,
  },
  {
    id: "w2s-9-4-3",
    lessonId: "w2l-9-4",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "Several common misunderstandings about the cross find correction within the Adventist theological framework.\n\n**Against limited atonement.** Adventists stand firmly with the biblical witness that Christ died for every human being without exception. First John 2:2 and Hebrews 2:9 leave no room for a secret decree that excludes some from the offer of salvation. The Adventist emphasis on the investigative judgment presupposes that Christ's sacrifice is sufficient for all — the question the judgment resolves is not whether Christ died for a person, but whether that person has responded in faith.\n\n**Against a purely penal model divorced from love.** Some presentations of the atonement reduce the cross to a cold legal transaction: God was angry, someone had to pay, and Jesus stepped in to absorb the punishment. While substitutionary atonement is biblically grounded, Adventists insist that the cross reveals the character of God, not merely the demands of law. Hebrews 2:9 says Christ tasted death \"by the grace of God\" — the cross is an act of grace, not of reluctant legal necessity. The Great Controversy framework underscores that God's purpose at Calvary was not to satisfy a bloodthirsty justice system but to demonstrate that love and justice are not in conflict — they meet perfectly in Christ.\n\n**Against the claim that Satan retains sovereignty.** Colossians 2:15 declares that the powers of darkness have been publicly disarmed. Adventists take this seriously while recognizing that the war continues until the second advent. The analogy is often drawn to the period between D-Day and V-Day in World War II: the decisive battle has been won, but the enemy continues to fight with diminishing power. Believers are not helpless victims awaiting an uncertain outcome — they fight from a position of victory already secured at the cross.\n\n**Against universalism.** While Adventists affirm the universal sufficiency of the atonement, they do not affirm universal salvation. The provision is for \"the whole world\" (1 John 2:2), but the application requires personal faith and ongoing relationship with Christ. The three angels' messages of Revelation 14 call every person to respond — precisely because the offer is genuine and the consequences of refusal are real.",
    sortOrder: 3,
  },
  {
    id: "w2s-9-4-4",
    lessonId: "w2l-9-4",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Correct misunderstandings and deepen conviction this week:\n\n1. **Confront a distorted image of God.** Write down, honestly, the first image that comes to mind when you think of God at the cross. Is He angry? Distant? Grieving? Triumphant? Compare your instinctive picture with Hebrews 2:9 (\"by the grace of God\") and John 3:16 (\"God so loved\"). If your image needs correction, write a new description of God at Calvary grounded in Scripture.\n\n2. **Pray Colossians 2:15 over a specific struggle.** Name one area of your life where you feel defeated or oppressed — an addiction, a fear, a recurring sin pattern. Read Colossians 2:15 aloud and pray: \"Lord, You have disarmed the powers. I claim the victory You won at the cross over this specific area.\" Repeat daily this week.\n\n3. **Share the universal scope.** This week, tell one person — a friend, a coworker, a family member — that Christ died for them personally. Not as a sermon but as a genuine, heartfelt statement rooted in 1 John 2:2.",
    sortOrder: 4,
  },
  {
    id: "w2s-9-4-5",
    lessonId: "w2l-9-4",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Hebrews says Jesus \"tasted death for everyone.\" How does the universality of Christ's sacrifice affect the way you view people you find difficult to love — or people the world considers beyond redemption?\n\n2. Colossians 2:15 pictures the cross as a military triumph. In what area of your life have you been living as though the enemy has not yet been defeated? What would change if you believed that victory has already been won?\n\n3. Some believers carry an image of God as perpetually angry, requiring blood to be appeased. Others picture a God so permissive that sin carries no real consequence. How do Hebrews 2:9 and Romans 3:25-26 together paint a more complete picture — and where does your own understanding need rebalancing?",
    sortOrder: 5,
  },
  {
    id: "w2s-9-4-6",
    lessonId: "w2l-9-4",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },
];

export const belief9Assessments = [
  {
    id: "w2a-9-1",
    lessonId: "w2l-9-1",
    title: "Biblical Foundations Assessment — Life and Death of Christ",
    passingScore: 70,
  },
  {
    id: "w2a-9-2",
    lessonId: "w2l-9-2",
    title: "Doctrinal Formulation Assessment — Atonement and Resurrection",
    passingScore: 70,
  },
  {
    id: "w2a-9-3",
    lessonId: "w2l-9-3",
    title: "Practical Implications Assessment — Living in the Shadow of the Cross",
    passingScore: 70,
  },
  {
    id: "w2a-9-4",
    lessonId: "w2l-9-4",
    title: "Misunderstandings & Challenges Assessment — Life, Death, and Resurrection of Christ",
    passingScore: 70,
  },
];

export const belief9Items = [
  {
    id: "w2i-9-1-1",
    assessmentId: "w2a-9-1",
    question: "In Isaiah 53:4-5, the Hebrew verbs 'nasa' and 'sabal' convey what image about the Servant's suffering?",
    options: ["He observed suffering from a distance", "He lifted and carried a crushing weight on behalf of others", "He delegated the burden to angelic beings", "He symbolically enacted a ritual drama"],
    correctIndex: 1,
    explanation: "Nasa ('borne') and sabal ('carried') picture someone lifting a heavy load onto their own shoulders. Isaiah insists the Servant's suffering was substitutionary — He bore what belonged to others.",
  },
  {
    id: "w2i-9-1-2",
    assessmentId: "w2a-9-1",
    question: "What does the verb 'gave' (edoken) in John 3:16 emphasize about God's action?",
    options: ["God loaned His Son temporarily", "God sacrificed what was most precious to Him", "God reluctantly complied with heavenly law", "God replaced His Son with a human substitute"],
    correctIndex: 1,
    explanation: "Edoken carries the weight of sacrifice, not merely sending. God did not dispatch an ambassador — He surrendered His only Son, anticipating the full cost of Calvary.",
  },
  {
    id: "w2i-9-1-3",
    assessmentId: "w2a-9-1",
    question: "According to 1 Peter 2:21-22, Christ's sinless life serves what purpose for believers?",
    options: ["It proves His divinity beyond doubt", "It provides a pattern (hypogrammon) for believers to follow under suffering", "It exempted Him from experiencing real temptation", "It was relevant only to first-century Jewish believers"],
    correctIndex: 1,
    explanation: "Peter uses hypogrammon — a writing template placed under a sheet for tracing. Christ's obedient life under pressure becomes the pattern believers trace in their own conduct.",
  },
  {
    id: "w2i-9-1-4",
    assessmentId: "w2a-9-1",
    question: "A friend says the cross was an improvised rescue plan after humanity fell. How do these passages respond?",
    options: ["They confirm that God had no plan until sin entered", "They show the cross was rooted in God's eternal purpose and prophesied centuries in advance", "They suggest the cross was one of several possible solutions", "They indicate the plan was devised by angels and approved by God later"],
    correctIndex: 1,
    explanation: "Isaiah 53 prophesied the Suffering Servant roughly 700 years before Christ. John 3:16 presents God's gift of His Son as flowing from eternal love, not emergency response. The cross was planned before the foundation of the world.",
  },
  {
    id: "w2i-9-1-5",
    assessmentId: "w2a-9-1",
    question: "Why do Adventists connect Isaiah 53 with the sanctuary service in Leviticus 16?",
    options: ["Because both describe heavenly architecture", "Because the Servant who bears iniquity parallels the Day of Atonement ritual of sin-bearing and removal", "Because Isaiah explicitly mentions the Ark of the Covenant", "Because Leviticus 16 was written after Isaiah as commentary"],
    correctIndex: 1,
    explanation: "The Servant bearing the iniquity of many (Isaiah 53:12) parallels the scapegoat and sacrificial rituals in Leviticus 16, where sin was symbolically transferred and removed. Adventists see a continuous arc from Calvary to Christ's heavenly priesthood.",
  },

  {
    id: "w2i-9-2-1",
    assessmentId: "w2a-9-2",
    question: "What Old Testament object does the Greek word 'hilasterion' in Romans 3:25 deliberately echo?",
    options: ["The bronze serpent in the wilderness", "The mercy seat (kapporet) on the Ark of the Covenant", "The altar of incense in the Holy Place", "The table of showbread"],
    correctIndex: 1,
    explanation: "Hilasterion is the same word used in the Greek Old Testament (Septuagint) for the kapporet — the gold cover of the Ark where blood was sprinkled on the Day of Atonement. Paul connects Christ's sacrifice directly to the sanctuary system.",
  },
  {
    id: "w2i-9-2-2",
    assessmentId: "w2a-9-2",
    question: "In 1 Corinthians 15:20, what does Paul mean by calling Christ the 'firstfruits' of those who have fallen asleep?",
    options: ["Christ was the first person ever to die", "Christ's resurrection is the guarantee and pledge that all who belong to Him will also rise", "Christ rose in spirit only, not bodily", "The term refers to agricultural offerings with no theological meaning"],
    correctIndex: 1,
    explanation: "Firstfruits was the first sheaf of harvest presented in the temple as a pledge that the full harvest was coming. Christ's bodily resurrection guarantees the future resurrection of all believers.",
  },
  {
    id: "w2i-9-2-3",
    assessmentId: "w2a-9-2",
    question: "What does 2 Corinthians 5:21 describe as the 'great exchange' of the gospel?",
    options: ["Believers exchange earthly wealth for heavenly treasure", "Christ who knew no sin was made sin, so believers might become the righteousness of God", "God exchanged the Old Covenant law for a New Covenant law", "Angels exchanged places with humans in the heavenly court"],
    correctIndex: 1,
    explanation: "The great exchange is substitutionary: the sinless Christ bore the full consequence of sin so that sinners could receive a standing of righteousness they could never produce on their own.",
  },
  {
    id: "w2i-9-2-4",
    assessmentId: "w2a-9-2",
    question: "A study group member claims that Christ's death was sufficient but His resurrection is theologically optional. How does Paul respond in 1 Corinthians 15?",
    options: ["Paul agrees that the resurrection is a secondary matter", "Paul argues that without the resurrection, faith is futile and believers are still in their sins", "Paul says the resurrection is important only as a symbol of spiritual renewal", "Paul treats the resurrection as relevant only to Jewish believers"],
    correctIndex: 1,
    explanation: "In 1 Corinthians 15:17 Paul states explicitly: 'If Christ is not risen, your faith is futile; you are still in your sins.' The resurrection validates the sacrifice — without it, the cross would be a tragedy, not a triumph.",
  },
  {
    id: "w2i-9-2-5",
    assessmentId: "w2a-9-2",
    question: "How does the Adventist understanding of death as unconscious sleep relate to Christ's resurrection as 'firstfruits'?",
    options: ["It has no connection; the two doctrines are independent", "It means the dead in Christ rest unconsciously until the resurrection at Christ's second coming, guaranteed by His own rising", "It implies Christ also slept unconsciously for centuries before rising", "It teaches that only righteous people sleep; the wicked are immediately judged"],
    correctIndex: 1,
    explanation: "Adventists understand that the dead rest unconsciously until the second advent. Christ's resurrection as 'firstfruits' guarantees that the same power that raised Him will raise believers at His return — bodily, not as disembodied spirits.",
  },

  {
    id: "w2i-9-3-1",
    assessmentId: "w2a-9-3",
    question: "In Galatians 2:20, what does the Greek perfect tense of 'crucified' (synestaurōmai) indicate?",
    options: ["A future event that has not yet occurred", "A completed action with continuing results — the old self remains dead", "A repeated action that must be performed daily through ritual", "A hypothetical condition that depends on human effort"],
    correctIndex: 1,
    explanation: "The perfect tense in Greek describes a past action with ongoing present effects. Paul's old identity was crucified at the cross and remains in that state — it is a settled spiritual reality, not a daily re-achievement.",
  },
  {
    id: "w2i-9-3-2",
    assessmentId: "w2a-9-3",
    question: "According to 2 Corinthians 5:14-15, what is the purpose of Christ's death for all?",
    options: ["That believers would live comfortable, prosperous lives", "That those who live should no longer live for themselves but for Him who died and rose", "That human effort in salvation becomes unnecessary", "That the moral law is permanently abolished"],
    correctIndex: 1,
    explanation: "Paul's logic is clear: because Christ died for all, all died representatively in Him. The result is a complete reorientation — believers no longer live for self but for the risen Christ.",
  },
  {
    id: "w2i-9-3-3",
    assessmentId: "w2a-9-3",
    question: "What unusual combination does Paul desire in Philippians 3:10-11?",
    options: ["Wealth and influence for the sake of mission", "Both the power of Christ's resurrection and the fellowship of His sufferings", "Freedom from all earthly responsibility", "Knowledge of every biblical language"],
    correctIndex: 1,
    explanation: "Paul refuses to separate glory from suffering. He longs to know Christ fully — not only the power of His resurrection but also intimate participation in His sufferings and conformity to His death.",
  },
  {
    id: "w2i-9-3-4",
    assessmentId: "w2a-9-3",
    question: "How does the Adventist health message connect to Paul's statement that believers no longer live for themselves?",
    options: ["It does not connect; health reform is purely cultural", "If the body belongs to Christ, stewardship of health is a natural consequence of the cross, not legalistic addition", "Health reform replaces the need for spiritual disciplines", "Only ordained ministers are required to follow health principles"],
    correctIndex: 1,
    explanation: "Adventists see the health message as flowing from the gospel: if the body is the temple of the Holy Spirit and the believer's life belongs to Christ, then caring for the body is an act of grateful stewardship, not works-based religion.",
  },
  {
    id: "w2i-9-3-5",
    assessmentId: "w2a-9-3",
    question: "A new believer says, 'I accepted Jesus, so now I can live however I want — grace covers everything.' Which passage most directly corrects this misunderstanding?",
    options: ["John 3:16, because it promises eternal life", "2 Corinthians 5:14-15, because it says those who live should no longer live for themselves but for Christ", "Philippians 3:10, because Paul desires resurrection power", "Hebrews 2:9, because Christ tasted death for everyone"],
    correctIndex: 1,
    explanation: "Paul's argument in 2 Corinthians 5:14-15 insists that Christ's death was not a license for self-indulgence but a transfer of ownership. The redeemed life is lived 'for Him who died and rose,' not for the gratification of the old self.",
  },

  {
    id: "w2i-9-4-1",
    assessmentId: "w2a-9-4",
    question: "In Hebrews 2:9, what does the verb 'taste' (geusetai) mean regarding Christ's experience of death?",
    options: ["He briefly approached death without fully entering it", "He fully experienced death, draining its cup completely", "He experienced only physical death but not spiritual separation", "He tasted a symbolic death during a ritual ceremony"],
    correctIndex: 1,
    explanation: "In Greek usage, geusetai means to fully experience, not merely to sample. Christ entered death completely on behalf of every human being — the scope is universal and the experience was total.",
  },
  {
    id: "w2i-9-4-2",
    assessmentId: "w2a-9-4",
    question: "What does 1 John 2:2 affirm about the scope of Christ's propitiation?",
    options: ["It covers only those predestined before the foundation of the world", "It extends not only to believers but to the whole world", "It applies exclusively to sins committed before baptism", "It is effective only for sins of ignorance, not deliberate sins"],
    correctIndex: 1,
    explanation: "John states plainly that Christ is the propitiation 'not for ours only but also for the whole world.' The provision is genuinely universal, though its benefits are appropriated through faith.",
  },
  {
    id: "w2i-9-4-3",
    assessmentId: "w2a-9-4",
    question: "According to Colossians 2:15, what happened to the principalities and powers at the cross?",
    options: ["They were temporarily restrained but remain fully armed", "They were disarmed and made a public spectacle in Christ's triumph", "They negotiated a truce with God", "They were absorbed into the divine nature"],
    correctIndex: 1,
    explanation: "Paul pictures a Roman triumph: the conquering general parading defeated enemies through the streets. At Calvary, the hostile powers were stripped of their weapons and authority — publicly exposed and defeated.",
  },
  {
    id: "w2i-9-4-4",
    assessmentId: "w2a-9-4",
    question: "Someone argues that God is an angry deity who required blood sacrifice to be appeased. How do these passages correct this view?",
    options: ["They confirm that God's primary attribute is wrath", "They show the cross was initiated by God's grace and love — not reluctant legal compliance — while still satisfying justice", "They indicate God played no active role in the crucifixion", "They teach that blood sacrifice was an Old Testament concept abandoned in the New Testament"],
    correctIndex: 1,
    explanation: "Hebrews 2:9 says Christ tasted death 'by the grace of God,' and John 3:16 roots the entire plan in divine love. The cross satisfies justice, but the initiative springs from a God who is love — not from a deity who must be pacified against His will.",
  },
  {
    id: "w2i-9-4-5",
    assessmentId: "w2a-9-4",
    question: "How do Adventists reconcile the universal provision of atonement (1 John 2:2) with the reality that not all will be saved?",
    options: ["They teach that all people will eventually be saved regardless of response", "They affirm that the atonement is sufficient for all but effective for those who respond in faith — the offer is genuine but requires personal acceptance", "They believe God secretly withholds the offer from certain groups", "They hold that the atonement's scope is irrelevant to the question of salvation"],
    correctIndex: 1,
    explanation: "Adventists affirm unlimited atonement — Christ died sufficiently for every person — while rejecting universalism. The provision is worldwide, but its application depends on personal faith. The three angels' messages call everyone to respond precisely because the offer is genuine.",
  },
];
