export const belief11Lessons = [
  {
    id: "w2l-11-1",
    moduleId: "bmod-011",
    title: "Biblical Foundations: Victory in Christ",
    description: "Tracing the scriptural witness to Christ's decisive triumph over evil powers — from Calvary's cross to the believer's daily experience of freedom.",
    lessonOrder: 1,
    anchorText: "Colossians 2:13-15; Luke 10:17-20; Ephesians 6:10-18",
    anchorBookId: 51,
    anchorChapter: 2,
    anchorVerseStart: 13,
    anchorVerseEnd: 15,
    estimatedMinutes: 35,
  },
  {
    id: "w2l-11-2",
    moduleId: "bmod-011",
    title: "Doctrinal Formulation: Sanctification and Spiritual Growth",
    description: "Understanding what Adventists affirm about the progressive work of the Holy Spirit in shaping believers into the image of Christ after conversion.",
    lessonOrder: 2,
    anchorText: "2 Peter 3:18; 2 Corinthians 3:17-18; 1 Thessalonians 5:23-24",
    anchorBookId: 61,
    anchorChapter: 3,
    anchorVerseStart: 18,
    anchorVerseEnd: 18,
    estimatedMinutes: 30,
  },
  {
    id: "w2l-11-3",
    moduleId: "bmod-011",
    title: "Practical Implications: Spiritual Disciplines for Daily Life",
    description: "Exploring the concrete habits and practices that cultivate sustained spiritual growth — meditation on Scripture, prayer, worship, and community.",
    lessonOrder: 3,
    anchorText: "Psalm 1:1-2; Ephesians 5:15-20; Colossians 2:6-7",
    anchorBookId: 19,
    anchorChapter: 1,
    anchorVerseStart: 1,
    anchorVerseEnd: 2,
    estimatedMinutes: 30,
  },
  {
    id: "w2l-11-4",
    moduleId: "bmod-011",
    title: "Misunderstandings & Challenges",
    description: "Addressing common errors about perfectionism, the ongoing struggle with sin, and the nature of spiritual maturity in the Christian life.",
    lessonOrder: 4,
    anchorText: "Romans 7:14-25; Philippians 1:6; 1 John 1:8-10",
    anchorBookId: 45,
    anchorChapter: 7,
    anchorVerseStart: 14,
    anchorVerseEnd: 25,
    estimatedMinutes: 30,
  },
];

export const belief11Sections = [
  {
    id: "w2s-11-1-1",
    lessonId: "w2l-11-1",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"And you, being dead in your trespasses and the uncircumcision of your flesh, He has made alive together with Him, having forgiven you all trespasses, having wiped out the handwriting of requirements that was against us, which was contrary to us. And He has taken it out of the way, having nailed it to the cross. Having disarmed principalities and powers, He made a public spectacle of them, triumphing over them in it.\" — Colossians 2:13-15 (NKJV)\n\n\"Then the seventy returned with joy, saying, 'Lord, even the demons are subject to us in Your name.' And He said to them, 'I saw Satan fall like lightning from heaven. Behold, I give you the authority to trample on serpents and scorpions, and over all the power of the enemy, and nothing shall by any means hurt you. Nevertheless do not rejoice in this, that the spirits are subject to you, but rather rejoice because your names are written in heaven.'\" — Luke 10:17-20 (NKJV)\n\n\"Finally, my brethren, be strong in the Lord and in the power of His might. Put on the whole armor of God, that you may be able to stand against the wiles of the devil. For we do not wrestle against flesh and blood, but against principalities, against powers, against the rulers of the darkness of this age, against spiritual hosts of wickedness in the heavenly places.\" — Ephesians 6:10-12 (NKJV)",
    sortOrder: 1,
  },
  {
    id: "w2s-11-1-2",
    lessonId: "w2l-11-1",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Paul's language in Colossians 2:13-15 is strikingly military. The cross was not simply a place of suffering — it was a battlefield where Christ achieved a decisive, irreversible victory. The verb \"disarmed\" (apekdysamenos) carries the image of stripping a defeated enemy of weapons and armor. The principalities and powers that held humanity captive through guilt, condemnation, and the accusation of broken law were publicly humiliated at Calvary. The certificate of debt — the record of every transgression that stood against us — was nailed to the cross and cancelled. This is not a partial victory or a ceasefire; it is total conquest.\n\nLuke 10:17-20 reveals that Christ's authority over demonic forces was already operative during His earthly ministry. The seventy disciples returned astonished that demons submitted to them when they invoked Jesus' name. Jesus confirmed the reality of this power but immediately redirected their attention: the ground of their joy should not be spiritual authority but covenant relationship — \"your names are written in heaven.\" Victory over evil is real, but it flows from belonging to Christ, not from personal spiritual prowess.\n\nEphesians 6:10-18 completes the picture by addressing the believer's ongoing posture after the decisive battle has been won. Paul does not say, \"Go conquer the devil.\" He says, \"Stand.\" The victory has already been achieved at the cross; the believer's task is to hold the ground Christ has taken. The armor described — truth, righteousness, the gospel, faith, salvation, the Word, and prayer — is entirely defensive and positional. We do not fight for victory; we fight from victory.\n\nThese three passages together establish a layered biblical foundation: Christ has defeated the powers (Colossians 2), His authority over evil extends to His followers (Luke 10), and believers are called to stand firm in the victory already secured (Ephesians 6).",
    sortOrder: 2,
  },
  {
    id: "w2s-11-1-3",
    lessonId: "w2l-11-1",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "The Adventist understanding of growing in Christ is inseparable from the Great Controversy framework. Christ's victory at the cross was not merely a transaction between the Father and Son — it was a public demonstration before the watching universe that God's government is just and Satan's accusations are false. Colossians 2:15 echoes the language of a Roman triumph, where a conquering general paraded defeated enemies through the streets. At the cross, the entire cosmos witnessed the exposure of Satan's true character.\n\nThis cosmic perspective shapes how Adventists understand the believer's daily experience. The forces that oppose spiritual growth are not impersonal tendencies or psychological quirks — they are intelligent, malicious agents operating within the Great Controversy. Ephesians 6:12 names them: principalities, powers, rulers of darkness, spiritual hosts of wickedness. Adventists take this language seriously, not as primitive mythology but as sober revelation about the nature of the conflict every believer faces.\n\nAt the same time, the Adventist emphasis on Christ's completed victory guards against two opposite errors. The first is fear-driven spirituality that treats Satan as an equal adversary to God. He is not. He is a defeated foe whose doom is certain (Revelation 20:10). The second is casual presumption that ignores the real danger of spiritual warfare. Paul's urgent language — \"put on the whole armor\" — indicates that while the war is won, individual battles remain fierce.\n\nThe Adventist doctrine of the sanctuary reinforces this tension beautifully. Christ's ministry in the heavenly sanctuary applies the benefits of Calvary's victory to individual believers through intercession, cleansing, and judgment. Growing in Christ means receiving, day by day, what Christ accomplished once for all. The victory is His; the appropriation is ours through faith, prayer, and obedience empowered by the Spirit.",
    sortOrder: 3,
  },
  {
    id: "w2s-11-1-4",
    lessonId: "w2l-11-1",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Ground these truths in your daily experience this week:\n\n1. **Declare the victory.** Each morning, read Colossians 2:13-15 aloud as a declaration over your day. Before addressing any challenge, remind yourself that the powers arrayed against you have been publicly disarmed. Notice how this awareness shifts your posture from anxiety to confidence.\n\n2. **Inventory the armor.** Using Ephesians 6:14-18 as a checklist, identify which piece of spiritual armor you tend to neglect. Is it the belt of truth — honest self-examination? The shield of faith — active trust in God's promises? Choose one piece to focus on intentionally this week and journal about what changes.\n\n3. **Redirect your joy.** When you experience a spiritual victory — a temptation resisted, a habit broken, a prayer answered — follow Jesus' instruction in Luke 10:20. Instead of celebrating the result, pause and thank God that your name is written in heaven. Let your identity in Christ, not your performance, be the source of your joy.",
    sortOrder: 4,
  },
  {
    id: "w2s-11-1-5",
    lessonId: "w2l-11-1",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Paul says we fight not against flesh and blood but against spiritual powers. How does this change the way you view the struggles you face — whether with temptation, discouragement, or relational conflict?\n\n2. Jesus told the seventy to rejoice not in their authority over demons but in their standing with God. Where in your own life have you confused spiritual performance with spiritual security?\n\n3. The armor of God is described entirely in terms of standing, not attacking. What does it mean practically for you to \"stand\" in Christ's victory rather than trying to win battles in your own strength?",
    sortOrder: 5,
  },
  {
    id: "w2s-11-1-6",
    lessonId: "w2l-11-1",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },

  {
    id: "w2s-11-2-1",
    lessonId: "w2l-11-2",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"But grow in the grace and knowledge of our Lord and Savior Jesus Christ. To Him be the glory both now and forever. Amen.\" — 2 Peter 3:18 (NKJV)\n\n\"Now the Lord is the Spirit; and where the Spirit of the Lord is, there is liberty. But we all, with unveiled face, beholding as in a mirror the glory of the Lord, are being transformed into the same image from glory to glory, just as by the Spirit of the Lord.\" — 2 Corinthians 3:17-18 (NKJV)\n\n\"Now may the God of peace Himself sanctify you completely; and may your whole spirit, soul, and body be preserved blameless at the coming of our Lord Jesus Christ. He who calls you is faithful, who also will do it.\" — 1 Thessalonians 5:23-24 (NKJV)",
    sortOrder: 1,
  },
  {
    id: "w2s-11-2-2",
    lessonId: "w2l-11-2",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Peter's closing exhortation in his second epistle is deceptively simple: \"grow in grace and knowledge.\" The verb auxanete (grow) is present imperative — a command for ongoing, continuous action. Christian maturity is not a destination reached but a direction maintained. And the growth Peter describes is not self-improvement; it is growth in grace — the unmerited favor and empowering presence of God — and knowledge — a deepening personal acquaintance with Jesus Christ. These two dimensions cannot be separated. Grace without knowledge becomes vague sentiment; knowledge without grace becomes cold orthodoxy.\n\nPaul's words in 2 Corinthians 3:17-18 reveal the mechanism of transformation. The believer who gazes at the glory of the Lord — contemplating Christ's character through Scripture, prayer, and worship — is progressively changed into that same image. The phrase \"from glory to glory\" (apo doxes eis doxan) indicates incremental, stage-by-stage transformation. This is not instant perfection but a sustained metamorphosis driven by the Spirit's work. The word \"transformed\" (metamorphoumetha) is the same root from which we get \"metamorphosis\" — a fundamental change of nature, not a cosmetic adjustment.\n\n1 Thessalonians 5:23-24 adds a critical assurance. Paul prays that God Himself will sanctify believers \"completely\" — spirit, soul, and body. The comprehensive scope is significant: sanctification is not limited to inner attitudes while outward behavior remains unchanged. Every dimension of human existence is being renewed. But the ground of confidence is not human effort — it is the faithfulness of the One who calls. \"He who calls you is faithful, who also will do it.\" The work of sanctification is initiated, sustained, and completed by God.\n\nTaken together, these passages define spiritual growth as a grace-empowered, Spirit-driven, comprehensive transformation that unfolds progressively as the believer beholds Christ.",
    sortOrder: 2,
  },
  {
    id: "w2s-11-2-3",
    lessonId: "w2l-11-2",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "Adventist theology distinguishes carefully between justification and sanctification while insisting that both are works of grace received by faith. Justification is God's declaration that the repentant sinner is righteous on the basis of Christ's merit — it happens in a moment. Sanctification is God's ongoing work of making the justified believer actually righteous in character and conduct — it unfolds over a lifetime. Both are indispensable; neither replaces the other.\n\nThis distinction protects against two dangerous errors that have troubled the Christian church. The first is antinomianism — the idea that because we are justified by faith, obedience to God's law is irrelevant. The second is legalism — the belief that our obedience contributes to our justification. Adventists insist that the justified believer, indwelt by the Spirit, will progressively reflect God's character as expressed in His law — not to earn salvation but because the same grace that pardons also transforms.\n\nThe Adventist emphasis on holistic sanctification — spirit, soul, and body (1 Thessalonians 5:23) — connects directly to the church's health message, Sabbath observance, and stewardship teachings. These are not peripheral programs but expressions of a theology that takes seriously God's intention to restore the whole person. The body is not a prison to escape but a temple to honor (1 Corinthians 6:19-20). The Sabbath is not merely a day of rest but a weekly encounter with the sanctifying God (Exodus 31:13).\n\nThe phrase \"from glory to glory\" in 2 Corinthians 3:18 resonates with the Adventist understanding of progressive revelation and present truth. Just as the Spirit unfolds deeper understanding of Scripture across time, so the Spirit unfolds deeper Christlikeness within the individual believer. The process is real, measurable, and ongoing — but its completion awaits the return of Christ, when \"we shall be like Him, for we shall see Him as He is\" (1 John 3:2).",
    sortOrder: 3,
  },
  {
    id: "w2s-11-2-4",
    lessonId: "w2l-11-2",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Cultivate intentional growth this week through these actions:\n\n1. **Behold to become.** Set aside ten minutes each day to read slowly through one chapter of the Gospels. Do not study for information — read to encounter Jesus. After reading, write one sentence describing an aspect of Christ's character you observed. At the end of the week, review your sentences and ask: how is beholding Him changing me?\n\n2. **Invite the Spirit's diagnostic work.** Pray 1 Thessalonians 5:23 over yourself each evening: \"God of peace, sanctify me completely — spirit, soul, and body.\" Then ask the Spirit to show you one area where growth is needed. Do not try to fix everything at once; focus on the one thing the Spirit highlights.\n\n3. **Measure growth by direction, not distance.** Write down where you were spiritually one year ago and where you are today. Note specific areas of change — not to boast but to recognize the Spirit's quiet, persistent work. Thank God for the growth you see, and trust Him with the areas that remain.",
    sortOrder: 4,
  },
  {
    id: "w2s-11-2-5",
    lessonId: "w2l-11-2",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Peter commands believers to grow in both grace and knowledge. Which of these two dimensions do you tend to emphasize, and which do you neglect? What would more balanced growth look like in your life?\n\n2. Paul says transformation happens as we behold the Lord's glory with unveiled face. What veils — distractions, habits, unconfessed sin — currently hinder your ability to see Christ clearly?\n\n3. The assurance in 1 Thessalonians 5:24 is that God Himself will complete the work of sanctification. How does this promise affect the way you respond to your own failures and slow progress?",
    sortOrder: 5,
  },
  {
    id: "w2s-11-2-6",
    lessonId: "w2l-11-2",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },

  {
    id: "w2s-11-3-1",
    lessonId: "w2l-11-3",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"Blessed is the man who walks not in the counsel of the ungodly, nor stands in the path of sinners, nor sits in the seat of the scornful; but his delight is in the law of the LORD, and in His law he meditates day and night.\" — Psalm 1:1-2 (NKJV)\n\n\"See then that you walk circumspectly, not as fools but as wise, redeeming the time, because the days are evil. Therefore do not be unwise, but understand what the will of the Lord is. And do not be drunk with wine, in which is dissipation; but be filled with the Spirit, speaking to one another in psalms and hymns and spiritual songs, singing and making melody in your heart to the Lord, giving thanks always for all things to God the Father in the name of our Lord Jesus Christ.\" — Ephesians 5:15-20 (NKJV)\n\n\"As you therefore have received Christ Jesus the Lord, so walk in Him, rooted and built up in Him and established in the faith, as you have been taught, abounding in it with thanksgiving.\" — Colossians 2:6-7 (NKJV)",
    sortOrder: 1,
  },
  {
    id: "w2s-11-3-2",
    lessonId: "w2l-11-3",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Psalm 1 opens the entire Psalter with a portrait of the person who flourishes. The progression in verse 1 is deliberately descending: walking, standing, sitting — each posture represents a deeper entrenchment in ungodly influence. The blessed person reverses this trajectory by choosing a different source of formation: the law of the Lord, meditated upon day and night. The Hebrew word for \"meditates\" (hagah) means to murmur, to turn over repeatedly, to chew on mentally. This is not casual reading but sustained, deliberate engagement with God's Word as the primary shaping influence in life.\n\nPaul's instruction in Ephesians 5:15-20 introduces urgency. The phrase \"redeeming the time\" (exagorazomenoi ton kairon) means buying up every opportunity, treating time as a precious commodity in an environment that works against spiritual growth. The antidote to the surrounding darkness is not isolation but filling — being filled with the Spirit, which expresses itself in communal worship, mutual encouragement, and habitual gratitude. Notice that Paul does not describe private devotion alone; the Spirit-filled life overflows into relationships and corporate worship.\n\nColossians 2:6-7 provides the governing metaphor: roots and building. Paul tells believers to continue in Christ the same way they first received Him — by faith. The image of roots suggests hidden, unseen nourishment drawn from deep soil. The image of building suggests visible, structured growth that others can observe. Both are necessary. A tree with shallow roots topples in the first storm; a building without a foundation crumbles under pressure. Spiritual disciplines are the means by which roots go deeper and the structure rises higher.\n\nThese passages collectively teach that spiritual growth is not accidental. It requires intentional practices — meditation, worship, gratitude, community — sustained over time and energized by the Spirit.",
    sortOrder: 2,
  },
  {
    id: "w2s-11-3-3",
    lessonId: "w2l-11-3",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "Adventists have historically emphasized spiritual disciplines as essential infrastructure for the life of faith, not as meritorious works but as channels through which God's grace flows. Several distinctive practices reflect this conviction:\n\n**Daily personal devotion.** The Adventist tradition of morning and evening devotional time — reading Scripture, praying, reflecting — mirrors the Psalm 1 pattern of meditating on God's Word day and night. This is not legalistic routine but a deliberate act of positioning oneself to receive what God offers. The health of the Adventist movement has always correlated directly with the devotional vitality of its members.\n\n**Sabbath as spiritual discipline.** The weekly Sabbath is the most distinctive Adventist spiritual practice, and it functions as a comprehensive discipline touching every area of life. Sabbath observance interrupts the relentless momentum of work and consumption, creates space for worship and community, and anchors identity in the Creator-Redeemer God. Paul's exhortation to \"redeem the time\" (Ephesians 5:16) finds its deepest expression in the Sabbath rhythm — setting apart twenty-four hours as sacred time in an age that commodifies every moment.\n\n**Corporate worship and mutual edification.** Ephesians 5:19-20 describes Spirit-filled believers speaking to one another in psalms, hymns, and spiritual songs. Adventist worship, Sabbath School, prayer meetings, and small groups are designed to fulfill this pattern. Growth in Christ is not a solitary project; it happens in community where believers encourage, challenge, and bear one another's burdens.\n\n**Stewardship as formation.** The Adventist emphasis on tithe, health, and simplicity reflects the Colossians 2:6-7 principle of being \"rooted and built up\" in Christ. How believers manage their bodies, their finances, and their time reveals whether Christ is Lord of the whole life or merely a compartmentalized religious interest. These practices are not burdens imposed from outside but fruits of a deepening relationship with the One who gave everything.",
    sortOrder: 3,
  },
  {
    id: "w2s-11-3-4",
    lessonId: "w2l-11-3",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Build sustainable spiritual habits this week:\n\n1. **Practice hagah.** Choose one verse from Psalm 1, Ephesians 5, or Colossians 2. Write it on a card or set it as your phone's lock screen. Return to it at least three times during the day — morning, midday, evening — and turn it over in your mind. At the end of the week, notice how repeated meditation changes the way the verse speaks to you.\n\n2. **Redeem one hour.** Identify one hour this week that you would normally spend on passive consumption — scrolling, streaming, browsing — and replace it with an intentional spiritual practice: extended prayer, nature worship, serving someone in need, or reading a chapter of Scripture slowly. Record what you experience.\n\n3. **Worship with others.** If you have been attending church services as a passive observer, choose one specific way to engage actively this Sabbath — join the prayer before service, participate in Sabbath School discussion, or express gratitude to someone whose faith encourages you. Spiritual growth accelerates in community.",
    sortOrder: 4,
  },
  {
    id: "w2s-11-3-5",
    lessonId: "w2l-11-3",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Psalm 1 describes a descending progression — walking, standing, sitting — in ungodly influence. Can you identify a similar pattern in your own life where a casual exposure gradually became a settled habit? What would reversal look like?\n\n2. Paul commands believers to be filled with the Spirit rather than drunk with wine. Both produce boldness, altered perception, and social loosening — but from radically different sources. What currently fills you, and how does it shape your behavior?\n\n3. Colossians 2:6-7 says to continue in Christ the same way you first received Him — by faith. Has your spiritual life become more about effort and performance than trust? How might returning to simple faith change your daily posture?",
    sortOrder: 5,
  },
  {
    id: "w2s-11-3-6",
    lessonId: "w2l-11-3",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },

  {
    id: "w2s-11-4-1",
    lessonId: "w2l-11-4",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"For we know that the law is spiritual, but I am carnal, sold under sin. For what I am doing, I do not understand. For what I will to do, that I do not practice; but what I hate, that I do... O wretched man that I am! Who will deliver me from this body of death? I thank God — through Jesus Christ our Lord!\" — Romans 7:14-15, 24-25 (NKJV)\n\n\"Being confident of this very thing, that He who has begun a good work in you will complete it until the day of Jesus Christ.\" — Philippians 1:6 (NKJV)\n\n\"If we say that we have no sin, we deceive ourselves, and the truth is not in us. If we confess our sins, He is faithful and just to forgive us our sins and to cleanse us from all unrighteousness. If we say that we have not sinned, we make Him a liar, and His word is not in us.\" — 1 John 1:8-10 (NKJV)",
    sortOrder: 1,
  },
  {
    id: "w2s-11-4-2",
    lessonId: "w2l-11-4",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Romans 7:14-25 is one of the most debated passages in the New Testament. Whether Paul describes his pre-conversion experience, his ongoing struggle as a mature believer, or the universal human condition apart from the Spirit's empowerment, the passage exposes a painful reality: the human will, even when it desires righteousness, cannot produce it by its own power. The anguished cry \"O wretched man that I am!\" is not the voice of someone who has never met God — it is the voice of someone who knows what is right and grieves the gap between aspiration and achievement. The answer Paul gives is not a technique or a program but a Person: \"I thank God — through Jesus Christ our Lord!\"\n\nPhilippians 1:6 answers the despair of Romans 7 with unshakable assurance. The God who began the work of salvation will carry it through to completion. The verb \"complete\" (epitelesei) is a term used for finishing a construction project or fulfilling a contractual obligation. God is not a builder who abandons half-finished houses. The timeline for completion extends to \"the day of Jesus Christ\" — the second coming. This means that the process of growth continues throughout the believer's entire earthly life. Perfection of character is the trajectory, not necessarily the present achievement.\n\n1 John 1:8-10 guards against two opposite distortions. Verse 8 confronts the claim of sinlessness: anyone who says they have no sin is self-deceived. Verse 10 is even stronger — to deny having sinned makes God a liar. But between these warnings stands the promise of verse 9: confession meets a faithful and just God who forgives and cleanses. The word \"cleanses\" (katharise) is present tense, suggesting ongoing purification. The Christian life is not one of sinless perfection but of continual confession, continual forgiveness, and continual cleansing.\n\nThese three passages together address the most common misunderstandings about growing in Christ: that sanctification should eliminate all struggle (Romans 7 says otherwise), that God might give up on slow learners (Philippians 1:6 says He will not), and that mature Christians should claim to have moved beyond sin (1 John 1:8 says that claim is self-deception).",
    sortOrder: 2,
  },
  {
    id: "w2s-11-4-3",
    lessonId: "w2l-11-4",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "The Adventist community has navigated significant internal debates about the nature of sanctification, the possibility of sinless perfection before the Second Coming, and the relationship between human effort and divine power. These passages provide essential biblical guardrails.\n\n**Against perfectionism.** Some voices within Adventist history have taught that believers must reach a state of absolute sinlessness before Christ can return — that the delay of the Advent is caused by the church's failure to achieve perfection. While Adventists rightly emphasize growth in holiness and the seriousness of sin, 1 John 1:8 stands as an immovable marker: claiming sinlessness is self-deception. The biblical call is to ongoing confession and cleansing, not to a final plateau of moral flawlessness achieved before glorification.\n\n**Against complacency.** The opposite error — treating grace as a license for spiritual carelessness — is equally foreign to Adventist theology. Paul's anguish in Romans 7 is not passive acceptance of sin but grief over its persistence. The believer who is growing in Christ does not make peace with sin; rather, sensitivity to sin actually increases as the Spirit deepens awareness of God's holiness. Complacency is not the fruit of grace; it is the evidence of its absence.\n\n**The assurance question.** Adventists have sometimes struggled with assurance of salvation, fearing that their imperfections disqualify them from God's favor. Philippians 1:6 addresses this directly: the confidence is not in the believer's performance but in God's faithfulness to finish what He started. Assurance does not rest on having arrived but on knowing who is doing the work. This is consistent with the Adventist understanding of Christ's ongoing intercession in the heavenly sanctuary — the same Savior who died for us now lives to intercede for us (Hebrews 7:25).\n\n**Character development and the investigative judgment.** Adventists understand that the pre-Advent judgment examines the lives of professed believers — not to determine whether they are sinless but whether they are genuinely connected to Christ by faith. Growing in Christ means living in transparent dependence on His merits, confessing failures honestly (1 John 1:9), and trusting the Spirit to produce fruit that demonstrates authentic faith. The judgment reveals the reality of the relationship, not the perfection of the performance.",
    sortOrder: 3,
  },
  {
    id: "w2s-11-4-4",
    lessonId: "w2l-11-4",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Address common misconceptions through lived experience this week:\n\n1. **Practice honest confession.** Each evening, review your day with the Spirit's help. Identify one specific failure — not vague guilt but a concrete action, word, or attitude — and confess it using the language of 1 John 1:9. Then receive the promise: He is faithful to forgive and cleanse. Do not rehearse the failure after confessing it; leave it with God.\n\n2. **Anchor your assurance.** Write Philippians 1:6 on a card and place it where you will see it during moments of discouragement. When you feel overwhelmed by your spiritual shortcomings, read the verse aloud and answer the question: Who began this work in me, and will He finish it?\n\n3. **Distinguish grief from despair.** When you fall short this week, notice your emotional response. Godly grief (2 Corinthians 7:10) drives you back to Christ; worldly sorrow drives you into self-condemnation and withdrawal. If you find yourself spiraling into shame, redirect by reading Romans 8:1: \"There is therefore now no condemnation to those who are in Christ Jesus.\"",
    sortOrder: 4,
  },
  {
    id: "w2s-11-4-5",
    lessonId: "w2l-11-4",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Paul's struggle in Romans 7 has been read as either pre-conversion despair or mature Christian honesty. Regardless of interpretation, does his description resonate with your own experience? How do you respond when you fail despite sincerely wanting to do right?\n\n2. Have you ever encountered the teaching that Christians must achieve sinless perfection before Christ returns? How does 1 John 1:8-10 inform your evaluation of that claim?\n\n3. Philippians 1:6 promises that God will complete the work He began. How does this assurance change the way you think about your spiritual failures — are they evidence of God's abandonment or part of the process He is faithfully managing?",
    sortOrder: 5,
  },
  {
    id: "w2s-11-4-6",
    lessonId: "w2l-11-4",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },
];

export const belief11Assessments = [
  {
    id: "w2a-11-1",
    lessonId: "w2l-11-1",
    title: "Biblical Foundations Assessment — Victory in Christ",
    passingScore: 70,
  },
  {
    id: "w2a-11-2",
    lessonId: "w2l-11-2",
    title: "Doctrinal Formulation Assessment — Sanctification and Spiritual Growth",
    passingScore: 70,
  },
  {
    id: "w2a-11-3",
    lessonId: "w2l-11-3",
    title: "Practical Implications Assessment — Spiritual Disciplines",
    passingScore: 70,
  },
  {
    id: "w2a-11-4",
    lessonId: "w2l-11-4",
    title: "Misunderstandings & Challenges Assessment — Growing in Christ",
    passingScore: 70,
  },
];

export const belief11Items = [
  {
    id: "w2i-11-1-1",
    assessmentId: "w2a-11-1",
    question: "In Colossians 2:15, what does Paul say Christ did to principalities and powers at the cross?",
    options: ["Negotiated a truce with them", "Disarmed them and made a public spectacle of them", "Temporarily restrained them until the Second Coming", "Converted them to serve God's purposes"],
    correctIndex: 1,
    explanation: "Paul uses military language — Christ stripped the hostile powers of their weapons and paraded them publicly as defeated enemies. The cross was not a negotiation but a decisive, irreversible victory.",
  },
  {
    id: "w2i-11-1-2",
    assessmentId: "w2a-11-1",
    question: "When the seventy returned rejoicing that demons were subject to them, what did Jesus tell them to rejoice about instead?",
    options: ["Their superior spiritual techniques", "Their names being written in heaven", "The number of demons they had cast out", "Their growing popularity among the people"],
    correctIndex: 1,
    explanation: "In Luke 10:20, Jesus redirected their joy from spiritual authority to covenant relationship — the ground of true security is belonging to God, not exercising power over evil spirits.",
  },
  {
    id: "w2i-11-1-3",
    assessmentId: "w2a-11-1",
    question: "According to Ephesians 6:12, what is the true nature of the believer's struggle?",
    options: ["A battle against corrupt political systems", "A wrestling match against spiritual forces of wickedness", "A competition with other religious traditions", "A psychological struggle against negative thoughts"],
    correctIndex: 1,
    explanation: "Paul names the real adversaries: principalities, powers, rulers of darkness, and spiritual hosts of wickedness in heavenly places. The conflict is spiritual, not merely social or psychological.",
  },
  {
    id: "w2i-11-1-4",
    assessmentId: "w2a-11-1",
    question: "A fellow believer says, 'Since Christ won the victory at the cross, spiritual warfare is no longer a real concern for Christians.' How would you respond using Ephesians 6?",
    options: ["Agree — the victory is complete and Christians face no opposition", "Disagree — Paul's urgent command to put on armor shows that real battles continue despite the war being won", "Suggest that spiritual warfare only affects non-Christians", "Argue that Paul was speaking metaphorically and there are no actual spiritual forces"],
    correctIndex: 1,
    explanation: "While Christ's victory is decisive and irreversible, Paul's urgent language in Ephesians 6 makes clear that believers must actively stand firm against ongoing attacks. The war is won, but individual battles remain real and fierce.",
  },
  {
    id: "w2i-11-1-5",
    assessmentId: "w2a-11-1",
    question: "What is the primary posture Paul calls believers to adopt in the spiritual warfare passage of Ephesians 6?",
    options: ["Aggressive attack against the enemy's strongholds", "Strategic retreat until Christ returns", "Standing firm in the victory already won", "Passive waiting for God to fight on their behalf"],
    correctIndex: 2,
    explanation: "Paul repeatedly uses the word 'stand' (histemi) — the armor is defensive and positional. Believers do not fight for victory but from the victory Christ has already secured at the cross.",
  },

  {
    id: "w2i-11-2-1",
    assessmentId: "w2a-11-2",
    question: "In 2 Peter 3:18, what two areas does Peter command believers to grow in?",
    options: ["Wealth and influence", "Grace and knowledge of Jesus Christ", "Church attendance and charitable giving", "Theological debate and apologetics"],
    correctIndex: 1,
    explanation: "Peter's final exhortation calls for growth in grace — God's unmerited favor and empowering presence — and knowledge — a deepening personal acquaintance with Jesus Christ. These two dimensions cannot be separated.",
  },
  {
    id: "w2i-11-2-2",
    assessmentId: "w2a-11-2",
    question: "According to 2 Corinthians 3:18, what is the mechanism by which believers are transformed?",
    options: ["Strict adherence to ceremonial regulations", "Beholding the glory of the Lord with unveiled face", "Accumulating theological knowledge through formal study", "Isolating themselves from all secular influences"],
    correctIndex: 1,
    explanation: "Paul teaches that transformation happens as believers contemplate Christ's glory — they are progressively changed 'from glory to glory' by the Spirit. The focus is on beholding Christ, not on self-effort.",
  },
  {
    id: "w2i-11-2-3",
    assessmentId: "w2a-11-2",
    question: "What does Paul mean by 'sanctify you completely' in 1 Thessalonians 5:23?",
    options: ["Salvation of the soul only, apart from the body", "A one-time experience at baptism that requires no further growth", "Comprehensive renewal touching spirit, soul, and body", "Reaching moral perfection before the Second Coming"],
    correctIndex: 2,
    explanation: "Paul prays for whole-person sanctification — spirit, soul, and body. Sanctification is not limited to the inner life but touches every dimension of human existence, consistent with the biblical view of humans as integrated beings.",
  },
  {
    id: "w2i-11-2-4",
    assessmentId: "w2a-11-2",
    question: "A new believer asks, 'If sanctification is God's work, why do I need to make any effort?' How would you explain the biblical balance?",
    options: ["Human effort is unnecessary — God does everything automatically", "God initiates and empowers growth, but believers cooperate through faith, prayer, and obedience", "Sanctification depends entirely on human willpower and discipline", "Effort is only needed at the beginning; after that, growth is effortless"],
    correctIndex: 1,
    explanation: "Scripture teaches divine initiative with human cooperation. God begins and completes the work (Philippians 1:6, 1 Thessalonians 5:24), but believers are commanded to grow (2 Peter 3:18) — through spiritual disciplines energized by the Spirit, not by self-powered effort.",
  },
  {
    id: "w2i-11-2-5",
    assessmentId: "w2a-11-2",
    question: "What assurance does 1 Thessalonians 5:24 provide about the process of sanctification?",
    options: ["The believer's determination guarantees success", "The faithfulness of God who calls ensures He will complete the work", "Human accountability partners will keep the believer on track", "Church membership provides automatic sanctification"],
    correctIndex: 1,
    explanation: "Paul grounds assurance not in human resolve but in divine faithfulness: 'He who calls you is faithful, who also will do it.' The work of sanctification is initiated, sustained, and completed by God Himself.",
  },

  {
    id: "w2i-11-3-1",
    assessmentId: "w2a-11-3",
    question: "In Psalm 1:2, what does the Hebrew word 'hagah' (translated 'meditates') specifically mean?",
    options: ["To read quickly through a large volume of text", "To murmur, turn over repeatedly, and chew on mentally", "To memorize without reflection", "To discuss loudly in a group setting"],
    correctIndex: 1,
    explanation: "Hagah describes a deliberate, repetitive engagement — like an animal chewing cud. It involves murmuring the text, turning it over in the mind throughout the day, and allowing it to shape thought patterns over time.",
  },
  {
    id: "w2i-11-3-2",
    assessmentId: "w2a-11-3",
    question: "What does Paul mean by 'redeeming the time' in Ephesians 5:16?",
    options: ["Earning salvation through productive activity", "Buying up every opportunity for spiritual growth because the days are evil", "Turning back the clock to undo past mistakes", "Working longer hours to prove one's faith"],
    correctIndex: 1,
    explanation: "The phrase 'exagorazomenoi ton kairon' means buying up every opportunity — treating time as a precious commodity in a hostile environment. Paul urges intentional, wise use of the moments God gives.",
  },
  {
    id: "w2i-11-3-3",
    assessmentId: "w2a-11-3",
    question: "According to Colossians 2:6-7, what two metaphors describe how believers should grow in Christ?",
    options: ["Running and competing", "Rooted and built up", "Swimming and diving", "Flying and soaring"],
    correctIndex: 1,
    explanation: "Paul uses the images of roots (hidden nourishment drawn from deep soil) and building (visible, structured growth). Both are necessary — roots provide stability while the structure demonstrates progress.",
  },
  {
    id: "w2i-11-3-4",
    assessmentId: "w2a-11-3",
    question: "Someone says, 'I can grow spiritually on my own — I don't need church or community.' How do these passages respond to that claim?",
    options: ["They support individual spirituality as sufficient", "Ephesians 5:19-20 describes the Spirit-filled life as inherently communal — speaking to one another in psalms, hymns, and songs", "They teach that church attendance replaces personal devotion", "They suggest community is optional but recommended"],
    correctIndex: 1,
    explanation: "Paul's description of the Spirit-filled life in Ephesians 5:19-20 is corporate — believers speak to one another, sing together, and give thanks together. Spiritual growth is designed to happen in community, not in isolation.",
  },
  {
    id: "w2i-11-3-5",
    assessmentId: "w2a-11-3",
    question: "Psalm 1:1 describes a descending progression of involvement with ungodly influence. What are the three stages?",
    options: ["Thinking, speaking, acting", "Walking, standing, sitting", "Hearing, accepting, teaching", "Doubting, questioning, rejecting"],
    correctIndex: 1,
    explanation: "The psalm traces a progression from casual association (walking) to lingering involvement (standing) to settled identification (sitting in the seat of the scornful). Each stage represents deeper entrenchment in ungodly patterns.",
  },

  {
    id: "w2i-11-4-1",
    assessmentId: "w2a-11-4",
    question: "In Romans 7:24-25, what is Paul's answer to his anguished cry, 'Who will deliver me from this body of death?'",
    options: ["A new set of religious rules", "Jesus Christ our Lord", "Increased personal willpower", "Complete withdrawal from society"],
    correctIndex: 1,
    explanation: "Paul's answer is not a method, technique, or program — it is a Person. Deliverance from the power of sin comes through Jesus Christ, not through human effort or religious systems.",
  },
  {
    id: "w2i-11-4-2",
    assessmentId: "w2a-11-4",
    question: "According to Philippians 1:6, when will God complete the good work He has begun in believers?",
    options: ["At the moment of baptism", "When the believer achieves sinless perfection", "At the day of Jesus Christ — His second coming", "After a specific number of years of faithful service"],
    correctIndex: 2,
    explanation: "Paul places the completion of sanctification at 'the day of Jesus Christ' — the Second Coming. This means the process of spiritual growth continues throughout the believer's entire earthly life and reaches its consummation at Christ's return.",
  },
  {
    id: "w2i-11-4-3",
    assessmentId: "w2a-11-4",
    question: "What does 1 John 1:8 say about anyone who claims to have no sin?",
    options: ["They have achieved the highest level of spiritual maturity", "They deceive themselves and the truth is not in them", "They should be recognized as examples for the church", "They have graduated beyond the need for confession"],
    correctIndex: 1,
    explanation: "John is unambiguous: claiming sinlessness is self-deception. The honest Christian acknowledges ongoing need for confession and cleansing, trusting in God's faithfulness to forgive (1 John 1:9).",
  },
  {
    id: "w2i-11-4-4",
    assessmentId: "w2a-11-4",
    question: "A church member is discouraged because they keep struggling with the same sin despite years of prayer. Using these passages, what counsel would you offer?",
    options: ["They should doubt their salvation because a true Christian would not struggle", "Even Paul experienced the tension between desire and action; they should continue confessing, trusting God's faithfulness to complete His work", "They should try harder through sheer willpower", "Ongoing struggle proves they were never genuinely converted"],
    correctIndex: 1,
    explanation: "Romans 7 validates the reality of ongoing struggle, 1 John 1:9 promises continual cleansing through confession, and Philippians 1:6 assures that God will complete what He started. Struggle does not negate salvation — it often indicates genuine sensitivity to the Spirit.",
  },
  {
    id: "w2i-11-4-5",
    assessmentId: "w2a-11-4",
    question: "What is the significance of the present tense used for 'cleanses' (katharise) in 1 John 1:9?",
    options: ["Cleansing happened once at conversion and never needs repeating", "God's cleansing is an ongoing, continuous process throughout the believer's life", "The believer must earn each instance of cleansing through good works", "Cleansing is available only during a specific period of probation"],
    correctIndex: 1,
    explanation: "The present tense suggests ongoing, repeated action — God's cleansing is not a one-time event but a continuous process. As believers confess, God faithfully and justly forgives and purifies, sustaining the relationship through the journey of growth.",
  },
];
