export const belief10Lessons = [
  {
    id: "w2l-10-1",
    moduleId: "bmod-010",
    title: "Biblical Foundations: The Gift of Salvation",
    description: "Tracing the biblical testimony of God's initiative in rescuing humanity — from the problem of sin to the provision of righteousness through Christ alone.",
    lessonOrder: 1,
    anchorText: "2 Corinthians 5:17-21; Romans 3:21-26; Titus 3:3-7",
    anchorBookId: 47,
    anchorChapter: 5,
    anchorVerseStart: 17,
    anchorVerseEnd: 21,
    estimatedMinutes: 35,
  },
  {
    id: "w2l-10-2",
    moduleId: "bmod-010",
    title: "Doctrinal Formulation: Justification, Sanctification, and Glorification",
    description: "Understanding the Adventist affirmation of salvation as a past, present, and future reality — declared righteous, being transformed, and awaiting final restoration.",
    lessonOrder: 2,
    anchorText: "Romans 5:1-2; Romans 8:1-4; Galatians 4:4-7",
    anchorBookId: 45,
    anchorChapter: 5,
    anchorVerseStart: 1,
    anchorVerseEnd: 2,
    estimatedMinutes: 30,
  },
  {
    id: "w2l-10-3",
    moduleId: "bmod-010",
    title: "Practical Implications: Walking in New Life",
    description: "Moving from theological understanding to daily experience — how salvation reshapes identity, choices, and relationships with God and others.",
    lessonOrder: 3,
    anchorText: "Ephesians 2:5-10; Colossians 1:13-14; 1 John 2:1-2",
    anchorBookId: 49,
    anchorChapter: 2,
    anchorVerseStart: 5,
    anchorVerseEnd: 10,
    estimatedMinutes: 30,
  },
  {
    id: "w2l-10-4",
    moduleId: "bmod-010",
    title: "Misunderstandings & Challenges",
    description: "Addressing persistent confusions about grace and law, faith and works, and the security of the believer — with clarity rooted in Scripture.",
    lessonOrder: 4,
    anchorText: "Romans 6:1-4; James 2:14-26; Galatians 5:1-6",
    anchorBookId: 45,
    anchorChapter: 6,
    anchorVerseStart: 1,
    anchorVerseEnd: 4,
    estimatedMinutes: 30,
  },
];

export const belief10Sections = [
  {
    id: "w2s-10-1-1",
    lessonId: "w2l-10-1",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"Therefore, if anyone is in Christ, he is a new creation; old things have passed away; behold, all things have become new. Now all things are of God, who has reconciled us to Himself through Jesus Christ, and has given us the ministry of reconciliation, that is, that God was in Christ reconciling the world to Himself, not imputing their trespasses to them, and has committed to us the word of reconciliation. Now then, we are ambassadors for Christ, as though God were pleading through us: we implore you on Christ's behalf, be reconciled to God. For He made Him who knew no sin to be sin for us, that we might become the righteousness of God in Him.\" — 2 Corinthians 5:17-21 (NKJV)\n\n\"But now the righteousness of God apart from the law is revealed, being witnessed by the Law and the Prophets, even the righteousness of God, through faith in Jesus Christ, to all and on all who believe. For there is no difference; for all have sinned and fall short of the glory of God, being justified freely by His grace through the redemption that is in Christ Jesus, whom God set forth as a propitiation by His blood, through faith, to demonstrate His righteousness... that He might be just and the justifier of the one who has faith in Jesus.\" — Romans 3:21-26 (NKJV)\n\n\"For we ourselves were also once foolish, disobedient, deceived, serving various lusts and pleasures, living in malice and envy, hateful and hating one another. But when the kindness and the love of God our Savior toward man appeared, not by works of righteousness which we have done, but according to His mercy He saved us, through the washing of regeneration and renewing of the Holy Spirit, whom He poured out on us abundantly through Jesus Christ our Savior, that having been justified by His grace we should become heirs according to the hope of eternal life.\" — Titus 3:3-7 (NKJV)",
    sortOrder: 1,
  },
  {
    id: "w2s-10-1-2",
    lessonId: "w2l-10-1",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Paul's declaration in 2 Corinthians 5:17-21 captures the full arc of salvation in a single paragraph. The phrase \"new creation\" is not metaphorical decoration — it echoes Genesis 1. The God who spoke light into darkness now speaks new life into dead souls. The old identity, shaped by rebellion and brokenness, is replaced by something that did not previously exist. This is not self-improvement or moral repair; it is re-creation by the same power that formed the universe.\n\nThe engine of this transformation is reconciliation, and Paul is emphatic about who initiates it: \"All things are of God.\" Humanity did not negotiate peace terms with heaven. God moved first, absorbing the offense of human sin into Himself through Christ. The stunning exchange of verse 21 — the sinless One \"made sin\" so that sinners might \"become the righteousness of God\" — is the deepest mystery of the gospel. Christ did not merely bear sin's penalty; He entered sin's condition so that believers could enter His righteousness.\n\nRomans 3:21-26 anchors this exchange in the language of the courtroom and the sanctuary. \"Justified freely\" means declared righteous without cost to the defendant — the debt is real, but Someone else has paid it. The word \"propitiation\" (hilasterion) carries sacrificial overtones: Christ's blood satisfies the just demands of God's law while simultaneously opening the door of mercy. Paul insists that this arrangement upholds rather than undermines divine justice — God is both \"just and the justifier.\"\n\nTitus 3:3-7 adds the autobiographical dimension. Paul includes himself among the \"foolish, disobedient, deceived\" — salvation is not a reward for the morally superior. The turning point is not human effort (\"not by works of righteousness which we have done\") but divine mercy expressed through the Spirit's regenerating work. The Holy Spirit is not an afterthought in the salvation process; He is the active agent who washes, renews, and transforms from within.\n\nTogether these three passages establish that salvation originates in God's initiative, operates through Christ's substitutionary work, and is applied by the Holy Spirit — a thoroughly Trinitarian rescue from start to finish.",
    sortOrder: 2,
  },
  {
    id: "w2s-10-1-3",
    lessonId: "w2l-10-1",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "The Adventist understanding of salvation resists two opposite errors that have plagued Christian history: the idea that human effort contributes to justification, and the idea that grace renders obedience irrelevant. The biblical passages in this lesson guard against both.\n\n**Grace as the sole basis.** When Paul writes \"not by works of righteousness which we have done\" (Titus 3:5), he eliminates every form of merit-based salvation. Adventists affirm without reservation that justification is by grace alone through faith alone in Christ alone. The 1888 Minneapolis General Conference session — where E. J. Waggoner and A. T. Jones pressed the centrality of righteousness by faith — stands as a landmark recovery of this emphasis within the movement. The gospel is not \"grace plus Sabbath-keeping\" or \"faith plus dietary reform\"; it is Christ's righteousness credited to the believer who trusts Him.\n\n**New creation and the Great Controversy.** The language of 2 Corinthians 5:17 resonates with the cosmic conflict theme. Satan's strategy from Eden forward has been to convince humanity that God's character is untrustworthy and His law is oppressive. The new creation demonstrates the opposite: God's love is so extravagant that He enters the sinner's condition to bring the sinner into His own righteousness. Every converted life is a living rebuttal of Satan's accusations against the divine character.\n\n**The sanctuary and propitiation.** Paul's use of hilasterion in Romans 3:25 deliberately evokes the mercy seat in the Most Holy Place (the same Greek word appears in Hebrews 9:5 for the mercy seat). For Adventists, the sanctuary is not an abstract theological category but the interpretive framework for understanding how atonement works — sacrifice, mediation, and judgment are interconnected realities, all centered in the person and ministry of Christ.\n\n**The Spirit's role in regeneration.** Titus 3:5-6 underscores that salvation is not merely a legal transaction; it involves inward transformation by the Holy Spirit. Adventists hold that justification (God's declaration of the sinner's new legal status) and regeneration (God's creation of a new heart) occur together at conversion. The declared status and the experienced reality belong to the same saving act.",
    sortOrder: 3,
  },
  {
    id: "w2s-10-1-4",
    lessonId: "w2l-10-1",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Begin experiencing salvation as a present reality, not merely a past event:\n\n1. **Write your before-and-after.** Using Titus 3:3-7 as a template, write two brief paragraphs: one describing your life before you understood God's grace, and one describing what has changed since. Be honest about both — neither romanticize the past nor exaggerate the present. Share this with someone you trust.\n\n2. **Practice receiving before doing.** Each morning this week, before you read a single verse or pray a single request, sit quietly for two minutes and say: \"God, You moved first. I receive what You have already given.\" Notice how this posture of reception changes the tone of the rest of your devotional time.\n\n3. **Identify one area of self-reliance.** Where in your spiritual life are you still trying to earn what God has freely given? Perhaps it is compulsive religious activity driven by guilt, or a persistent belief that God's acceptance depends on your performance. Name it specifically and bring it to God in prayer.",
    sortOrder: 4,
  },
  {
    id: "w2s-10-1-5",
    lessonId: "w2l-10-1",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Paul says God \"made Him who knew no sin to be sin for us.\" How does the depth of that exchange affect the way you think about your own unworthiness before God?\n\n2. Titus 3:3-7 describes salvation as entirely God's initiative — His kindness appeared, His mercy saved, His Spirit renewed. In what ways do you still struggle to accept that salvation is a gift rather than a reward?\n\n3. Romans 3:26 says God is both \"just and the justifier.\" Why is it important that salvation satisfies God's justice rather than setting it aside?",
    sortOrder: 5,
  },
  {
    id: "w2s-10-1-6",
    lessonId: "w2l-10-1",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },

  {
    id: "w2s-10-2-1",
    lessonId: "w2l-10-2",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"Therefore, having been justified by faith, we have peace with God through our Lord Jesus Christ, through whom also we have access by faith into this grace in which we stand, and rejoice in hope of the glory of God.\" — Romans 5:1-2 (NKJV)\n\n\"There is therefore now no condemnation to those who are in Christ Jesus, who do not walk according to the flesh, but according to the Spirit. For the law of the Spirit of life in Christ Jesus has made me free from the law of sin and death. For what the law could not do in that it was weak through the flesh, God did by sending His own Son in the likeness of sinful flesh, on account of sin: He condemned sin in the flesh, that the righteous requirement of the law might be fulfilled in us who do not walk according to the flesh but according to the Spirit.\" — Romans 8:1-4 (NKJV)\n\n\"But when the fullness of the time had come, God sent forth His Son, born of a woman, born under the law, to redeem those who were under the law, that we might receive the adoption as sons. And because you are sons, God has sent forth the Spirit of His Son into your hearts, crying out, 'Abba, Father!' Therefore you are no longer a slave but a son, and if a son, then an heir of God through Christ.\" — Galatians 4:4-7 (NKJV)",
    sortOrder: 1,
  },
  {
    id: "w2s-10-2-2",
    lessonId: "w2l-10-2",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Romans 5:1-2 opens with a settled verdict: \"having been justified\" is a completed action with ongoing results. The believer who has trusted Christ now possesses peace with God — not the absence of conflict in daily life, but the end of hostility between Creator and creature. The war is over. Access to grace is not a revolving door that swings open and shut with each moral success or failure; it is a standing position (\"this grace in which we stand\") secured by Christ's faithfulness, not the believer's consistency.\n\nRomans 8:1-4 addresses the question that justification inevitably raises: if the legal verdict is settled, what about the ongoing reality of sin in the believer's life? Paul's answer is the \"law of the Spirit of life\" — a new governing principle that overpowers the old gravitational pull of sin. The law of Moses diagnosed sin but could not cure it; human flesh was too weak to keep it. God's solution was not to lower the standard but to meet it Himself: Christ came \"in the likeness of sinful flesh\" and condemned sin in the very arena where sin had reigned. The result is that the law's righteous requirement is \"fulfilled in us\" — not by strenuous self-effort, but by walking in the Spirit.\n\nGalatians 4:4-7 reframes salvation in the language of family. The transition from slave to son captures the shift from fearful obedience to filial trust. \"Abba\" is the intimate Aramaic address of a child to a father — Jesus Himself used it in Gethsemane (Mark 14:36). That the Spirit enables believers to use the same word reveals something extraordinary: the relationship Jesus has with the Father is now shared with those He redeems. The inheritance that follows is not earned by service but bestowed by birth — adoption into the divine family.\n\nThese passages together map the three tenses of salvation. Justification addresses the past: the verdict of acquittal. Sanctification addresses the present: the Spirit's transforming work within. Glorification addresses the future: the hope of sharing God's glory. All three are grounded in grace, sustained by faith, and accomplished through Christ.",
    sortOrder: 2,
  },
  {
    id: "w2s-10-2-3",
    lessonId: "w2l-10-2",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "Adventist theology affirms the full biblical scope of salvation — past, present, and future — while carefully distinguishing each phase without separating them from one another.\n\n**Justification: declared righteous.** Adventists teach that justification is a forensic act of God in which the sinner is declared righteous on the basis of Christ's merits, received through faith. This is not a gradual process but an instantaneous change of legal status. When God looks at the justified believer, He sees Christ's perfect record, not the believer's imperfect one. This conviction stands at the center of the Adventist gospel proclamation.\n\n**Sanctification: being made righteous.** While justification changes the believer's standing before God, sanctification changes the believer's character. Romans 8:4 — \"the righteous requirement of the law fulfilled in us\" — describes a progressive conformity to God's will empowered by the indwelling Spirit. Adventists insist that sanctification is as much a work of grace as justification; it is not human effort substituted for divine action but divine action expressed through human cooperation. The Sabbath, health principles, and ethical standards are not conditions for acceptance but fruits of a life yielded to the Spirit.\n\n**Glorification: the hope ahead.** Romans 5:2 points forward to \"the glory of God\" — the final transformation at Christ's return when mortality gives way to immortality and the image of God is fully restored. For Adventists, glorification is inseparable from the Second Coming and the eschatological restoration of all things. Salvation is not complete until sin is eradicated and the universe is made whole.\n\n**Adoption and assurance.** Galatians 4:4-7 grounds the believer's assurance in a relational reality: you are a child of God, not a servant on probation. The Adventist understanding of the investigative judgment does not negate this assurance; rather, the judgment vindicates before the universe the genuineness of those who have placed their faith in Christ. The adopted child does not live in fear of the courtroom but in confidence that the Father who declared them His own will sustain them to the end.\n\n**The sanctuary connection.** The three phases of salvation correspond naturally to the sanctuary structure: the altar of sacrifice (justification), the daily ministry in the Holy Place (sanctification), and the final cleansing of the Day of Atonement (glorification and vindication). Christ's ongoing high-priestly ministry ensures that the salvation begun at the cross is applied and completed.",
    sortOrder: 3,
  },
  {
    id: "w2s-10-2-4",
    lessonId: "w2l-10-2",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Deepen your understanding of salvation's three dimensions this week:\n\n1. **Claim the verdict daily.** Each morning, read Romans 8:1 aloud: \"There is therefore now no condemnation to those who are in Christ Jesus.\" Before you review your failures from yesterday or your anxieties about today, let the settled verdict of justification shape your emotional posture. Write down any resistance you feel and examine its source.\n\n2. **Cooperate with the Spirit in one specific area.** Identify one habit, attitude, or relational pattern where you sense the Spirit pressing for change. Rather than attacking it with willpower alone, pray each day: \"Spirit, fulfill the law's righteous requirement in me in this area.\" Record what you observe over the week.\n\n3. **Use the language of adoption.** In your prayer time, experiment with addressing God as \"Abba\" — not as a formula but as an expression of the intimacy Galatians 4:6 describes. Notice whether this shifts how you experience prayer.",
    sortOrder: 4,
  },
  {
    id: "w2s-10-2-5",
    lessonId: "w2l-10-2",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Romans 5:1 says justified believers \"have peace with God.\" Do you experience this peace consistently, or does your sense of acceptance fluctuate with your behavior? What does that reveal about where you locate your confidence?\n\n2. How do you understand the relationship between justification and sanctification in your own life? Do you tend to emphasize one at the expense of the other?\n\n3. Galatians 4:7 says you are no longer a slave but a son, and therefore an heir. How would your daily decisions change if you truly lived as an heir rather than a servant trying to earn approval?",
    sortOrder: 5,
  },
  {
    id: "w2s-10-2-6",
    lessonId: "w2l-10-2",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },

  {
    id: "w2s-10-3-1",
    lessonId: "w2l-10-3",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"And you He made alive, who were dead in trespasses and sins... But God, who is rich in mercy, because of His great love with which He loved us, even when we were dead in trespasses, made us alive together with Christ (by grace you have been saved), and raised us up together, and made us sit together in the heavenly places in Christ Jesus... For by grace you have been saved through faith, and that not of yourselves; it is the gift of God, not of works, lest anyone should boast. For we are His workmanship, created in Christ Jesus for good works, which God prepared beforehand that we should walk in them.\" — Ephesians 2:1,4-6,8-10 (NKJV)\n\n\"He has delivered us from the power of darkness and conveyed us into the kingdom of the Son of His love, in whom we have redemption through His blood, the forgiveness of sins.\" — Colossians 1:13-14 (NKJV)\n\n\"My little children, these things I write to you, so that you may not sin. And if anyone sins, we have an Advocate with the Father, Jesus Christ the righteous. And He Himself is the propitiation for our sins, and not for ours only but also for the whole world.\" — 1 John 2:1-2 (NKJV)",
    sortOrder: 1,
  },
  {
    id: "w2s-10-3-2",
    lessonId: "w2l-10-3",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Ephesians 2:1-10 presents the most comprehensive single-passage portrait of salvation's practical shape. Paul begins with a diagnosis: humanity was not merely sick but dead — \"dead in trespasses and sins.\" Dead people do not contribute to their own resuscitation. The action belongs entirely to God, who is \"rich in mercy.\" The verbs that follow are all divine actions: He made alive, He raised up, He seated us in heavenly places. Salvation is something done to us and for us before it is ever something done through us.\n\nYet Paul does not stop at rescue. Verse 10 pivots to purpose: \"We are His workmanship, created in Christ Jesus for good works.\" The Greek word poiema (from which we get \"poem\") suggests a crafted masterpiece. Good works are not the cause of salvation but its intended product. God designed specific paths of service for each believer before they were born. Living the saved life means walking into those prepared works — not manufacturing righteousness but inhabiting what grace has already arranged.\n\nColossians 1:13-14 uses the language of regime change. Salvation is not a minor adjustment within the same system; it is a transfer of citizenship from one kingdom to another. The \"power of darkness\" is not a vague spiritual atmosphere but a dominion with real authority over its subjects. Christ's redemptive act physically relocates the believer from one jurisdiction to another. The forgiveness of sins is not simply the removal of guilt but the legal basis for the transfer — without it, the old kingdom retains its claim.\n\n1 John 2:1-2 addresses the practical reality that saved people still sin. John's purpose is dual: he writes \"so that you may not sin\" — the goal is holiness — but he immediately provides for failure: \"if anyone sins, we have an Advocate.\" The present tense of \"we have\" indicates an ongoing ministry, not a one-time event. Christ's advocacy before the Father means that the believer who stumbles is not abandoned to the old kingdom but represented by the righteous One whose propitiation covers all sin.",
    sortOrder: 2,
  },
  {
    id: "w2s-10-3-3",
    lessonId: "w2l-10-3",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "These passages shape several distinctively Adventist convictions about how salvation works in daily experience:\n\n**Salvation as kingdom transfer.** The Colossians 1:13-14 imagery of deliverance from one dominion into another resonates deeply with the Great Controversy framework. Every conversion is a defection from Satan's rebel government into the kingdom of Christ. This is why Adventists understand baptism as more than personal devotion — it is a public declaration of allegiance, a visible transfer of citizenship witnessed by both the church and the watching universe.\n\n**Good works as fruit, not root.** Ephesians 2:8-10 is the Adventist answer to the persistent charge that emphasis on Sabbath observance, health reform, or other lifestyle standards amounts to legalism. The sequence is clear: saved by grace (v. 8), not of works (v. 9), created for good works (v. 10). Obedience flows from gratitude and new identity, not from anxiety about acceptance. When an Adventist keeps the Sabbath, the motivation is not to secure salvation but to respond to a Savior who has already secured it.\n\n**Christ's ongoing advocacy.** 1 John 2:1-2 connects directly to the Adventist doctrine of Christ's high-priestly ministry in the heavenly sanctuary. The Advocate before the Father is not a theological abstraction but a present-tense reality: right now, Christ represents believing sinners in heaven's courtroom. This ministry does not add to the sufficiency of the cross but applies its benefits to each believer's ongoing experience. The assurance it provides is not that the believer will never fail, but that failure does not sever the relationship.\n\n**The tension between aspiration and reality.** John writes both \"that you may not sin\" and \"if anyone sins\" in the same breath. Adventists hold this tension honestly: the goal of the Christian life is victory over sin through the Spirit's power, but the reality of ongoing struggle does not disqualify the believer from grace. Perfectionism that denies the need for the Advocate and antinomianism that dismisses the call to holiness are both rejected.\n\n**Prepared works and the Adventist mission.** The phrase \"good works, which God prepared beforehand\" (Ephesians 2:10) suggests that every believer has a divinely assigned role in God's end-time purposes. Adventist emphasis on spiritual gifts, missionary service, and health ministry flows from this conviction that salvation is not only rescue from destruction but commissioning for service.",
    sortOrder: 3,
  },
  {
    id: "w2s-10-3-4",
    lessonId: "w2l-10-3",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Let the reality of salvation reshape your daily rhythms this week:\n\n1. **Discover your prepared works.** Ephesians 2:10 says God prepared good works for you in advance. This week, pay deliberate attention to opportunities that arise — a conversation that needs truth, a neighbor who needs help, a task that fits your abilities. At the end of each day, write down one moment where you may have walked into a \"prepared work.\" Over time, patterns will emerge.\n\n2. **Practice advocacy, not self-defense.** When you sin this week, resist the impulse to either minimize it or spiral into shame. Instead, go directly to the Advocate: \"Jesus, I have sinned. You are righteous. You stand for me before the Father.\" Let 1 John 2:1 replace both denial and despair with honest confession and confident trust.\n\n3. **Remember your transfer.** Colossians 1:13 says you have been delivered from the power of darkness. When temptation presses or old habits reassert themselves, speak this truth aloud: \"I no longer belong to that kingdom. I have been transferred into the kingdom of Christ.\" Authority over your life has changed hands — act on that reality.",
    sortOrder: 4,
  },
  {
    id: "w2s-10-3-5",
    lessonId: "w2l-10-3",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Ephesians 2:10 calls you God's \"workmanship\" — a crafted masterpiece. How does that identity compare with the way you typically think about yourself? What would change if you believed it more deeply?\n\n2. When you sin after becoming a believer, is your first instinct to run to the Advocate or to run from God? What does your instinct reveal about how you understand grace?\n\n3. Colossians 1:13 describes salvation as a transfer from one kingdom to another. Are there areas of your life where you still operate as though the old kingdom has authority? What would it look like to live fully under the new King's rule?",
    sortOrder: 5,
  },
  {
    id: "w2s-10-3-6",
    lessonId: "w2l-10-3",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },

  {
    id: "w2s-10-4-1",
    lessonId: "w2l-10-4",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"What shall we say then? Shall we continue in sin that grace may abound? Certainly not! How shall we who died to sin live any longer in it? Or do you not know that as many of us as were baptized into Christ Jesus were baptized into His death? Therefore we were buried with Him through baptism into death, that just as Christ was raised from the dead by the glory of the Father, even so we also should walk in newness of life.\" — Romans 6:1-4 (NKJV)\n\n\"What does it profit, my brethren, if someone says he has faith but does not have works? Can faith save him?... Thus also faith by itself, if it does not have works, is dead. But someone will say, 'You have faith, and I have works.' Show me your faith without your works, and I will show you my faith by my works... For as the body without the spirit is dead, so faith without works is dead also.\" — James 2:14,17-18,26 (NKJV)\n\n\"Stand fast therefore in the liberty by which Christ has made us free, and do not be entangled again with a yoke of bondage... For in Christ Jesus neither circumcision nor uncircumcision avails anything, but faith working through love.\" — Galatians 5:1,6 (NKJV)",
    sortOrder: 1,
  },
  {
    id: "w2s-10-4-2",
    lessonId: "w2l-10-4",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Romans 6:1-4 anticipates and demolishes the most dangerous misunderstanding of grace: that if salvation is free, sin no longer matters. Paul's response is not a polite correction but a visceral recoil — \"Certainly not!\" The logic is not merely moral but ontological: the believer has died to sin through union with Christ in baptism. A dead person does not return to the habits of their former life. Baptism is not a ceremonial accessory but a participation in Christ's death and resurrection; the old self was buried, and a new self was raised. To continue in deliberate sin is to behave as though the death and resurrection never happened.\n\nJames 2:14-26 addresses the opposite error: the belief that intellectual assent to correct doctrine constitutes saving faith. James is relentless in his logic — faith that produces no corresponding action is not merely inadequate; it is dead. His illustrations are pointed: Abraham's willingness to offer Isaac and Rahab's protection of the spies were not meritorious works that earned favor but visible evidence of a trust that was already alive within them. James does not contradict Paul; he confronts a different problem. Paul combats those who add works to faith as a condition of justification. James combats those who subtract works from faith as though obedience were optional.\n\nGalatians 5:1,6 introduces a third misunderstanding: the return to legalism after experiencing grace. The Galatian churches were being pressured to adopt circumcision and Torah observance as requirements for full acceptance by God. Paul calls this a return to slavery. The liberty Christ purchased is not a license to sin (Romans 6) but a freedom from the futile attempt to earn God's favor through religious performance. The summary phrase — \"faith working through love\" — encapsulates the Pauline vision: genuine faith is active, but its energy source is love, not fear; its motive is gratitude, not merit.\n\nThese three passages together guard the biblical doctrine of salvation from its most persistent distortions: cheap grace that tolerates sin, dead orthodoxy that substitutes knowledge for trust, and enslaving legalism that replaces Christ's sufficiency with human effort.",
    sortOrder: 2,
  },
  {
    id: "w2s-10-4-3",
    lessonId: "w2l-10-4",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "The Adventist community has wrestled with each of these misunderstandings, and the biblical correctives in this lesson illuminate the path forward:\n\n**Against cheap grace.** Some critics accuse Adventists of legalism because of their emphasis on the law, Sabbath, and lifestyle standards. But Romans 6:1-4 shows that the real danger runs in the opposite direction: a grace that asks nothing is a grace that changes nothing. Adventists insist that genuine conversion produces visible transformation — not as the basis of acceptance, but as the evidence of new life. The believer who has died with Christ in baptism walks in \"newness of life,\" and that newness has observable, practical dimensions.\n\n**Against dead orthodoxy.** James's warning strikes close to home for any tradition that values doctrinal precision. It is possible to hold all twenty-eight fundamental beliefs intellectually while remaining unchanged in character. Adventist faith is not merely a list of correct propositions but a living trust that reshapes priorities, relationships, and daily habits. The danger for doctrinally rigorous communities is assuming that knowing the right answers is the same as having living faith.\n\n**Against legalism.** Galatians 5:1 is the standing rebuke to every form of spiritual bondage that creeps into religious communities — the unwritten rules, the cultural expectations masquerading as divine requirements, the subtle belief that God's acceptance depends on perfect performance. Adventists must continually distinguish between obedience as a response to grace and obedience as a condition for grace. The first produces joy and freedom; the second produces anxiety and burnout.\n\n**Faith working through love.** Paul's summary in Galatians 5:6 — \"faith working through love\" — provides the Adventist integration point. Sabbath-keeping motivated by love for the Creator is worship. Health reform motivated by love for the body God gave is stewardship. Evangelism motivated by love for the lost is mission. When love is the engine, obedience ceases to be burden and becomes delight. The law becomes what the psalmist always said it was: the expression of God's character, cherished by those who know Him.\n\n**Baptism and the Great Controversy.** Romans 6:3-4 gives baptism a cosmic significance. The public act of immersion — going under the water as Christ went into the grave, rising as Christ rose — is a declaration before the watching universe that this person has changed allegiances. In the Great Controversy framework, every baptism is a victory for Christ's kingdom and a loss for the enemy's domain.",
    sortOrder: 3,
  },
  {
    id: "w2s-10-4-4",
    lessonId: "w2l-10-4",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Guard against these common distortions of the gospel this week:\n\n1. **Examine your motives for obedience.** Choose one spiritual practice you maintain regularly — Sabbath observance, tithing, dietary choices, prayer habits. Ask yourself honestly: \"Am I doing this because I love God, or because I fear rejection?\" If fear is the dominant motive, bring it to God and ask Him to replace it with the \"faith working through love\" that Paul describes.\n\n2. **Let faith produce a visible work.** James insists that living faith is active. Identify one concrete act of service you can perform this week that costs you something — time, money, comfort, or pride. Do it without announcing it. Let the action be the evidence of the faith you profess.\n\n3. **Remember your baptism.** If you have been baptized, recall the moment and what it signified. Read Romans 6:1-4 and reflect: \"I died with Christ. I was buried with Him. I was raised to walk in new life.\" If patterns from the old life are reasserting themselves, bring them under the authority of what happened at that water.",
    sortOrder: 4,
  },
  {
    id: "w2s-10-4-5",
    lessonId: "w2l-10-4",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Paul asks, \"Shall we continue in sin that grace may abound?\" Have you ever — consciously or unconsciously — treated grace as permission to remain unchanged? What would Paul's answer mean for that area of your life?\n\n2. James says faith without works is dead. How do you distinguish between works that flow from genuine faith and works performed to earn God's favor? What does the difference feel like in practice?\n\n3. Galatians 5:6 describes \"faith working through love\" as the essence of the Christian life. In your current spiritual experience, is love or fear the stronger motivator? What would need to change for love to take the lead?",
    sortOrder: 5,
  },
  {
    id: "w2s-10-4-6",
    lessonId: "w2l-10-4",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },
];

export const belief10Assessments = [
  {
    id: "w2a-10-1",
    lessonId: "w2l-10-1",
    title: "Biblical Foundations Assessment — The Experience of Salvation",
    passingScore: 70,
  },
  {
    id: "w2a-10-2",
    lessonId: "w2l-10-2",
    title: "Doctrinal Formulation Assessment — The Experience of Salvation",
    passingScore: 70,
  },
  {
    id: "w2a-10-3",
    lessonId: "w2l-10-3",
    title: "Practical Implications Assessment — The Experience of Salvation",
    passingScore: 70,
  },
  {
    id: "w2a-10-4",
    lessonId: "w2l-10-4",
    title: "Misunderstandings & Challenges Assessment — The Experience of Salvation",
    passingScore: 70,
  },
];

export const belief10Items = [
  {
    id: "w2i-10-1-1",
    assessmentId: "w2a-10-1",
    question: "According to 2 Corinthians 5:17, what happens to someone who is 'in Christ'?",
    options: ["They receive improved moral capacity", "They become a new creation", "They gain exemption from future suffering", "They are given political authority"],
    correctIndex: 1,
    explanation: "Paul declares that anyone in Christ is a 'new creation' — old things pass away and all things become new. This is re-creation, not mere self-improvement, echoing the creative power of Genesis 1.",
  },
  {
    id: "w2i-10-1-2",
    assessmentId: "w2a-10-1",
    question: "In Romans 3:25, the word 'propitiation' (hilasterion) carries overtones of which Old Testament object?",
    options: ["The altar of incense", "The mercy seat in the Most Holy Place", "The bronze serpent in the wilderness", "The table of showbread"],
    correctIndex: 1,
    explanation: "Hilasterion is the same Greek word used for the mercy seat (kapporet) in Hebrews 9:5. Paul deliberately links Christ's atoning death to the sanctuary's mercy seat, where God's justice and mercy converged.",
  },
  {
    id: "w2i-10-1-3",
    assessmentId: "w2a-10-1",
    question: "According to Titus 3:5, what is the basis on which God saved us?",
    options: ["Our sincere repentance", "Works of righteousness we had done", "His mercy, through the washing of regeneration and renewing of the Holy Spirit", "Our consistent church attendance"],
    correctIndex: 2,
    explanation: "Paul explicitly states it was 'not by works of righteousness which we have done, but according to His mercy' — salvation is entirely God's initiative, applied through the Spirit's regenerating work.",
  },
  {
    id: "w2i-10-1-4",
    assessmentId: "w2a-10-1",
    question: "A friend says, 'I believe God helps those who help themselves — He does His part and we do ours.' How does 2 Corinthians 5:17-21 challenge this view?",
    options: ["It confirms the idea — reconciliation requires equal effort from both sides", "It shows that God initiated reconciliation unilaterally while humanity was still in rebellion", "It teaches that salvation depends entirely on human willpower", "It suggests that God waits for human effort before acting"],
    correctIndex: 1,
    explanation: "Paul emphasizes that 'all things are of God, who has reconciled us to Himself' — the initiative belongs entirely to God. He moved first, while humanity was still hostile, making Christ to be sin for us.",
  },
  {
    id: "w2i-10-1-5",
    assessmentId: "w2a-10-1",
    question: "Romans 3:26 says God is both 'just and the justifier.' Why is it important that salvation satisfies divine justice?",
    options: ["Because God's power would be diminished if He simply pardoned sin", "Because the universe must see that God does not ignore the moral law He established", "Because justice is more important than mercy in God's character", "Because humans need to fear God in order to obey"],
    correctIndex: 1,
    explanation: "If God simply set aside justice to save sinners, His moral government would be compromised. The cross demonstrates that mercy does not cancel justice — Christ's sacrifice satisfies the law's demands, allowing God to be both righteous and the one who declares sinners righteous.",
  },

  {
    id: "w2i-10-2-1",
    assessmentId: "w2a-10-2",
    question: "In Romans 5:1, what is the immediate result of justification by faith?",
    options: ["Freedom from all future temptation", "Peace with God through our Lord Jesus Christ", "Instant perfection of character", "Exemption from earthly hardship"],
    correctIndex: 1,
    explanation: "Paul states that justified believers 'have peace with God' — the hostility between Creator and creature is ended. This is a settled relational reality, not the absence of life's difficulties.",
  },
  {
    id: "w2i-10-2-2",
    assessmentId: "w2a-10-2",
    question: "According to Romans 8:3-4, how is the righteous requirement of the law fulfilled in believers?",
    options: ["By strenuous personal effort to obey every commandment", "By the Spirit's indwelling power as believers walk according to the Spirit", "By lowering the standard of the law to match human ability", "By eliminating the law entirely under the new covenant"],
    correctIndex: 1,
    explanation: "God sent Christ in the likeness of sinful flesh to condemn sin, so that the law's requirement 'might be fulfilled in us who do not walk according to the flesh but according to the Spirit.' The Spirit enables what willpower alone cannot achieve.",
  },
  {
    id: "w2i-10-2-3",
    assessmentId: "w2a-10-2",
    question: "In Galatians 4:6, what intimate term does the Spirit enable believers to use when addressing God?",
    options: ["Lord of Hosts", "Almighty Judge", "Abba, Father", "Holy Creator"],
    correctIndex: 2,
    explanation: "The Spirit of God's Son cries 'Abba, Father' in the believer's heart — the same intimate Aramaic address Jesus used in Gethsemane. Adoption into God's family means sharing the relational intimacy that Jesus Himself enjoys with the Father.",
  },
  {
    id: "w2i-10-2-4",
    assessmentId: "w2a-10-2",
    question: "A church member says, 'Justification gets you into God's family, but you stay in by your own good behavior.' How do these passages respond?",
    options: ["They confirm that continued membership depends on perfect performance", "They show that the same grace that justifies also sanctifies — the believer stands in grace, not in personal merit", "They teach that justification can be lost and re-earned repeatedly", "They suggest that once justified, behavior is irrelevant"],
    correctIndex: 1,
    explanation: "Romans 5:2 says believers stand in grace — their position is sustained by Christ's faithfulness, not their consistency. Sanctification is also a work of grace through the Spirit (Romans 8:4), not a shift from grace to human effort.",
  },
  {
    id: "w2i-10-2-5",
    assessmentId: "w2a-10-2",
    question: "What are the three phases of salvation described across these passages?",
    options: ["Conviction, conversion, and church membership", "Justification, sanctification, and glorification", "Repentance, baptism, and Sabbath-keeping", "Knowledge, belief, and emotional experience"],
    correctIndex: 1,
    explanation: "Justification addresses the past verdict of acquittal (Romans 5:1), sanctification addresses the present transforming work of the Spirit (Romans 8:4), and glorification addresses the future hope of sharing God's glory (Romans 5:2). All three are grounded in grace.",
  },

  {
    id: "w2i-10-3-1",
    assessmentId: "w2a-10-3",
    question: "In Ephesians 2:10, what does Paul call believers?",
    options: ["God's servants", "God's workmanship (poiema)", "God's judges", "God's prophets"],
    correctIndex: 1,
    explanation: "Paul uses the Greek word poiema — a crafted masterpiece or poem — to describe believers. They are not self-made but divinely crafted, created in Christ Jesus for good works that God prepared in advance.",
  },
  {
    id: "w2i-10-3-2",
    assessmentId: "w2a-10-3",
    question: "According to Colossians 1:13-14, what has God done for believers in terms of their spiritual citizenship?",
    options: ["He improved conditions within the kingdom of darkness", "He delivered them from the power of darkness and transferred them into the kingdom of His Son", "He merged the two kingdoms into one", "He allowed them to hold dual citizenship"],
    correctIndex: 1,
    explanation: "Paul describes salvation as a regime change — a transfer from one dominion to another. Believers have been physically relocated from Satan's jurisdiction into Christ's kingdom, with forgiveness of sins as the legal basis for the transfer.",
  },
  {
    id: "w2i-10-3-3",
    assessmentId: "w2a-10-3",
    question: "In 1 John 2:1-2, what two purposes does John state for his letter?",
    options: ["To encourage wealth and to promise health", "To prevent sin and to provide assurance of an Advocate when sin occurs", "To establish church hierarchy and to collect tithes", "To predict the future and to explain the past"],
    correctIndex: 1,
    explanation: "John writes 'so that you may not sin' (the goal is holiness) and 'if anyone sins, we have an Advocate' (the provision for failure). Both purposes coexist without contradiction — aspiration for victory and assurance in failure.",
  },
  {
    id: "w2i-10-3-4",
    assessmentId: "w2a-10-3",
    question: "Ephesians 2:8-10 teaches that good works are the _______ of salvation, not the _______ of it.",
    options: ["condition ... result", "result ... cause", "cause ... consequence", "price ... reward"],
    correctIndex: 1,
    explanation: "Paul's sequence is definitive: saved by grace through faith (v. 8), not of works (v. 9), created for good works (v. 10). Good works are the product and purpose of salvation, not its basis or cause.",
  },
  {
    id: "w2i-10-3-5",
    assessmentId: "w2a-10-3",
    question: "A believer who has sinned feels they must earn their way back into God's favor through extra religious activity. How does 1 John 2:1 address this?",
    options: ["It confirms that additional religious effort is required after each sin", "It directs the believer to the Advocate — Jesus Christ the righteous — whose ongoing intercession restores without re-earning", "It suggests that certain sins are beyond forgiveness", "It teaches that sin after conversion proves the person was never truly saved"],
    correctIndex: 1,
    explanation: "John provides an Advocate, not a program of re-qualification. Christ's present-tense ministry before the Father means the sinning believer goes to the Advocate, not to self-generated penance. Restoration is received, not achieved.",
  },

  {
    id: "w2i-10-4-1",
    assessmentId: "w2a-10-4",
    question: "In Romans 6:1-2, how does Paul respond to the suggestion that believers should continue in sin so that grace may abound?",
    options: ["He agrees that grace covers all future sin automatically", "He responds with a forceful 'Certainly not!' — believers have died to sin", "He says it depends on the severity of the sin", "He defers the answer to a later letter"],
    correctIndex: 1,
    explanation: "Paul's response is visceral: 'Certainly not!' (me genoito — the strongest Greek negation). The logic is not merely moral but ontological — the believer has died to sin through union with Christ in baptism and can no longer live in it.",
  },
  {
    id: "w2i-10-4-2",
    assessmentId: "w2a-10-4",
    question: "What does James 2:26 compare dead faith to?",
    options: ["A tree without roots", "A body without the spirit", "A river without water", "A sky without stars"],
    correctIndex: 1,
    explanation: "James states, 'As the body without the spirit is dead, so faith without works is dead also.' Faith that produces no corresponding obedience is not merely weak — it is lifeless, like a corpse without breath.",
  },
  {
    id: "w2i-10-4-3",
    assessmentId: "w2a-10-4",
    question: "According to Galatians 5:6, what is the essential quality of faith that avails in Christ Jesus?",
    options: ["Faith producing impressive religious credentials", "Faith working through love", "Faith demonstrated through public displays", "Faith measured by doctrinal knowledge"],
    correctIndex: 1,
    explanation: "Paul writes that 'neither circumcision nor uncircumcision avails anything, but faith working through love.' Genuine faith is active, but its energy source is love — not fear, merit, or cultural conformity.",
  },
  {
    id: "w2i-10-4-4",
    assessmentId: "w2a-10-4",
    question: "A church member keeps all the health and lifestyle standards meticulously but does so out of fear of losing salvation rather than love for God. Which passage most directly addresses this situation?",
    options: ["Romans 6:1-4 — the argument against cheap grace", "James 2:14-26 — the argument against dead faith", "Galatians 5:1,6 — the warning against returning to bondage and the call to faith working through love", "None of these passages is relevant"],
    correctIndex: 2,
    explanation: "Galatians 5:1 warns against returning to 'a yoke of bondage,' and 5:6 identifies love as the proper motive for faith's expression. Obedience driven by fear of rejection is a return to the slavery Christ died to end.",
  },
  {
    id: "w2i-10-4-5",
    assessmentId: "w2a-10-4",
    question: "Do Paul (Romans/Galatians) and James contradict each other on the relationship between faith and works?",
    options: ["Yes — Paul says faith alone saves and James says works save", "No — Paul combats adding works as a condition of justification while James combats subtracting works as evidence of genuine faith", "Yes — they wrote to opposing theological camps and never resolved the disagreement", "No — James was correcting Paul's errors in later writings"],
    correctIndex: 1,
    explanation: "Paul and James address different distortions. Paul fights the error that works earn justification; James fights the error that faith can exist without fruit. Both affirm that genuine saving faith is alive, active, and produces obedience — but neither locates the basis of acceptance in human performance.",
  },
];
