export const belief3Lessons = [
  {
    id: "w1l-3-2",
    moduleId: "bmod-003",
    title: "Doctrinal Formulation: The Character of the Father",
    description: "Examining how Scripture reveals the Father's character through His self-disclosure, sovereignty, and covenant faithfulness.",
    lessonOrder: 2,
    anchorText: "Exodus 34:6-7; 1 Timothy 1:17; John 14:9",
    anchorBookId: 2,
    anchorChapter: 34,
    anchorVerseStart: 6,
    anchorVerseEnd: 7,
    estimatedMinutes: 30,
  },
  {
    id: "w1l-3-3",
    moduleId: "bmod-003",
    title: "Practical Implications: Knowing the Father",
    description: "Discovering how an accurate understanding of God the Father reshapes prayer, trust, and daily dependence.",
    lessonOrder: 3,
    anchorText: "Matthew 6:9-13; James 1:17; Psalm 103:8-14",
    anchorBookId: 40,
    anchorChapter: 6,
    anchorVerseStart: 9,
    anchorVerseEnd: 13,
    estimatedMinutes: 30,
  },
  {
    id: "w1l-3-4",
    moduleId: "bmod-003",
    title: "Misunderstandings & Challenges",
    description: "Addressing common distortions of God the Father — from distant deity to harsh judge — and restoring the biblical portrait.",
    lessonOrder: 4,
    anchorText: "John 14:6-11; Hebrews 1:1-3; Jonah 4:2",
    anchorBookId: 43,
    anchorChapter: 14,
    anchorVerseStart: 6,
    anchorVerseEnd: 11,
    estimatedMinutes: 30,
  },
];

export const belief3Sections = [
  {
    id: "w1s-3-2-1",
    lessonId: "w1l-3-2",
    sectionType: "anchor",
    title: "Anchor Text",
    content:
      "Read the following passages carefully before proceeding:\n\n• Exodus 34:6-7 — God's self-revelation to Moses on Sinai\n• 1 Timothy 1:17 — Paul's doxology to the immortal, invisible God\n• John 14:9 — Jesus' declaration: \"He who has seen Me has seen the Father\"",
    sortOrder: 1,
  },
  {
    id: "w1s-3-2-2",
    lessonId: "w1l-3-2",
    sectionType: "explain",
    title: "What Does This Mean?",
    content:
      "Exodus 34:6-7 stands as the single most quoted Old Testament passage within the Old Testament itself. When Moses asked to see God's glory, the Lord responded not with a display of raw power but with a verbal self-portrait: \"The LORD, the LORD God, merciful and gracious, longsuffering, and abounding in goodness and truth.\" The Hebrew word chesed — rendered \"goodness\" or \"lovingkindness\" — describes a loyal, covenant love that persists even when the other party falters. This is who God says He is when He defines Himself.\n\nNotice the sequence: mercy comes before judgment. Grace precedes the warning about iniquity. The Father does not grudgingly forgive; forgiveness flows from His essential nature. Yet the passage also affirms that God \"will by no means clear the guilty.\" Justice and mercy are not opposites in the Father's character — they are partners. He takes sin seriously precisely because He loves deeply.\n\nPaul's hymn in 1 Timothy 1:17 adds another dimension: the Father is \"the King eternal, immortal, invisible.\" He transcends time, decay, and human sight. This is not a God we can reduce to a comfortable image. His sovereignty is absolute — yet it is the sovereignty of One whose defining trait is chesed.\n\nJesus sharpened this portrait decisively in John 14:9. Philip asked to see the Father, and Jesus replied that anyone who had seen Him had already seen the Father. The Father is not hiding behind the Son; the Son is the visible expression of the Father's character. Every act of healing, every word of pardon, every meal with sinners — these are the Father's own dispositions made tangible in human form.",
    sortOrder: 2,
  },
  {
    id: "w1s-3-2-3",
    lessonId: "w1l-3-2",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content:
      "Adventist theology places the Father's character at the center of the Great Controversy. The conflict between Christ and Satan is not merely a power struggle; it is a courtroom drama in which the Father's government of love is on trial. Satan's original accusation in heaven was that God's law is arbitrary and His rule self-serving. Every act of God in Scripture answers that charge.\n\nThe Exodus 34 self-disclosure becomes a key exhibit. God chose to reveal His character at the very moment Israel had broken the covenant through the golden calf (Exodus 32). He did not wait for a worthy audience; He spoke His name to a rebellious people. This pattern — grace rushing toward failure — is the heartbeat of the Father's character.\n\nAdventists affirm that the Father's justice is restorative, not merely retributive. The warning that He visits \"the iniquity of the fathers upon the children\" describes the natural consequences of sin's hereditary influence, not vindictive punishment imposed on innocents. The cross is the ultimate demonstration: justice satisfied, mercy extended, and the Father's character vindicated before the watching universe (Romans 3:25-26).\n\nFor further reading on the Father's role in the Great Controversy, visit egwwritings.org and explore the chapter \"God's Love for Man\" in Steps to Christ.",
    sortOrder: 3,
  },
  {
    id: "w1s-3-2-4",
    lessonId: "w1l-3-2",
    sectionType: "practice",
    title: "Daily Practice",
    content:
      "1. Memorize Exodus 34:6-7 this week. Write it on a card and read it aloud each morning. Let God's self-description become your default definition of Him.\n\n2. Each evening, identify one event from your day and ask: \"How does Exodus 34:6-7 help me interpret this moment?\" Write a single sentence connecting the event to one attribute of the Father.\n\n3. Share the Exodus 34 passage with someone this week — a friend, family member, or study partner. Ask them what surprises them most about how God introduces Himself.",
    sortOrder: 4,
  },
  {
    id: "w1s-3-2-5",
    lessonId: "w1l-3-2",
    sectionType: "reflection",
    title: "Personal Reflection",
    content:
      "1. When you think of God the Father, which attribute comes to mind first — His power, His love, or His holiness? How does Exodus 34:6-7 challenge or confirm that instinct?\n\n2. Jesus said that seeing Him is seeing the Father. Which moment in Jesus' life most powerfully reveals the Father's character to you, and why?",
    sortOrder: 5,
  },
  {
    id: "w1s-3-2-6",
    lessonId: "w1l-3-2",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of the Adventist doctrine of God the Father's character.",
    sortOrder: 6,
  },

  {
    id: "w1s-3-3-1",
    lessonId: "w1l-3-3",
    sectionType: "anchor",
    title: "Anchor Text",
    content:
      "Read the following passages carefully before proceeding:\n\n• Matthew 6:9-13 — The Lord's Prayer as Jesus taught it\n• James 1:17 — Every good gift comes from the Father of lights\n• Psalm 103:8-14 — The Father's compassion toward His children",
    sortOrder: 1,
  },
  {
    id: "w1s-3-3-2",
    lessonId: "w1l-3-3",
    sectionType: "explain",
    title: "What Does This Mean?",
    content:
      "When Jesus taught His disciples to pray, the first word was \"Father.\" Not \"Almighty,\" not \"Judge,\" not \"Creator\" — though He is all of those. Jesus chose the term that communicates relationship before role. The Aramaic abba behind the Greek pater was a word of intimate trust, used by children addressing a beloved parent. By placing it at the head of the prayer, Jesus established that every request, every act of worship, and every confession flows from the security of belonging to a Father who already knows what we need (Matthew 6:8).\n\nThe prayer then moves outward — \"hallowed be Your name, Your kingdom come\" — before turning to daily needs: bread, forgiveness, protection. This sequence reveals a practical theology of the Father. He is transcendent (\"in heaven\") yet concerned with the ordinary (\"daily bread\"). He extends mercy (\"forgive us\") and provides shelter from evil. The Father is not distant from the texture of everyday life; He meets us in the mundane.\n\nJames 1:17 reinforces this with a striking image: the Father is the \"Father of lights, with whom there is no variation or shadow of turning.\" Unlike the sun that casts shifting shadows, the Father's generosity is constant. Every good gift — health, friendship, insight, provision — traces its origin back to Him. There is no dark side to His giving.\n\nPsalm 103:8-14 completes the portrait with tender realism. The Father \"knows our frame; He remembers that we are dust.\" He does not hold impossible expectations. His compassion accounts for human frailty without excusing sin. He is patient because He understands, not because He is indifferent.",
    sortOrder: 2,
  },
  {
    id: "w1s-3-3-3",
    lessonId: "w1l-3-3",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content:
      "Adventists understand the Lord's Prayer not as a ritual formula but as a relational blueprint. When we pray \"Your kingdom come,\" we align ourselves with the Father's end-time purpose — the full restoration of His reign over a universe cleansed of sin. This is the prayer of a people who live between the cross and the Second Coming, trusting that the Father is actively steering history toward its conclusion.\n\nThe phrase \"give us this day our daily bread\" connects directly to the Adventist emphasis on stewardship. If the Father is the source of every provision, then nothing we possess is truly \"ours.\" Tithing, health reform, and Sabbath rest all flow from this conviction: we receive from the Father and return to Him in gratitude.\n\nSabbath itself is the weekly experience of Psalm 103 made tangible. On the seventh day, we stop striving and rest in the Father's compassion. We acknowledge that we are dust — dependent, limited — and that this dependence is not shameful but designed. The Father made us finite on purpose, so that every breath would remind us of the Giver.\n\nThe Great Controversy framework heightens all of this. Satan's lie is that the Father withholds good things, that His rules are chains rather than guardrails. Every answered prayer, every good gift recognized, every Sabbath rest enjoyed is a living rebuttal of that accusation.",
    sortOrder: 3,
  },
  {
    id: "w1s-3-3-4",
    lessonId: "w1l-3-3",
    sectionType: "practice",
    title: "Daily Practice",
    content:
      "1. Pray through the Lord's Prayer slowly each morning this week. Pause after each phrase and personalize it — turn \"give us our daily bread\" into a specific request for today's provision.\n\n2. Keep a \"Good Gifts\" list. At the end of each day, write down three specific things you received that trace back to the Father's generosity (James 1:17). By Sabbath, review the full list and offer a prayer of thanksgiving.\n\n3. Choose one person in your life who may carry a distorted image of God as Father. Without preaching, share one thing from Psalm 103:8-14 that has shaped your own understanding.",
    sortOrder: 4,
  },
  {
    id: "w1s-3-3-5",
    lessonId: "w1l-3-3",
    sectionType: "reflection",
    title: "Personal Reflection",
    content:
      "1. How does addressing God as \"Father\" in prayer change the way you bring your needs to Him? Does it feel natural or difficult — and what might that reveal about your picture of God?\n\n2. Psalm 103:14 says the Father \"remembers that we are dust.\" How does this truth affect the way you handle your own failures and limitations?\n\n3. If every good gift comes from the Father (James 1:17), what is one gift you have received recently that you had not yet thanked Him for?",
    sortOrder: 5,
  },
  {
    id: "w1s-3-3-6",
    lessonId: "w1l-3-3",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of the practical implications of knowing God the Father.",
    sortOrder: 6,
  },

  {
    id: "w1s-3-4-1",
    lessonId: "w1l-3-4",
    sectionType: "anchor",
    title: "Anchor Text",
    content:
      "Read the following passages carefully before proceeding:\n\n• John 14:6-11 — Jesus reveals the Father through Himself\n• Hebrews 1:1-3 — The Son is the exact representation of the Father's nature\n• Jonah 4:2 — Jonah's complaint reveals the Father's character",
    sortOrder: 1,
  },
  {
    id: "w1s-3-4-2",
    lessonId: "w1l-3-4",
    sectionType: "explain",
    title: "What Does This Mean?",
    content:
      "Few doctrines suffer more distortion than the character of God the Father. A persistent misunderstanding casts the Father as the stern figure of the Old Testament whose wrath had to be calmed by a gentle Son in the New Testament. This reading pits Father against Son, as though Jesus persuaded a reluctant God to show mercy. Scripture dismantles this error at every turn.\n\nJohn 14:6-11 is the decisive corrective. When Philip said, \"Show us the Father,\" Jesus answered with gentle astonishment: \"Have I been with you so long, and yet you have not known Me, Philip? He who has seen Me has seen the Father.\" There is no gap between the character of the Son and the character of the Father. Every parable of grace, every touch of healing, every tear at Lazarus's tomb — these are the Father's own heart expressed through the Son.\n\nHebrews 1:1-3 deepens this point. The Son is \"the brightness of His glory and the express image of His person.\" The Greek word charakter — from which we get \"character\" — originally described the exact imprint a seal leaves in wax. Jesus is not approximately like the Father; He is the precise imprint of the Father's being.\n\nJonah 4:2 offers a surprising confirmation. When Nineveh repented and God relented, Jonah was furious — and his complaint is telling: \"I know that You are a gracious and merciful God, slow to anger and abundant in lovingkindness, One who relents from doing harm.\" Jonah quoted Exodus 34:6 not in praise but in protest. He knew the Father's character perfectly well; he simply did not want it applied to his enemies. The problem was never God's nature. The problem was Jonah's unwillingness to let God be who God has always been.",
    sortOrder: 2,
  },
  {
    id: "w1s-3-4-3",
    lessonId: "w1l-3-4",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content:
      "The Great Controversy theme directly addresses the most damaging misunderstanding of the Father. Satan's strategy from Eden onward has been to misrepresent the Father's character — to suggest that God is arbitrary, secretive, or vindictive. Every false picture of the Father advances that agenda, whether it comes from pagan religion, cultural conditioning, or careless theology.\n\nAdventists insist that the Old Testament Father and the New Testament Christ reveal the same character. The God who walked with Adam in Eden, who called Abraham \"friend,\" who wept through Hosea over wayward Israel — this is the same God who wept at Lazarus's tomb and forgave from the cross. There is no dispensational shift in the divine temperament.\n\nA second common error places the Father so far above creation that He becomes unknowable — a philosophical absolute rather than a relational Person. Scripture resists this abstraction. The Father names, calls, speaks, grieves, and rejoices. He is transcendent without being remote. The Sabbath itself testifies to this: an infinite God paused to rest — not from fatigue but from delight — and invites finite creatures to share that rest.\n\nA third distortion reduces the Father to a permissive grandfather who overlooks sin without addressing it. Adventist theology holds both sides: the Father is merciful AND just. The cross is the proof that He refuses to trivialize either. He bore the full weight of justice in the Son so that mercy could flow without compromise.\n\nFor further reading on correcting misrepresentations of the Father, visit egwwritings.org and explore \"A Revelation of God\" in Testimonies for the Church, vol. 8.",
    sortOrder: 3,
  },
  {
    id: "w1s-3-4-4",
    lessonId: "w1l-3-4",
    sectionType: "practice",
    title: "Daily Practice",
    content:
      "1. Identify one false picture of God the Father that has influenced your thinking — perhaps from childhood, culture, or past teaching. Write it down, then place beside it a specific Scripture that corrects it.\n\n2. Read Jonah 4 in full this week. Ask yourself honestly: Is there any person or group you would rather God not extend mercy to? Bring that resistance to Him in prayer.\n\n3. Share Hebrews 1:1-3 with a friend or study partner. Discuss what it means that Jesus is the \"exact representation\" of the Father. How does this change the way you read Old Testament stories about God?",
    sortOrder: 4,
  },
  {
    id: "w1s-3-4-5",
    lessonId: "w1l-3-4",
    sectionType: "reflection",
    title: "Personal Reflection",
    content:
      "1. Have you ever thought of the Father as harsher or more distant than Jesus? Where did that impression come from, and how does John 14:9 challenge it?\n\n2. Jonah knew God's character (Jonah 4:2) but resented it. In what situations are you tempted to wish God were less merciful toward others?\n\n3. How does the truth that Jesus is the \"exact imprint\" of the Father (Hebrews 1:3) affect the way you approach God in prayer?",
    sortOrder: 5,
  },
  {
    id: "w1s-3-4-6",
    lessonId: "w1l-3-4",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of common misunderstandings about God the Father.",
    sortOrder: 6,
  },
];

export const belief3Assessments = [
  { id: "w1a-3-2", lessonId: "w1l-3-2", title: "The Character of the Father Assessment", passingScore: 70 },
  { id: "w1a-3-3", lessonId: "w1l-3-3", title: "Knowing the Father Assessment", passingScore: 70 },
  { id: "w1a-3-4", lessonId: "w1l-3-4", title: "Father Misunderstandings Assessment", passingScore: 70 },
];

export const belief3Items = [
  {
    id: "w1i-3-2-1",
    assessmentId: "w1a-3-2",
    question: "In Exodus 34:6-7, what is the first attribute God uses to describe Himself to Moses?",
    options: ["Holy", "Merciful", "Just", "Almighty"],
    correctIndex: 1,
    explanation: "God begins His self-revelation with mercy: 'The LORD, the LORD God, merciful and gracious.' Mercy leads the list of divine attributes in this foundational passage.",
  },
  {
    id: "w1i-3-2-2",
    assessmentId: "w1a-3-2",
    question: "What does the Hebrew word 'chesed' in Exodus 34:6 primarily convey about God's character?",
    options: ["Absolute power", "Wrathful judgment", "Loyal, covenant love", "Distant sovereignty"],
    correctIndex: 2,
    explanation: "Chesed describes a steadfast, loyal love that persists even when the covenant partner fails. It is one of the most important words for God's character in the Old Testament.",
  },
  {
    id: "w1i-3-2-3",
    assessmentId: "w1a-3-2",
    question: "According to John 14:9, how did Jesus respond when Philip asked to see the Father?",
    options: [
      "He said the Father cannot be seen",
      "He pointed to the sky",
      "He said anyone who has seen Him has seen the Father",
      "He told Philip to read the Torah",
    ],
    correctIndex: 2,
    explanation: "Jesus said, 'He who has seen Me has seen the Father,' establishing that the Son is the visible revelation of the Father's character.",
  },
  {
    id: "w1i-3-2-4",
    assessmentId: "w1a-3-2",
    question: "A friend claims the Old Testament God is angry while the New Testament God is loving. How would you respond using Exodus 34:6-7 and John 14:9?",
    options: [
      "Agree that God changed His approach over time",
      "Explain that Exodus 34 reveals a merciful Father and Jesus says He is the exact reflection of that same Father",
      "Say the Old Testament should be read differently from the New",
      "Argue that the Father's anger is separate from the Son's love",
    ],
    correctIndex: 1,
    explanation: "Exodus 34:6-7 already portrays the Father as merciful and gracious in the Old Testament. Jesus then confirms in John 14:9 that His character is identical to the Father's. There is no shift between Testaments.",
  },
  {
    id: "w1i-3-2-5",
    assessmentId: "w1a-3-2",
    question: "Why does the Adventist Great Controversy framework make the Father's character especially important?",
    options: [
      "Because the Father needs defending from critics",
      "Because the cosmic conflict centers on whether the Father's government of love is trustworthy",
      "Because the Father is more powerful than Satan",
      "Because the Father's character is irrelevant to the conflict",
    ],
    correctIndex: 1,
    explanation: "The Great Controversy is fundamentally about vindicating the Father's character. Satan accused God of being self-serving, and the entire plan of salvation answers that charge by revealing the Father's love.",
  },

  {
    id: "w1i-3-3-1",
    assessmentId: "w1a-3-3",
    question: "In the Lord's Prayer (Matthew 6:9-13), what is the first word Jesus uses to address God?",
    options: ["Almighty", "Creator", "Father", "Lord"],
    correctIndex: 2,
    explanation: "Jesus begins the prayer with 'Our Father,' establishing relationship as the foundation for every request and act of worship that follows.",
  },
  {
    id: "w1i-3-3-2",
    assessmentId: "w1a-3-3",
    question: "According to James 1:17, what distinguishes the Father from created sources of light?",
    options: [
      "He shines brighter than the sun",
      "He has no variation or shadow of turning",
      "He created light on the first day",
      "He only gives spiritual gifts",
    ],
    correctIndex: 1,
    explanation: "James describes the Father of lights as having 'no variation or shadow of turning' — His generosity and character are constant, unlike shifting shadows cast by the sun.",
  },
  {
    id: "w1i-3-3-3",
    assessmentId: "w1a-3-3",
    question: "What does Psalm 103:14 say the Father 'remembers' about humanity?",
    options: [
      "That we are sinners",
      "That we are dust",
      "That we are powerful",
      "That we are angels",
    ],
    correctIndex: 1,
    explanation: "The psalmist writes that the Father 'remembers that we are dust.' His compassion accounts for human frailty without excusing sin.",
  },
  {
    id: "w1i-3-3-4",
    assessmentId: "w1a-3-3",
    question: "How does the Adventist understanding of stewardship connect to the Lord's Prayer petition 'give us this day our daily bread'?",
    options: [
      "It does not connect — stewardship is about money, not prayer",
      "It teaches that if the Father provides everything, nothing we possess is ultimately ours, and we respond with faithful stewardship",
      "It means we should only eat bread",
      "It proves that tithing earns God's blessings",
    ],
    correctIndex: 1,
    explanation: "If the Father is the source of all provision (daily bread), then everything we have belongs to Him. Stewardship — including tithing and health — flows from recognizing the Father as Giver.",
  },
  {
    id: "w1i-3-3-5",
    assessmentId: "w1a-3-3",
    question: "How does Sabbath rest relate to the Father's compassion described in Psalm 103?",
    options: [
      "Sabbath is unrelated to the Father's compassion",
      "Sabbath proves that God requires obedience above all else",
      "Sabbath is the weekly experience of resting in the Father's compassion and acknowledging our dependence on Him",
      "Sabbath is only about physical rest",
    ],
    correctIndex: 2,
    explanation: "Sabbath rest embodies Psalm 103's truth: we are finite, dependent creatures, and that dependence is by design. On the seventh day we stop striving and rest in the Father's care.",
  },

  {
    id: "w1i-3-4-1",
    assessmentId: "w1a-3-4",
    question: "What common misunderstanding about God does the contrast between 'Old Testament Father' and 'New Testament Son' represent?",
    options: [
      "That the Father is stern and wrathful while the Son is gentle and forgiving",
      "That the Father only appears in Genesis",
      "That the Son existed before the Father",
      "That the Father and Son have different names",
    ],
    correctIndex: 0,
    explanation: "A widespread distortion casts the Father as harsh in the Old Testament and Jesus as gentle in the New. Scripture shows the Father has always been merciful (Exodus 34:6-7) and the Son always reflects the Father's character (John 14:9).",
  },
  {
    id: "w1i-3-4-2",
    assessmentId: "w1a-3-4",
    question: "In Hebrews 1:3, what Greek word — from which we derive the English word 'character' — describes the Son's relationship to the Father?",
    options: ["Logos", "Charakter", "Pneuma", "Agape"],
    correctIndex: 1,
    explanation: "The Greek word charakter means 'exact imprint,' like a seal pressed into wax. Hebrews uses this term to affirm that Jesus is the precise representation of the Father's nature.",
  },
  {
    id: "w1i-3-4-3",
    assessmentId: "w1a-3-4",
    question: "Why was Jonah angry when God spared Nineveh (Jonah 4:2)?",
    options: [
      "He did not believe God could save pagans",
      "He knew God was gracious and merciful and did not want that mercy extended to his enemies",
      "He thought God was too weak to destroy the city",
      "He had never heard of Exodus 34:6",
    ],
    correctIndex: 1,
    explanation: "Jonah explicitly quoted Exodus 34:6 — he knew God's merciful character. His anger was not from ignorance but from resenting that God would extend that mercy to Nineveh.",
  },
  {
    id: "w1i-3-4-4",
    assessmentId: "w1a-3-4",
    question: "Someone argues that a truly loving Father would never allow suffering or judgment. How does the Adventist understanding of the cross respond?",
    options: [
      "It agrees that a loving God would never judge",
      "It shows that the Father bore the full weight of justice in the Son so that mercy could flow without compromising justice",
      "It says suffering proves God is indifferent",
      "It avoids discussing suffering entirely",
    ],
    correctIndex: 1,
    explanation: "The cross demonstrates that the Father refuses to trivialize either justice or mercy. He bore the cost of justice in the Son so that forgiveness could be offered without pretending sin does not matter.",
  },
  {
    id: "w1i-3-4-5",
    assessmentId: "w1a-3-4",
    question: "What is wrong with reducing the Father to an abstract, unknowable philosophical principle?",
    options: [
      "Nothing — God is beyond human comprehension",
      "Scripture reveals the Father as a relational Person who names, calls, speaks, grieves, and rejoices",
      "Only the Son can be known personally",
      "The Father is a concept, not a Person",
    ],
    correctIndex: 1,
    explanation: "While the Father is transcendent, Scripture consistently portrays Him as a Person who engages relationally — He speaks, grieves, rejoices, and invites humans into covenant relationship.",
  },
];

export const belief4Lessons = [
  {
    id: "w1l-4-1",
    moduleId: "bmod-004",
    title: "Biblical Foundations: The Eternal Son",
    description: "Tracing the scriptural testimony to the pre-existence, deity, and incarnation of Jesus Christ.",
    lessonOrder: 1,
    anchorText: "John 1:1-3,14; Colossians 1:15-19; Philippians 2:5-11",
    anchorBookId: 43,
    anchorChapter: 1,
    anchorVerseStart: 1,
    anchorVerseEnd: 14,
    estimatedMinutes: 35,
  },
  {
    id: "w1l-4-2",
    moduleId: "bmod-004",
    title: "Doctrinal Formulation: Fully God, Fully Human",
    description: "Examining the Adventist affirmation that Jesus Christ possesses both complete deity and genuine humanity.",
    lessonOrder: 2,
    anchorText: "Hebrews 2:17-18; John 10:30; 1 Timothy 2:5",
    anchorBookId: 58,
    anchorChapter: 2,
    anchorVerseStart: 17,
    anchorVerseEnd: 18,
    estimatedMinutes: 30,
  },
  {
    id: "w1l-4-3",
    moduleId: "bmod-004",
    title: "Practical Implications: Christ in Daily Life",
    description: "Understanding how the person and work of Christ reshape identity, purpose, and daily practice.",
    lessonOrder: 3,
    anchorText: "Galatians 2:20; 2 Corinthians 5:17-19; Hebrews 4:15-16",
    anchorBookId: 48,
    anchorChapter: 2,
    anchorVerseStart: 20,
    anchorVerseEnd: 20,
    estimatedMinutes: 30,
  },
  {
    id: "w1l-4-4",
    moduleId: "bmod-004",
    title: "Misunderstandings & Challenges",
    description: "Confronting errors about Christ's nature, role, and authority — and restoring the biblical portrait.",
    lessonOrder: 4,
    anchorText: "John 5:22-23; Romans 6:23; Luke 24:25-27",
    anchorBookId: 43,
    anchorChapter: 5,
    anchorVerseStart: 22,
    anchorVerseEnd: 23,
    estimatedMinutes: 30,
  },
];

export const belief4Sections = [
  {
    id: "w1s-4-1-1",
    lessonId: "w1l-4-1",
    sectionType: "anchor",
    title: "Anchor Text",
    content:
      "Read the following passages carefully before proceeding:\n\n• John 1:1-3, 14 — The Word who was God became flesh\n• Colossians 1:15-19 — The supremacy and sufficiency of Christ\n• Philippians 2:5-11 — The self-emptying of the eternal Son",
    sortOrder: 1,
  },
  {
    id: "w1s-4-1-2",
    lessonId: "w1l-4-1",
    sectionType: "explain",
    title: "What Does This Mean?",
    content:
      "John's Gospel opens with a declaration that echoes Genesis 1:1: \"In the beginning was the Word.\" But John goes further. The Word was not created in the beginning; He already \"was.\" The imperfect tense in Greek (ēn) denotes continuous existence without a starting point. Before anything was made, the Word already existed — and He existed \"with God\" and \"was God.\" Two truths are held simultaneously: the Word is distinct from the Father (\"with God\") and shares the Father's nature (\"was God\").\n\nVerse 3 assigns all creative activity to the Word: \"All things were made through Him, and without Him nothing was made that was made.\" This is a comprehensive claim. There is no category of created reality that exists apart from the Son's creative agency. He is not part of creation; He is the source of it.\n\nVerse 14 introduces the staggering pivot: \"The Word became flesh and dwelt among us.\" The Greek eskēnōsen — \"tabernacled\" — deliberately recalls the Old Testament sanctuary where God's presence dwelt among Israel. The incarnation is the ultimate sanctuary: God taking up residence in human nature.\n\nColossians 1:15-19 adds structure to this portrait. Christ is \"the image of the invisible God, the firstborn over all creation.\" \"Firstborn\" (prōtotokos) is a title of rank and authority, not a statement about origin — the firstborn held supremacy over the household. Paul immediately clarifies: \"by Him all things were created\" (v. 16). The one who created all things cannot Himself be a created thing.\n\nPhilippians 2:5-11 reveals the cost. The Son existed \"in the form of God\" — sharing the very essence of deity — yet \"did not consider equality with God something to be grasped.\" He emptied Himself, took the form of a servant, and became obedient to death on a cross. This was not a demotion imposed from outside; it was a voluntary descent motivated by love.",
    sortOrder: 2,
  },
  {
    id: "w1s-4-1-3",
    lessonId: "w1l-4-1",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content:
      "Adventist Christology is anchored in the conviction that Jesus Christ is fully, eternally God — not a created being, not an exalted angel, not a lesser divine figure. This was not always unanimously held among early Adventist pioneers; some initially questioned the Son's co-eternity with the Father. But through careful Bible study and the confirmatory witness of Ellen G. White, the church came to affirm the full, eternal deity of Christ as a non-negotiable truth.\n\nThe Great Controversy framework depends on this. If the Son is not fully God, the cross cannot bear the weight of cosmic atonement. Only an infinite sacrifice can answer the infinite problem of sin. The Creator entering His own creation to rescue it from within — this is the scandal and the glory of the gospel.\n\nColossians 1:17 — \"in Him all things hold together\" — carries special significance for Adventist theology. Christ is not only the originator of creation but its sustainer. Every heartbeat, every orbit, every law of nature operates because the Son upholds it. This connects directly to the Adventist understanding of Sabbath: we rest on the seventh day because the One who holds all things together has declared that rest is good.\n\nThe Philippians hymn also shapes Adventist thinking about character and service. If the Lord of the universe stooped to wash feet and die on a cross, then no act of humble service is beneath His followers. The church's mission — health ministry, education, disaster relief — flows from a Savior who \"made Himself of no reputation\" for the sake of others.\n\nFor further exploration of Christ's pre-existence and deity, visit egwwritings.org and read the opening chapters of The Desire of Ages.",
    sortOrder: 3,
  },
  {
    id: "w1s-4-1-4",
    lessonId: "w1l-4-1",
    sectionType: "practice",
    title: "Daily Practice",
    content:
      "1. Read John 1:1-18 in a single sitting three times this week — once aloud. Each time, note a phrase or word you had not previously noticed. Record your observations.\n\n2. Memorize Philippians 2:5-8 over the course of the week. As you commit it to memory, ask yourself: what does the Son's voluntary self-emptying reveal about the nature of divine love?\n\n3. During your Sabbath worship this week, consciously reflect on Colossians 1:17 — the One you are worshiping is the same One who holds every atom of your body together. Let that awareness shape your praise.",
    sortOrder: 4,
  },
  {
    id: "w1s-4-1-5",
    lessonId: "w1l-4-1",
    sectionType: "reflection",
    title: "Personal Reflection",
    content:
      "1. John says the Word \"was God\" and then \"became flesh.\" What does it mean to you that the infinite God chose to inhabit a finite human body?\n\n2. Philippians 2 describes Jesus emptying Himself. What would it look like for you to adopt the same mindset in your relationships and responsibilities this week?",
    sortOrder: 5,
  },
  {
    id: "w1s-4-1-6",
    lessonId: "w1l-4-1",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of the biblical foundations for the eternal deity of the Son.",
    sortOrder: 6,
  },

  {
    id: "w1s-4-2-1",
    lessonId: "w1l-4-2",
    sectionType: "anchor",
    title: "Anchor Text",
    content:
      "Read the following passages carefully before proceeding:\n\n• Hebrews 2:17-18 — Christ made like His brothers in every respect\n• John 10:30 — \"I and My Father are one\"\n• 1 Timothy 2:5 — One mediator between God and humanity",
    sortOrder: 1,
  },
  {
    id: "w1s-4-2-2",
    lessonId: "w1l-4-2",
    sectionType: "explain",
    title: "What Does This Mean?",
    content:
      "Christian theology has always faced the challenge of holding two truths about Jesus Christ in tension: He is fully God, and He is fully human. The early church debated this for centuries, and the temptation to collapse one side into the other remains strong today.\n\nHebrews 2:17-18 stakes out the human side with unflinching clarity: \"In all things He had to be made like His brethren, that He might be a merciful and faithful High Priest.\" The word \"all\" is comprehensive. Jesus experienced hunger, exhaustion, grief, temptation, and death. His humanity was not a costume; it was real, bodily, and vulnerable. The author of Hebrews explains why this matters: \"In that He Himself has suffered, being tempted, He is able to aid those who are tempted.\" A savior who never faced genuine temptation could not genuinely sympathize.\n\nJohn 10:30 anchors the divine side: \"I and My Father are one.\" The response of the Jewish leaders confirms they understood the claim — they picked up stones because \"You, being a Man, make Yourself God\" (John 10:33). Jesus did not correct their interpretation. He affirmed absolute unity with the Father.\n\n1 Timothy 2:5 holds both realities together in a single phrase: \"There is one God and one Mediator between God and men, the Man Christ Jesus.\" A mediator must have standing with both parties. Only someone who is truly God can represent God to humanity; only someone who is truly human can represent humanity before God. Jesus alone occupies both positions.\n\nThe Adventist affirmation of Christ's two natures is not a philosophical puzzle to be solved but a gospel reality to be proclaimed. Because He is God, His sacrifice has infinite value. Because He is human, He stands beside us as a brother who understands.",
    sortOrder: 2,
  },
  {
    id: "w1s-4-2-3",
    lessonId: "w1l-4-2",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content:
      "The Adventist doctrine of Christ's nature carries direct implications for the sanctuary and judgment teachings. In the heavenly sanctuary, Christ serves as our High Priest — a role that requires genuine humanity (Hebrews 2:17). He does not plead our case as a distant deity; He intercedes as one who wore our flesh, bore our sorrows, and conquered our temptations. His mediation is experiential, not theoretical.\n\nAdventists have historically discussed the precise nature of Christ's human flesh — whether He took Adam's pre-fall or post-fall nature. While the church has not issued a dogmatic ruling on this question, the biblical emphasis is clear: Christ was \"in all points tempted as we are, yet without sin\" (Hebrews 4:15). Whatever position one holds, two boundaries must be maintained: Christ's temptations were real (not staged), and He never sinned (not even internally).\n\nThe Great Controversy framework adds urgency to this doctrine. Satan argued that God's law cannot be kept, that obedience is impossible. By living a fully human life of complete obedience, Jesus answered that charge. He demonstrated that a human being, dependent on the Father and empowered by the Spirit, can reflect God's character — and He did so under conditions far harder than Eden.\n\n1 Timothy 2:5 also undergirds the Adventist rejection of any earthly priestly mediator between God and the believer. Christ alone holds that office. No human institution, no saint, no ritual can substitute for His direct, personal intercession. This conviction shapes Adventist worship: we come directly to the Father through the Son, without human intermediaries.",
    sortOrder: 3,
  },
  {
    id: "w1s-4-2-4",
    lessonId: "w1l-4-2",
    sectionType: "practice",
    title: "Daily Practice",
    content:
      "1. Read Hebrews 2:14-18 and 4:14-16 together this week. When you face a specific temptation or trial, pause and speak aloud: \"Jesus, You experienced this. You understand. Help me now.\" Let His humanity make your prayer concrete.\n\n2. Spend fifteen minutes journaling on 1 Timothy 2:5. What does it mean for your prayer life that you need no mediator other than Christ? How does this truth simplify or deepen the way you approach God?\n\n3. Identify one area of your life where you tend to feel that God cannot understand your struggle. Bring that specific area to Hebrews 2:18 and ask the Spirit to help you trust that Jesus has already walked that ground.",
    sortOrder: 4,
  },
  {
    id: "w1s-4-2-5",
    lessonId: "w1l-4-2",
    sectionType: "reflection",
    title: "Personal Reflection",
    content:
      "1. Does it comfort or challenge you to know that Jesus was tempted \"in all points\" as you are? Why?\n\n2. How does the truth that Christ is the sole Mediator between God and humanity affect the way you think about religious authority and institutions?\n\n3. If a friend asked, \"Why does it matter that Jesus was both God and human — why not just one or the other?\" how would you answer?",
    sortOrder: 5,
  },
  {
    id: "w1s-4-2-6",
    lessonId: "w1l-4-2",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of the Adventist affirmation that Christ is fully God and fully human.",
    sortOrder: 6,
  },

  {
    id: "w1s-4-3-1",
    lessonId: "w1l-4-3",
    sectionType: "anchor",
    title: "Anchor Text",
    content:
      "Read the following passages carefully before proceeding:\n\n• Galatians 2:20 — \"I have been crucified with Christ; it is no longer I who live, but Christ lives in me\"\n• 2 Corinthians 5:17-19 — The new creation and the ministry of reconciliation\n• Hebrews 4:15-16 — A High Priest who sympathizes and invites us to the throne of grace",
    sortOrder: 1,
  },
  {
    id: "w1s-4-3-2",
    lessonId: "w1l-4-3",
    sectionType: "explain",
    title: "What Does This Mean?",
    content:
      "Paul's declaration in Galatians 2:20 is among the most radical statements in Scripture. \"I have been crucified with Christ\" — the old self, with its enslaving patterns and self-centered ambitions, has been put to death. \"It is no longer I who live, but Christ lives in me\" — the believer's identity is no longer self-constructed but Christ-inhabited. This is not mystical absorption; Paul immediately adds, \"the life which I now live in the flesh I live by faith in the Son of God, who loved me and gave Himself for me.\" The Christian still lives a concrete, embodied life — but the animating principle has changed from self to Christ.\n\nThis inner transformation produces outward results. 2 Corinthians 5:17 announces: \"If anyone is in Christ, he is a new creation; old things have passed away; behold, all things have become new.\" Paul does not say \"improved\" or \"upgraded\" — he says \"new creation.\" The language deliberately echoes Genesis. What God did at the dawn of time — calling something out of nothing — He does again in the life of every person who is united to Christ. And this new creation carries a mission: God has given us \"the ministry of reconciliation\" (v. 18). Those who have been reconciled to God now carry that message to others.\n\nHebrews 4:15-16 assures us that this life of faith is not a solo endeavor. We have a High Priest who \"was in all points tempted as we are, yet without sin.\" Because of this, we can \"come boldly to the throne of grace, that we may obtain mercy and find grace to help in time of need.\" The throne is not a courtroom bench before which we cower; it is a throne of grace to which we are invited — boldly.",
    sortOrder: 2,
  },
  {
    id: "w1s-4-3-3",
    lessonId: "w1l-4-3",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content:
      "Adventist theology holds together what some traditions separate: justification (God's declaration that we are righteous in Christ) and sanctification (the Spirit's ongoing work of transforming our character). Galatians 2:20 captures this unity. \"I have been crucified with Christ\" speaks to the definitive break with sin's dominion — justification. \"Christ lives in me\" describes the ongoing reality of sanctification — Christ's character being formed within the believer.\n\nThis is not salvation by works. The entire process is powered by grace received through faith. But Adventists resist any theology that treats justification as the whole story and sanctification as optional. The new creation of 2 Corinthians 5:17 is real, not merely positional. Regenerated lives bear visible fruit: changed habits, restored relationships, service to others.\n\nThe \"ministry of reconciliation\" (2 Corinthians 5:18-19) connects directly to the Adventist sense of mission. The church exists not for itself but to carry the Father's reconciling love to every nation, tribe, and tongue. Health ministries, education, community service, and the proclamation of the three angels' messages all flow from the conviction that God has entrusted this ministry to His people.\n\nHebrews 4:15-16 undergirds the Adventist sanctuary teaching. The heavenly High Priest is not a distant theological concept; He is an active, sympathetic intercessor who understands human struggle from the inside. Coming \"boldly to the throne of grace\" is not presumption — it is the privilege purchased by Christ's blood and sustained by His ongoing ministry.",
    sortOrder: 3,
  },
  {
    id: "w1s-4-3-4",
    lessonId: "w1l-4-3",
    sectionType: "practice",
    title: "Daily Practice",
    content:
      "1. Each morning this week, read Galatians 2:20 aloud and then ask: \"What does it look like for Christ to live in me today — in my conversations, my work, my relationships?\" Write one specific intention.\n\n2. Identify one relationship in your life that needs reconciliation. Take a concrete step this week — a phone call, a letter, a conversation — that reflects the ministry of reconciliation God has given you (2 Corinthians 5:18).\n\n3. When you face a moment of weakness or temptation, practice the Hebrews 4:16 response: approach the throne of grace boldly. Speak to Jesus as one who understands, and ask for grace in that specific moment.",
    sortOrder: 4,
  },
  {
    id: "w1s-4-3-5",
    lessonId: "w1l-4-3",
    sectionType: "reflection",
    title: "Personal Reflection",
    content:
      "1. Paul says he has been \"crucified with Christ.\" What part of your old self do you find hardest to let go of, and how does Christ's indwelling life address that struggle?\n\n2. 2 Corinthians 5:17 calls you a \"new creation.\" In what specific ways has your life changed since encountering Christ? Where do you long to see more transformation?\n\n3. Do you tend to approach God's throne timidly or boldly (Hebrews 4:16)? What would change if you truly believed the throne is one of grace?",
    sortOrder: 5,
  },
  {
    id: "w1s-4-3-6",
    lessonId: "w1l-4-3",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of how Christ's person and work shape daily Christian living.",
    sortOrder: 6,
  },

  {
    id: "w1s-4-4-1",
    lessonId: "w1l-4-4",
    sectionType: "anchor",
    title: "Anchor Text",
    content:
      "Read the following passages carefully before proceeding:\n\n• John 5:22-23 — The Father has committed all judgment to the Son\n• Romans 6:23 — The wages of sin and the gift of God\n• Luke 24:25-27 — Jesus opens the Scriptures concerning Himself",
    sortOrder: 1,
  },
  {
    id: "w1s-4-4-2",
    lessonId: "w1l-4-4",
    sectionType: "explain",
    title: "What Does This Mean?",
    content:
      "Several persistent misunderstandings about the Son circulate in popular religious thought. Addressing them directly strengthens faith and sharpens witness.\n\nThe first error reduces Jesus to a great moral teacher but denies His deity. This position cannot survive contact with Jesus' own claims. In John 5:22-23, Jesus states that the Father \"has committed all judgment to the Son, that all should honor the Son just as they honor the Father.\" Receiving the same honor as the Father is a claim no mere teacher could make without blasphemy. Jesus did not leave the \"good teacher\" option open; He claimed divine prerogatives and accepted worship.\n\nA second error treats salvation as something humans earn through moral effort, with Jesus serving merely as an example. Romans 6:23 dismantles this: \"The wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.\" Eternal life is a gift, not a wage. The problem of sin is not a behavioral deficit that better effort can fix; it is a death sentence that only divine intervention can reverse. Jesus is not merely a model to imitate but a Savior who accomplished what no human effort could achieve.\n\nA third misunderstanding separates Jesus from the Old Testament, as if He appears only in Matthew through Revelation. Luke 24:25-27 corrects this powerfully. On the road to Emmaus, the risen Christ \"beginning at Moses and all the Prophets, expounded to them in all the Scriptures the things concerning Himself.\" The entire Old Testament — law, prophets, psalms — points to and finds its fulfillment in the Son. He is not a New Testament addition; He is the subject of the whole Bible.\n\nA fourth error treats Jesus' sacrifice as a transaction that changed the Father's mind — as though the cross persuaded an angry God to forgive. Scripture tells a different story. God \"so loved the world that He gave His only begotten Son\" (John 3:16). The cross originated in the Father's love, not in spite of it. Father and Son acted together in the plan of salvation from before the foundation of the world.",
    sortOrder: 2,
  },
  {
    id: "w1s-4-4-3",
    lessonId: "w1l-4-4",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content:
      "Adventist theology confronts each of these errors through its distinctive doctrinal framework.\n\nThe deity of Christ is essential to the sanctuary teaching. If Jesus were merely human, His priestly ministry in the heavenly sanctuary would carry no more weight than any earthly priest's. Because He is the eternal Son — \"I and My Father are one\" (John 10:30) — His intercession is effectual and His sacrifice sufficient for all humanity across all ages.\n\nThe gift-nature of salvation (Romans 6:23) aligns with the Adventist emphasis on righteousness by faith. The 1888 message delivered by Jones and Waggoner, and affirmed in principle by Ellen G. White, stressed that Christ's righteousness is received by faith, not earned by law-keeping. Obedience flows from salvation; it does not produce it. The law reveals our need; Christ meets it.\n\nThe Christ-centered reading of the Old Testament (Luke 24:27) is foundational to Adventist prophetic interpretation. Daniel's prophecies, the sanctuary typology, the Sabbath institution, the sacrificial system — all of these point forward to Christ and find their meaning in Him. An Adventist who reads Daniel 8-9 without seeing Christ at the center has missed the point of the prophecy.\n\nFinally, the Great Controversy perspective guards against the error of pitting Father against Son. Satan's accusation is precisely that God is unwilling to forgive, that His law demands blood to satisfy wounded pride. The cross reveals the opposite: the Father gave His most precious gift because His love demanded it, not because His anger required appeasement. The atonement is the Father and the Son working in perfect unity to rescue humanity and vindicate divine love.\n\nFor deeper study on Christ in the Old Testament Scriptures, visit egwwritings.org and explore Patriarchs and Prophets.",
    sortOrder: 3,
  },
  {
    id: "w1s-4-4-4",
    lessonId: "w1l-4-4",
    sectionType: "practice",
    title: "Daily Practice",
    content:
      "1. Read Luke 24:13-35 in full this week. As you read other parts of the Old Testament during your devotional time, practice the Emmaus method: ask, \"Where is Christ in this passage?\" Record your discoveries.\n\n2. Prepare a brief, personal response to the statement: \"Jesus was a good teacher, but not God.\" Use John 5:22-23 and one other passage as your foundation. Practice saying it aloud until it feels natural.\n\n3. Reflect on Romans 6:23 each evening. Before sleep, thank God specifically for one aspect of the gift of eternal life that you experienced or were reminded of that day.",
    sortOrder: 4,
  },
  {
    id: "w1s-4-4-5",
    lessonId: "w1l-4-4",
    sectionType: "reflection",
    title: "Personal Reflection",
    content:
      "1. Which of the four misunderstandings about Jesus discussed in this lesson have you encountered most often — in your own thinking or in conversations with others? How has this lesson equipped you to respond?\n\n2. Jesus said the Father committed all judgment to the Son (John 5:22). How does it change your view of the judgment to know that the One who judges you is the same One who died for you?\n\n3. Romans 6:23 calls eternal life a \"gift.\" Are there areas of your spiritual life where you still operate as though you need to earn God's favor? What would it look like to receive rather than achieve?",
    sortOrder: 5,
  },
  {
    id: "w1s-4-4-6",
    lessonId: "w1l-4-4",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of common misunderstandings about the Son.",
    sortOrder: 6,
  },
];

export const belief4Assessments = [
  { id: "w1a-4-1", lessonId: "w1l-4-1", title: "The Eternal Son Assessment", passingScore: 70 },
  { id: "w1a-4-2", lessonId: "w1l-4-2", title: "Fully God Fully Human Assessment", passingScore: 70 },
  { id: "w1a-4-3", lessonId: "w1l-4-3", title: "Christ in Daily Life Assessment", passingScore: 70 },
  { id: "w1a-4-4", lessonId: "w1l-4-4", title: "Son Misunderstandings Assessment", passingScore: 70 },
];

export const belief4Items = [
  {
    id: "w1i-4-1-1",
    assessmentId: "w1a-4-1",
    question: "What does the Greek imperfect tense of 'was' (ēn) in John 1:1 indicate about the Word?",
    options: [
      "The Word was created at the beginning of time",
      "The Word already existed continuously before anything was made",
      "The Word appeared briefly and then departed",
      "The Word came into existence when the world was created",
    ],
    correctIndex: 1,
    explanation: "The imperfect tense ēn indicates ongoing, continuous existence without a point of origin. The Word did not begin at creation — He already 'was' before it.",
  },
  {
    id: "w1i-4-1-2",
    assessmentId: "w1a-4-1",
    question: "In Colossians 1:15, what does the title 'firstborn over all creation' mean?",
    options: [
      "Christ was the first creature God made",
      "Christ was born before all other humans",
      "It is a title of rank and supremacy, not a statement about origin",
      "Christ inherited creation from the Father",
    ],
    correctIndex: 2,
    explanation: "Prōtotokos ('firstborn') is a title of supremacy and authority, as clarified by the immediate context: 'by Him all things were created' (v. 16). The Creator of all cannot be part of creation.",
  },
  {
    id: "w1i-4-1-3",
    assessmentId: "w1a-4-1",
    question: "According to Philippians 2:6-7, what did the Son do with His equality with God?",
    options: [
      "He demanded that others recognize it",
      "He lost it permanently at the incarnation",
      "He did not consider it something to be grasped but emptied Himself voluntarily",
      "He shared it equally with all angels",
    ],
    correctIndex: 2,
    explanation: "Philippians 2 describes a voluntary self-emptying. The Son chose not to cling to divine prerogatives but took the form of a servant out of love.",
  },
  {
    id: "w1i-4-1-4",
    assessmentId: "w1a-4-1",
    question: "Why does the Adventist Great Controversy framework require the Son to be fully, eternally God rather than a created being?",
    options: [
      "A created savior would be impressive enough",
      "Only an infinite sacrifice by the Creator Himself can answer the infinite problem of sin and vindicate God's character before the universe",
      "The distinction between Creator and creature does not matter theologically",
      "The Great Controversy is only about power, not character",
    ],
    correctIndex: 1,
    explanation: "If the Son were created, His death could not carry infinite atoning value. The Great Controversy demands that the Creator Himself entered creation to vindicate the Father's character and rescue humanity.",
  },
  {
    id: "w1i-4-1-5",
    assessmentId: "w1a-4-1",
    question: "John 1:14 says the Word 'dwelt' (eskēnōsen) among us. What Old Testament concept does this Greek word deliberately echo?",
    options: [
      "The throne room in heaven",
      "The burning bush",
      "The tabernacle/sanctuary where God's presence dwelt among Israel",
      "The garden of Eden",
    ],
    correctIndex: 2,
    explanation: "Eskēnōsen means 'tabernacled.' It directly recalls the Old Testament sanctuary where God's presence resided among His people. The incarnation is the ultimate sanctuary — God dwelling in human flesh.",
  },

  {
    id: "w1i-4-2-1",
    assessmentId: "w1a-4-2",
    question: "According to Hebrews 2:17, why did Jesus have to be made like His brothers 'in all things'?",
    options: [
      "So that He could understand philosophy",
      "So that He could be a merciful and faithful High Priest",
      "So that He could avoid death",
      "So that He could become an angel",
    ],
    correctIndex: 1,
    explanation: "Hebrews 2:17 states that Jesus was made like His brothers in all things specifically so He could serve as a merciful and faithful High Priest who truly understands human experience.",
  },
  {
    id: "w1i-4-2-2",
    assessmentId: "w1a-4-2",
    question: "What was the response of the Jewish leaders when Jesus said 'I and My Father are one' (John 10:30)?",
    options: [
      "They praised Him",
      "They ignored Him",
      "They picked up stones to kill Him for claiming to be God",
      "They asked Him to explain further",
    ],
    correctIndex: 2,
    explanation: "The Jewish leaders understood that Jesus was claiming deity and responded by attempting to stone Him for blasphemy (John 10:33). Jesus did not correct their interpretation.",
  },
  {
    id: "w1i-4-2-3",
    assessmentId: "w1a-4-2",
    question: "According to 1 Timothy 2:5, why must the Mediator between God and humanity be both divine and human?",
    options: [
      "A mediator must have standing with only one party",
      "A mediator must have standing with both parties — only one who is God can represent God, and only one who is human can represent humanity",
      "The mediator's nature is irrelevant to the role",
      "A purely divine mediator would be sufficient",
    ],
    correctIndex: 1,
    explanation: "A mediator bridges two parties. Christ's full deity qualifies Him to represent God; His full humanity qualifies Him to represent us. Only He occupies both positions.",
  },
  {
    id: "w1i-4-2-4",
    assessmentId: "w1a-4-2",
    question: "A new believer asks: 'If Jesus was really God, how could He genuinely be tempted?' How would you respond using Hebrews 2:17-18 and 4:15?",
    options: [
      "His temptations were not real — they were staged for our benefit",
      "He stopped being God during the incarnation",
      "His humanity was genuine and complete; He experienced real temptation through His human nature, yet never sinned",
      "Temptation only affects beings who are entirely human",
    ],
    correctIndex: 2,
    explanation: "Hebrews affirms that Christ's temptations were real and that He 'suffered, being tempted' (2:18). His humanity was genuine — He faced temptation through His human nature and overcame by dependence on the Father.",
  },
  {
    id: "w1i-4-2-5",
    assessmentId: "w1a-4-2",
    question: "Why do Adventists reject the idea that any earthly priest or saint can serve as mediator between God and believers?",
    options: [
      "Because earthly priests are too busy",
      "Because 1 Timothy 2:5 declares there is one Mediator — the Man Christ Jesus — and His intercession is fully sufficient",
      "Because priests have never existed in Christianity",
      "Because only angels can mediate",
    ],
    correctIndex: 1,
    explanation: "Scripture declares one Mediator. Christ's priesthood is unique, personal, and all-sufficient. No human institution or individual can replace or supplement His intercession.",
  },

  {
    id: "w1i-4-3-1",
    assessmentId: "w1a-4-3",
    question: "In Galatians 2:20, what does Paul mean when he says 'I have been crucified with Christ'?",
    options: [
      "Paul literally died on a cross",
      "Paul's old self-centered identity has been put to death, and his life is now animated by Christ",
      "Paul stopped living entirely",
      "Paul was physically tortured alongside Jesus",
    ],
    correctIndex: 1,
    explanation: "Paul uses crucifixion as a metaphor for the death of his old, self-centered way of living. His identity is now rooted in Christ, who lives in and through him.",
  },
  {
    id: "w1i-4-3-2",
    assessmentId: "w1a-4-3",
    question: "What Old Testament concept does Paul deliberately echo when he calls believers a 'new creation' in 2 Corinthians 5:17?",
    options: [
      "The flood of Noah",
      "The Exodus from Egypt",
      "The original creation in Genesis",
      "The Tower of Babel",
    ],
    correctIndex: 2,
    explanation: "The phrase 'new creation' echoes Genesis, where God called something out of nothing. What God did at creation He does again in the life of every person united to Christ.",
  },
  {
    id: "w1i-4-3-3",
    assessmentId: "w1a-4-3",
    question: "According to 2 Corinthians 5:18-19, what ministry has God given to those who are reconciled to Him?",
    options: [
      "The ministry of judgment",
      "The ministry of reconciliation",
      "The ministry of isolation",
      "The ministry of self-improvement",
    ],
    correctIndex: 1,
    explanation: "Those who have been reconciled to God are entrusted with the ministry of reconciliation — carrying the Father's restoring love to others.",
  },
  {
    id: "w1i-4-3-4",
    assessmentId: "w1a-4-3",
    question: "How does the Adventist understanding of Hebrews 4:15-16 shape the way believers should approach God in prayer?",
    options: [
      "With fear and distance, because God is holy",
      "Boldly, because the throne is one of grace and our High Priest fully understands human struggle",
      "Only through elaborate rituals",
      "Indifferently, since God already knows everything",
    ],
    correctIndex: 1,
    explanation: "Because Christ has experienced human temptation and serves as our sympathetic High Priest, we are invited to come boldly — not timidly — to the throne of grace for mercy and help.",
  },
  {
    id: "w1i-4-3-5",
    assessmentId: "w1a-4-3",
    question: "How do Adventists hold together justification and sanctification in light of Galatians 2:20?",
    options: [
      "Justification is enough; sanctification is unnecessary",
      "Sanctification earns justification",
      "'Crucified with Christ' speaks to the definitive break with sin's dominion (justification), while 'Christ lives in me' describes the ongoing transformation of character (sanctification) — both by grace through faith",
      "They are identical concepts with no distinction",
    ],
    correctIndex: 2,
    explanation: "Galatians 2:20 captures the unity of justification and sanctification. Both are powered by grace through faith — the decisive break from sin and the ongoing formation of Christ's character in the believer.",
  },

  {
    id: "w1i-4-4-1",
    assessmentId: "w1a-4-4",
    question: "In John 5:22-23, what does Jesus say the Father has committed entirely to the Son?",
    options: ["Creation", "Judgment", "The giving of the law", "The governance of angels"],
    correctIndex: 1,
    explanation: "Jesus states that the Father 'has committed all judgment to the Son, that all should honor the Son just as they honor the Father.' This is a claim to divine prerogative.",
  },
  {
    id: "w1i-4-4-2",
    assessmentId: "w1a-4-4",
    question: "Why does the claim that 'Jesus was just a good teacher' fail to account for His own words?",
    options: [
      "Because good teachers never discuss morality",
      "Because Jesus accepted divine honor and claimed equality with the Father — a good teacher who is not God would be committing blasphemy",
      "Because teachers in the first century were not respected",
      "Because Jesus never claimed to teach anything",
    ],
    correctIndex: 1,
    explanation: "Jesus claimed to receive the same honor as the Father (John 5:23), accepted worship, and asserted authority over life and death. These claims force a choice: He is who He claimed to be, or He is not merely a good teacher.",
  },
  {
    id: "w1i-4-4-3",
    assessmentId: "w1a-4-4",
    question: "According to Romans 6:23, what is the relationship between eternal life and human effort?",
    options: [
      "Eternal life is earned through moral achievement",
      "Eternal life is a gift of God, not a wage earned by human effort",
      "Only certain people deserve eternal life",
      "Eternal life requires a combination of faith and sufficient good works",
    ],
    correctIndex: 1,
    explanation: "Paul contrasts wages (what sin earns — death) with gift (what God gives — eternal life). Salvation is received, not achieved.",
  },
  {
    id: "w1i-4-4-4",
    assessmentId: "w1a-4-4",
    question: "In Luke 24:25-27, what did the risen Jesus do to help the Emmaus disciples understand His identity?",
    options: [
      "He performed a miracle in front of them",
      "He showed them His wounds",
      "Beginning with Moses and all the Prophets, He expounded the things concerning Himself in all the Scriptures",
      "He asked them to read the New Testament",
    ],
    correctIndex: 2,
    explanation: "Jesus opened the entire Old Testament — from Moses through the Prophets — to show that all of Scripture points to Him. The Old Testament is not separate from Christ; He is its central subject.",
  },
  {
    id: "w1i-4-4-5",
    assessmentId: "w1a-4-4",
    question: "Someone says the cross was needed to change the Father's mind about forgiving humanity. How does the Adventist Great Controversy perspective correct this?",
    options: [
      "It agrees that the Father needed convincing",
      "It teaches that the cross originated in the Father's love — Father and Son acted together to rescue humanity, not against each other",
      "It says the cross was unnecessary",
      "It ignores the Father's role entirely",
    ],
    correctIndex: 1,
    explanation: "John 3:16 makes clear that 'God so loved the world that He gave His only begotten Son.' The cross was the Father's initiative, born from love. The Great Controversy shows Father and Son working in perfect unity.",
  },
];
