export const belief8Lessons = [
  {
    id: "w2l-8-1",
    moduleId: "bmod-008",
    title: "Biblical Foundations: The Cosmic Conflict",
    description: "Tracing the origin, nature, and scope of the great controversy between Christ and Satan through the Bible's own testimony — from the rebellion in heaven to its consequences on earth.",
    lessonOrder: 1,
    anchorText: "Revelation 12:7-12; Isaiah 14:12-14; Ezekiel 28:12-18",
    anchorBookId: 66,
    anchorChapter: 12,
    anchorVerseStart: 7,
    anchorVerseEnd: 12,
    estimatedMinutes: 35,
  },
  {
    id: "w2l-8-2",
    moduleId: "bmod-008",
    title: "Doctrinal Formulation: The Adventist Great Controversy Theme",
    description: "Examining what Seventh-day Adventists specifically affirm about the cosmic conflict — its entrance into human history through the fall, the role of the cross, and the vindication of God's character.",
    lessonOrder: 2,
    anchorText: "Genesis 3:1-15; Romans 5:12-21; 1 John 3:8",
    anchorBookId: 1,
    anchorChapter: 3,
    anchorVerseStart: 1,
    anchorVerseEnd: 15,
    estimatedMinutes: 30,
  },
  {
    id: "w2l-8-3",
    moduleId: "bmod-008",
    title: "Practical Implications: Living in the Conflict",
    description: "Understanding how the reality of cosmic warfare shapes daily Christian experience — from spiritual armor to the assurance of God's sustaining love amid suffering and temptation.",
    lessonOrder: 3,
    anchorText: "Ephesians 6:10-18; Romans 8:28-39; 2 Corinthians 10:3-5",
    anchorBookId: 49,
    anchorChapter: 6,
    anchorVerseStart: 10,
    anchorVerseEnd: 18,
    estimatedMinutes: 30,
  },
  {
    id: "w2l-8-4",
    moduleId: "bmod-008",
    title: "Misunderstandings & Challenges",
    description: "Addressing the hardest questions the great controversy raises — the problem of evil, God's apparent inaction, and the groaning of a creation caught in a war it did not choose.",
    lessonOrder: 4,
    anchorText: "Job 1:6-12; Habakkuk 1:13; Romans 8:19-22",
    anchorBookId: 18,
    anchorChapter: 1,
    anchorVerseStart: 6,
    anchorVerseEnd: 12,
    estimatedMinutes: 30,
  },
];

export const belief8Sections = [
  // ── Lesson 1: Biblical Foundations ──────────────────────────────
  {
    id: "w2s-8-1-1",
    lessonId: "w2l-8-1",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"And war broke out in heaven: Michael and his angels fought with the dragon; and the dragon and his angels fought, but they did not prevail, nor was a place found for them in heaven any longer. So the great dragon was cast out, that serpent of old, called the Devil and Satan, who deceives the whole world; he was cast to the earth, and his angels were cast out with him. Then I heard a loud voice saying in heaven, 'Now salvation, and strength, and the kingdom of our God, and the power of His Christ have come, for the accuser of our brethren, who accused them before our God day and night, has been cast down.'\" — Revelation 12:7-10 (NKJV)\n\n\"How you are fallen from heaven, O Lucifer, son of the morning! How you are cut down to the ground, you who weakened the nations! For you have said in your heart: 'I will ascend into heaven, I will exalt my throne above the stars of God… I will be like the Most High.'\" — Isaiah 14:12-14 (NKJV)\n\n\"You were the anointed cherub who covers; I established you; you were on the holy mountain of God… You were perfect in your ways from the day you were created, till iniquity was found in you.\" — Ezekiel 28:14-15 (NKJV)",
    sortOrder: 1,
  },
  {
    id: "w2s-8-1-2",
    lessonId: "w2l-8-1",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Revelation 12 pulls back the curtain on an event most of Scripture only hints at: a war that began before any human drew breath. The combatants are staggering — Michael (a title for Christ in His role as heaven's commander) and the dragon, identified explicitly as \"that serpent of old, called the Devil and Satan.\" John's language is deliberate: by linking the dragon to the serpent of Genesis 3, he frames the entire biblical narrative as a single, continuous conflict. What Adam and Eve encountered in Eden was not the opening act but the earthward extension of a rebellion already underway in the courts of heaven.\n\nIsaiah 14:12-14 supplies the motive. Five times the rebel declares \"I will\" — I will ascend, I will exalt my throne, I will sit on the mount of the congregation, I will ascend above the heights of the clouds, I will be like the Most High. The repetition is revealing. The conflict did not begin with a dispute over policy or territory; it began with a creature's determination to occupy the place that belongs to God alone. Pride — self-exaltation pursued to its logical extreme — is the taproot of every subsequent evil.\n\nEzekiel 28:12-18 adds a dimension that makes the tragedy sharper. The being described was \"perfect in your ways from the day you were created.\" He was not fashioned with a flaw that made rebellion inevitable. He stood in the presence of God on the holy mountain, adorned and anointed, and chose — freely, without external coercion — to turn inward. Iniquity was \"found\" in him, the Hebrew verb suggesting something that surfaced from within, not something imposed from without.\n\nThe convergence of these three texts establishes the biblical framework for the great controversy: a personal, intelligent adversary who originated in God's immediate presence, who fell through self-generated pride, and who carries on a war that now encompasses the earth and every person on it. This is not mythology or metaphor. Scripture presents it as history — cosmic history that gives meaning to every smaller struggle humans face.",
    sortOrder: 2,
  },
  {
    id: "w2s-8-1-3",
    lessonId: "w2l-8-1",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "The great controversy is not merely one doctrine among many in Adventist theology — it is the interpretive lens through which all other doctrines come into focus. Where other Christian traditions may treat the problem of evil as a philosophical puzzle, Adventism reads it as a narrative with a beginning, a decisive turning point, and a promised resolution.\n\n**Origin in freedom, not in God.** The fact that Lucifer was created perfect and fell by choice protects two truths simultaneously: God is not the author of evil, and genuine freedom is real. A universe of love requires the possibility of rejection. The risk God took in creating free beings was not recklessness but the only alternative to a cosmos of programmed obedience — which would not be a cosmos of love at all.\n\n**Satan's accusation against God's character.** At its core, the controversy is a courtroom drama. Satan's rebellion was accompanied by charges against God — that His law is arbitrary, that His government is unjust, that obedience is impossible and therefore unfair to require. These accusations could not be silenced by raw power; they had to be answered by demonstration. This is why the conflict has been permitted to run its course rather than being crushed at its inception. Every generation of human history provides additional evidence that sin produces misery, while God's character remains consistently self-giving.\n\n**The scope of the conflict.** Revelation 12:9 says Satan \"deceives the whole world.\" Romans 8:19-22 adds that creation itself groans under the weight of this conflict. The controversy is not limited to spiritual transactions; it touches nature, nations, families, and individual hearts. Adventists understand natural disasters, systemic injustice, and personal suffering not as evidence of God's absence but as symptoms of a world caught in a war zone.\n\n**Heaven's interest in the outcome.** Paul notes in 1 Corinthians 4:9 that believers have become \"a spectacle to the world, both to angels and to men.\" The watching universe is not passive entertainment; unfallen beings observe how God handles the crisis of sin because the resolution will establish the security of the universe for eternity. God's justice must be seen to be just — not merely declared.",
    sortOrder: 3,
  },
  {
    id: "w2s-8-1-4",
    lessonId: "w2l-8-1",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Begin to see your daily experience through the lens of the cosmic conflict:\n\n1. **Map the five \"I wills.\"** Read Isaiah 14:12-14 slowly and identify each self-exalting declaration. Then examine your own week: where did you catch yourself placing your will above God's? Write down one specific instance and offer it back to God in prayer.\n\n2. **Read Revelation 12:7-12 as personal assurance.** Verse 11 says the saints overcame the accuser \"by the blood of the Lamb and by the word of their testimony.\" Before bed each night this week, name one area where you feel accused or defeated, and consciously place it under the blood of Christ.\n\n3. **Engage someone else with the big picture.** Share the great controversy framework with a friend, family member, or study partner who may not be familiar with it. Use simple language: \"The Bible describes a conflict that started in heaven and explains why the world is the way it is.\" Invite their questions.",
    sortOrder: 4,
  },
  {
    id: "w2s-8-1-5",
    lessonId: "w2l-8-1",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Ezekiel says Lucifer was \"perfect in your ways\" until iniquity was found in him. How does the knowledge that evil originated in a perfect being affect your understanding of temptation in your own life — does it increase your vigilance or your compassion, or both?\n\n2. If the great controversy is real, how does that change the way you interpret suffering — your own and the suffering you see in the world around you?\n\n3. Revelation 12:11 says the saints overcame by the blood of the Lamb and the word of their testimony. What part of your own story testifies to God's faithfulness in the midst of conflict?",
    sortOrder: 5,
  },
  {
    id: "w2s-8-1-6",
    lessonId: "w2l-8-1",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of the biblical foundations of the cosmic conflict.",
    sortOrder: 6,
  },

  // ── Lesson 2: Doctrinal Formulation ────────────────────────────
  {
    id: "w2s-8-2-1",
    lessonId: "w2l-8-2",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"Now the serpent was more cunning than any beast of the field which the Lord God had made. And he said to the woman, 'Has God indeed said, \"You shall not eat of every tree of the garden\"?'… And I will put enmity between you and the woman, and between your seed and her Seed; He shall bruise your head, and you shall bruise His heel.\" — Genesis 3:1, 15 (NKJV)\n\n\"Therefore, just as through one man sin entered the world, and death through sin, and thus death spread to all men, because all sinned… But the free gift is not like the offense. For if by the one man's offense many died, much more the grace of God and the gift by the grace of the one Man, Jesus Christ, abounded to many.\" — Romans 5:12, 15 (NKJV)\n\n\"He who sins is of the devil, for the devil has sinned from the beginning. For this purpose the Son of God was manifested, that He might destroy the works of the devil.\" — 1 John 3:8 (NKJV)",
    sortOrder: 1,
  },
  {
    id: "w2s-8-2-2",
    lessonId: "w2l-8-2",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Genesis 3 records the moment the heavenly war became a human war. The serpent's opening question — \"Has God indeed said?\" — is not a request for information; it is the first theological attack on earth. Satan's strategy is to distort God's word, reframe God's generosity as restriction, and cast doubt on God's motives. The tactic has not changed in thousands of years. Every temptation still carries an embedded accusation: God is withholding something good from you.\n\nGenesis 3:15 — sometimes called the protoevangelium, or \"first gospel\" — is God's immediate response to the catastrophe. Before pronouncing consequences on Adam and Eve, God addresses the serpent and announces the conflict's eventual outcome: the Seed of the woman will crush the serpent's head, though at the cost of His own wounding. The entire redemptive plan is compressed into a single verse. The cross is visible in Eden.\n\nPaul's argument in Romans 5:12-21 places Adam and Christ as the two representative figures of human history. Through Adam, sin and death entered; through Christ, grace and life overflow. The comparison is not symmetrical — Paul insists that grace exceeds the damage of sin: \"much more the grace of God… abounded to many.\" The controversy framework makes this asymmetry intelligible. Satan's power is derivative and parasitic; Christ's power is original and creative. The outcome was never in genuine doubt; what was at stake was the demonstration of God's justice and love before the watching universe.\n\nJohn's declaration in 1 John 3:8 brings the purpose of the incarnation into sharp relief: the Son of God appeared \"that He might destroy the works of the devil.\" The Greek verb luo means to untie, dismantle, or dissolve. Christ did not come merely to rescue individuals (though He does that); He came to systematically undo every structure, consequence, and deception that Satan's rebellion set in motion. The cross, the resurrection, and the final judgment are all phases of that dismantling.",
    sortOrder: 2,
  },
  {
    id: "w2s-8-2-3",
    lessonId: "w2l-8-2",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "The Adventist understanding of the great controversy shapes how the denomination reads virtually every major doctrine. Several distinctive emphases emerge from these foundational texts:\n\n**The fall as the earthly front of the cosmic war.** Genesis 3 is not an isolated incident of human disobedience; it is the opening of a new theater in a conflict that predates the earth. When Satan approached Eve, he was extending the same strategy he had used in heaven — misrepresenting God's character and challenging God's authority. This means that sin is not merely a legal infraction; it is participation in a rebellion that has cosmic dimensions.\n\n**The cross as the decisive battle.** Adventists affirm that Calvary was the turning point of the great controversy. At the cross, Satan's accusations were permanently answered. He had claimed that God's law could not be kept, that forgiveness was incompatible with justice, and that God's creatures served Him only out of self-interest. Christ's perfect life refuted the first charge, His substitutionary death reconciled the second, and His voluntary suffering — endured out of love, not compulsion — demolished the third. Colossians 2:15 declares that Christ \"disarmed principalities and powers\" and \"made a public spectacle of them, triumphing over them\" at the cross.\n\n**God's character on trial.** A distinguishing feature of Adventist theology is the insistence that the controversy is fundamentally about God's character, not merely about human salvation. Satan's charges must be answered not by force but by evidence. Every act of God in Scripture — from the Flood to the Exodus, from the prophetic warnings to the incarnation — serves as evidence in a universe-wide courtroom. This is why Adventists speak of the \"vindication of God's character\" as an essential outcome of the plan of salvation.\n\n**The protoevangelium and the remnant.** Genesis 3:15 introduces the theme of enmity between the woman's seed and the serpent. Adventists trace this line through the faithful remnant of every generation — Abel, Noah, Abraham, Israel, the apostolic church — and ultimately to the end-time remnant described in Revelation 12:17, those who \"keep the commandments of God and have the testimony of Jesus Christ.\" The great controversy is not abstract theology; it produces a people who live out its implications.",
    sortOrder: 3,
  },
  {
    id: "w2s-8-2-4",
    lessonId: "w2l-8-2",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Deepen your grasp of the doctrinal dimensions of the great controversy this week:\n\n1. **Trace the serpent's strategy.** Read Genesis 3:1-6 and list every tactic Satan used: questioning God's word, contradicting God's warning, appealing to desire. Over the next three days, notice which of these tactics appears in temptations you face. Record your observations in a journal.\n\n2. **Meditate on Romans 5:15-17.** Paul repeats the phrase \"much more\" to emphasize that grace surpasses sin's damage. Each morning, read these three verses and finish with a prayer of gratitude for one specific way God's grace has exceeded the damage of sin in your life.\n\n3. **Explain the cross as victory.** Practice articulating this truth to another person: \"The cross was not just a rescue mission — it was the decisive battle in a cosmic conflict.\" Invite their response and listen carefully.",
    sortOrder: 4,
  },
  {
    id: "w2s-8-2-5",
    lessonId: "w2l-8-2",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Satan's first recorded words on earth were a distortion of God's word: \"Has God indeed said?\" Where in your own experience have you felt the pull to doubt or reinterpret what God has clearly spoken?\n\n2. Paul says that grace \"much more\" abounds where sin increased (Romans 5:15-17). How does this shape your confidence when you consider the scope of evil in the world today?\n\n3. If the great controversy is primarily about the vindication of God's character, how does that change the way you understand your role as a believer — are you a bystander, a beneficiary, or a witness?",
    sortOrder: 5,
  },
  {
    id: "w2s-8-2-6",
    lessonId: "w2l-8-2",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of the Adventist doctrinal formulation of the great controversy.",
    sortOrder: 6,
  },

  // ── Lesson 3: Practical Implications ───────────────────────────
  {
    id: "w2s-8-3-1",
    lessonId: "w2l-8-3",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"Finally, my brethren, be strong in the Lord and in the power of His might. Put on the whole armor of God, that you may be able to stand against the wiles of the devil. For we do not wrestle against flesh and blood, but against principalities, against powers, against the rulers of the darkness of this age, against spiritual hosts of wickedness in the heavenly places.\" — Ephesians 6:10-12 (NKJV)\n\n\"And we know that all things work together for good to those who love God, to those who are the called according to His purpose… For I am persuaded that neither death nor life, nor angels nor principalities nor powers, nor things present nor things to come, nor height nor depth, nor any other created thing, shall be able to separate us from the love of God which is in Christ Jesus our Lord.\" — Romans 8:28, 38-39 (NKJV)\n\n\"For the weapons of our warfare are not carnal but mighty in God for pulling down strongholds, casting down arguments and every high thing that exalts itself against the knowledge of God, bringing every thought into captivity to the obedience of Christ.\" — 2 Corinthians 10:4-5 (NKJV)",
    sortOrder: 1,
  },
  {
    id: "w2s-8-3-2",
    lessonId: "w2l-8-3",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Paul's instruction in Ephesians 6 is built on a single, jarring premise: your real enemy is invisible. The struggles that consume daily life — relational friction, moral failure, discouragement, anxiety — are surface expressions of a deeper warfare. Behind \"flesh and blood\" opponents stand principalities and powers, organized spiritual forces operating with strategic intent. Paul does not invite speculation about demonic hierarchies; he redirects attention to the believer's response. The armor he describes is not decorative. Each piece — truth, righteousness, the gospel of peace, faith, salvation, the Word of God — represents a dimension of life that must be deliberately fortified.\n\nRomans 8:28-39 addresses the emotional reality of living in a war zone. Paul does not promise that believers will be spared suffering; he lists tribulation, distress, persecution, famine, nakedness, peril, and sword as experiences Christians may face. The promise is not exemption but inseparability — nothing in the created order can sever the believer from God's love. This assurance is not wishful thinking; it is grounded in the cross. The God who \"did not spare His own Son\" (Romans 8:32) has already paid the highest price and will not abandon the investment.\n\n2 Corinthians 10:3-5 relocates the battlefield to the mind. The \"strongholds\" Paul targets are not physical fortifications but entrenched patterns of thought — arguments, assumptions, and ideologies that resist the knowledge of God. Every distorted view of God's character, every rationalization for sin, every cynical dismissal of faith is a stronghold that the gospel is designed to dismantle. The phrase \"bringing every thought into captivity\" suggests a disciplined, intentional engagement with one's own interior life. The great controversy is fought, in part, between your ears.\n\nTaken together, these passages paint a portrait of the Christian life as active engagement, not passive waiting. The believer is a soldier with armor, a beloved child with an unbreakable bond, and a thinker whose mind is a theater of war. The practical implications are demanding — and deeply hopeful.",
    sortOrder: 2,
  },
  {
    id: "w2s-8-3-3",
    lessonId: "w2l-8-3",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "The Adventist understanding of living within the great controversy produces several practical commitments that distinguish its approach to the Christian life:\n\n**Spiritual warfare is not sensational but steady.** Popular culture (and some Christian traditions) portrays spiritual warfare as dramatic encounters with visible demonic manifestations. The Adventist approach, rooted in Ephesians 6 and 2 Corinthians 10, emphasizes the daily, often undramatic discipline of putting on the armor — saturating the mind with Scripture, maintaining a posture of prayer, and making decisions in conscious dependence on God. The most important battles are fought in ordinary moments: at the breakfast table, in the workplace, during moments of solitude when no one is watching.\n\n**Suffering interpreted through the conflict.** When Adventists encounter tragedy — a diagnosis, a loss, a natural disaster — the great controversy provides a framework that neither blames God nor dismisses the pain. Suffering is real evidence that the world is occupied territory, damaged by a rebellion God did not author and is working to end. Romans 8:28 does not say all things are good; it says God works all things together for good. The distinction matters. God is not the source of evil; He is the Redeemer who weaves even the wreckage into a larger purpose.\n\n**The mind as sacred ground.** The Adventist emphasis on health, education, and thoughtful media consumption flows directly from 2 Corinthians 10:3-5. If the mind is where strongholds are built or demolished, then what a person reads, watches, eats, and entertains matters — not because God is a cosmic killjoy, but because the conflict is real and the stakes are eternal. The health message, Sabbath rest, and educational philosophy are not cultural preferences; they are strategic responses to a war fought in the interior life.\n\n**Assurance rooted in Christ, not performance.** Romans 8:38-39 provides the emotional anchor for believers living in a conflict they did not start and cannot resolve on their own. Adventist theology, at its best, holds together the urgency of obedience (Ephesians 6) with the security of love (Romans 8). The Christian fights not to earn acceptance but because acceptance has already been secured at the cross.",
    sortOrder: 3,
  },
  {
    id: "w2s-8-3-4",
    lessonId: "w2l-8-3",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Live this week with conscious awareness of the conflict and the resources God provides:\n\n1. **Put on the armor deliberately.** Each morning this week, read Ephesians 6:14-17 and name one piece of armor you will intentionally \"wear\" that day. For example, on Monday choose the belt of truth and ask: Where am I tempted to believe or live a lie? Record what you notice by evening.\n\n2. **Take a thought captive.** When a recurring anxious, bitter, or self-condemning thought surfaces this week, pause and ask: Is this thought consistent with the knowledge of God revealed in Christ? If not, consciously replace it with a specific Scripture verse. Write down both the thought and the verse.\n\n3. **Declare Romans 8:38-39 over a current struggle.** Identify one situation where you feel separated from God's love — perhaps by guilt, exhaustion, or unanswered prayer — and read Paul's list aloud, inserting your own circumstance: \"Neither [this situation] nor any other created thing shall be able to separate me from the love of God.\"",
    sortOrder: 4,
  },
  {
    id: "w2s-8-3-5",
    lessonId: "w2l-8-3",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Paul says our real adversaries are invisible principalities and powers, not flesh and blood. How might your relationships change if you consistently remembered that the people who frustrate or oppose you are not the ultimate enemy?\n\n2. Which piece of the spiritual armor in Ephesians 6 do you tend to neglect most? What pattern in your life might be connected to that gap?\n\n3. Romans 8:28 promises that God works all things together for good. Can you identify a past difficulty that you now see differently in light of God's larger purposes? How does that memory strengthen your trust for the present?",
    sortOrder: 5,
  },
  {
    id: "w2s-8-3-6",
    lessonId: "w2l-8-3",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of the practical implications of living in the great controversy.",
    sortOrder: 6,
  },

  // ── Lesson 4: Misunderstandings & Challenges ───────────────────
  {
    id: "w2s-8-4-1",
    lessonId: "w2l-8-4",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"Now there was a day when the sons of God came to present themselves before the Lord, and Satan also came among them. And the Lord said to Satan, 'From where do you come?' So Satan answered the Lord and said, 'From going to and fro on the earth, and from walking back and forth on it.' Then the Lord said to Satan, 'Have you considered My servant Job…?' So Satan answered the Lord and said, 'Does Job fear God for nothing?… But now, stretch out Your hand and touch all that he has, and he will surely curse You to Your face!' And the Lord said to Satan, 'Behold, all that he has is in your power; only do not lay a hand on his person.'\" — Job 1:6-12 (NKJV)\n\n\"You are of purer eyes than to behold evil, and cannot look on wickedness. Why do You look on those who deal treacherously, and hold Your tongue when the wicked devours a person more righteous than he?\" — Habakkuk 1:13 (NKJV)\n\n\"For the earnest expectation of the creation eagerly waits for the revealing of the sons of God. For the creation was subjected to futility, not willingly, but because of Him who subjected it in hope; because the creation itself also will be delivered from the bondage of corruption into the glorious liberty of the children of God. For we know that the whole creation groans and labors with birth pains together until now.\" — Romans 8:19-22 (NKJV)",
    sortOrder: 1,
  },
  {
    id: "w2s-8-4-2",
    lessonId: "w2l-8-4",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Job 1 opens a window into a scene no human was meant to witness: a heavenly council in which Satan appears before God and levels a devastating accusation against a righteous man. \"Does Job fear God for nothing?\" is not really about Job — it is about God. Satan's underlying claim is that God can only secure loyalty through bribery, that no one would serve Him without the payoff of protection and prosperity. God's response is startling: He permits Satan to strip Job of everything, confident that Job's faithfulness will expose the lie. The discomfort modern readers feel at this scene is precisely the point. God does not owe us an explanation in advance; He invites trust in the midst of mystery.\n\nHabakkuk's protest in 1:13 gives voice to every honest believer who has looked at injustice and asked, \"Why?\" The prophet does not doubt God's purity; he affirms it — \"You are of purer eyes than to behold evil.\" His question is not whether God is good but how a good God can appear to tolerate wickedness. Habakkuk receives an answer, but it is not the one he expected. God reveals that He is already at work through instruments the prophet would never have chosen (the Babylonians), and the final resolution requires patience: \"the just shall live by his faith\" (Habakkuk 2:4). The prophet's journey from complaint to worship in chapter 3 models a mature response to the problem of evil: honest questions, willingness to wait, and trust anchored in God's past faithfulness.\n\nPaul's language in Romans 8:19-22 extends the scope of the controversy beyond human experience. Creation itself groans — not because it sinned, but because it was \"subjected to futility\" as a consequence of the human fall. Earthquakes, disease, decay, and ecological devastation are not God's design; they are symptoms of a creation trapped in the fallout of rebellion. Yet Paul frames this groaning as birth pains, not a death rattle. The suffering points toward delivery, not extinction. The entire created order waits for the moment when the children of God are fully revealed and the curse is reversed.\n\nThese three texts address the hardest objection to the great controversy: If God is sovereign and good, why does evil persist? The biblical answer is layered. God permits evil temporarily because the moral issues raised by Satan's rebellion require a full demonstration (Job). God is not indifferent to injustice but works on a timeline that transcends human impatience (Habakkuk). And the suffering of the present age, though real and grievous, is not the final word — it is the labor preceding birth (Romans 8).",
    sortOrder: 2,
  },
  {
    id: "w2s-8-4-3",
    lessonId: "w2l-8-4",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "The great controversy doctrine faces several common misunderstandings that Adventist theology addresses with care:\n\n**\"God is testing us like lab rats.\"** A superficial reading of Job might suggest that God gambles with human suffering to win a bet with Satan. The Adventist understanding rejects this caricature. God is not experimenting; He is vindicating. The controversy requires that His character be demonstrated under every conceivable condition — including the condition of undeserved suffering borne in faith. Job's story is not about God's cruelty; it is about God's confidence in the covenant relationship and the exposure of Satan's lie that love is always mercenary.\n\n**\"If God is sovereign, He must be responsible for evil.\"** This deterministic conclusion fails to account for the reality of free will. Adventist theology insists that God created beings with genuine moral freedom — a freedom that carries the real possibility of rebellion. Sovereignty does not mean micromanagement; it means that God's purposes will ultimately prevail despite the chaos introduced by sin. Habakkuk's journey illustrates this: God is not absent or passive, but His methods and timeline often defy human expectation.\n\n**\"The great controversy makes God look weak.\"** The opposite is true. A God who could annihilate His opponent instantly but instead chooses to answer accusations through patient demonstration displays a kind of strength that raw power cannot achieve. Force can compel submission; only love and truth can win allegiance. The great controversy framework reveals a God who respects the intelligence and freedom of His creatures enough to make His case rather than impose His will.\n\n**\"Nature's suffering disproves a loving Creator.\"** Romans 8:19-22 addresses this directly. The natural world's brokenness is not evidence against God; it is evidence of the reach of sin's consequences. Adventists affirm that God's original creation was \"very good\" (Genesis 1:31) and that the decay and violence now visible in nature are aberrations, not design features. The promise that creation will be \"delivered from the bondage of corruption\" grounds the Adventist hope in a new earth — not an ethereal heaven but a restored, physical world where the curse is completely undone.\n\n**The patience of God as a moral necessity.** Peter writes that the Lord is \"not slack concerning His promise… but is longsuffering toward us, not willing that any should perish\" (2 Peter 3:9). The delay in ending the controversy is not divine indifference; it is divine patience. Every additional day is an opportunity for repentance and an additional line of evidence in the record that God has done everything possible to save.",
    sortOrder: 3,
  },
  {
    id: "w2s-8-4-4",
    lessonId: "w2l-8-4",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Engage honestly with the hardest questions the great controversy raises:\n\n1. **Sit with Habakkuk.** Read Habakkuk 1:1-2:4 in one sitting. Write your own honest question to God about something in the world — or in your life — that troubles you. Then read Habakkuk 3:17-19 and write a response of trust, even if your question remains unanswered.\n\n2. **Listen to creation's groaning.** Spend time outdoors this week and notice both the beauty and the brokenness of the natural world. Reflect on Romans 8:19-22 and pray for the day when creation will be delivered. Let this exercise deepen your longing for the new earth.\n\n3. **Respond to a skeptic's question.** If someone asks you, \"How can you believe in a good God when there is so much suffering?\" practice a response that includes these elements: God did not create evil; the conflict is temporary; the cross proves God's commitment; and the resolution is coming. Write your response in your own words and refine it.",
    sortOrder: 4,
  },
  {
    id: "w2s-8-4-5",
    lessonId: "w2l-8-4",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Satan asked, \"Does Job fear God for nothing?\" If you lost everything tomorrow — health, possessions, relationships — would your faith survive? What sustains your trust in God beyond the blessings He provides?\n\n2. Habakkuk moved from protest (chapter 1) to worship (chapter 3) without receiving a full explanation. Have you experienced a season where you had to trust God without understanding His reasons? What did that season teach you?\n\n3. Paul says creation groans like a woman in labor. How does the image of birth pains — suffering that leads to something new — reshape the way you view the difficulties of the present age?",
    sortOrder: 5,
  },
  {
    id: "w2s-8-4-6",
    lessonId: "w2l-8-4",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of common misunderstandings and challenges regarding the great controversy.",
    sortOrder: 6,
  },
];

export const belief8Assessments = [
  {
    id: "w2a-8-1",
    lessonId: "w2l-8-1",
    title: "Biblical Foundations Assessment — The Great Controversy",
    passingScore: 70,
  },
  {
    id: "w2a-8-2",
    lessonId: "w2l-8-2",
    title: "Doctrinal Formulation Assessment — The Great Controversy",
    passingScore: 70,
  },
  {
    id: "w2a-8-3",
    lessonId: "w2l-8-3",
    title: "Practical Implications Assessment — The Great Controversy",
    passingScore: 70,
  },
  {
    id: "w2a-8-4",
    lessonId: "w2l-8-4",
    title: "Misunderstandings & Challenges Assessment — The Great Controversy",
    passingScore: 70,
  },
];

export const belief8Items = [
  // ── Lesson 1 Assessment Items ──────────────────────────────────
  {
    id: "w2i-8-1-1",
    assessmentId: "w2a-8-1",
    question: "According to Revelation 12:7-9, who are the primary combatants in the war that began in heaven?",
    options: ["Adam and Satan", "Michael and his angels versus the dragon and his angels", "Gabriel and Lucifer", "The saints and the beast"],
    correctIndex: 1,
    explanation: "Revelation 12:7 identifies the combatants as Michael (Christ in His role as heaven's commander) and His angels fighting against the dragon (Satan) and his angels. The war originated in heaven before extending to earth.",
  },
  {
    id: "w2i-8-1-2",
    assessmentId: "w2a-8-1",
    question: "In Isaiah 14:12-14, how many times does the rebellious being declare 'I will,' and what do these declarations reveal?",
    options: ["Three times, revealing his desire for knowledge", "Five times, revealing self-exaltation as the root of his rebellion", "Seven times, revealing his plan to create a rival kingdom", "Two times, revealing his frustration with divine authority"],
    correctIndex: 1,
    explanation: "Isaiah records five 'I will' statements, each escalating in ambition — from ascending to heaven to being 'like the Most High.' These reveal that the conflict's root was pride and self-exaltation, not a legitimate grievance.",
  },
  {
    id: "w2i-8-1-3",
    assessmentId: "w2a-8-1",
    question: "What does Ezekiel 28:15 tell us about the original condition of the being who became Satan?",
    options: ["He was created with a flawed nature that inevitably led to sin", "He was perfect in his ways from the day he was created until iniquity was found in him", "He was a minor angel who gradually gained power", "He was created as God's equal but chose a different path"],
    correctIndex: 1,
    explanation: "Ezekiel 28:15 states he was 'perfect in your ways from the day you were created, till iniquity was found in you.' Evil was not built into his nature — it originated from within a perfect being who had genuine freedom of choice.",
  },
  {
    id: "w2i-8-1-4",
    assessmentId: "w2a-8-1",
    question: "A friend argues that the story of Satan's fall is just ancient mythology with no relevance today. Using the passages studied, what is the strongest biblical response?",
    options: ["The story is indeed symbolic and should not be taken literally", "Revelation 12:9 explicitly identifies the dragon as Satan who 'deceives the whole world' — connecting the heavenly war to present global reality", "The story only applies to the time of the early church", "Satan's fall is mentioned only once and may be a later addition"],
    correctIndex: 1,
    explanation: "Revelation 12:9 links the ancient heavenly war directly to the present by identifying the dragon as the one who 'deceives the whole world.' The conflict is not confined to the past — it shapes current human experience on a global scale.",
  },
  {
    id: "w2i-8-1-5",
    assessmentId: "w2a-8-1",
    question: "Why does the Adventist understanding of the great controversy insist that God did not immediately destroy Satan after his rebellion?",
    options: ["God lacked the power to destroy a being of such high rank", "Immediate destruction would have silenced the accusations by force rather than answering them through demonstration", "God was uncertain whether Satan's charges had merit", "The angels requested that Satan be given a second chance"],
    correctIndex: 1,
    explanation: "Destroying Satan immediately would have addressed the rebel but not the rebellion's underlying questions about God's character and justice. Allowing the controversy to unfold answers the accusations through evidence rather than coercion, securing the loyalty of the universe through understanding, not fear.",
  },

  // ── Lesson 2 Assessment Items ──────────────────────────────────
  {
    id: "w2i-8-2-1",
    assessmentId: "w2a-8-2",
    question: "What was Satan's opening strategy when he approached Eve in Genesis 3:1?",
    options: ["He offered her supernatural powers", "He distorted God's word by asking 'Has God indeed said?'", "He appeared as a glowing angel", "He threatened her with punishment"],
    correctIndex: 1,
    explanation: "Satan's first words on earth were a distortion of God's command: 'Has God indeed said, You shall not eat of every tree?' He reframed God's generous provision (eat from any tree except one) as restrictive, casting doubt on God's character and motives.",
  },
  {
    id: "w2i-8-2-2",
    assessmentId: "w2a-8-2",
    question: "Genesis 3:15 is sometimes called the 'protoevangelium.' What does it promise?",
    options: ["That humanity will eventually evolve beyond the need for God", "That the Seed of the woman will crush the serpent's head, though at the cost of His own wounding", "That the serpent will be immediately destroyed after the fall", "That Adam and Eve will be restored to Eden within their lifetime"],
    correctIndex: 1,
    explanation: "The protoevangelium ('first gospel') in Genesis 3:15 announces that the woman's Seed will crush the serpent's head while suffering a bruised heel — a compressed prophecy of Christ's victory at the cross, where He defeated Satan at the cost of His own suffering.",
  },
  {
    id: "w2i-8-2-3",
    assessmentId: "w2a-8-2",
    question: "In Romans 5:12-21, Paul contrasts Adam and Christ. What key point does he emphasize about the comparison?",
    options: ["Adam and Christ are equal in their impact on humanity", "Grace through Christ far exceeds the damage caused by Adam's sin", "Christ's work merely reversed Adam's sin with no surplus", "Adam's sin was worse than any subsequent human sin"],
    correctIndex: 1,
    explanation: "Paul insists the comparison is asymmetrical — grace is greater: 'much more the grace of God and the gift by the grace of the one Man, Jesus Christ, abounded to many' (Romans 5:15). Christ's redemptive work surpasses the damage of the fall.",
  },
  {
    id: "w2i-8-2-4",
    assessmentId: "w2a-8-2",
    question: "According to 1 John 3:8, why was the Son of God manifested?",
    options: ["To establish a new political kingdom on earth", "To destroy the works of the devil", "To provide philosophical teachings about morality", "To demonstrate that God can suffer"],
    correctIndex: 1,
    explanation: "John states the purpose of the incarnation with crystalline clarity: the Son of God appeared 'that He might destroy the works of the devil.' The Greek verb luo means to untie or dismantle — Christ came to systematically undo every consequence of Satan's rebellion.",
  },
  {
    id: "w2i-8-2-5",
    assessmentId: "w2a-8-2",
    question: "An Adventist friend says the great controversy is 'mainly about getting humans to heaven.' How would a more complete Adventist understanding correct this?",
    options: ["By agreeing that human salvation is the only purpose of the plan of redemption", "By explaining that the controversy is fundamentally about vindicating God's character before the universe, with human salvation as a central but not exclusive outcome", "By arguing that humans are unimportant in the cosmic scheme", "By shifting focus entirely to angelic beings"],
    correctIndex: 1,
    explanation: "While human salvation is essential, the Adventist understanding holds that the controversy is ultimately about God's character being vindicated before all created intelligences. Satan's accusations about God's justice and love must be answered universally, not just personally.",
  },

  // ── Lesson 3 Assessment Items ──────────────────────────────────
  {
    id: "w2i-8-3-1",
    assessmentId: "w2a-8-3",
    question: "According to Ephesians 6:12, what is the true nature of the Christian's struggle?",
    options: ["A battle against corrupt political systems", "A wrestling match against principalities, powers, and spiritual hosts of wickedness", "A competition between religious denominations", "A personal effort to achieve moral perfection through willpower"],
    correctIndex: 1,
    explanation: "Paul explicitly states that 'we do not wrestle against flesh and blood, but against principalities, against powers, against the rulers of the darkness of this age.' The real conflict is spiritual, involving organized forces of evil operating behind visible circumstances.",
  },
  {
    id: "w2i-8-3-2",
    assessmentId: "w2a-8-3",
    question: "In 2 Corinthians 10:4-5, what are the 'strongholds' that spiritual weapons are designed to demolish?",
    options: ["Physical military fortresses", "Entrenched patterns of thought, arguments, and ideologies that resist the knowledge of God", "Church buildings controlled by false teachers", "Financial institutions that exploit the poor"],
    correctIndex: 1,
    explanation: "Paul's 'strongholds' are mental and ideological — 'arguments and every high thing that exalts itself against the knowledge of God.' The great controversy is fought partly in the mind, where distorted views of God and rationalized sin must be dismantled by truth.",
  },
  {
    id: "w2i-8-3-3",
    assessmentId: "w2a-8-3",
    question: "What does Romans 8:28 promise about the relationship between suffering and God's purposes?",
    options: ["All things that happen to believers are inherently good", "God causes suffering to teach lessons", "God works all things together for good for those who love Him and are called according to His purpose", "Believers who suffer enough will eventually be rewarded with material blessings"],
    correctIndex: 2,
    explanation: "Romans 8:28 does not say all things are good — it says God works them 'together for good.' The distinction is critical: God does not author evil, but He sovereignly weaves even painful circumstances into a larger redemptive purpose for those who love Him.",
  },
  {
    id: "w2i-8-3-4",
    assessmentId: "w2a-8-3",
    question: "A believer struggling with anxiety asks whether the great controversy doctrine offers any practical comfort. Which response best reflects the lesson's teaching?",
    options: ["Not really — the doctrine is theoretical and does not address emotional struggles", "Yes — Romans 8:38-39 assures that nothing in all creation can separate us from God's love, and Ephesians 6 provides spiritual resources for the real battle behind the anxiety", "Yes — if you put on the armor, you will never feel anxious again", "The great controversy only applies to end-time events, not personal struggles"],
    correctIndex: 1,
    explanation: "The great controversy framework provides both an explanation (the adversary is real) and a resource (the armor of God, the inseparable love of Christ). It does not promise the absence of struggle but guarantees God's presence and the ultimate security of the believer within it.",
  },
  {
    id: "w2i-8-3-5",
    assessmentId: "w2a-8-3",
    question: "Why does the Adventist emphasis on health, education, and thoughtful media consumption connect to the great controversy?",
    options: ["These are cultural traditions unrelated to theology", "Because the mind is a battlefield where strongholds are built or demolished, making what we consume spiritually significant", "Because physical health determines one's salvation", "Because Adventists believe entertainment is inherently sinful"],
    correctIndex: 1,
    explanation: "Since 2 Corinthians 10:3-5 identifies the mind as a theater of spiritual warfare, what shapes the mind — diet, education, media — has strategic importance. The Adventist lifestyle is not about earning merit but about guarding the ground where the great controversy plays out daily.",
  },

  // ── Lesson 4 Assessment Items ──────────────────────────────────
  {
    id: "w2i-8-4-1",
    assessmentId: "w2a-8-4",
    question: "In Job 1:9, what is the core accusation Satan makes against Job — and by extension, against God?",
    options: ["That Job is secretly sinning in private", "That Job only fears God because God has bribed him with blessings and protection", "That Job is not really a righteous man", "That God is too lenient with sinners"],
    correctIndex: 1,
    explanation: "Satan's question — 'Does Job fear God for nothing?' — accuses God of buying loyalty. The implication is that no creature would serve God freely; remove the benefits, and worship collapses. This strikes at the heart of whether love-based government is possible.",
  },
  {
    id: "w2i-8-4-2",
    assessmentId: "w2a-8-4",
    question: "What is the significance of Habakkuk's journey from protest in chapter 1 to worship in chapter 3?",
    options: ["It shows that questioning God is sinful and should be avoided", "It models a mature faith that brings honest questions to God yet chooses trust when full explanations are not given", "It demonstrates that God always answers every question immediately", "It proves that suffering is always punishment for hidden sin"],
    correctIndex: 1,
    explanation: "Habakkuk does not receive a complete explanation, yet he moves from raw complaint to profound worship ('Though the fig tree may not blossom… yet I will rejoice in the Lord'). His journey models faith that is honest about difficulty but anchored in God's proven character.",
  },
  {
    id: "w2i-8-4-3",
    assessmentId: "w2a-8-4",
    question: "According to Romans 8:19-22, why does the natural world experience suffering and decay?",
    options: ["Because God designed nature to be violent and competitive", "Because creation was subjected to futility as a consequence of the human fall, not by its own choice", "Because the natural world has its own form of sin", "Because God withdrew His sustaining power permanently after Eden"],
    correctIndex: 1,
    explanation: "Paul says creation was 'subjected to futility, not willingly' — nature did not rebel; it suffers collateral damage from humanity's fall. This preserves God's original design as 'very good' while honestly acknowledging the present brokenness of the physical world.",
  },
  {
    id: "w2i-8-4-4",
    assessmentId: "w2a-8-4",
    question: "A skeptic says, 'If God is all-powerful, He could end suffering instantly. The fact that He doesn't proves He is either weak or indifferent.' How does the great controversy framework respond?",
    options: ["By admitting that God may indeed be limited in power", "By explaining that God permits evil temporarily because the moral questions raised by Satan's rebellion require a full demonstration, not a forceful silencing", "By arguing that suffering is an illusion and does not really exist", "By claiming that all suffering is deserved punishment"],
    correctIndex: 1,
    explanation: "The great controversy framework holds that God could end evil by force but chooses not to — not from weakness but from wisdom. Silencing accusations by power would leave the underlying questions unanswered. God allows the controversy to demonstrate His justice and love fully, securing the universe against future rebellion.",
  },
  {
    id: "w2i-8-4-5",
    assessmentId: "w2a-8-4",
    question: "Paul describes creation's suffering as 'birth pains' in Romans 8:22. What does this metaphor communicate about the nature of present suffering?",
    options: ["That suffering is permanent and will never end", "That present suffering, though real and intense, is leading toward a new creation — delivery, not extinction", "That only the natural world suffers, not humans", "That the earth will give birth to a new species"],
    correctIndex: 1,
    explanation: "Birth pains are severe but purposeful — they lead to new life. Paul uses this image to reframe present suffering: it is not a death rattle but a labor leading to 'the glorious liberty of the children of God.' The groaning of creation points forward to restoration, not backward to despair.",
  },
];
