export const belief21Lessons = [
  {
    id: "w4l-21-1",
    moduleId: "bmod-021",
    title: "Biblical Foundations: Managers, Not Owners",
    description: "Discovering the biblical framework for stewardship — that everything belongs to God, and human beings are entrusted managers of His gifts, resources, and creation.",
    lessonOrder: 1,
    anchorText: "Genesis 1:26-28; 1 Chronicles 29:14; 2 Corinthians 9:7",
    anchorBookId: 1,
    anchorChapter: 1,
    anchorVerseStart: 26,
    anchorVerseEnd: 28,
    estimatedMinutes: 35,
  },
  {
    id: "w4l-21-2",
    moduleId: "bmod-021",
    title: "Doctrinal Formulation: Whole-Life Stewardship",
    description: "Exploring the Adventist understanding of stewardship as encompassing finances, time, health, abilities, relationships, and influence — far broader than a conversation about money.",
    lessonOrder: 2,
    anchorText: "Malachi 3:8-12; 2 Corinthians 8:1-15; Matthew 23:23",
    anchorBookId: 39,
    anchorChapter: 3,
    anchorVerseStart: 8,
    anchorVerseEnd: 12,
    estimatedMinutes: 30,
  },
  {
    id: "w4l-21-3",
    moduleId: "bmod-021",
    title: "Practical Implications: Faithful in All Things",
    description: "Moving stewardship from doctrine to daily life — practical steps for managing time, treasure, health, and influence in alignment with God's purposes.",
    lessonOrder: 3,
    anchorText: "Genesis 2:15; Haggai 1:3-11; Romans 15:26-27",
    anchorBookId: 1,
    anchorChapter: 2,
    anchorVerseStart: 15,
    anchorVerseEnd: 15,
    estimatedMinutes: 30,
  },
  {
    id: "w4l-21-4",
    moduleId: "bmod-021",
    title: "Misunderstandings & Challenges",
    description: "Addressing common misconceptions about stewardship — from reducing it to tithing alone, to prosperity theology, to the tension between generosity and financial wisdom.",
    lessonOrder: 4,
    anchorText: "1 Corinthians 9:9-14; Luke 12:13-21; Matthew 6:19-24",
    anchorBookId: 46,
    anchorChapter: 9,
    anchorVerseStart: 9,
    anchorVerseEnd: 14,
    estimatedMinutes: 30,
  },
];

export const belief21Sections = [
  // ── Lesson 1: Biblical Foundations ──────────────────────────────
  {
    id: "w4s-21-1-1",
    lessonId: "w4l-21-1",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"Then God said, 'Let Us make man in Our image, according to Our likeness; let them have dominion over the fish of the sea, over the birds of the air, and over the cattle, over all the earth and over every creeping thing that creeps on the earth.' So God created man in His own image; in the image of God He created him; male and female He created them. Then God blessed them, and God said to them, 'Be fruitful and multiply; fill the earth and subdue it; have dominion over the fish of the sea, over the birds of the air, and over every living thing that moves on the earth.'\" — Genesis 1:26-28 (NKJV)\n\n\"But who am I, and who are my people, that we should be able to offer so willingly as this? For all things come from You, and of Your own we have given You.\" — 1 Chronicles 29:14 (NKJV)\n\n\"So let each one give as he purposes in his heart, not grudgingly or of necessity; for God loves a cheerful giver.\" — 2 Corinthians 9:7 (NKJV)\n\nAs you read, consider: What does it mean that dominion is given rather than inherent? What does David's prayer reveal about the true source of every gift?",
    sortOrder: 1,
  },
  {
    id: "w4s-21-1-2",
    lessonId: "w4l-21-1",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "The opening chapters of Genesis establish a principle that runs through the entire Bible: God is the owner, and human beings are entrusted managers. When God placed Adam and Eve in the garden with instructions to tend and keep it (Genesis 2:15), He was not transferring title. He was delegating responsibility. The earth remained His — \"The earth is the LORD's, and all its fullness\" (Psalm 24:1). Dominion is a gift accompanied by accountability, not a license for exploitation or self-enrichment.\n\nDavid understood this deeply. At the end of his reign, after the people of Israel had given generously toward the construction of the temple, David did not congratulate them on their philanthropy. He prayed with startling honesty: \"All things come from You, and of Your own we have given You\" (1 Chronicles 29:14). Every resource Israel offered had originated with God. Their giving was not a donation to a needy deity but a return of what already belonged to Him. This reframes generosity entirely. Stewardship is not about God needing our money; it is about whether we recognize whose money it is.\n\nPaul extends the principle into the interior life of the giver. In 2 Corinthians 9:7, the emphasis falls not on the amount but on the posture of the heart: \"not grudgingly or of necessity.\" God does not extract resources under threat. He invites willing participation in His purposes. The cheerful giver is not someone who has mastered positive thinking about parting with cash; it is someone who has so internalized the reality that everything belongs to God that returning a portion feels natural — even joyful. Compulsion and resentment signal that the giver has not yet grasped the foundation: we are managers returning a share of what was never ours to begin with.",
    sortOrder: 2,
  },
  {
    id: "w4s-21-1-3",
    lessonId: "w4l-21-1",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "Seventh-day Adventists ground stewardship in the doctrine of creation. Because God made all things and sustains all things, ownership rests permanently with Him. Human beings are caretakers — honored with responsibility but never promoted to proprietors. This conviction shapes several distinctive Adventist emphases:\n\n**Creation as the foundation of stewardship.** The dominion mandate of Genesis 1:26-28 is not a blank check. It is a commission from the Creator to manage His world wisely, sustainably, and in a way that reflects His character. Stewardship begins with the recognition that we did not make ourselves, we did not earn our abilities, and we did not create the resources we manage.\n\n**Stewardship as broader than money.** While tithe and offerings are important (and will be explored in the next lesson), the Adventist understanding of stewardship encompasses all of life — time, health, talents, relationships, influence, and the natural environment. A person who tithes faithfully but squanders health, neglects family, or abuses creation has not yet embraced whole-life stewardship.\n\n**Gratitude, not guilt.** David's prayer in 1 Chronicles 29 sets the tone. Stewardship flows from amazement that God entrusts anything to us, not from shame that we have not given enough. A guilt-driven approach to stewardship distorts the gospel and makes giving a form of self-atonement rather than a response to grace.\n\n**Corrective boundary:** Stewardship is not a prosperity arrangement. Faithful management does not guarantee material wealth. The Bible is candid about righteous people who suffered loss (Job, Paul, the early church). Stewardship promises faithfulness, not fortune — and the ultimate return is eternal, not temporal.",
    sortOrder: 3,
  },
  {
    id: "w4s-21-1-4",
    lessonId: "w4l-21-1",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Begin reorienting your daily life around the conviction that everything belongs to God:\n\n1. **Write a stewardship confession.** In four to five sentences, articulate what it means that you are a manager and not an owner. Include at least one specific area of your life — finances, time, health, relationships — where this truth needs to reshape your habits. Share it with a trusted friend or small group.\n\n2. **Conduct a gratitude inventory.** List ten resources, abilities, or relationships God has entrusted to you. For each one, ask: Am I managing this in a way that honors the Owner? Identify one area where an adjustment is needed and take a first step this week.\n\n3. **Pray David's prayer daily.** Read 1 Chronicles 29:14 each morning and let its words become your own: \"All things come from You, and of Your own we have given You.\" Notice how this reframes every decision you make about time, money, and energy throughout the day.",
    sortOrder: 4,
  },
  {
    id: "w4s-21-1-5",
    lessonId: "w4l-21-1",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. David said, \"Of Your own we have given You.\" How does the realization that your resources ultimately belong to God change the way you feel about giving — whether financially, relationally, or in service?\n\n2. Genesis 1:26-28 gives humanity dominion over creation. In what ways have you exercised that dominion well, and in what ways has it drifted toward ownership rather than caretaking?\n\n3. Paul says God loves a cheerful giver. What specific attitudes or fears make generosity feel grudging rather than joyful for you — and what might help shift that posture?",
    sortOrder: 5,
  },
  {
    id: "w4s-21-1-6",
    lessonId: "w4l-21-1",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },

  // ── Lesson 2: Doctrinal Formulation ────────────────────────────
  {
    id: "w4s-21-2-1",
    lessonId: "w4l-21-2",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"'Will a man rob God? Yet you have robbed Me! But you say, \"In what way have we robbed You?\" In tithes and offerings. You are cursed with a curse, for you have robbed Me, even this whole nation. Bring all the tithes into the storehouse, that there may be food in My house, and try Me now in this,' says the LORD of hosts, 'if I will not open for you the windows of heaven and pour out for you such blessing that there will not be room enough to receive it.'\" — Malachi 3:8-10 (NKJV)\n\n\"Moreover, brethren, we make known to you the grace of God bestowed on the churches of Macedonia: that in a great trial of affliction the abundance of their joy and their deep poverty abounded in the riches of their liberality.\" — 2 Corinthians 8:1-2 (NKJV)\n\n\"Woe to you, scribes and Pharisees, hypocrites! For you pay tithe of mint and anise and cummin, and have neglected the weightier matters of the law: justice and mercy and faith. These you ought to have done, without leaving the others undone.\" — Matthew 23:23 (NKJV)\n\nAs you read, notice how Jesus affirms tithing while insisting on a fuller picture. What does the Macedonian church teach about the relationship between poverty and generosity?",
    sortOrder: 1,
  },
  {
    id: "w4s-21-2-2",
    lessonId: "w4l-21-2",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Malachi 3 is one of the strongest passages in Scripture on financial faithfulness, and it requires careful reading. God's charge — \"you have robbed Me\" — is directed at a nation that had grown indifferent to its covenant responsibilities. Tithes and offerings were not arbitrary taxes; they sustained the Levitical priesthood, the temple services, and the care of the poor. To withhold them was to starve the institutions God had established for worship and justice. The invitation that follows — \"try Me now in this\" — is remarkable. God rarely invites testing, but here He does, promising tangible blessing for covenant faithfulness.\n\nYet tithing is not the whole story. Jesus' words in Matthew 23:23 are pivotal. He does not abolish tithe — \"these you ought to have done\" — but He refuses to let it stand alone. The Pharisees were meticulous about tithing their herb gardens while neglecting justice, mercy, and faith. Stewardship that counts coins but ignores character is incomplete. Jesus insists on both: faithful financial practice and the deeper commitments that give it meaning.\n\nPaul's account of the Macedonian churches in 2 Corinthians 8 provides a stunning illustration. These believers were desperately poor, yet they gave beyond their ability — and they did so with joy. Paul attributes their generosity not to willpower but to grace: \"the grace of God bestowed on the churches of Macedonia.\" Generosity, in Paul's theology, is itself a gift of grace. It is not something the strong achieve through discipline; it is something the transformed experience as an overflow of gratitude. The Macedonians did not give because they had surplus. They gave because they had encountered the One who \"though He was rich, yet for your sakes He became poor\" (2 Corinthians 8:9).\n\nTaken together, these passages paint a picture of stewardship that is both structured and Spirit-led. Tithe provides an ordered framework; freewill offerings express the overflow of a grateful heart; and both are embedded in a life committed to justice, mercy, and faithfulness.",
    sortOrder: 2,
  },
  {
    id: "w4s-21-2-3",
    lessonId: "w4l-21-2",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "Adventist stewardship theology moves beyond the offering plate to embrace every dimension of human life. Several key convictions shape this holistic vision:\n\n**Tithe as covenant acknowledgment.** Adventists understand tithe — returning ten percent of one's increase — as a recognition that God is the source of all income. It is not a fee for services rendered but a tangible act of trust. Malachi's promise of blessing is received not as a transactional guarantee but as a covenant assurance that God honors faithfulness. Tithe is returned to the \"storehouse\" (the organized church) to support gospel ministry, following the biblical pattern of sustaining those who serve (1 Corinthians 9:13-14).\n\n**Offerings beyond tithe.** Tithe is the starting point, not the ceiling. Freewill offerings support local church needs, community outreach, education, disaster relief, and global mission. Paul's commendation of the Macedonians demonstrates that generosity is not determined by financial capacity but by spiritual depth.\n\n**Stewardship of the body.** Adventists extend stewardship to health — the body is \"the temple of the Holy Spirit\" (1 Corinthians 6:19). Diet, exercise, rest, and the avoidance of harmful substances are stewardship decisions. Managing the body well is not legalism; it is gratitude expressed physically.\n\n**Stewardship of time and talent.** Every hour and every ability is a trust from God. How believers spend their time, develop their gifts, and deploy their influence in their families, workplaces, and communities is as much a stewardship question as how they allocate their finances.\n\n**Stewardship of creation.** The dominion mandate carries ecological responsibility. Adventists affirm that caring for the natural world is part of faithful management, not an optional add-on.\n\n**Corrective boundary:** Stewardship must never become a tool for institutional coercion or guilt manipulation. God invites cheerful giving; He does not extort reluctant compliance. Any appeal to stewardship that relies on shame, fear, or spiritual threats distorts the gospel it claims to serve.",
    sortOrder: 3,
  },
  {
    id: "w4s-21-2-4",
    lessonId: "w4l-21-2",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Expand your understanding and practice of whole-life stewardship this week:\n\n1. **Articulate the Adventist view of stewardship.** Write a brief summary (four to six sentences) explaining why Adventist stewardship is broader than tithing. Mention at least three areas — finances, health, time, talent, or creation — and share it with a study partner or small group for feedback.\n\n2. **Audit one non-financial area.** Choose one stewardship domain other than money — your time, your health habits, your use of a particular talent, or your care for the environment. Spend fifteen minutes honestly evaluating how you are managing it. Identify one concrete change you can implement this week and begin.\n\n3. **Practice generosity with someone in need.** Following the Macedonian example, find a way to give — time, resources, or encouragement — to someone who is struggling. Let the act be quiet, joy-driven, and detached from any expectation of return.",
    sortOrder: 4,
  },
  {
    id: "w4s-21-2-5",
    lessonId: "w4l-21-2",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Jesus affirmed tithing but insisted that justice, mercy, and faith are \"weightier matters.\" How do you balance structured financial faithfulness with the broader demands of stewardship in your daily life?\n\n2. The Macedonian believers gave generously out of deep poverty. What does their example teach you about the relationship between material resources and spiritual generosity?\n\n3. Stewardship includes your body, your time, and your influence — not just your income. Which of these non-financial areas most needs your attention right now, and what would faithful management look like?",
    sortOrder: 5,
  },
  {
    id: "w4s-21-2-6",
    lessonId: "w4l-21-2",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },

  // ── Lesson 3: Practical Implications ───────────────────────────
  {
    id: "w4s-21-3-1",
    lessonId: "w4l-21-3",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"Then the LORD God took the man and put him in the garden of Eden to tend and keep it.\" — Genesis 2:15 (NKJV)\n\n\"'You looked for much, but indeed it came to little; and when you brought it home, I blew it away. Why?' says the LORD of hosts. 'Because of My house that is in ruins, while every one of you runs to his own house.'\" — Haggai 1:9 (NKJV)\n\n\"For it pleased those from Macedonia and Achaia to make a certain contribution for the poor among the saints in Jerusalem. It pleased them indeed, and they are their debtors. For if the Gentiles have been partakers of their spiritual things, their duty is also to minister to them in material things.\" — Romans 15:26-27 (NKJV)\n\nAs you read, ask yourself: How does Haggai's rebuke connect personal priorities to spiritual vitality? What does Paul mean when he calls material generosity a \"duty\" in response to spiritual blessings?",
    sortOrder: 1,
  },
  {
    id: "w4s-21-3-2",
    lessonId: "w4l-21-3",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Genesis 2:15 introduces stewardship in its most elemental form: God placed humanity in a garden and gave two verbs — tend and keep. The Hebrew words (abad and shamar) carry the dual sense of working the land and guarding it. Stewardship is both productive and protective. It requires effort and restraint, development and conservation. The mandate was given before the fall, which means stewardship is not a punishment but a privilege — part of what it means to bear God's image in a material world.\n\nHaggai's prophecy confronts a different kind of stewardship failure. The returned exiles had rebuilt their own houses while leaving God's temple in ruins. The result was economic frustration: they earned wages, but the money seemed to vanish (Haggai 1:6). God's point was not that He needed a building. It was that their priorities were disordered. When personal comfort consistently takes precedence over God's purposes, the entire fabric of life begins to fray. Stewardship is ultimately a question of priorities — not whether we have enough, but whether we are directing what we have toward the right things.\n\nPaul's appeal in Romans 15:26-27 adds a relational dimension. The Gentile churches owed a spiritual debt to the Jewish believers in Jerusalem — the gospel had come to them through Israel. Returning material support was an expression of gratitude and solidarity, not charity from a position of superiority. Stewardship, in Paul's framework, is reciprocal. Those who have received spiritual blessings respond with tangible generosity. Those who have material resources share with those who lack them. The result is a community where no one has too much and no one has too little — the very pattern Paul describes in 2 Corinthians 8:13-15.",
    sortOrder: 2,
  },
  {
    id: "w4s-21-3-3",
    lessonId: "w4l-21-3",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "Adventist stewardship moves from conviction to concrete practice through several key commitments:\n\n**Priority alignment.** Haggai's rebuke resonates in any era where personal comfort eclipses mission. Adventists understand that stewardship begins with getting priorities right — God's purposes first, personal preferences second. This does not mean neglecting family or self-care; it means refusing to let comfort become the organizing principle of life.\n\n**Care for creation.** The Genesis 2:15 mandate to tend and keep the earth is not a dispensational relic. It is a standing commission. Adventists, who ground the Sabbath in creation, have particular reason to care for the created world. Environmental stewardship is not a political stance but a theological conviction — the earth belongs to the Lord, and caretakers answer to the Owner.\n\n**Mutual aid and community support.** Paul's collection for Jerusalem models what Adventist development agencies (ADRA) and local church benevolence funds practice today. Stewardship is not merely individual; it is communal. Resources flow from areas of abundance to areas of need, crossing cultural and geographic boundaries.\n\n**Health stewardship as witness.** The Adventist emphasis on healthful living — vegetarianism, temperance, physical activity, adequate rest — is not a cultural quirk. It is a stewardship conviction rooted in 1 Corinthians 6:19-20: the body belongs to God, and managing it well honors the Creator and extends one's capacity for service.\n\n**Corrective boundary:** Stewardship is not a performance metric for spiritual ranking. God does not grade on a curve. Faithful stewardship in small things (Luke 16:10) is as honorable as faithful stewardship of vast resources. The widow's two mites outweighed the treasury contributions of the wealthy because she gave from her heart, not from her surplus.",
    sortOrder: 3,
  },
  {
    id: "w4s-21-3-4",
    lessonId: "w4l-21-3",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Put stewardship into action across multiple areas of your life:\n\n1. **Realign one priority.** Reflect on Haggai's challenge: Is there an area where personal comfort has quietly displaced a commitment God has placed on your heart — volunteering, financial generosity, time with family, care for your health? Identify it and take one corrective step this week.\n\n2. **Practice environmental stewardship.** Choose one tangible action this week that honors the Genesis 2:15 mandate — reduce waste, care for a shared green space, conserve water or energy, or support a community garden. Let it be a small, sustainable habit rather than a grand gesture.\n\n3. **Give to someone across a boundary.** Following Paul's model in Romans 15, extend material or practical help to someone outside your immediate circle — a different generation, a different culture, a different socioeconomic group. Let the gift express gratitude for what you have received, not superiority over what they lack.",
    sortOrder: 4,
  },
  {
    id: "w4s-21-3-5",
    lessonId: "w4l-21-3",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Haggai challenged Israel for prioritizing personal comfort over God's purposes. Where in your life might comfort be quietly displacing a calling or responsibility God has given you?\n\n2. Genesis 2:15 frames stewardship as both tending and keeping — productive work and careful protection. How do you balance the drive to develop and produce with the responsibility to conserve and protect?\n\n3. Paul described generosity as a reciprocal exchange — spiritual blessings flowing one direction, material support flowing the other. Who has blessed you spiritually, and how might you respond with tangible generosity?",
    sortOrder: 5,
  },
  {
    id: "w4s-21-3-6",
    lessonId: "w4l-21-3",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },

  // ── Lesson 4: Misunderstandings & Challenges ───────────────────
  {
    id: "w4s-21-4-1",
    lessonId: "w4l-21-4",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"For it is written in the law of Moses, 'You shall not muzzle an ox while it treads out the grain.' Is it oxen God is concerned about? Or does He say it altogether for our sakes? For our sakes, no doubt, this is written, that he who plows should plow in hope, and he who threshes in hope should be partaker of his hope… If we have sown spiritual things for you, is it a great thing if we reap your material things?\" — 1 Corinthians 9:9-11 (NKJV)\n\n\"Then He spoke a parable to them, saying: 'The ground of a certain rich man yielded plentifully. And he thought within himself, saying, \"What shall I do, since I have no room to store my crops?\" So he said, \"I will do this: I will pull down my barns and build greater, and there I will store all my crops and my goods. And I will say to my soul, 'Soul, you have many goods laid up for many years; take your ease; eat, drink, and be merry.'\" But God said to him, \"Fool! This night your soul will be required of you; then whose will those things be which you have provided?\" So is he who lays up treasure for himself, and is not rich toward God.'\" — Luke 12:16-21 (NKJV)\n\n\"No one can serve two masters; for either he will hate the one and love the other, or else he will be loyal to the one and despise the other. You cannot serve God and mammon.\" — Matthew 6:24 (NKJV)\n\nAs you read, notice the sharp contrast between legitimate provision and idolatrous accumulation. What does Jesus mean by being \"rich toward God\"?",
    sortOrder: 1,
  },
  {
    id: "w4s-21-4-2",
    lessonId: "w4l-21-4",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Paul's argument in 1 Corinthians 9 addresses a question that surfaces in every generation: Should those who labor in gospel ministry be materially supported by the communities they serve? Paul's answer is unequivocal: yes. Drawing on the Old Testament principle that an ox should eat while it works, he establishes that those who sow spiritual things have a legitimate claim to material support. This is not greed; it is justice. Withholding support from those who serve full-time in ministry is a stewardship failure — not because ministers deserve luxury, but because the work of the gospel requires sustained investment.\n\nJesus' parable of the rich fool in Luke 12 attacks a different distortion. The man's problem was not that he was wealthy — Scripture never condemns wealth per se. His problem was that he treated accumulation as the purpose of life. He built bigger barns, congratulated himself, and planned a retirement of ease. He never once considered that his abundance might have been given for the sake of others. God's verdict — \"Fool!\" — is devastating not because the man was rich but because he was \"not rich toward God.\" He stored everything in barns and nothing in relationships, generosity, or eternal investment.\n\nJesus' declaration in Matthew 6:24 frames the issue as a matter of ultimate allegiance. Mammon — wealth personified — demands the same total devotion that God does. You cannot split your loyalty. Either God is the master and money is a tool, or money is the master and God is a convenient accessory. The language is binary because the human heart is not infinitely divisible. Whatever occupies the throne of your affections will shape your decisions, your relationships, and your destiny.\n\nThese three passages together address the most common distortions of stewardship: underfunding ministry (1 Corinthians 9), hoarding resources (Luke 12), and serving wealth instead of God (Matthew 6). Each distortion flows from the same root — a failure to recognize that everything belongs to God and is entrusted for His purposes.",
    sortOrder: 2,
  },
  {
    id: "w4s-21-4-3",
    lessonId: "w4l-21-4",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "Several persistent misunderstandings surround stewardship, and Adventist theology addresses them with both conviction and pastoral care:\n\n**Misunderstanding 1: Stewardship equals tithing.** Many reduce stewardship to a ten-percent calculation. While tithe is an important component, Jesus' rebuke in Matthew 23:23 makes clear that financial faithfulness without justice, mercy, and faith is incomplete. A person who tithes meticulously but hoards time, neglects health, or exploits relationships has not grasped whole-life stewardship.\n\n**Misunderstanding 2: Prosperity theology.** Some teach that generous giving triggers automatic material return — a kind of spiritual vending machine. Malachi 3:10 is often cited in support, but the promise of blessing must be read within the full biblical witness, which includes faithful people who experienced poverty, persecution, and loss. God blesses faithfulness, but blessing takes many forms — and the ultimate reward is eternal, not temporal.\n\n**Misunderstanding 3: Stewardship is only about money.** Even within church communities, stewardship campaigns often focus narrowly on financial giving. The biblical vision is far broader: time, talent, health, influence, creation care, and relational integrity are all stewardship domains. An effective stewardship theology addresses the whole person, not just the wallet.\n\n**Misunderstanding 4: Saving and investing are unspiritual.** Jesus condemned hoarding, not prudent planning. Proverbs commends the ant for storing in summer (Proverbs 6:6-8). The steward who buried his talent was rebuked not for caution but for faithlessness (Matthew 25:24-27). Financial wisdom — saving for the future, avoiding unnecessary debt, investing thoughtfully — is part of responsible stewardship, not a contradiction of generosity.\n\n**Corrective boundary:** Stewardship appeals must never manipulate through guilt, shame, or spiritual threats. God invites cheerful giving (2 Corinthians 9:7). Any approach that coerces, pressures, or weaponizes Scripture to extract resources violates the spirit of the very doctrine it claims to uphold.",
    sortOrder: 3,
  },
  {
    id: "w4s-21-4-4",
    lessonId: "w4l-21-4",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Confront common stewardship distortions with biblical clarity and personal action:\n\n1. **Articulate the difference between stewardship and prosperity theology.** Write a four-sentence explanation of why faithful stewardship does not guarantee material wealth. Use at least one biblical example of a faithful person who experienced hardship. Share your summary with a friend or study group.\n\n2. **Evaluate your relationship with money.** Spend time honestly examining whether money functions as a tool or a master in your life. Review your spending patterns from the past month. Are they aligned with the priorities of someone who believes everything belongs to God? Make one adjustment where needed.\n\n3. **Support someone in ministry.** Following Paul's teaching in 1 Corinthians 9, find a concrete way to support a person serving in ministry — financially, through encouragement, or by relieving a practical burden. Let the act reflect the conviction that those who sow spiritual things deserve material care.",
    sortOrder: 4,
  },
  {
    id: "w4s-21-4-5",
    lessonId: "w4l-21-4",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. The rich fool in Luke 12 was not condemned for being wealthy but for being \"not rich toward God.\" What does it look like in your context to be rich toward God — and where might you be building bigger barns instead?\n\n2. Jesus said you cannot serve both God and mammon. In honest self-assessment, where does money compete with God for your loyalty — in your decisions, your anxieties, or your sense of security?\n\n3. Paul argued that those who serve in ministry deserve material support. How do you personally contribute to sustaining the people and institutions that feed you spiritually — and is there room to grow?",
    sortOrder: 5,
  },
  {
    id: "w4s-21-4-6",
    lessonId: "w4l-21-4",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },
];

export const belief21Assessments = [
  {
    id: "w4a-21-1",
    lessonId: "w4l-21-1",
    title: "Knowledge Check",
    passingScore: 70,
  },
  {
    id: "w4a-21-2",
    lessonId: "w4l-21-2",
    title: "Knowledge Check",
    passingScore: 70,
  },
  {
    id: "w4a-21-3",
    lessonId: "w4l-21-3",
    title: "Knowledge Check",
    passingScore: 70,
  },
  {
    id: "w4a-21-4",
    lessonId: "w4l-21-4",
    title: "Knowledge Check",
    passingScore: 70,
  },
];

export const belief21Items = [
  // ── Lesson 1 Assessment Items ──────────────────────────────────
  {
    id: "w4i-21-1-1",
    assessmentId: "w4a-21-1",
    question: "In Genesis 1:26-28, what does God grant to humanity over creation?",
    options: ["Absolute ownership", "Equal partnership with God", "Permission to exploit freely", "Dominion as entrusted managers"],
    correctIndex: 3,
    explanation: "God grants dominion — a delegated authority to manage creation on His behalf — not outright ownership. The earth remains the Lord's (Psalm 24:1).",
  },
  {
    id: "w4i-21-1-2",
    assessmentId: "w4a-21-1",
    question: "What does David's prayer in 1 Chronicles 29:14 reveal about the source of Israel's generous offerings?",
    options: ["Israel's hard work earned everything they gave", "David personally funded the temple project", "Everything they offered originally came from God", "The offerings were borrowed from neighboring nations"],
    correctIndex: 2,
    explanation: "David acknowledged, 'All things come from You, and of Your own we have given You,' recognizing that every resource Israel gave had originated with God.",
  },
  {
    id: "w4i-21-1-3",
    assessmentId: "w4a-21-1",
    question: "According to 2 Corinthians 9:7, what kind of giver does God love?",
    options: ["A sacrificial giver", "A cheerful giver", "A consistent giver", "A generous giver"],
    correctIndex: 1,
    explanation: "Paul writes that God loves a cheerful giver — one who gives willingly from the heart, not under compulsion or resentment.",
  },
  {
    id: "w4i-21-1-4",
    assessmentId: "w4a-21-1",
    question: "Why is stewardship more accurately described as management rather than ownership?",
    options: ["Because God created and sustains all things, retaining ultimate ownership", "Because legal title always belongs to the government", "Because humans lack the intelligence to truly own anything", "Because ownership requires divine permission that was never granted"],
    correctIndex: 0,
    explanation: "Stewardship is management because God is the Creator and Sustainer of all things. Human beings are entrusted with responsibility, but the title remains with God.",
  },
  {
    id: "w4i-21-1-5",
    assessmentId: "w4a-21-1",
    question: "A church member tithes faithfully but feels resentful every time. According to 2 Corinthians 9:7 and the stewardship principles in this lesson, what is the core issue?",
    options: ["The member is giving too much and should reduce their tithe", "The member has not yet internalized that everything belongs to God, so giving feels like loss rather than return", "The church should stop asking for tithes so members do not feel pressured", "Resentment is normal and spiritually irrelevant as long as the tithe is paid"],
    correctIndex: 1,
    explanation: "Resentment in giving suggests the giver still views the resources as fundamentally their own. When a person grasps that all things come from God, returning a portion feels natural rather than burdensome.",
  },

  // ── Lesson 2 Assessment Items ──────────────────────────────────
  {
    id: "w4i-21-2-1",
    assessmentId: "w4a-21-2",
    question: "In Matthew 23:23, what did Jesus say the Pharisees had neglected while faithfully tithing?",
    options: ["Prayer and fasting", "Temple attendance", "Sabbath observance", "Justice, mercy, and faith"],
    correctIndex: 3,
    explanation: "Jesus rebuked the Pharisees for tithing meticulously while neglecting the weightier matters of the law: justice, mercy, and faith.",
  },
  {
    id: "w4i-21-2-2",
    assessmentId: "w4a-21-2",
    question: "What distinguished the generosity of the Macedonian churches described in 2 Corinthians 8:1-2?",
    options: ["They gave from great wealth", "They gave out of deep poverty with abundant joy", "They gave reluctantly under apostolic pressure", "They gave only after their own needs were fully met"],
    correctIndex: 1,
    explanation: "The Macedonian churches gave generously out of deep poverty and great joy — demonstrating that generosity flows from grace, not surplus.",
  },
  {
    id: "w4i-21-2-3",
    assessmentId: "w4a-21-2",
    question: "According to Adventist stewardship theology, what is the purpose of returning tithe to the 'storehouse'?",
    options: ["To support gospel ministry through the organized church", "To fund political campaigns", "To enrich church leaders personally", "To accumulate wealth for future investment"],
    correctIndex: 0,
    explanation: "Tithe is returned to the storehouse — the organized church — to sustain gospel ministry, following the biblical principle that those who serve in ministry deserve support (1 Corinthians 9:13-14).",
  },
  {
    id: "w4i-21-2-4",
    assessmentId: "w4a-21-2",
    question: "Which of the following best describes the Adventist understanding of whole-life stewardship?",
    options: ["Stewardship is primarily about tithing ten percent of income", "Stewardship encompasses finances, time, health, talents, relationships, and creation care", "Stewardship applies only during designated offering seasons", "Stewardship is an obligation for church leaders but optional for laypersons"],
    correctIndex: 1,
    explanation: "Adventist stewardship is holistic — encompassing finances, time, health, talents, relationships, influence, and care for the natural world, not just monetary giving.",
  },
  {
    id: "w4i-21-2-5",
    assessmentId: "w4a-21-2",
    question: "A young professional earns a good salary, tithes regularly, but rarely exercises, sleeps poorly, and has no margin in their schedule for family or service. From a whole-life stewardship perspective, what is missing?",
    options: ["Nothing — financial faithfulness is all stewardship requires", "They need to increase their tithe percentage to compensate", "They are neglecting stewardship of their body, time, and relationships", "They should quit their job and enter full-time ministry"],
    correctIndex: 2,
    explanation: "Whole-life stewardship includes the body, time, and relationships — not just finances. Neglecting health and relational commitments while tithing faithfully still represents incomplete stewardship.",
  },

  // ── Lesson 3 Assessment Items ──────────────────────────────────
  {
    id: "w4i-21-3-1",
    assessmentId: "w4a-21-3",
    question: "What two tasks did God assign to Adam in Genesis 2:15?",
    options: ["To name the animals and build a house", "To tend and keep the garden", "To rule over Eve and subdue the earth", "To plant crops and harvest them"],
    correctIndex: 1,
    explanation: "God placed Adam in the garden to tend (abad — work, cultivate) and keep (shamar — guard, protect) it, establishing stewardship as both productive and protective.",
  },
  {
    id: "w4i-21-3-2",
    assessmentId: "w4a-21-3",
    question: "In Haggai 1:9, why did God say Israel's efforts produced so little?",
    options: ["Because they had sinned against the Sabbath", "Because they prioritized their own houses while God's house lay in ruins", "Because they had intermarried with foreign nations", "Because they refused to offer animal sacrifices"],
    correctIndex: 1,
    explanation: "God rebuked Israel because they had prioritized building and beautifying their own homes while neglecting the temple. Disordered priorities led to frustration and scarcity.",
  },
  {
    id: "w4i-21-3-3",
    assessmentId: "w4a-21-3",
    question: "According to Romans 15:26-27, why did the Gentile churches feel obligated to support the believers in Jerusalem?",
    options: ["Because Jerusalem was the political capital of the Roman Empire", "Because the Gentiles had received spiritual blessings through Israel and responded with material support", "Because Paul commanded them to pay a mandatory tax", "Because the Jerusalem church was wealthier than the Gentile churches"],
    correctIndex: 1,
    explanation: "Paul explained that the Gentile churches shared material resources with Jerusalem because they had received spiritual blessings through the Jewish believers — generosity as reciprocal gratitude.",
  },
  {
    id: "w4i-21-3-4",
    assessmentId: "w4a-21-3",
    question: "How does Adventist theology connect Sabbath-keeping to environmental stewardship?",
    options: ["The Sabbath prohibits all interaction with nature", "Both are rooted in creation — the God who rested on the seventh day entrusted humanity with the care of His created world", "Environmental stewardship replaces Sabbath observance in modern practice", "There is no connection between Sabbath and creation care"],
    correctIndex: 1,
    explanation: "Adventists ground both Sabbath and creation care in the doctrine of creation. The same God who sanctified the seventh day commissioned humanity to tend and keep the earth.",
  },
  {
    id: "w4i-21-3-5",
    assessmentId: "w4a-21-3",
    question: "A family spends generously on their home, vacations, and hobbies but consistently delays repairs to the church building and declines volunteer opportunities. Based on Haggai's message, what stewardship principle are they overlooking?",
    options: ["The principle that Christians should never enjoy material blessings", "The principle that personal comfort should not consistently displace God's purposes and community responsibility", "The principle that only pastors are responsible for church upkeep", "The principle that volunteering is optional for families with children"],
    correctIndex: 1,
    explanation: "Haggai challenged Israel for running to their own houses while God's house lay in ruins. The principle is that personal comfort should not habitually take precedence over God's purposes and the needs of the community.",
  },

  // ── Lesson 4 Assessment Items ──────────────────────────────────
  {
    id: "w4i-21-4-1",
    assessmentId: "w4a-21-4",
    question: "In 1 Corinthians 9:9-14, what argument does Paul make about supporting those in gospel ministry?",
    options: ["Ministers should work secular jobs and never accept financial support", "Those who labor in spiritual service have a legitimate right to material support from the community", "Only apostles deserve financial compensation", "Financial support corrupts the integrity of ministry"],
    correctIndex: 1,
    explanation: "Paul uses the Old Testament principle of not muzzling the working ox to argue that those who sow spiritual things have a rightful claim to material support from those they serve.",
  },
  {
    id: "w4i-21-4-2",
    assessmentId: "w4a-21-4",
    question: "Why did God call the man in Luke 12:16-21 a fool?",
    options: ["Because he was a successful farmer", "Because he stored grain instead of selling it", "Because he accumulated wealth for himself without being rich toward God", "Because he planned to retire early"],
    correctIndex: 2,
    explanation: "The rich fool was condemned not for being wealthy but for treating accumulation as life's purpose while neglecting generosity and relationship with God — he was not 'rich toward God.'",
  },
  {
    id: "w4i-21-4-3",
    assessmentId: "w4a-21-4",
    question: "According to Matthew 6:24, what is the fundamental problem with trying to serve both God and mammon?",
    options: ["It is physically impossible to hold money and pray at the same time", "The human heart cannot sustain divided ultimate allegiance — one master will always dominate", "God forbids all financial activity", "Mammon is a literal demon that possesses wealthy people"],
    correctIndex: 1,
    explanation: "Jesus teaches that ultimate loyalty cannot be split. Either God is the master and money is a tool, or money becomes the master and God is sidelined. The heart cannot serve two ultimate authorities.",
  },
  {
    id: "w4i-21-4-4",
    assessmentId: "w4a-21-4",
    question: "Which of the following best describes the difference between biblical stewardship and prosperity theology?",
    options: ["There is no difference — both teach that giving leads to financial blessing", "Biblical stewardship promises faithful management leads to eternal reward; prosperity theology promises material return for material giving", "Biblical stewardship discourages all giving; prosperity theology encourages it", "Prosperity theology is simply another name for the Adventist view of stewardship"],
    correctIndex: 1,
    explanation: "Biblical stewardship teaches faithfulness with the promise of eternal reward and God's varied blessings, while prosperity theology reduces the relationship to a transactional formula: give money, get money back.",
  },
  {
    id: "w4i-21-4-5",
    assessmentId: "w4a-21-4",
    question: "A church leader tells the congregation, 'If you do not tithe, God will curse your finances.' Based on the stewardship principles in this lesson, what is wrong with this approach?",
    options: ["Nothing — Malachi 3 supports this exact statement", "It uses guilt and fear to coerce giving, which violates the principle that God loves a cheerful giver (2 Corinthians 9:7)", "It is wrong because tithing is no longer required in the New Testament", "The statement is too gentle and should be even stronger"],
    correctIndex: 1,
    explanation: "While Malachi 3 uses strong language, using it to coerce giving through fear and guilt contradicts Paul's teaching that God loves a cheerful giver. Stewardship appeals must invite, not manipulate.",
  },
];

// ════════════════════════════════════════════════════════════════
// BELIEF 22 — Christian Behavior
// ════════════════════════════════════════════════════════════════

export const belief22Lessons = [
  {
    id: "w4l-22-1",
    moduleId: "bmod-022",
    title: "Biblical Foundations: Transformed, Not Conformed",
    description: "Exploring the New Testament call to a renewed mind and a Christ-shaped life — understanding Christian behavior as the fruit of transformation, not a prerequisite for acceptance.",
    lessonOrder: 1,
    anchorText: "Romans 12:1-2; Philippians 4:8; 1 John 2:6",
    anchorBookId: 45,
    anchorChapter: 12,
    anchorVerseStart: 1,
    anchorVerseEnd: 2,
    estimatedMinutes: 35,
  },
  {
    id: "w4l-22-2",
    moduleId: "bmod-022",
    title: "Doctrinal Formulation: Holiness as Response to Grace",
    description: "Understanding the Adventist perspective on sanctified living — not as moral self-improvement but as the Spirit-empowered response of those who have already been accepted in Christ.",
    lessonOrder: 2,
    anchorText: "Ephesians 5:1-21; 1 Corinthians 6:19-20; 2 Corinthians 6:14-7:1",
    anchorBookId: 49,
    anchorChapter: 5,
    anchorVerseStart: 1,
    anchorVerseEnd: 21,
    estimatedMinutes: 30,
  },
  {
    id: "w4l-22-3",
    moduleId: "bmod-022",
    title: "Practical Implications: Living as Light",
    description: "Translating the call to holy living into everyday decisions — how faith shapes what we consume, how we treat our bodies, how we interact with others, and how we engage with culture.",
    lessonOrder: 3,
    anchorText: "1 Corinthians 10:31; 1 Peter 3:1-4; 3 John 1:2",
    anchorBookId: 46,
    anchorChapter: 10,
    anchorVerseStart: 31,
    anchorVerseEnd: 31,
    estimatedMinutes: 30,
  },
  {
    id: "w4l-22-4",
    moduleId: "bmod-022",
    title: "Misunderstandings & Challenges",
    description: "Addressing the tension between liberty and holiness, the danger of legalism, and the challenge of cultural engagement — clarifying what Christian behavior is and what it is not.",
    lessonOrder: 4,
    anchorText: "Galatians 5:1,13-26; Colossians 2:20-23; Matthew 23:23-28",
    anchorBookId: 48,
    anchorChapter: 5,
    anchorVerseStart: 1,
    anchorVerseEnd: 1,
    estimatedMinutes: 30,
  },
];

export const belief22Sections = [
  // ── Lesson 1: Biblical Foundations ──────────────────────────────
  {
    id: "w4s-22-1-1",
    lessonId: "w4l-22-1",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"I beseech you therefore, brethren, by the mercies of God, that you present your bodies a living sacrifice, holy, acceptable to God, which is your reasonable service. And do not be conformed to this world, but be transformed by the renewing of your mind, that you may prove what is that good and acceptable and perfect will of God.\" — Romans 12:1-2 (NKJV)\n\n\"Finally, brethren, whatever things are true, whatever things are noble, whatever things are just, whatever things are pure, whatever things are lovely, whatever things are of good report, if there is any virtue and if there is anything praiseworthy — meditate on these things.\" — Philippians 4:8 (NKJV)\n\n\"He who says he abides in Him ought himself also to walk just as He walked.\" — 1 John 2:6 (NKJV)\n\nAs you read, notice that Paul's appeal in Romans 12 begins with \"therefore\" — it rests on everything he has said in the previous eleven chapters about God's mercy. What does this sequence tell you about the relationship between grace and behavior?",
    sortOrder: 1,
  },
  {
    id: "w4s-22-1-2",
    lessonId: "w4l-22-1",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Romans 12:1-2 is one of the most important passages in the New Testament for understanding Christian behavior, and its placement is everything. Paul does not begin his letter with moral instructions. He spends eleven chapters laying out the depths of human sin, the sufficiency of Christ's atonement, the gift of justification by faith, the power of the Spirit, and the faithfulness of God's purposes. Only then — with the word \"therefore\" — does he turn to how believers should live. The sequence is non-negotiable: mercy first, then response. Behavior is the fruit of salvation, not the root of it.\n\nThe call to present your body as a \"living sacrifice\" would have startled Paul's original audience. Sacrifices were dead animals on an altar. Paul reimagines the concept: the believer's entire embodied existence — choices, habits, relationships, appetites — becomes an offering to God. This is not the suppression of the body but its consecration. The body is not a prison to escape but a temple to honor.\n\n\"Do not be conformed to this world, but be transformed by the renewing of your mind.\" The Greek verbs reveal a contrast between passive molding (syschematizo — being pressed into an external shape) and active internal change (metamorphoo — metamorphosis, transformation from within). Conformity is what happens when you stop thinking. Transformation is what happens when God's Spirit reshapes the way you see, evaluate, and respond to reality.\n\nPhilippians 4:8 provides a practical filter for the renewed mind. Paul does not issue a list of prohibited activities. Instead, he describes a quality of attention: focus on what is true, noble, just, pure, lovely, and praiseworthy. The principle is generative rather than restrictive — it gives the believer a compass for every cultural, relational, and entertainment decision without reducing the Christian life to a checklist.\n\nJohn anchors it all in Christ Himself: \"He who says he abides in Him ought himself also to walk just as He walked.\" The standard is not an abstract moral code but a living Person. Christian behavior is Christ-shaped behavior — not perfection achieved by willpower but resemblance cultivated by relationship.",
    sortOrder: 2,
  },
  {
    id: "w4s-22-1-3",
    lessonId: "w4l-22-1",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "Seventh-day Adventists understand Christian behavior within the framework of sanctification — the ongoing work of the Holy Spirit in the believer's life after justification. Several key convictions shape this understanding:\n\n**Grace precedes obedience.** The sequence of Romans — eleven chapters of gospel before one word of moral instruction — reflects Adventist theology at its best. Behavior change that is not rooted in an experience of God's mercy degenerates into moralism. Adventists affirm that we are saved by grace through faith (Ephesians 2:8-9) and that good works are the result, not the cause, of salvation (Ephesians 2:10).\n\n**The whole person is involved.** Paul's call to present \"your bodies\" makes sanctification tangible. It is not a disembodied spirituality. How believers eat, exercise, rest, and care for their physical health is part of the life of faith. Adventist health principles — including dietary care, temperance, and physical activity — flow from this conviction, not from cultural preference.\n\n**Transformation, not mere compliance.** The renewed mind of Romans 12:2 is the engine of genuine Christian behavior. External conformity to a set of rules without internal transformation produces the kind of religion Jesus condemned in the Pharisees. Adventist teaching at its best emphasizes heart change empowered by the Spirit, not behavioral modification enforced by community pressure.\n\n**Christ as the pattern.** John's standard — walking as Jesus walked — prevents Christian behavior from becoming an arbitrary list of dos and don'ts. Every behavioral question can be tested against the life of Jesus: Does this reflect His compassion? His integrity? His priorities? His relationship with the Father?\n\n**Corrective boundary:** Christian behavior is never a ladder to God's approval. It is the evidence that God's approval has already been received. Any teaching that makes behavioral conformity the condition of salvation reverses the gospel and produces either pride or despair.",
    sortOrder: 3,
  },
  {
    id: "w4s-22-1-4",
    lessonId: "w4l-22-1",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Begin cultivating a transformed mind and a Christ-shaped life this week:\n\n1. **Articulate the grace-behavior sequence.** Write a brief explanation (four to five sentences) of why Christian behavior follows grace rather than earning it. Use Romans 12:1-2 as your anchor text. Share it with someone who may be struggling with legalism or discouragement.\n\n2. **Apply the Philippians 4:8 filter.** For one full day, consciously evaluate what you read, watch, listen to, and discuss against Paul's criteria: Is it true? Noble? Just? Pure? Lovely? Praiseworthy? At the end of the day, journal what you noticed — what passed the filter easily, and what did not.\n\n3. **Spend time with Jesus in the Gospels.** Read one chapter from the Gospel of Mark this week with a single question in mind: How did Jesus walk? Note one specific quality of His life — patience, courage, compassion, honesty — and ask the Holy Spirit to cultivate that quality in you this week.",
    sortOrder: 4,
  },
  {
    id: "w4s-22-1-5",
    lessonId: "w4l-22-1",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Paul says to present your body as a living sacrifice. What does it mean for you, practically, to treat your daily embodied life — eating, working, resting, relating — as an offering to God?\n\n2. Romans 12:2 contrasts being conformed (pressed into a mold from outside) with being transformed (changed from within). In what areas of your life do you feel the pressure of conformity most strongly, and what would genuine transformation look like there?\n\n3. John says that those who abide in Christ should walk as He walked. When you look at the life of Jesus, which aspect of His character do you most long to see reflected in your own daily behavior?",
    sortOrder: 5,
  },
  {
    id: "w4s-22-1-6",
    lessonId: "w4l-22-1",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },

  // ── Lesson 2: Doctrinal Formulation ────────────────────────────
  {
    id: "w4s-22-2-1",
    lessonId: "w4l-22-2",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"Therefore be imitators of God as dear children. And walk in love, as Christ also has loved us and given Himself for us, an offering and a sacrifice to God for a sweet-smelling aroma. But fornication and all uncleanness or covetousness, let it not even be named among you, as is fitting for saints… See then that you walk circumspectly, not as fools but as wise, redeeming the time, because the days are evil.\" — Ephesians 5:1-3, 15-16 (NKJV)\n\n\"Or do you not know that your body is the temple of the Holy Spirit who is in you, whom you have from God, and you are not your own? For you were bought at a price; therefore glorify God in your body and in your spirit, which are God's.\" — 1 Corinthians 6:19-20 (NKJV)\n\n\"Do not be unequally yoked together with unbelievers. For what fellowship has righteousness with lawlessness? And what communion has light with darkness?… Therefore, having these promises, beloved, let us cleanse ourselves from all filthiness of the flesh and spirit, perfecting holiness in the fear of God.\" — 2 Corinthians 6:14; 7:1 (NKJV)\n\nAs you read, consider: What is the basis for Paul's call to purity in each passage? Is it fear of punishment, or something else entirely?",
    sortOrder: 1,
  },
  {
    id: "w4s-22-2-2",
    lessonId: "w4l-22-2",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Ephesians 5 opens with a breathtaking identity statement: \"Be imitators of God as dear children.\" Children imitate their parents not out of obligation but out of admiration and belonging. Paul's moral instructions flow from this relational identity. The believer is a beloved child of God, and holy living is the natural expression of that identity — not a performance designed to earn the Father's love.\n\nThe specific behaviors Paul addresses — sexual immorality, impurity, covetousness, foolish talk — are not arbitrary taboos. They are patterns that erode the very relationships, integrity, and spiritual sensitivity that define a life lived in the light. Paul contrasts darkness and light not as moral categories imposed from outside but as environments that shape perception and behavior. Those who walk in light see clearly; those who walk in darkness stumble without knowing why.\n\nPaul's declaration in 1 Corinthians 6:19-20 provides the theological engine for bodily holiness: \"You are not your own. You were bought at a price.\" This is not a statement of divine coercion but of redemptive belonging. The body of the believer is the residence of the Holy Spirit. What we do with our bodies — sexually, dietarily, recreationally — either honors or dishonors the One who dwells within. The logic is not \"obey or be punished\" but \"you belong to Someone; live accordingly.\"\n\nThe call in 2 Corinthians 6:14-7:1 to avoid being \"unequally yoked\" has often been misapplied to isolate believers from all contact with unbelievers. Paul's concern is more specific: he is warning against entangling commitments — partnerships, alliances, and intimate bonds — that compromise the believer's primary allegiance to Christ. The principle is not withdrawal from the world but discernment about the commitments that shape one's life. The goal is holiness \"in the fear of God\" — a reverent awareness of who God is and who we are in relation to Him.",
    sortOrder: 2,
  },
  {
    id: "w4s-22-2-3",
    lessonId: "w4l-22-2",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "Adventist teaching on Christian behavior draws together several strands of biblical theology into a coherent, grace-rooted vision of sanctified living:\n\n**Identity before behavior.** Ephesians 5:1 establishes the order: you are a dear child of God, therefore live like one. Adventist theology at its best begins with what God has done (justification) and moves to what God is doing (sanctification). Behavior is evidence of identity, not the means of acquiring it.\n\n**The body as temple.** The Adventist emphasis on health — including dietary principles, avoidance of harmful substances, and care for physical well-being — is grounded directly in 1 Corinthians 6:19-20. The body is not incidental to the spiritual life; it is the very dwelling place of the Spirit. This conviction gives Adventist health teaching its theological rationale: caring for the body is an act of worship, not a cultural preference.\n\n**Holistic sanctification.** Paul's vision in Ephesians 5 touches speech, sexuality, time management, worship, and relationships. Adventists understand sanctification as a process that encompasses the whole person — mind, body, relationships, and habits. The Spirit does not sanctify only the \"spiritual\" parts of a person while leaving daily behavior untouched.\n\n**Discernment, not isolation.** The \"unequal yoke\" passage is not a call to retreat from society. Adventists are called to be in the world — serving, witnessing, loving — while exercising wisdom about the commitments that shape their deepest loyalties. Jesus ate with sinners but never compromised His mission.\n\n**Corrective boundary:** Holiness is not a behavioral checklist enforced by community surveillance. When standards become tools of judgment rather than expressions of love, they cease to reflect the character of the God they claim to honor. The fruit of the Spirit — love, joy, peace, patience — is the true measure of sanctification, not external conformity alone.",
    sortOrder: 3,
  },
  {
    id: "w4s-22-2-4",
    lessonId: "w4l-22-2",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Let the doctrine of holiness shape your daily habits this week:\n\n1. **Articulate holiness as response.** Write a four-sentence summary explaining why Adventist teaching roots holy living in grace rather than in self-improvement. Use 1 Corinthians 6:19-20 as your anchor. Share it with a friend and discuss how this framing changes the way you approach behavioral decisions.\n\n2. **Honor the temple.** Choose one way to better care for your body this week as an act of worship — improve your sleep, take a daily walk, drink more water, or reduce consumption of something that harms your health. Frame the decision explicitly as stewardship of the Spirit's dwelling place.\n\n3. **Practice redemptive time use.** Paul says to redeem the time because the days are evil (Ephesians 5:16). Audit how you spent your time over the past three days. Identify one block of time that could be better aligned with your identity as a child of God — and redirect it toward prayer, service, or meaningful relationship.",
    sortOrder: 4,
  },
  {
    id: "w4s-22-2-5",
    lessonId: "w4l-22-2",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Paul says to be imitators of God \"as dear children.\" How does thinking of holiness as imitation of a loving Father — rather than compliance with a strict rule-giver — change the way you approach daily moral decisions?\n\n2. Your body is described as the temple of the Holy Spirit. How does this reality affect the way you think about what you eat, how you rest, and how you treat your physical self?\n\n3. The call to avoid being \"unequally yoked\" is about the commitments that shape your deepest loyalties. Are there relationships, partnerships, or habits in your life that compete with your allegiance to Christ — and how might you address them with grace and wisdom?",
    sortOrder: 5,
  },
  {
    id: "w4s-22-2-6",
    lessonId: "w4l-22-2",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },

  // ── Lesson 3: Practical Implications ───────────────────────────
  {
    id: "w4s-22-3-1",
    lessonId: "w4l-22-3",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"Therefore, whether you eat or drink, or whatever you do, do all to the glory of God.\" — 1 Corinthians 10:31 (NKJV)\n\n\"Do not let your adornment be merely outward — arranging the hair, wearing gold, or putting on fine apparel — rather let it be the hidden person of the heart, with the incorruptible beauty of a gentle and quiet spirit, which is very precious in the sight of God.\" — 1 Peter 3:3-4 (NKJV)\n\n\"Beloved, I pray that you may prosper in all things and be in health, just as your soul prospers.\" — 3 John 1:2 (NKJV)\n\nAs you read, notice how these texts address the most ordinary dimensions of life — eating, drinking, appearance, health. What does it mean that even these mundane areas fall under the umbrella of glorifying God?",
    sortOrder: 1,
  },
  {
    id: "w4s-22-3-2",
    lessonId: "w4l-22-3",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Paul's declaration in 1 Corinthians 10:31 is deceptively simple: \"Whatever you do, do all to the glory of God.\" The scope of the word \"whatever\" is total. Paul does not divide life into sacred and secular compartments. Eating is not beneath spiritual concern. Drinking is not outside the scope of discipleship. The daily, mundane, repetitive decisions of ordinary life are all occasions for glorifying God — or for failing to. This principle liberates the Christian from the false notion that God cares only about church activities and is indifferent to the rest of life.\n\nPeter's counsel to women in 1 Peter 3:3-4 has sometimes been wielded as a prohibition against all adornment. A careful reading reveals a different emphasis. Peter does not forbid outward appearance but redirects attention to what is \"very precious in the sight of God\" — the inner character of the person. The contrast is between a life organized around external display and a life that cultivates inner beauty: gentleness, strength of spirit, integrity. The principle applies to all believers, not only women. When appearance becomes the primary investment of time, energy, and identity, something essential has been displaced.\n\nJohn's prayer in 3 John 1:2 connects physical health to spiritual health: \"I pray that you may prosper in all things and be in health, just as your soul prospers.\" The body and the soul are not independent systems. Physical well-being affects spiritual capacity, and spiritual health shapes physical choices. This integrated view of the person — body, mind, spirit — is foundational to the way believers approach health, recreation, diet, and self-care. It is not that the body must be punished into submission; it is that the body is part of the person God is redeeming.",
    sortOrder: 2,
  },
  {
    id: "w4s-22-3-3",
    lessonId: "w4l-22-3",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "Adventist practical theology applies the principle of \"all to the glory of God\" across the full range of daily life:\n\n**Diet and health.** Adventists are widely recognized for their emphasis on healthful living. This is not a salvation requirement but a stewardship response. The body, as the temple of the Holy Spirit, deserves intentional care. Adventist health principles — including a plant-rich diet, avoidance of alcohol and tobacco, regular exercise, and adequate rest — are rooted in Scripture, supported by scientific evidence, and practiced as a form of gratitude, not as a means of earning God's favor.\n\n**Simplicity in appearance.** Peter's counsel toward inner beauty over outward display informs Adventist teaching on modesty and simplicity. The goal is not uniformity or self-denial for its own sake but a reorientation of values — investing more in character than in image, more in generosity than in consumption. Different cultures will express this principle differently, but the underlying conviction remains: what is most precious to God is the hidden person of the heart.\n\n**Entertainment and media.** Paul's \"whatever you do\" principle applies directly to the content believers consume. Philippians 4:8 provides a filter — true, noble, just, pure, lovely, praiseworthy — that can guide decisions about media, recreation, and leisure without requiring an exhaustive list of approved and banned activities. The question is not \"Is this explicitly forbidden?\" but \"Does this nourish my mind and draw me closer to Christ?\"\n\n**Relationships and social life.** Christian behavior extends to how believers speak, listen, resolve conflict, and treat others — especially those who are different, difficult, or marginalized. The Sermon on the Mount (Matthew 5-7) provides the charter for relational holiness: integrity, peacemaking, generosity, and love for enemies.\n\n**Corrective boundary:** Christian behavior must never become a set of cultural markers used to judge, exclude, or rank believers. When standards of diet, dress, or entertainment become instruments of superiority rather than expressions of love, they distort the gospel. The fruit of the Spirit — not conformity to a cultural code — is the true evidence of the transformed life.",
    sortOrder: 3,
  },
  {
    id: "w4s-22-3-4",
    lessonId: "w4l-22-3",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Apply the principle of \"all to the glory of God\" to the ordinary details of your life:\n\n1. **Articulate why daily choices matter.** Write a brief paragraph explaining to a friend how eating, dressing, and recreational choices can glorify God — without sounding legalistic. Ground your explanation in 1 Corinthians 10:31 and the conviction that the body is the Spirit's temple.\n\n2. **Make one health-honoring change.** Identify one area of physical well-being you have been neglecting — sleep, nutrition, exercise, hydration, or stress management. Commit to one specific, measurable improvement this week. Frame it as worship, not willpower.\n\n3. **Serve someone with quiet kindness.** Peter highlights the beauty of a gentle and quiet spirit. This week, look for an opportunity to serve someone without drawing attention to yourself — a note of encouragement, a practical favor, a listening ear. Let the act cultivate the inner beauty Peter describes.",
    sortOrder: 4,
  },
  {
    id: "w4s-22-3-5",
    lessonId: "w4l-22-3",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Paul says to do all things — even eating and drinking — to the glory of God. Which ordinary area of your life have you treated as spiritually neutral that might actually be an opportunity for worship?\n\n2. Peter contrasts outward adornment with the hidden person of the heart. Where do you tend to invest more energy — in how you appear to others or in the cultivation of inner character? What would a shift in that balance look like?\n\n3. John prays for health that matches the prosperity of the soul. How do your physical habits reflect — or contradict — the spiritual values you profess?",
    sortOrder: 5,
  },
  {
    id: "w4s-22-3-6",
    lessonId: "w4l-22-3",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },

  // ── Lesson 4: Misunderstandings & Challenges ───────────────────
  {
    id: "w4s-22-4-1",
    lessonId: "w4l-22-4",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"Stand fast therefore in the liberty by which Christ has made us free, and do not be entangled again with a yoke of bondage… For you, brethren, have been called to liberty; only do not use liberty as an opportunity for the flesh, but through love serve one another. For all the law is fulfilled in one word, even in this: 'You shall love your neighbor as yourself.'\" — Galatians 5:1, 13-14 (NKJV)\n\n\"Therefore, if you died with Christ from the basic principles of the world, why, as though living in the world, do you subject yourselves to regulations — 'Do not touch, do not taste, do not handle,' which all concern things which perish with the using — according to the commandments and doctrines of men? These things indeed have an appearance of wisdom in self-imposed religion, false humility, and neglect of the body, but are of no value against the indulgence of the flesh.\" — Colossians 2:20-23 (NKJV)\n\n\"Woe to you, scribes and Pharisees, hypocrites! For you pay tithe of mint and anise and cummin, and have neglected the weightier matters of the law: justice and mercy and faith. These you ought to have done, without leaving the others undone… You are like whitewashed tombs which indeed appear beautiful outwardly, but inside are full of dead men's bones and all uncleanness.\" — Matthew 23:23, 27 (NKJV)\n\nAs you read, notice the sharp distinction Paul draws between liberty and license, and between genuine holiness and human-made regulations.",
    sortOrder: 1,
  },
  {
    id: "w4s-22-4-2",
    lessonId: "w4l-22-4",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Galatians 5 holds two equal and opposite dangers in tension. On one side is legalism — the attempt to earn standing with God through behavioral performance. Paul calls it a \"yoke of bondage\" and commands believers to stand free from it. Christ has liberated them; to return to a system of merit is to nullify the grace that set them free. On the other side is license — using freedom as a cover for self-indulgence. Paul refuses to let liberty become an excuse for the flesh. The solution to both dangers is the same: love. \"Through love serve one another.\" Love fulfills the law because love does no harm to its neighbor and actively seeks the other's good.\n\nColossians 2:20-23 is one of Paul's most pointed warnings against human-made religious regulations. \"Do not touch, do not taste, do not handle\" — these were not God's commands but human additions that gave an appearance of devotion while accomplishing nothing of spiritual value. Paul's verdict is devastating: they look wise, but they have \"no value against the indulgence of the flesh.\" External restrictions imposed by human authority cannot transform the heart. Only the Spirit of God can do that. This passage is a permanent caution to every religious community that is tempted to multiply rules beyond what Scripture requires.\n\nJesus' words in Matthew 23 deliver the same verdict from a different angle. The Pharisees were paragons of external compliance. They tithed their herb gardens down to the last sprig of mint. But they neglected justice, mercy, and faith — the matters that actually reveal the condition of the heart. Jesus' image of whitewashed tombs is unforgettable: beautiful on the outside, full of death on the inside. External conformity without internal transformation is the most dangerous form of religion because it looks real to everyone — including, often, the person practicing it.\n\nTaken together, these passages define a narrow path. Christian behavior is neither a system of human-made rules nor a blank check for self-indulgence. It is Spirit-empowered, love-motivated, Christ-shaped living that flows from a transformed heart and expresses itself in justice, mercy, and faithfulness.",
    sortOrder: 2,
  },
  {
    id: "w4s-22-4-3",
    lessonId: "w4l-22-4",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "Adventist engagement with Christian behavior must navigate the same tensions Paul and Jesus addressed — and the same risks:\n\n**Misunderstanding 1: Christian behavior as a salvation checklist.** Some reduce the Christian life to a series of dos and don'ts — a behavioral scorecard that determines one's standing with God. This is precisely what Paul opposes in Galatians 5 and Colossians 2. Adventist theology affirms that salvation is by grace through faith. Behavioral standards are the fruit of a saved life, not the price of admission. When standards become the measure of spiritual worth, the community slides toward the Pharisaism Jesus condemned.\n\n**Misunderstanding 2: Liberty means anything goes.** Others react against legalism by discarding all behavioral expectations. Paul anticipates this move and blocks it: \"Do not use liberty as an opportunity for the flesh.\" Freedom in Christ is not freedom to do whatever feels good; it is freedom to love and serve without the burden of earning acceptance. Liberty and holiness are companions, not competitors.\n\n**Misunderstanding 3: Human traditions equal divine commands.** Every religious community develops cultural norms — expectations about dress, diet, entertainment, Sabbath practice — that may be wise but are not explicitly commanded by Scripture. Paul's warning in Colossians 2:20-23 cautions against elevating these traditions to the level of divine requirements. Adventists must distinguish between biblical principles (which are binding) and cultural applications (which may vary across time and geography).\n\n**Misunderstanding 4: External conformity equals holiness.** Jesus' rebuke of the Pharisees remains relevant. A person can keep every standard in a church manual and still be full of pride, gossip, and lovelessness. The fruit of the Spirit — love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control (Galatians 5:22-23) — is the ultimate test of genuine sanctification.\n\n**Corrective boundary:** Christian behavior is the evidence of grace at work in the life, never its substitute. Any approach to behavioral standards that produces pride in the compliant or shame in the struggling has departed from the gospel it claims to defend.",
    sortOrder: 3,
  },
  {
    id: "w4s-22-4-4",
    lessonId: "w4l-22-4",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Navigate the tension between liberty and holiness with clarity and grace:\n\n1. **Articulate the difference between legalism and sanctification.** Write a four-to-five-sentence explanation of how genuine Christian behavior differs from a moral checklist. Use Galatians 5:1, 13 as your guide. Share it with a study partner or small group and discuss where your community may be drifting toward one extreme or the other.\n\n2. **Examine your motivations.** Choose one behavioral standard you currently practice — dietary, Sabbath observance, media habits, or another area. Ask yourself honestly: Am I doing this because I love God and believe it honors Him, or because I fear judgment from others? If the motivation has drifted toward fear or performance, spend time in prayer recentering on grace.\n\n3. **Extend grace to someone who lives differently.** Identify a fellow believer whose lifestyle choices differ from yours on a matter that is not explicitly commanded in Scripture. Instead of judging, pray for them, seek to understand their perspective, and let love — not conformity — define the relationship.",
    sortOrder: 4,
  },
  {
    id: "w4s-22-4-5",
    lessonId: "w4l-22-4",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Paul warns against both legalism and license. Which danger do you find yourself more naturally drawn toward — adding rules to feel secure, or relaxing standards to feel free? How does the gospel address your particular tendency?\n\n2. Colossians 2:20-23 says that human-made regulations have \"an appearance of wisdom\" but no real power to change the heart. Are there practices in your spiritual life that look impressive externally but have not actually transformed you internally? What would genuine change look like?\n\n3. Jesus called the Pharisees \"whitewashed tombs\" — beautiful outside, dead inside. How do you guard against the subtle temptation of maintaining an outward appearance of holiness while neglecting justice, mercy, and faith in your private life?",
    sortOrder: 5,
  },
  {
    id: "w4s-22-4-6",
    lessonId: "w4l-22-4",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },
];

export const belief22Assessments = [
  {
    id: "w4a-22-1",
    lessonId: "w4l-22-1",
    title: "Knowledge Check",
    passingScore: 70,
  },
  {
    id: "w4a-22-2",
    lessonId: "w4l-22-2",
    title: "Knowledge Check",
    passingScore: 70,
  },
  {
    id: "w4a-22-3",
    lessonId: "w4l-22-3",
    title: "Knowledge Check",
    passingScore: 70,
  },
  {
    id: "w4a-22-4",
    lessonId: "w4l-22-4",
    title: "Knowledge Check",
    passingScore: 70,
  },
];

export const belief22Items = [
  // ── Lesson 1 Assessment Items ──────────────────────────────────
  {
    id: "w4i-22-1-1",
    assessmentId: "w4a-22-1",
    question: "Why does Paul place his moral instructions in Romans 12 after eleven chapters about God's mercy?",
    options: ["Because he ran out of theological material", "Because behavior is the response to grace, not the means of earning it", "Because moral teaching is less important than doctrine", "Because the Roman church was already perfectly obedient"],
    correctIndex: 1,
    explanation: "Paul's structure is intentional: mercy first, then response. The word 'therefore' in Romans 12:1 signals that all behavioral instructions flow from the grace described in chapters 1-11.",
  },
  {
    id: "w4i-22-1-2",
    assessmentId: "w4a-22-1",
    question: "In Romans 12:2, what is the difference between being 'conformed' and being 'transformed'?",
    options: ["Conformed means changing voluntarily; transformed means being forced to change", "Conformed means being passively pressed into an external mold; transformed means internal change from within by the Spirit", "There is no meaningful difference between the two words", "Conformed refers to physical appearance; transformed refers to financial habits"],
    correctIndex: 1,
    explanation: "The Greek words reveal a contrast: syschematizo (conformed) is passive molding by external pressure, while metamorphoo (transformed) is active internal change — a metamorphosis of the mind by God's Spirit.",
  },
  {
    id: "w4i-22-1-3",
    assessmentId: "w4a-22-1",
    question: "According to Philippians 4:8, what approach does Paul take to guiding the believer's thought life?",
    options: ["He provides an exhaustive list of forbidden thoughts", "He describes qualities to focus on — true, noble, just, pure, lovely, praiseworthy — giving a compass rather than a checklist", "He says believers should not think about anything except Scripture", "He encourages ignoring all cultural engagement"],
    correctIndex: 1,
    explanation: "Paul provides a generative filter — qualities of attention (true, noble, just, pure, lovely, praiseworthy) — rather than an exhaustive list of prohibitions, giving believers a compass for every decision.",
  },
  {
    id: "w4i-22-1-4",
    assessmentId: "w4a-22-1",
    question: "What is the ultimate standard for Christian behavior according to 1 John 2:6?",
    options: ["Church tradition", "The life and example of Jesus Christ", "The opinions of respected church leaders", "Cultural norms of the surrounding society"],
    correctIndex: 1,
    explanation: "John says that those who abide in Christ should 'walk just as He walked.' The standard for Christian behavior is not an abstract code but the living Person of Jesus.",
  },
  {
    id: "w4i-22-1-5",
    assessmentId: "w4a-22-1",
    question: "A new believer asks, 'Do I need to clean up my life before God will accept me?' Based on the Romans 12:1-2 principle, what is the best response?",
    options: ["Yes — God requires moral perfection before extending grace", "No — God's mercy comes first, and behavioral transformation is the grateful response to acceptance already given", "Behavior and grace are completely unrelated, so live however you want", "It depends on how serious your sins are"],
    correctIndex: 1,
    explanation: "Romans 12 teaches that God's mercy comes first (chapters 1-11), and behavior is the response ('therefore'). Acceptance precedes transformation, not the other way around.",
  },

  // ── Lesson 2 Assessment Items ──────────────────────────────────
  {
    id: "w4i-22-2-1",
    assessmentId: "w4a-22-2",
    question: "According to Ephesians 5:1, what is the basis for Paul's call to holy living?",
    options: ["Fear of divine punishment", "The believer's identity as a dear child of God", "Desire for social respectability", "The need to earn God's approval"],
    correctIndex: 1,
    explanation: "Paul roots holy living in identity: 'Be imitators of God as dear children.' Holiness flows from knowing who you are — a beloved child — not from fear or performance.",
  },
  {
    id: "w4i-22-2-2",
    assessmentId: "w4a-22-2",
    question: "In 1 Corinthians 6:19-20, Paul says believers are 'not your own.' What does this mean for bodily choices?",
    options: ["The body is irrelevant to spiritual life", "The body belongs to God as the temple of the Holy Spirit, so physical choices are acts of worship", "Christians should neglect the body to focus on the soul", "Only dietary choices are affected by this principle"],
    correctIndex: 1,
    explanation: "Paul teaches that the believer's body is the dwelling place of the Holy Spirit and was purchased at the price of Christ's blood. Therefore, how we treat our bodies is a matter of worship and stewardship.",
  },
  {
    id: "w4i-22-2-3",
    assessmentId: "w4a-22-2",
    question: "What does Paul mean by warning against being 'unequally yoked' in 2 Corinthians 6:14?",
    options: ["Christians should have no contact with non-Christians", "Believers should avoid entangling commitments that compromise their primary allegiance to Christ", "Marriage between people of different denominations is forbidden", "Christians must separate from society entirely"],
    correctIndex: 1,
    explanation: "Paul's warning is about deep, binding commitments — partnerships and alliances — that could compromise the believer's loyalty to Christ, not about avoiding all contact with unbelievers.",
  },
  {
    id: "w4i-22-2-4",
    assessmentId: "w4a-22-2",
    question: "How does Adventist theology distinguish between sanctification and legalism?",
    options: ["There is no distinction — they are the same thing", "Sanctification is the Spirit-empowered response to grace; legalism is behavioral compliance aimed at earning salvation", "Sanctification is for pastors; legalism is for laypeople", "Legalism is simply a stricter form of sanctification"],
    correctIndex: 1,
    explanation: "Sanctification is the Holy Spirit's ongoing work of transformation in a person who has already been accepted by grace. Legalism reverses the order, making behavior the condition for acceptance rather than the fruit of it.",
  },
  {
    id: "w4i-22-2-5",
    assessmentId: "w4a-22-2",
    question: "A church member criticizes another member for eating certain foods, claiming it proves the second member is not truly committed to God. Based on the principles in this lesson, what is problematic about this judgment?",
    options: ["Nothing — dietary standards determine one's standing with God", "It uses a behavioral standard as a measure of salvation rather than recognizing it as a fruit of grace, and it judges another believer's heart based on external observation", "The first member is simply being honest and helpful", "Dietary standards are completely irrelevant and should never be discussed"],
    correctIndex: 1,
    explanation: "Using behavioral standards to judge another person's relationship with God reverses the grace-behavior sequence and violates the corrective boundary: standards should express love, not become tools of judgment.",
  },

  // ── Lesson 3 Assessment Items ──────────────────────────────────
  {
    id: "w4i-22-3-1",
    assessmentId: "w4a-22-3",
    question: "What is the scope of Paul's instruction in 1 Corinthians 10:31 — 'whatever you do, do all to the glory of God'?",
    options: ["It applies only to church activities", "It encompasses every dimension of daily life, including eating, drinking, and ordinary decisions", "It applies only to morally significant decisions", "It is a suggestion for advanced Christians, not a general principle"],
    correctIndex: 1,
    explanation: "The word 'whatever' makes the scope total. Paul does not divide life into sacred and secular — every daily activity, including eating and drinking, is an occasion for glorifying God.",
  },
  {
    id: "w4i-22-3-2",
    assessmentId: "w4a-22-3",
    question: "In 1 Peter 3:3-4, what does Peter contrast with outward adornment?",
    options: ["Wealth and possessions", "The hidden person of the heart — a gentle and quiet spirit", "Church attendance and committee service", "Academic achievement and professional success"],
    correctIndex: 1,
    explanation: "Peter redirects attention from outward display to inner character — 'the hidden person of the heart, with the incorruptible beauty of a gentle and quiet spirit, which is very precious in the sight of God.'",
  },
  {
    id: "w4i-22-3-3",
    assessmentId: "w4a-22-3",
    question: "How does 3 John 1:2 connect physical health to spiritual life?",
    options: ["It says physical health is irrelevant to faith", "It prays for health and prosperity that matches the prosperity of the soul, linking body and spirit", "It says spiritual people will never get sick", "It teaches that only spiritual health matters"],
    correctIndex: 1,
    explanation: "John prays that the believer's physical health would match their spiritual health, demonstrating an integrated view of the person — body and soul are interconnected, not independent.",
  },
  {
    id: "w4i-22-3-4",
    assessmentId: "w4a-22-3",
    question: "According to Adventist teaching, why do health principles like dietary care and temperance matter spiritually?",
    options: ["They are cultural preferences with no spiritual significance", "The body is the temple of the Holy Spirit, so physical stewardship is an act of worship and gratitude", "They earn favor with God and guarantee salvation", "They are required only for church leaders and missionaries"],
    correctIndex: 1,
    explanation: "Adventist health principles flow from the conviction that the body is the Spirit's temple (1 Corinthians 6:19-20). Caring for the body is an expression of worship and stewardship, not a salvation requirement.",
  },
  {
    id: "w4i-22-3-5",
    assessmentId: "w4a-22-3",
    question: "A teenager asks, 'Why does God care what I eat or what music I listen to? Isn't that my personal choice?' Based on the principles in this lesson, what is the most helpful response?",
    options: ["God does not actually care — those are purely personal preferences", "Because you belong to God and your body is the Spirit's dwelling place, even ordinary choices like food and entertainment are opportunities to honor Him — not through rigid rules, but through thoughtful stewardship", "You must follow every church rule exactly or face spiritual consequences", "Only what you do on Sabbath matters to God"],
    correctIndex: 1,
    explanation: "1 Corinthians 10:31 teaches that all of life — including ordinary daily choices — is an arena for glorifying God. This is not about rigid rules but about recognizing that our entire embodied existence belongs to God.",
  },

  // ── Lesson 4 Assessment Items ──────────────────────────────────
  {
    id: "w4i-22-4-1",
    assessmentId: "w4a-22-4",
    question: "In Galatians 5:1, 13, what two dangers does Paul warn against?",
    options: ["Poverty and wealth", "Legalism (bondage to rules for salvation) and license (using freedom as an excuse for self-indulgence)", "Sabbath-keeping and Sunday worship", "Old Testament obedience and New Testament grace"],
    correctIndex: 1,
    explanation: "Paul holds two dangers in tension: returning to a 'yoke of bondage' (legalism) and using 'liberty as an opportunity for the flesh' (license). Love is the solution to both.",
  },
  {
    id: "w4i-22-4-2",
    assessmentId: "w4a-22-4",
    question: "What does Paul say about human-made religious regulations in Colossians 2:20-23?",
    options: ["They are essential for spiritual growth", "They have an appearance of wisdom but are of no value against the indulgence of the flesh", "They should replace biblical commands", "They are helpful but not required"],
    correctIndex: 1,
    explanation: "Paul says human-made regulations — 'Do not touch, do not taste, do not handle' — look wise in their self-imposed religion but have no actual power to transform the heart or restrain sin.",
  },
  {
    id: "w4i-22-4-3",
    assessmentId: "w4a-22-4",
    question: "In Matthew 23:23-28, what did Jesus criticize the Pharisees for?",
    options: ["For failing to attend synagogue regularly", "For meticulous external compliance while neglecting justice, mercy, and faith — beautiful outside but dead inside", "For being too generous with their tithes", "For refusing to follow any religious traditions"],
    correctIndex: 1,
    explanation: "Jesus rebuked the Pharisees as 'whitewashed tombs' — they maintained impeccable external religious performance while neglecting the weightier matters of justice, mercy, and faith.",
  },
  {
    id: "w4i-22-4-4",
    assessmentId: "w4a-22-4",
    question: "According to Galatians 5:22-23, what is the true evidence of sanctified living?",
    options: ["Perfect attendance at church services", "The fruit of the Spirit: love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control", "Strict adherence to a denominational dress code", "Financial prosperity and social influence"],
    correctIndex: 1,
    explanation: "Paul identifies the fruit of the Spirit — love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control — as the genuine evidence of the Spirit's transforming work, not external conformity alone.",
  },
  {
    id: "w4i-22-4-5",
    assessmentId: "w4a-22-4",
    question: "A church develops an unofficial list of lifestyle expectations — specific clothing brands, music genres, and leisure activities — and uses it to evaluate members' spirituality. Based on Colossians 2:20-23 and the principles in this lesson, what is the risk?",
    options: ["No risk — detailed lifestyle rules ensure holiness", "The risk is elevating human traditions to the level of divine commands and using external compliance as a substitute for genuine heart transformation", "The list should be made official and enforced more strictly", "Members who disagree should be asked to leave"],
    correctIndex: 1,
    explanation: "Paul warns that human-made regulations have 'an appearance of wisdom' but no real power to change hearts. When cultural preferences are treated as divine requirements, the community risks the very Pharisaism Jesus condemned.",
  },
];
