export const belief16Lessons = [
  {
    id: "w3l-16-1",
    moduleId: "bmod-016",
    title: "Biblical Foundations: At the Lord's Table",
    description: "Exploring the institution, meaning, and practice of the Lord's Supper as recorded in the New Testament — from the upper room to the apostolic church.",
    lessonOrder: 1,
    anchorText: "1 Corinthians 11:23-30; Matthew 26:17-30; John 13:1-17",
    anchorBookId: 46,
    anchorChapter: 11,
    anchorVerseStart: 23,
    anchorVerseEnd: 30,
    estimatedMinutes: 35,
  },
  {
    id: "w3l-16-2",
    moduleId: "bmod-016",
    title: "Doctrinal Formulation: Remembrance, Not Repetition",
    description: "Understanding the Adventist view of communion as a memorial of Christ's once-for-all sacrifice — affirming real spiritual presence while rejecting transubstantiation and repeated sacrifice.",
    lessonOrder: 2,
    anchorText: "1 Corinthians 10:16-17; John 6:48-63; Revelation 3:20",
    anchorBookId: 46,
    anchorChapter: 10,
    anchorVerseStart: 16,
    anchorVerseEnd: 17,
    estimatedMinutes: 30,
  },
  {
    id: "w3l-16-3",
    moduleId: "bmod-016",
    title: "Practical Implications: Preparing for the Table",
    description: "Examining the call to self-examination, reconciliation, and reverent participation that Scripture attaches to the communion service — individually and as a gathered body.",
    lessonOrder: 3,
    anchorText: "1 Corinthians 11:27-29; Matthew 5:23-24; 2 Corinthians 13:5",
    anchorBookId: 46,
    anchorChapter: 11,
    anchorVerseStart: 27,
    anchorVerseEnd: 29,
    estimatedMinutes: 30,
  },
  {
    id: "w3l-16-4",
    moduleId: "bmod-016",
    title: "Misunderstandings & Challenges",
    description: "Addressing common misconceptions about the Lord's Supper — from the nature of the elements to whether communion conveys saving grace or repeats Christ's sacrifice.",
    lessonOrder: 4,
    anchorText: "Hebrews 9:25-28; John 6:53-58; 1 Corinthians 11:17-22",
    anchorBookId: 58,
    anchorChapter: 9,
    anchorVerseStart: 25,
    anchorVerseEnd: 28,
    estimatedMinutes: 30,
  },
];

export const belief16Sections = [
  // ── Lesson 1: Biblical Foundations ──────────────────────────────
  {
    id: "w3s-16-1-1",
    lessonId: "w3l-16-1",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"For I received from the Lord what I also delivered to you, that the Lord Jesus on the same night in which He was betrayed took bread; and when He had given thanks, He broke it and said, 'Take, eat; this is My body which is broken for you; do this in remembrance of Me.' In the same manner He also took the cup after supper, saying, 'This cup is the new covenant in My blood. This do, as often as you drink it, in remembrance of Me.' For as often as you eat this bread and drink this cup, you proclaim the Lord's death till He comes.\" — 1 Corinthians 11:23-26 (NKJV)\n\n\"And as they were eating, Jesus took bread, blessed and broke it, and gave it to the disciples and said, 'Take, eat; this is My body.' Then He took the cup, and gave thanks, and gave it to them, saying, 'Drink from it, all of you. For this is My blood of the new covenant, which is shed for many for the remission of sins.'\" — Matthew 26:26-28 (NKJV)\n\n\"Jesus, knowing that the Father had given all things into His hands, and that He had come from God and was going to God, rose from supper and laid aside His garments, took a towel and girded Himself. After that, He poured water into a basin and began to wash the disciples' feet.\" — John 13:3-5 (NKJV)",
    sortOrder: 1,
  },
  {
    id: "w3s-16-1-2",
    lessonId: "w3l-16-1",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "The Lord's Supper was not invented by the early church. Paul is emphatic: \"I received from the Lord what I also delivered to you.\" The tradition traces directly to Jesus Himself, on the night of His betrayal, in the context of the Passover meal. This setting matters enormously. The Passover commemorated Israel's deliverance from Egypt — the lamb's blood on the doorpost, the angel of death passing over, the exodus into freedom. By taking the bread and cup of that ancient feast and investing them with new meaning, Jesus declared Himself the fulfillment of everything the Passover foreshadowed. He is the Lamb. His blood establishes a new covenant.\n\nThe words \"this is My body\" and \"this is My blood\" are spoken within a culture steeped in symbolic language. Jesus was physically present at the table when He said them; no one present could have imagined that the bread had become His literal flesh. The language is covenantal and representative, just as the Passover lamb was called \"the Lord's Passover\" though it was, plainly, a lamb. What Jesus offers is not a piece of Himself but a participation in the reality His death accomplishes — the forgiveness of sins, the sealing of a new covenant, and the promise of His return.\n\nPaul adds a dimension the Gospels only imply: \"you proclaim the Lord's death till He comes.\" The Lord's Supper is simultaneously backward-looking (remembering the cross), inward-looking (examining oneself), and forward-looking (anticipating the second coming). It is an acted sermon — every time the church gathers at the table, it declares to itself and to the watching world that Christ died, that the death was sufficient, and that the story is not over.\n\nJohn 13 introduces the foot-washing that precedes the supper. Jesus, fully aware of His divine authority, stooped to the task of a household servant. Peter's resistance and Jesus' insistence — \"If I do not wash you, you have no part with Me\" — reveal that the ordinance is not optional sentiment. It embodies the humility, mutual service, and cleansing that must characterize any community that gathers at Christ's table. The foot-washing and the supper together form a unified ordinance: service precedes communion, humility precedes remembrance.",
    sortOrder: 2,
  },
  {
    id: "w3s-16-1-3",
    lessonId: "w3l-16-1",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "Seventh-day Adventists observe the Lord's Supper as a church ordinance — a sacred practice instituted by Christ Himself for the gathered body of believers. Several distinctive features shape the Adventist understanding:\n\n**A memorial, not a sacrifice.** The bread and grape juice represent Christ's body and blood; they do not become them. Jesus offered Himself \"once for all\" (Hebrews 10:10). The communion service remembers that completed sacrifice; it does not repeat, extend, or re-present it. This conviction stands at the heart of Adventist sacramental theology and distinguishes it from traditions that teach transubstantiation or the sacrificial nature of the Mass.\n\n**The ordinance of foot-washing.** Adventists practice foot-washing (sometimes called the ordinance of humility) as an integral part of the communion service, following Christ's explicit command and example in John 13. It is not a cultural relic but a living symbol of ongoing cleansing, mutual service, and the leveling of all social distinctions before the cross.\n\n**Open communion.** The Adventist communion table is open to all baptized Christians who profess faith in Christ and desire to participate. It is not restricted to church members in good standing. This openness reflects the conviction that the table belongs to the Lord, not to any human institution.\n\n**A corporate ordinance, not a private devotion.** Communion is practiced by the gathered church, not by individuals in isolation. The Lord's Supper is a church ordinance — it belongs to the community of faith assembled together. Private communion undermines the communal witness that Paul describes: \"For as often as you eat this bread and drink this cup, you proclaim the Lord's death till He comes.\" The proclamation is public and collective.\n\n**Corrective boundary:** The Lord's Supper is not a means of earning grace, nor is it a magical ritual that confers spiritual benefit apart from faith. It is a means of grace only in the sense that Christ meets the believing community at the table — but the grace flows from Christ, not from the elements themselves.",
    sortOrder: 3,
  },
  {
    id: "w3s-16-1-4",
    lessonId: "w3l-16-1",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Begin living out the truths embedded in the Lord's Supper this week:\n\n1. **Articulate the meaning of communion.** Practice explaining the Lord's Supper to someone unfamiliar with it — a friend, a family member, or a new believer. Use simple, Scripture-rooted language: \"Jesus gave us bread and juice to remember His death for us and to look forward to His return. The church gathers to do this together.\"\n\n2. **Serve someone in the spirit of foot-washing.** Identify one person in your church or community who could use practical, humble service this week — a meal delivered, an errand run, a burden shared. Do it quietly, remembering that Jesus washed the feet of the one who would betray Him. Let the act reshape your posture toward others before the next communion service.\n\n3. **Reflect on 1 Corinthians 11:26 each evening.** Before sleep, read the verse aloud: \"You proclaim the Lord's death till He comes.\" Ask yourself: Did my life today proclaim anything about the cross? Record one way you saw God's sacrificial love at work — in your actions or in someone else's.",
    sortOrder: 4,
  },
  {
    id: "w3s-16-1-5",
    lessonId: "w3l-16-1",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Jesus instituted the Lord's Supper on the night He was betrayed — a moment of profound vulnerability. How does knowing the emotional context of that evening shape the way you approach the communion table?\n\n2. Peter initially refused to let Jesus wash his feet. Have you ever resisted an act of humble service — either receiving it or offering it? What might that resistance reveal about your understanding of grace?\n\n3. Paul says that every time we eat the bread and drink the cup, we \"proclaim the Lord's death till He comes.\" What does it mean to you that communion is not only a memory but also a promise?",
    sortOrder: 5,
  },
  {
    id: "w3s-16-1-6",
    lessonId: "w3l-16-1",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },

  // ── Lesson 2: Doctrinal Formulation ────────────────────────────
  {
    id: "w3s-16-2-1",
    lessonId: "w3l-16-2",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"The cup of blessing which we bless, is it not the communion of the blood of Christ? The bread which we break, is it not the communion of the body of Christ? For we, though many, are one bread and one body; for we all partake of that one bread.\" — 1 Corinthians 10:16-17 (NKJV)\n\n\"I am the bread of life… Most assuredly, I say to you, unless you eat the flesh of the Son of Man and drink His blood, you have no life in you… It is the Spirit who gives life; the flesh profits nothing. The words that I speak to you are spirit, and they are life.\" — John 6:48, 53, 63 (NKJV)\n\n\"Behold, I stand at the door and knock. If anyone hears My voice and opens the door, I will come in to him and dine with him, and he with Me.\" — Revelation 3:20 (NKJV)",
    sortOrder: 1,
  },
  {
    id: "w3s-16-2-2",
    lessonId: "w3l-16-2",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Paul's language in 1 Corinthians 10:16-17 introduces the word koinonia — communion, fellowship, participation. The cup and the bread are not empty symbols. They are a genuine participation in the body and blood of Christ — not because the elements change substance, but because by faith the believer enters into the reality they represent. The distinction is vital: spiritual reality is communicated through physical symbols, but the symbols are not the reality itself. A wedding ring is not a marriage, yet to throw it away would be to despise what it represents.\n\nPaul immediately draws a corporate conclusion: \"we, though many, are one bread and one body.\" Communion is not a private devotional exercise. It is an act of the assembled church that makes visible the unity believers share in Christ. When a congregation eats from the same loaf and drinks from the same cup, it declares that its members — regardless of background, status, or personality — belong to one body. This is why Paul is so disturbed by the divisions at Corinth: to eat the Lord's Supper in a divided, self-serving manner contradicts the very thing the supper proclaims.\n\nJohn 6 is often cited in debates about the nature of the Lord's Supper, but Jesus Himself provides the interpretive key in verse 63: \"It is the Spirit who gives life; the flesh profits nothing.\" His language about eating His flesh and drinking His blood is spiritual, not material. He is not prescribing cannibalism or describing a chemical change in bread and wine. He is describing the intimate, life-giving union between Himself and the believer — a union sustained by faith, mediated by the Spirit, and symbolized at the table.\n\nRevelation 3:20 rounds out the picture with an image of astonishing intimacy. Christ stands at the door and knocks. He does not force entry. He waits for a response. And when the door is opened, He comes in to dine — the same verb used for a full, unhurried meal shared between friends. Communion is not a transaction; it is a relationship. Christ is genuinely present at the table, not in the bread, but with His people, by His Spirit, through faith.",
    sortOrder: 2,
  },
  {
    id: "w3s-16-2-3",
    lessonId: "w3l-16-2",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "The Adventist doctrine of the Lord's Supper navigates carefully between two extremes: reducing communion to a bare memory with no spiritual power, and elevating the elements into objects of worship.\n\n**Real spiritual presence, not material transformation.** Adventists affirm that Christ is genuinely present at the communion table — but His presence is mediated by the Holy Spirit and received by faith, not contained in the bread and juice. The elements remain bread and juice. They do not undergo transubstantiation (a change of substance) or consubstantiation (the coexistence of Christ's body with the elements). Jesus' own clarification in John 6:63 — \"the flesh profits nothing\" — guards against materializing what is a spiritual reality.\n\n**Remembrance with power.** The command \"do this in remembrance of Me\" does not reduce communion to nostalgia. Biblical remembrance (anamnesis) is active and participatory. When Israel \"remembered\" the Exodus at Passover, each generation entered into the story as though it were their own. Similarly, at the Lord's table believers do not merely recall a historical event; they enter into its continuing significance. The cross is past, but its power is present.\n\n**Unity made visible.** Paul's insistence that \"we, though many, are one bread and one body\" gives communion an ecclesiological dimension. The Lord's Supper is a church ordinance practiced in the gathered assembly. It makes the invisible reality of the body of Christ visible in a local congregation. This is why communion belongs to the worshiping community, not to isolated individuals — the ordinance loses its meaning when divorced from the gathered church.\n\n**Forward-looking hope.** The phrase \"till He comes\" anchors the Lord's Supper in Adventist eschatology. Every communion service is a rehearsal of the marriage supper of the Lamb (Revelation 19:9). Believers eat in anticipation, not merely in retrospect.\n\n**Corrective boundary:** The Lord's Supper does not forgive sins; Christ does. The elements are not channels of automatic grace. Eating and drinking without faith and self-examination offers no spiritual benefit and may, as Paul warns, bring judgment rather than blessing (1 Corinthians 11:29).",
    sortOrder: 3,
  },
  {
    id: "w3s-16-2-4",
    lessonId: "w3l-16-2",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Deepen your understanding of what happens — and what does not happen — at the Lord's table:\n\n1. **Articulate the Adventist position clearly.** Write a one-paragraph explanation of why Adventists believe Christ is present at communion but not in the bread and juice. Share it with a study partner or small group and invite questions. Use John 6:63 and 1 Corinthians 10:16 as your anchoring texts.\n\n2. **Practice koinonia beyond the table.** The word Paul uses for communion also means fellowship and sharing. This week, identify one practical way to deepen fellowship within your local church body — perhaps by reaching out to someone you do not know well, sharing a meal, or offering encouragement to a member who has been absent. Let the communion table extend into daily community life.\n\n3. **Meditate on Revelation 3:20.** Each morning this week, spend two minutes in silence after reading the verse. Picture Christ at the door. Open it. What does it mean that He wants to dine with you — not lecture you, not inspect you, but share a meal?",
    sortOrder: 4,
  },
  {
    id: "w3s-16-2-5",
    lessonId: "w3l-16-2",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Paul says the bread and cup are a \"communion\" (koinonia) of the body and blood of Christ. How does your personal experience of the Lord's Supper reflect genuine participation in Christ, rather than mere ritual?\n\n2. Jesus said, \"The flesh profits nothing. The words that I speak to you are spirit, and they are life\" (John 6:63). How does this statement shape the way you understand His presence at the communion table?\n\n3. Revelation 3:20 pictures Christ dining with those who open the door. What barriers — doubt, distraction, guilt — most often keep you from experiencing that intimate fellowship with Him?",
    sortOrder: 5,
  },
  {
    id: "w3s-16-2-6",
    lessonId: "w3l-16-2",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },

  // ── Lesson 3: Practical Implications ───────────────────────────
  {
    id: "w3s-16-3-1",
    lessonId: "w3l-16-3",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"Therefore whoever eats this bread or drinks this cup of the Lord in an unworthy manner will be guilty of the body and blood of the Lord. But let a man examine himself, and so let him eat of the bread and drink of the cup. For he who eats and drinks in an unworthy manner eats and drinks judgment to himself, not discerning the Lord's body.\" — 1 Corinthians 11:27-29 (NKJV)\n\n\"Therefore if you bring your gift to the altar, and there remember that your brother has something against you, leave your gift there before the altar, and go your way. First be reconciled to your brother, and then come and offer your gift.\" — Matthew 5:23-24 (NKJV)\n\n\"Examine yourselves as to whether you are in the faith. Test yourselves. Do you not know yourselves, that Jesus Christ is in you? — unless indeed you are disqualified.\" — 2 Corinthians 13:5 (NKJV)",
    sortOrder: 1,
  },
  {
    id: "w3s-16-3-2",
    lessonId: "w3l-16-3",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Paul's warning in 1 Corinthians 11:27-29 is one of the most sobering passages in the New Testament. To eat and drink \"in an unworthy manner\" is not a statement about the worthiness of the person — no one comes to the table deserving of what Christ offers. It is a statement about the manner of participation. In Corinth, the abuse was concrete: wealthy members were gorging themselves while poorer members went hungry (11:21). They were turning the Lord's Supper into a display of social hierarchy, which contradicted the very death it commemorated — a death endured for all, without partiality.\n\n\"Let a man examine himself\" is Paul's remedy. The Greek word dokimazo means to test, to assay as a metallurgist tests metal for purity. Self-examination before communion is not an exercise in guilt but a moment of honest inventory: Am I harboring resentment? Am I living in unconfessed sin? Am I approaching the table with reverence for what it represents? The purpose of the examination is not to disqualify participants but to prepare them — to ensure that they eat and drink \"discerning the Lord's body.\"\n\nJesus' instruction in Matthew 5:23-24 extends the principle beyond the individual. If you remember at the altar that a brother has something against you, leave your gift and be reconciled first. The priority is unmistakable: right relationships precede right worship. Communion at the table of the Lord is hollow if accompanied by broken relationships within the body of the Lord. This is why the Adventist practice of foot-washing before the supper serves as a natural moment for reconciliation.\n\nPaul's broader call in 2 Corinthians 13:5 — \"examine yourselves as to whether you are in the faith\" — widens the lens. Self-examination is not limited to the moments before communion; it is a habit of the mature Christian life. But the communion table provides a regular, sacred occasion for this discipline, preventing the kind of spiritual autopilot that turns worship into routine.",
    sortOrder: 2,
  },
  {
    id: "w3s-16-3-3",
    lessonId: "w3l-16-3",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "The Adventist practice of preparing for communion reflects a careful reading of Paul's instructions and Jesus' example:\n\n**The ordinance of humility as preparation.** The foot-washing service is not incidental to communion — it is integral. It provides a structured moment for self-examination, reconciliation, and the reorientation of the heart before approaching the bread and cup. In washing one another's feet, members physically enact the humility and mutual service that the Lord's Supper symbolizes. Social distinctions dissolve; the CEO washes the feet of the custodian, and vice versa.\n\n**Self-examination, not self-exclusion.** Paul says \"let a man examine himself, and so let him eat\" — examine and then eat, not examine and then abstain. The purpose of self-examination is participation, not avoidance. Adventists encourage members to come to the table humbly, not to stay away out of excessive scrupulosity. The table is for sinners who know they need a Savior, not for saints who believe they have arrived.\n\n**Reconciliation as a prerequisite.** Jesus' words in Matthew 5:23-24 give the communion preparation a relational dimension. Adventist churches often encourage members to use the foot-washing time to seek reconciliation with anyone from whom they are estranged. The Lord's Supper is a church ordinance — it belongs to the gathered community — and a divided community cannot honestly share the bread that symbolizes unity.\n\n**Reverence without superstition.** Paul's warning about eating and drinking \"judgment\" is serious, but it should not be interpreted as magical. The danger is not that the bread will poison the unworthy but that treating the supper with contempt reveals a hardened heart that is already under judgment. Reverence is appropriate; fear of the elements themselves is not.\n\n**Corrective boundary:** Self-examination is not a tool for spiritual gatekeeping by church leaders. No human authority stands between the believer and the Lord's table. The examination Paul prescribes is personal, Spirit-led, and oriented toward restoration — never toward exclusion or public shaming.",
    sortOrder: 3,
  },
  {
    id: "w3s-16-3-4",
    lessonId: "w3l-16-3",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Prepare your heart for the Lord's table — not just before the next communion service, but as a way of life:\n\n1. **Practice daily self-examination.** Each evening this week, spend five minutes in quiet reflection using 2 Corinthians 13:5 as a guide. Ask: Am I living in the faith I profess? Where did I act out of alignment with the gospel today? Confess what surfaces and receive God's forgiveness before sleep.\n\n2. **Pursue reconciliation.** Is there a relationship in your church or family that is strained? Before the next communion service, take one concrete step toward reconciliation — a phone call, a written note, a face-to-face conversation. Follow Jesus' instruction: first be reconciled, then come to the table.\n\n3. **Explain to someone why preparation matters.** Articulate to a friend or fellow member why Adventists practice foot-washing before communion. Use language like: \"We wash feet because Jesus told us to — it's a way of saying we need cleansing, we need each other, and we come to the table as servants, not spectators.\"",
    sortOrder: 4,
  },
  {
    id: "w3s-16-3-5",
    lessonId: "w3l-16-3",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Paul warns against eating and drinking \"in an unworthy manner.\" When you approach the communion table, what does genuine self-examination look like for you — and how do you keep it from becoming either mechanical or paralyzing?\n\n2. Jesus said to be reconciled with your brother before bringing your gift to the altar. Is there a relationship in your life right now that needs attention before you next come to the Lord's table?\n\n3. The foot-washing service levels all social distinctions — age, wealth, position. How has participating in (or observing) this ordinance shaped your understanding of what it means to be part of the body of Christ?",
    sortOrder: 5,
  },
  {
    id: "w3s-16-3-6",
    lessonId: "w3l-16-3",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },

  // ── Lesson 4: Misunderstandings & Challenges ───────────────────
  {
    id: "w3s-16-4-1",
    lessonId: "w3l-16-4",
    sectionType: "anchor",
    title: "Anchor Text",
    content: "Read the following passages carefully before proceeding:\n\n\"Not that He should offer Himself often, as the high priest enters the Most Holy Place every year with blood of another — He then would have had to suffer often since the foundation of the world; but now, once at the end of the ages, He has appeared to put away sin by the sacrifice of Himself. And as it is appointed for men to die once, but after this the judgment, so Christ was offered once to bear the sins of many.\" — Hebrews 9:25-28 (NKJV)\n\n\"Then Jesus said to them, 'Most assuredly, I say to you, unless you eat the flesh of the Son of Man and drink His blood, you have no life in you. Whoever eats My flesh and drinks My blood has eternal life, and I will raise him up at the last day. For My flesh is food indeed, and My blood is drink indeed.'\" — John 6:53-55 (NKJV)\n\n\"Therefore when you come together in one place, it is not to eat the Lord's Supper. For in eating, each one takes his own supper ahead of others; and one is hungry and another is drunk. What! Do you not have houses to eat and drink in? Or do you despise the church of God and shame those who have nothing?\" — 1 Corinthians 11:20-22 (NKJV)",
    sortOrder: 1,
  },
  {
    id: "w3s-16-4-2",
    lessonId: "w3l-16-4",
    sectionType: "explain",
    title: "What Does This Mean?",
    content: "Hebrews 9:25-28 addresses one of the most consequential theological questions surrounding the Lord's Supper: Is Christ's sacrifice repeated in the communion service? The writer's answer is unequivocal: Christ does not offer Himself \"often.\" He appeared \"once at the end of the ages\" to put away sin by the sacrifice of Himself. The word hapax — once, once for all — is the controlling concept. Any theology of the Lord's Supper that treats the service as a re-offering or continuation of Christ's sacrifice contradicts the finished work declared in Hebrews. The cross was complete. Communion remembers what was accomplished; it does not add to it.\n\nJohn 6:53-58 has been the subject of intense debate across Christian history. Jesus' language — \"eat My flesh,\" \"drink My blood\" — shocked His original audience and continues to generate controversy. Some traditions read these verses as a mandate for the literal consumption of Christ's body and blood in the Eucharist. But the context resists that interpretation. In John 6:63, Jesus explicitly states: \"It is the Spirit who gives life; the flesh profits nothing.\" The eating and drinking He describes is the act of believing — receiving Him by faith, depending on Him for life, as surely as the body depends on food. To \"eat\" Christ is to trust Him so completely that His life becomes the sustaining reality of yours.\n\n1 Corinthians 11:17-22 exposes a different kind of misunderstanding — not theological but behavioral. The Corinthians were turning the Lord's Supper into a private dinner party. The wealthy arrived early and ate their fill; the poor arrived late and went hungry. Paul is blunt: \"it is not to eat the Lord's Supper.\" When the service becomes an occasion for social division, selfishness, or disregard for the body, it ceases to be the Lord's Supper at all, regardless of what the participants call it. The name on the event is irrelevant if the character of Christ is absent from the practice.\n\nThese three passages together guard the Lord's Supper from three persistent errors: re-sacrificing Christ (Hebrews 9), materializing the elements (John 6), and privatizing the practice (1 Corinthians 11). Each error distorts the supper's purpose: to remember, to commune, and to unite.",
    sortOrder: 2,
  },
  {
    id: "w3s-16-4-3",
    lessonId: "w3l-16-4",
    sectionType: "integrate",
    title: "SDA Theological Integration",
    content: "Adventist theology addresses several common misunderstandings about the Lord's Supper with clarity and pastoral care:\n\n**The supper does not repeat Christ's sacrifice.** Hebrews 9:25-28 is foundational for the Adventist rejection of any doctrine that treats communion as a re-offering of Christ. The sacrifice of Calvary was singular, sufficient, and unrepeatable. The Lord's Supper is a memorial — it points back to a finished work. To treat it as a continuation of sacrifice undermines the very \"once for all\" character that makes the cross effective.\n\n**The elements do not become Christ's body and blood.** Adventists reject transubstantiation because Scripture does not teach it and because Jesus Himself clarified that His language about eating flesh and drinking blood was spiritual, not material (John 6:63). The bread is bread. The juice is juice. Christ is present — genuinely, powerfully present — but His presence is mediated by the Spirit and received by faith, not contained in the physical elements.\n\n**Communion is not a private or optional practice.** Paul's rebuke of the Corinthians underscores that the Lord's Supper is inherently communal. It is a church ordinance — a practice of the gathered body. Communion celebrated in isolation from the local church loses its essential character as a declaration of unity. Adventists practice communion as a congregational act, typically quarterly, with the entire worshiping body participating together.\n\n**Grace is not automatic.** Eating and drinking does not mechanically dispense grace. Paul warns that those who participate without discernment eat and drink judgment to themselves (1 Corinthians 11:29). The grace of communion flows through faith, repentance, and self-examination — not through the physical act of consuming the elements.\n\n**Corrective boundary:** While Adventists use unfermented grape juice (reflecting Christ's sinless blood and the new covenant's purity), the emphasis must remain on the reality the elements represent, not on the elements themselves. Debates about the type of bread or juice must never overshadow the person and work of Christ that the supper proclaims.",
    sortOrder: 3,
  },
  {
    id: "w3s-16-4-4",
    lessonId: "w3l-16-4",
    sectionType: "practice",
    title: "Daily Practice",
    content: "Guard your understanding and practice of the Lord's Supper against common distortions:\n\n1. **Articulate the 'once for all' principle.** This week, read Hebrews 9:25-28 three times. Then write a brief paragraph in your own words explaining why communion is a memorial and not a repeated sacrifice. Share it with a study partner or small group and invite their questions.\n\n2. **Examine your church's communion practice.** Attend the next communion service with fresh eyes. Before, during, and after, notice: Is the atmosphere reverent? Are all members welcomed equally? Does the service reflect the unity Paul called for? If you notice an area for growth, bring it respectfully to a church leader as a constructive conversation, not a complaint.\n\n3. **Extend the table into your week.** The Corinthians' failure was treating communion as self-serving rather than other-serving. This week, share a meal with someone in your church who is often overlooked — a newcomer, a single parent, an elderly member. Let the spirit of the Lord's table shape your hospitality.",
    sortOrder: 4,
  },
  {
    id: "w3s-16-4-5",
    lessonId: "w3l-16-4",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Hebrews insists that Christ was offered \"once\" to bear the sins of many. How does the finality of the cross affect the way you approach the communion table — does it increase your gratitude, your confidence, or both?\n\n2. Paul rebuked the Corinthians for turning the Lord's Supper into an occasion for division and selfishness. In what ways might modern communion practices — in your church or in broader Christianity — risk the same error?\n\n3. Jesus said, \"The flesh profits nothing. The words that I speak to you are spirit, and they are life\" (John 6:63). How does this statement help you navigate disagreements with Christians who hold different views about the nature of the communion elements?",
    sortOrder: 5,
  },
  {
    id: "w3s-16-4-6",
    lessonId: "w3l-16-4",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },
];

export const belief16Assessments = [
  {
    id: "w3a-16-1",
    lessonId: "w3l-16-1",
    title: "Biblical Foundations Assessment",
    passingScore: 80,
  },
  {
    id: "w3a-16-2",
    lessonId: "w3l-16-2",
    title: "Doctrinal Formulation Assessment",
    passingScore: 80,
  },
  {
    id: "w3a-16-3",
    lessonId: "w3l-16-3",
    title: "Practical Implications Assessment",
    passingScore: 80,
  },
  {
    id: "w3a-16-4",
    lessonId: "w3l-16-4",
    title: "Misunderstandings & Challenges Assessment",
    passingScore: 80,
  },
];

export const belief16Items = [
  // ── Lesson 1 Assessment Items ──────────────────────────────────
  {
    id: "w3i-16-1-1",
    assessmentId: "w3a-16-1",
    question: "According to 1 Corinthians 11:23-25, what two elements did Jesus use to institute the Lord's Supper?",
    options: ["Water and oil", "Bread and the cup (wine/juice)", "Lamb and unleavened bread", "Fish and bread"],
    correctIndex: 1,
    explanation: "Paul records that Jesus took bread and the cup, investing them with covenantal meaning: the bread representing His body broken for believers, and the cup representing the new covenant in His blood.",
  },
  {
    id: "w3i-16-1-2",
    assessmentId: "w3a-16-1",
    question: "What does Paul say believers 'proclaim' every time they eat the bread and drink the cup (1 Corinthians 11:26)?",
    options: ["Their own righteousness before God", "The Lord's death till He comes", "The establishment of an earthly kingdom", "Their membership in a particular denomination"],
    correctIndex: 1,
    explanation: "Paul states that the Lord's Supper is a proclamation — 'you proclaim the Lord's death till He comes.' It is simultaneously a memorial of the cross and an anticipation of the second coming.",
  },
  {
    id: "w3i-16-1-3",
    assessmentId: "w3a-16-1",
    question: "In John 13, what act did Jesus perform before the Last Supper, and what did He command the disciples to do?",
    options: ["He anointed them with oil and told them to heal the sick", "He washed their feet and told them to wash one another's feet", "He baptized them in the Jordan and told them to baptize others", "He laid hands on them and told them to ordain leaders"],
    correctIndex: 1,
    explanation: "Jesus washed the disciples' feet as an act of humble service and explicitly commanded them to follow His example (John 13:14-15). This act of foot-washing precedes and prepares for the communion meal.",
  },
  {
    id: "w3i-16-1-4",
    assessmentId: "w3a-16-1",
    question: "Why is it significant that Jesus instituted the Lord's Supper during the Passover meal?",
    options: ["It was simply convenient timing with no deeper meaning", "It connects His sacrifice to the entire Exodus narrative — He is the Lamb whose blood delivers God's people from death", "The Passover was the only meal at which unleavened bread was available", "He wanted to abolish the Passover and replace it with a Christian holiday"],
    correctIndex: 1,
    explanation: "The Passover commemorated Israel's deliverance through the blood of a lamb. By instituting the Lord's Supper in this context, Jesus identified Himself as the ultimate Passover Lamb whose sacrifice establishes a new covenant and delivers believers from the power of sin and death.",
  },
  {
    id: "w3i-16-1-5",
    assessmentId: "w3a-16-1",
    question: "A church member suggests that communion can be practiced privately at home as a personal devotion, separate from the church body. How does the biblical teaching respond?",
    options: ["It fully supports private communion as equally valid", "Paul's language in 1 Corinthians 11 frames the Lord's Supper as a gathered church practice — 'when you come together' — making it a corporate ordinance, not an individual exercise", "The Bible is silent on the matter and leaves it to personal preference", "Private communion is actually preferred because it avoids the divisions Paul warned about"],
    correctIndex: 1,
    explanation: "Paul repeatedly addresses the Lord's Supper as something that happens 'when you come together' (1 Corinthians 11:17, 18, 20, 33). The supper is a church ordinance — it belongs to the gathered community of faith. Its proclamation of unity, mutual service, and shared hope requires the assembled body.",
  },

  // ── Lesson 2 Assessment Items ──────────────────────────────────
  {
    id: "w3i-16-2-1",
    assessmentId: "w3a-16-2",
    question: "What does the Greek word koinonia, used in 1 Corinthians 10:16, communicate about the Lord's Supper?",
    options: ["That the bread literally becomes Christ's body", "That communion involves genuine participation and fellowship in the body and blood of Christ", "That only ordained ministers may handle the elements", "That the supper is a purely symbolic act with no spiritual reality"],
    correctIndex: 1,
    explanation: "Koinonia means communion, fellowship, or participation. Paul uses it to affirm that the Lord's Supper is a genuine spiritual participation in Christ — not a bare memorial, but not a material transformation of the elements either.",
  },
  {
    id: "w3i-16-2-2",
    assessmentId: "w3a-16-2",
    question: "In John 6:63, how does Jesus clarify His earlier statements about eating His flesh and drinking His blood?",
    options: ["He confirms that His words should be taken literally and physically", "He says, 'It is the Spirit who gives life; the flesh profits nothing,' indicating His language is spiritual, not material", "He withdraws the statements entirely as a misunderstanding", "He explains that only priests can perform this act"],
    correctIndex: 1,
    explanation: "Jesus provides His own interpretive key: 'It is the Spirit who gives life; the flesh profits nothing.' His language about eating and drinking describes the intimate, life-giving union between Himself and the believer — sustained by faith and mediated by the Spirit, not achieved through physical consumption.",
  },
  {
    id: "w3i-16-2-3",
    assessmentId: "w3a-16-2",
    question: "According to 1 Corinthians 10:17, what corporate reality does the Lord's Supper make visible?",
    options: ["The hierarchy of church leadership", "That believers, though many, are one body because they all partake of one bread", "That each individual has a private relationship with God unrelated to others", "That the church is divided into separate groups by spiritual gifts"],
    correctIndex: 1,
    explanation: "Paul draws a direct line from the shared bread to the unity of the body: 'we, though many, are one bread and one body; for we all partake of that one bread.' Communion makes the invisible reality of the body of Christ visible in the gathered congregation.",
  },
  {
    id: "w3i-16-2-4",
    assessmentId: "w3a-16-2",
    question: "What is the Adventist understanding of Christ's presence at the communion table?",
    options: ["Christ is physically present inside the bread and juice after consecration", "Christ is genuinely present by His Spirit and received by faith, but the elements remain bread and juice", "Christ is entirely absent and the supper is only a human tradition", "Christ's presence depends on the spiritual worthiness of the officiating pastor"],
    correctIndex: 1,
    explanation: "Adventists affirm a real spiritual presence — Christ genuinely meets His people at the table through the Holy Spirit. However, the elements do not undergo transubstantiation or any material change. The bread remains bread; the juice remains juice. Christ's presence is received by faith.",
  },
  {
    id: "w3i-16-2-5",
    assessmentId: "w3a-16-2",
    question: "A fellow believer says, 'Communion is just a memorial — nothing actually happens spiritually.' How would a balanced Adventist response correct this view?",
    options: ["By agreeing that communion is merely a historical reenactment", "By explaining that biblical remembrance (anamnesis) is active and participatory — believers enter into the continuing significance of Christ's death, and Christ is genuinely present by His Spirit", "By insisting that the bread physically becomes Christ's body", "By suggesting that the spiritual dimension is uncertain and unknowable"],
    correctIndex: 1,
    explanation: "The Adventist position avoids both extremes. Communion is not bare memory — biblical remembrance is participatory, and Christ is genuinely present by the Spirit. But neither is it a material transformation of the elements. The Lord's Supper is a powerful, Spirit-mediated encounter with the living Christ.",
  },

  // ── Lesson 3 Assessment Items ──────────────────────────────────
  {
    id: "w3i-16-3-1",
    assessmentId: "w3a-16-3",
    question: "What does Paul mean by eating and drinking 'in an unworthy manner' in 1 Corinthians 11:27?",
    options: ["That only sinless people may take communion", "That the manner of participation — treating the supper with irreverence, selfishness, or disregard for the body — is the issue, not the personal worthiness of the participant", "That believers must fast for 24 hours before communion", "That only baptized Adventists may participate"],
    correctIndex: 1,
    explanation: "Paul addresses the manner, not the merit, of participation. The Corinthians were eating selfishly and divisively, contradicting the unity the supper represents. No one is personally 'worthy' — but everyone is called to participate with reverence, self-examination, and regard for the body of Christ.",
  },
  {
    id: "w3i-16-3-2",
    assessmentId: "w3a-16-3",
    question: "According to 1 Corinthians 11:28, what should a believer do before eating the bread and drinking the cup?",
    options: ["Recite a specific prayer formula prescribed by church tradition", "Examine himself or herself", "Obtain permission from a church elder", "Memorize the entire communion liturgy"],
    correctIndex: 1,
    explanation: "Paul's instruction is direct: 'Let a man examine himself, and so let him eat.' The Greek word dokimazo means to test or prove. Self-examination is personal and Spirit-led, not dependent on external authorization.",
  },
  {
    id: "w3i-16-3-3",
    assessmentId: "w3a-16-3",
    question: "In Matthew 5:23-24, what does Jesus say takes priority over bringing a gift to the altar?",
    options: ["Tithing accurately", "Being reconciled with a brother who has something against you", "Offering a larger gift to compensate for the offense", "Waiting until the next worship service"],
    correctIndex: 1,
    explanation: "Jesus is explicit: 'First be reconciled to your brother, and then come and offer your gift.' Right relationships precede right worship. This principle directly applies to communion preparation — unresolved conflict must be addressed before approaching the Lord's table.",
  },
  {
    id: "w3i-16-3-4",
    assessmentId: "w3a-16-3",
    question: "How does the Adventist practice of foot-washing connect to the preparation Paul calls for in 1 Corinthians 11?",
    options: ["It is unrelated — foot-washing is cultural and communion is theological", "It provides a structured, embodied moment for self-examination, reconciliation, and the humility that Paul requires before approaching the bread and cup", "It replaces the need for self-examination entirely", "It is a way for church leaders to evaluate members' worthiness"],
    correctIndex: 1,
    explanation: "Foot-washing serves as a living enactment of the self-examination, humility, and mutual reconciliation Paul calls for. It is not a replacement for inner examination but a physical, communal expression of it — preparing hearts before the bread and cup are shared.",
  },
  {
    id: "w3i-16-3-5",
    assessmentId: "w3a-16-3",
    question: "A new member feels too sinful to participate in communion and plans to abstain. What pastoral guidance best reflects the biblical teaching?",
    options: ["Affirm their decision — only those who feel worthy should participate", "Gently explain that Paul says 'examine yourself, and so let him eat' — the purpose of self-examination is to prepare for participation, not to justify abstaining; the table is for sinners who need a Savior", "Suggest they wait until they have achieved a certain level of spiritual maturity", "Tell them the decision is entirely personal and the Bible offers no guidance"],
    correctIndex: 1,
    explanation: "Paul's instruction is 'examine yourself, and so let him eat' — the examination leads to eating, not to abstaining. The communion table is for those who recognize their need for Christ. Coming with humility and repentance is exactly the disposition the supper was designed for.",
  },

  // ── Lesson 4 Assessment Items ──────────────────────────────────
  {
    id: "w3i-16-4-1",
    assessmentId: "w3a-16-4",
    question: "According to Hebrews 9:25-28, how many times was Christ offered as a sacrifice for sin?",
    options: ["Every time communion is celebrated", "Once — 'once at the end of the ages' to put away sin by the sacrifice of Himself", "Twice — once in the heavenly sanctuary and once on the cross", "Continually, through an ongoing heavenly ministry"],
    correctIndex: 1,
    explanation: "The writer of Hebrews is emphatic: Christ appeared 'once at the end of the ages' to put away sin. The Greek word hapax means once for all. Any view that treats communion as a repetition or continuation of Christ's sacrifice contradicts this foundational declaration.",
  },
  {
    id: "w3i-16-4-2",
    assessmentId: "w3a-16-4",
    question: "What was the specific problem Paul identified in the Corinthian communion practice (1 Corinthians 11:20-22)?",
    options: ["They used the wrong type of bread", "Wealthy members were eating their fill while poor members went hungry, turning the supper into an occasion for social division", "They celebrated communion too frequently", "They did not allow women to participate"],
    correctIndex: 1,
    explanation: "Paul rebuked the Corinthians because their practice reflected social hierarchy rather than Christian unity: 'each one takes his own supper ahead of others; and one is hungry and another is drunk.' This self-serving behavior contradicted the self-giving death the supper was meant to proclaim.",
  },
  {
    id: "w3i-16-4-3",
    assessmentId: "w3a-16-4",
    question: "Why do Adventists reject the doctrine of transubstantiation?",
    options: ["Because Adventists do not value tradition", "Because Jesus clarified in John 6:63 that His words are spiritual, and Hebrews 9 declares His sacrifice was offered once — the elements remain bread and juice, and Christ is present by the Spirit, not in the elements", "Because the doctrine was never taught before the modern era", "Because Adventists believe Christ is entirely absent from the communion service"],
    correctIndex: 1,
    explanation: "Adventists reject transubstantiation on biblical grounds: Jesus said 'the flesh profits nothing' (John 6:63), and Hebrews declares Christ was offered once. The elements do not change substance. Christ is genuinely present — but by the Spirit and through faith, not materially in the bread and juice.",
  },
  {
    id: "w3i-16-4-4",
    assessmentId: "w3a-16-4",
    question: "A friend from another tradition asks, 'If communion doesn't actually become Christ's body, why bother with it at all?' How would you respond based on the lessons studied?",
    options: ["Admit that communion is outdated and unnecessary for modern Christians", "Explain that communion is a powerful, Spirit-mediated encounter where Christ is genuinely present with His people — it proclaims His death, nourishes faith, demonstrates unity, and anticipates His return, all without requiring a material change in the elements", "Agree that without transubstantiation, the supper has little value", "Argue that the physical elements are what make communion meaningful"],
    correctIndex: 1,
    explanation: "The value of communion does not depend on a material transformation. Christ is present by His Spirit. The supper proclaims the gospel, nourishes the faith of participants, makes visible the unity of the body, and points forward to the second coming. Its power is in the Person it represents, not in the physical elements.",
  },
  {
    id: "w3i-16-4-5",
    assessmentId: "w3a-16-4",
    question: "Paul told the Corinthians their gatherings were doing 'more harm than good' because of their communion abuses (1 Corinthians 11:17). What principle does this establish for modern church practice?",
    options: ["That communion should be discontinued to avoid any possibility of abuse", "That the manner in which a church practices communion matters as much as the theology behind it — social division, selfishness, or exclusion at the table contradicts the gospel the supper proclaims", "That only small churches can practice communion correctly", "That communion should be limited to ordained clergy to prevent lay errors"],
    correctIndex: 1,
    explanation: "Paul's rebuke establishes that practice and theology must align. A communion service that perpetuates division, favoritism, or selfishness is not the Lord's Supper, regardless of correct words or elements. The manner of celebration must reflect the self-giving love of the Christ it commemorates.",
  },
];
