export const belief23Lessons = [
  {
    id: "w4l-23-1",
    moduleId: "bmod-023",
    title: "Biblical Foundations: Marriage in God's Design",
    description: "Exploring the origin and purpose of marriage as established by God in Eden, affirmed by Jesus, and illuminated throughout Scripture.",
    lessonOrder: 1,
    anchorText: "Genesis 2:18-25; Ephesians 5:21-33; Matthew 19:3-9",
    anchorBookId: 1,
    anchorChapter: 2,
    anchorVerseStart: 18,
    anchorVerseEnd: 25,
    estimatedMinutes: 35,
  },
  {
    id: "w4l-23-2",
    moduleId: "bmod-023",
    title: "Doctrinal Formulation: Covenant, Not Contract",
    description: "Understanding marriage as a sacred covenant reflecting God's faithful love, and the theological foundations that shape Adventist teaching on the family.",
    lessonOrder: 2,
    anchorText: "Malachi 2:14-16; 2 Corinthians 6:14; Mark 10:6-9",
    anchorBookId: 39,
    anchorChapter: 2,
    anchorVerseStart: 14,
    anchorVerseEnd: 16,
    estimatedMinutes: 30,
  },
  {
    id: "w4l-23-3",
    moduleId: "bmod-023",
    title: "Practical Implications: Building a Godly Home",
    description: "Applying biblical principles to the daily realities of family life, child-rearing, and intergenerational faith formation.",
    lessonOrder: 3,
    anchorText: "Deuteronomy 6:5-9; Ephesians 6:1-4; Proverbs 22:6",
    anchorBookId: 5,
    anchorChapter: 6,
    anchorVerseStart: 5,
    anchorVerseEnd: 9,
    estimatedMinutes: 30,
  },
  {
    id: "w4l-23-4",
    moduleId: "bmod-023",
    title: "Misunderstandings & Challenges",
    description: "Addressing difficult questions about divorce, remarriage, singleness, and the pastoral care needed when families face brokenness.",
    lessonOrder: 4,
    anchorText: "1 Corinthians 7:10-16; Matthew 5:31-32; Malachi 4:5-6",
    anchorBookId: 46,
    anchorChapter: 7,
    anchorVerseStart: 10,
    anchorVerseEnd: 16,
    estimatedMinutes: 30,
  },
];

export const belief23Sections = [
  {
    id: "w4s-23-1-1",
    lessonId: "w4l-23-1",
    sectionType: "anchor",
    title: "Anchor Passages",
    content: "Read the following passages carefully, paying attention to why God created marriage, how it reflects His character, and what Jesus taught about its permanence.\n\n1. **Genesis 2:18-25** — The creation of Eve and the institution of marriage. Notice God's own assessment: \"It is not good that man should be alone.\" Observe the language of unity: \"they shall become one flesh.\"\n2. **Ephesians 5:21-33** — Paul's teaching on marriage as a reflection of Christ and the church. Pay attention to the mutual submission in verse 21 that frames everything that follows.\n3. **Matthew 19:3-9** — Jesus answers the Pharisees' question about divorce by pointing back to creation. Notice how He appeals to God's original design as the standard.\n4. **Genesis 1:27-28** — The creation of humanity as male and female, and the blessing of fruitfulness. Note that both bear God's image together.\n5. **John 2:1-11** — Jesus' first miracle at the wedding in Cana. Consider why Jesus chose a marriage celebration as the setting for His first public sign.",
    sortOrder: 1,
  },
  {
    id: "w4s-23-1-2",
    lessonId: "w4l-23-1",
    sectionType: "explain",
    title: "Marriage as God's Gift",
    content: "Marriage did not originate as a human invention or a cultural convention. It was established by God Himself before sin entered the world. After creating Adam, the Lord declared, \"It is not good that man should be alone; I will make him a helper comparable to him\" (Genesis 2:18). The word translated \"helper\" (ezer) is used elsewhere in Scripture of God Himself coming to the aid of His people (Psalm 33:20; 70:5). It carries no connotation of inferiority; rather, it speaks of essential partnership. God fashioned Eve from Adam's side — not from his head to rule over him, nor from his feet to be trampled, but from near his heart to be loved and cherished. Adam's joyful response — \"This is now bone of my bones and flesh of my flesh\" (Genesis 2:23) — is the Bible's first poem, a song of recognition and delight.\n\nJesus affirmed this creation pattern as the permanent standard for marriage. When the Pharisees tested Him with questions about divorce, He did not begin with Mosaic legislation but with Eden: \"Have you not read that He who made them at the beginning 'made them male and female,' and said, 'For this reason a man shall leave his father and mother and be joined to his wife, and the two shall become one flesh'?\" (Matthew 19:4-5). The \"one flesh\" union is not merely physical; it encompasses emotional intimacy, spiritual companionship, shared purpose, and covenantal commitment. Paul later reveals the deepest dimension of marriage: it is a living parable of Christ's self-giving love for the church (Ephesians 5:31-32). Marriage, at its best, is a window through which the watching world sees something of God's faithful, sacrificial, redeeming love.",
    sortOrder: 2,
  },
  {
    id: "w4s-23-1-3",
    lessonId: "w4l-23-1",
    sectionType: "integrate",
    title: "Adventist Theological Integration",
    content: "Adventists understand marriage within the larger narrative of creation, fall, and restoration. Because marriage was instituted before sin, it belongs to God's original design for human flourishing. The fall distorted relationships — introducing shame, blame, and domination (Genesis 3:16) — but it did not abolish God's ideal. Redemption in Christ restores the possibility of marriages built on mutual love, respect, and sacrificial service.\n\nSeveral convictions shape the Adventist understanding:\n\n1. **Marriage is between a man and a woman** — Following the creation pattern of Genesis 1:27 and 2:24, Adventists affirm that marriage is a lifelong union between a man and a woman. This conviction is held with pastoral sensitivity, recognizing that all people are created in God's image and deserve dignity and kindness.\n2. **Marriage reflects Christ and the church** — Ephesians 5:21-33 elevates marriage beyond a social arrangement to a theological reality. Husbands are called to love as Christ loved; wives are called to respect as the church honors Christ. The framework is mutual submission \"in the fear of God\" (5:21).\n3. **Marriage is a covenant, not merely a contract** — God is witness to the marriage vow (Malachi 2:14). The permanence of marriage reflects the permanence of God's covenant faithfulness.\n4. **The family is the primary setting for faith formation** — Deuteronomy 6:5-9 envisions parents teaching God's ways in the ordinary rhythms of daily life.\n\n**Corrective boundary:** This belief guards against reducing marriage to either a romantic ideal (disconnected from covenant faithfulness) or a legalistic institution (disconnected from grace). Marriage is a grace-sustained covenant that reflects God's own relational character.\n\nFor further study on the Adventist understanding of marriage and family, visit adventist.org/marriage-and-the-family.",
    sortOrder: 3,
  },
  {
    id: "w4s-23-1-4",
    lessonId: "w4l-23-1",
    sectionType: "practice",
    title: "Putting It Into Practice",
    content: "1. **Articulation exercise:** Write a four-sentence explanation of why Adventists believe marriage was established by God and what purpose it serves. Use at least two Scripture references. Share your summary with a friend and ask if it communicates clearly.\n2. **Relational investment:** If you are married, plan a meaningful conversation with your spouse this week — not about logistics, but about your shared spiritual journey. If you are single, write a letter of encouragement to a married couple you admire, thanking them for the way their relationship reflects God's love.\n3. **Prayer for families:** Spend time this week praying specifically for the families in your local church. Pray for marriages under strain, for single parents carrying heavy burdens, and for children growing up in the faith.",
    sortOrder: 4,
  },
  {
    id: "w4s-23-1-5",
    lessonId: "w4l-23-1",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Genesis 2:18 says, \"It is not good that man should be alone.\" What does this tell you about God's understanding of human need? How does this shape your view of relationships — whether married or single?\n2. Jesus pointed back to creation when asked about marriage (Matthew 19:4-5). Why do you think He chose Genesis rather than Mosaic law as His starting point? What does this teach about how to evaluate cultural practices?\n3. Paul says marriage is a \"mystery\" that points to Christ and the church (Ephesians 5:32). In what ways have you seen marriages reflect — or fail to reflect — this deeper reality?",
    sortOrder: 5,
  },
  {
    id: "w4s-23-1-6",
    lessonId: "w4l-23-1",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },
  {
    id: "w4s-23-2-1",
    lessonId: "w4l-23-2",
    sectionType: "anchor",
    title: "Anchor Passages",
    content: "Read these passages with attention to the covenantal nature of marriage, God's role as witness, and the principle of spiritual compatibility.\n\n1. **Malachi 2:14-16** — God as witness to the marriage covenant. Notice the strong language: \"the Lord has been witness between you and the wife of your youth.\" Observe the connection between faithfulness and covenant.\n2. **2 Corinthians 6:14** — The principle of being \"unequally yoked.\" Consider what this means for the spiritual foundation of marriage.\n3. **Mark 10:6-9** — Jesus' teaching that what God has joined together, no one should separate. Notice how He links the creation narrative to the permanence of marriage.\n4. **Proverbs 31:10-31** — A portrait of a capable, godly wife. Look for the partnership language and the breadth of her contribution to family and community.\n5. **Song of Solomon 8:6-7** — Poetic celebration of faithful love. Note the imagery: love as strong as death, many waters cannot quench it.",
    sortOrder: 1,
  },
  {
    id: "w4s-23-2-2",
    lessonId: "w4l-23-2",
    sectionType: "explain",
    title: "Covenant Faithfulness in Marriage",
    content: "A contract is an agreement between two parties that can be dissolved if either side fails to meet its terms. A covenant is fundamentally different: it is a solemn, binding commitment witnessed by God, rooted in faithfulness rather than performance. When Malachi speaks of marriage, he uses covenant language: \"The Lord has been witness between you and the wife of your youth, with whom you have dealt treacherously; yet she is your companion and your wife by covenant\" (Malachi 2:14). God does not merely approve of marriage from a distance; He stands as witness and guarantor of the vow. This is why Jesus could say, \"What God has joined together, let not man separate\" (Mark 10:9). The union is not merely a human arrangement; it has a divine dimension.\n\nThis covenantal understanding has profound implications. First, it means that marriage is sustained not primarily by romantic feelings (which fluctuate) but by committed faithfulness (which endures). Second, it means that both spouses are accountable not only to each other but to God, who witnessed their vow. Third, it elevates the seriousness of marital breakdown — not to heap guilt on those who suffer it, but to underscore how much is at stake when a covenant is broken. Paul's instruction in 2 Corinthians 6:14 about not being unequally yoked reflects this covenantal depth: a shared spiritual foundation is not an optional bonus but a structural necessity for a marriage that seeks to honor God and nurture faith in the next generation.",
    sortOrder: 2,
  },
  {
    id: "w4s-23-2-3",
    lessonId: "w4l-23-2",
    sectionType: "integrate",
    title: "Adventist Theological Integration",
    content: "Adventist theology places marriage within the cosmic narrative of the Great Controversy. Marriage was God's first human institution — established before the Sabbath, before the sanctuary, before the church. Satan's attacks on the family are therefore strategic: to distort marriage is to obscure one of God's most powerful witnesses to His character of faithful love.\n\nKey Adventist emphases include:\n\n1. **Covenant over contract** — Adventist teaching consistently frames marriage as a covenant before God, not a civil contract between consenting adults. This shapes pastoral counsel, premarital preparation, and the church's ministry to families in crisis.\n2. **Spiritual compatibility** — The principle of being equally yoked (2 Corinthians 6:14) is not about cultural similarity but about shared commitment to Christ. Adventists encourage believers to seek spouses who share their faith, not out of exclusivism but out of recognition that spiritual unity strengthens the marriage covenant.\n3. **Mutual submission** — Ephesians 5:21 (\"submitting to one another in the fear of God\") is the heading under which all instructions to husbands and wives are given. Adventist teaching rejects both authoritarian patriarchy and cultural individualism in favor of Christ-centered mutuality.\n4. **Marriage as witness** — A faithful marriage is an evangelistic testimony. In a world of broken promises, a couple whose love reflects Christ's steadfast commitment speaks volumes about the gospel.\n\n**Corrective boundary:** This belief guards against treating marriage as disposable (undermining its covenantal weight) or as a legalistic trap (ignoring the grace available to those in broken marriages). The gospel offers both the ideal and the mercy needed when the ideal is not reached.\n\nFor further reading, visit adventist.org/marriage-and-the-family.",
    sortOrder: 3,
  },
  {
    id: "w4s-23-2-4",
    lessonId: "w4l-23-2",
    sectionType: "practice",
    title: "Putting It Into Practice",
    content: "1. **Articulation exercise:** Write a brief paragraph explaining the difference between a covenant and a contract as it applies to marriage. Include at least one Scripture reference (e.g., Malachi 2:14 or Mark 10:9). Practice sharing this with someone who asks why marriage matters.\n2. **Covenant renewal:** If you are married, take time this week to verbally reaffirm your commitment to your spouse. This does not need to be a formal ceremony — a heartfelt conversation over a meal can carry deep significance. If single, write a prayer expressing your trust in God's faithfulness in your own relational journey.\n3. **Mentorship connection:** Identify an older couple in your congregation whose marriage you respect. Ask them to share one lesson they have learned about covenant faithfulness over the years. Listen with humility and gratitude.",
    sortOrder: 4,
  },
  {
    id: "w4s-23-2-5",
    lessonId: "w4l-23-2",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Malachi describes God as a \"witness\" to the marriage covenant. How does knowing that God stands as witness to marriage vows change how you think about commitment — whether your own or others'?\n2. What does it mean practically to be \"equally yoked\"? How have you seen shared faith (or the lack of it) affect marriages you have observed?\n3. Our culture tends to view marriage as a contract based on mutual benefit. How does the biblical covenant model challenge this perspective? What difference does it make in how couples navigate hardship?",
    sortOrder: 5,
  },
  {
    id: "w4s-23-2-6",
    lessonId: "w4l-23-2",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },
  {
    id: "w4s-23-3-1",
    lessonId: "w4l-23-3",
    sectionType: "anchor",
    title: "Anchor Passages",
    content: "Read these passages looking for how Scripture envisions the home as a place of faith formation, the responsibilities of parents, and the promise attached to godly child-rearing.\n\n1. **Deuteronomy 6:5-9** — The Shema and its application to family life. Notice the comprehensive settings: \"when you sit in your house, when you walk by the way, when you lie down, and when you rise up.\" Faith is taught in the rhythm of ordinary life.\n2. **Ephesians 6:1-4** — Paul's instructions to children and fathers. Note the balance: children are to obey and honor; fathers are not to provoke but to bring up children \"in the training and admonition of the Lord.\"\n3. **Proverbs 22:6** — The proverbial wisdom about training a child. Consider this as a general principle of wisdom, not a guaranteed formula.\n4. **Psalm 127:3-5** — Children as a heritage from the Lord. Notice the language of gift and blessing.\n5. **2 Timothy 1:5; 3:14-15** — Timothy's faith nurtured by his grandmother Lois and mother Eunice. Observe the intergenerational chain of faith.",
    sortOrder: 1,
  },
  {
    id: "w4s-23-3-2",
    lessonId: "w4l-23-3",
    sectionType: "explain",
    title: "The Home as a School of Faith",
    content: "The most powerful classroom for faith is not a church building but a home. Moses instructed Israel: \"You shall teach them diligently to your children, and shall talk of them when you sit in your house, when you walk by the way, when you lie down, and when you rise up\" (Deuteronomy 6:7). The verbs are active and continuous. Faith formation is not a weekly event but a daily practice embedded in the ordinary rhythms of eating, traveling, resting, and rising. The home becomes a sanctuary of learning where children absorb not just information about God but a lived experience of what it means to trust Him.\n\nPaul adds a crucial pastoral dimension: \"Fathers, do not provoke your children to wrath, but bring them up in the training and admonition of the Lord\" (Ephesians 6:4). The word \"training\" (paideia) includes instruction, discipline, and modeling. The word \"admonition\" (nouthesia) involves gentle correction and encouragement. Paul's warning against provoking children to anger reveals that harsh, authoritarian parenting undermines faith rather than building it. Children who experience their parents' faith as rigid and punitive may reject not only the parents' religion but the God behind it. By contrast, Timothy's story illustrates the beauty of intergenerational faithfulness: his grandmother Lois and mother Eunice nurtured in him a \"genuine faith\" (2 Timothy 1:5) that became the foundation of his apostolic ministry. Faith is most effectively passed on not through lecture but through loving presence.",
    sortOrder: 2,
  },
  {
    id: "w4s-23-3-3",
    lessonId: "w4l-23-3",
    sectionType: "integrate",
    title: "Adventist Theological Integration",
    content: "Adventists have historically placed enormous emphasis on the home as the first and most important institution for faith development. This conviction is rooted in the Deuteronomy 6 model: parents are the primary faith educators, and the rhythms of daily life are the primary curriculum.\n\nSeveral practical emphases flow from this theology:\n\n1. **Family worship** — The Adventist tradition of daily family worship (morning and evening) reflects the Deuteronomy principle of teaching \"when you lie down and when you rise up.\" Simple, consistent devotional practices — reading Scripture, singing, praying together — build a foundation that formal education cannot replace.\n2. **Sabbath as family time** — The weekly Sabbath provides a built-in rhythm for family connection, worship, and rest. Adventist families are encouraged to make Sabbath a day of joy, not merely a day of restriction, creating positive associations with God's presence.\n3. **Adventist education** — The church's global network of schools, from primary through university, extends the family's faith-forming role into the classroom. Education is understood as redemptive: restoring the image of God in the learner.\n4. **Intergenerational ministry** — The church serves as an extended family where older members mentor younger ones, single adults find belonging, and children are welcomed as full participants in the community of faith.\n\n**Corrective boundary:** This belief guards against the privatization of faith (the idea that religion is a personal matter with no communal or familial dimension) and against the outsourcing of spiritual formation entirely to the church or school. Parents bear primary responsibility, supported by the church community.\n\nFor further reading, visit adventist.org/marriage-and-the-family.",
    sortOrder: 3,
  },
  {
    id: "w4s-23-3-4",
    lessonId: "w4l-23-3",
    sectionType: "practice",
    title: "Putting It Into Practice",
    content: "1. **Articulation exercise:** Write a four-sentence summary of what Deuteronomy 6:5-9 teaches about the role of parents in faith formation. Explain why the home is described as the primary classroom for faith. Share your summary with a parent or mentor and invite their response.\n2. **Family worship initiative:** If your household does not currently practice daily worship together, begin this week with a simple five-minute routine: read a short passage of Scripture, share one thing you are thankful for, and pray together. Consistency matters more than length.\n3. **Intergenerational connection:** Reach out to an older member of your church and ask them to share a story of how their family practiced faith at home when they were growing up. Listen for patterns you might adopt in your own household or community.",
    sortOrder: 4,
  },
  {
    id: "w4s-23-3-5",
    lessonId: "w4l-23-3",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Think about your own childhood. What spiritual practices from your home (or absence of them) most shaped your faith? How does this influence the kind of home environment you want to create or contribute to?\n2. Ephesians 6:4 warns fathers not to \"provoke your children to wrath.\" What parenting approaches tend to push children away from faith rather than drawing them toward it? How can grace reshape discipline?\n3. Timothy's faith was nurtured by his grandmother and mother (2 Timothy 1:5). Who are the people who have most influenced your spiritual development? How can you play a similar role for someone younger in the faith?",
    sortOrder: 5,
  },
  {
    id: "w4s-23-3-6",
    lessonId: "w4l-23-3",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },
  {
    id: "w4s-23-4-1",
    lessonId: "w4l-23-4",
    sectionType: "anchor",
    title: "Anchor Passages",
    content: "Read these passages with pastoral sensitivity, paying attention to what Scripture says about divorce, remarriage, singleness, and the hope of restoration.\n\n1. **1 Corinthians 7:10-16** — Paul's instructions regarding separation and mixed-faith marriages. Notice the distinction between the Lord's command (v. 10) and Paul's counsel (v. 12). Observe the pastoral nuance in verses 15-16.\n2. **Matthew 5:31-32** — Jesus' teaching on divorce in the Sermon on the Mount. Note the seriousness with which He treats the marriage covenant.\n3. **Malachi 4:5-6** — The promise that God will \"turn the hearts of the fathers to the children, and the hearts of the children to their fathers.\" Consider this as a promise of relational restoration.\n4. **1 Corinthians 7:7-9,25-35** — Paul's positive teaching on singleness as a legitimate and even advantageous calling. Note that singleness is not presented as a lesser state.\n5. **Hosea 3:1-3** — God commands Hosea to love his unfaithful wife again. Consider this as a picture of God's redemptive love for broken relationships.",
    sortOrder: 1,
  },
  {
    id: "w4s-23-4-2",
    lessonId: "w4l-23-4",
    sectionType: "explain",
    title: "Navigating Difficult Questions",
    content: "Marriage is God's ideal, but we live in a fallen world where that ideal is frequently damaged. Scripture addresses this reality with both honesty and compassion. Jesus taught that divorce was not part of God's original plan — \"from the beginning it was not so\" (Matthew 19:8) — yet He acknowledged that Moses permitted it because of the hardness of human hearts. Paul, writing to the Corinthians, relays the Lord's command that a wife should not separate from her husband and a husband should not divorce his wife (1 Corinthians 7:10-11). Yet he also addresses situations where an unbelieving spouse chooses to leave: \"if the unbeliever departs, let him depart; a brother or a sister is not under bondage in such cases\" (7:15). Scripture does not ignore the pain of broken marriages; it meets that pain with pastoral wisdom.\n\nTwo common misunderstandings need correction. First, the idea that divorced persons are permanently disqualified from God's grace or church fellowship distorts the gospel. While divorce grieves God's heart (Malachi 2:16), it does not place anyone beyond the reach of forgiveness and restoration. Second, the assumption that singleness is a deficiency contradicts Paul's teaching. Paul described his own singleness as a gift (1 Corinthians 7:7) and commended it as a state that allows undivided devotion to the Lord (7:35). The church must be a place where single adults, divorced persons, widows, and blended families all find belonging, dignity, and support — not judgment or exclusion.",
    sortOrder: 2,
  },
  {
    id: "w4s-23-4-3",
    lessonId: "w4l-23-4",
    sectionType: "integrate",
    title: "Adventist Theological Integration",
    content: "The Adventist Church seeks to hold together two convictions that are sometimes perceived as conflicting: the high ideal of lifelong marriage and the pastoral compassion required when that ideal is broken. Both are rooted in Scripture.\n\nKey pastoral principles include:\n\n1. **Upholding the ideal without condemning the broken** — Adventists affirm that marriage is intended to be a lifelong covenant. At the same time, the church recognizes that sin damages relationships, and that Scripture itself makes provision for situations where marriages end (Matthew 19:9; 1 Corinthians 7:15). The church's role is not to impose shame but to offer grace, guidance, and community support.\n2. **Remarriage with pastoral discernment** — The Adventist Church Manual provides guidelines for situations involving remarriage, seeking to balance fidelity to Scripture with sensitivity to individual circumstances. Pastoral counsel and congregational care are essential in these situations.\n3. **Valuing singleness** — The church must resist the cultural assumption that marriage is the only path to a fulfilled life. Paul's commendation of singleness (1 Corinthians 7:7-8,32-35) reminds us that wholeness is found in Christ, not in marital status. Single members deserve full inclusion, respect, and meaningful ministry roles.\n4. **Restoration as the goal** — Malachi 4:5-6 promises that God will turn hearts toward reconciliation. The church's ministry to families should always point toward healing, whether that means restoring a strained marriage, supporting a grieving divorcee, or helping a blended family build new foundations.\n\n**Corrective boundary:** This belief guards against both permissiveness (treating marriage as disposable) and rigidity (using biblical standards as weapons against wounded people). The gospel holds truth and grace together.\n\nFor further reading, visit adventist.org/marriage-and-the-family.",
    sortOrder: 3,
  },
  {
    id: "w4s-23-4-4",
    lessonId: "w4l-23-4",
    sectionType: "practice",
    title: "Putting It Into Practice",
    content: "1. **Articulation exercise:** Write a four-sentence response to someone who says, \"The Bible condemns divorce absolutely, and divorced people should not be welcome in church.\" Use Scripture (especially Matthew 19:8-9 and 1 Corinthians 7:15) to show both the seriousness of divorce and the availability of grace.\n2. **Ministry of presence:** Identify someone in your congregation who has gone through a divorce or is currently in a struggling marriage. Reach out — not to give advice, but simply to listen, pray, and remind them that they are valued and not alone.\n3. **Hospitality action:** Invite a single adult, a single parent, or a widowed person to share a Sabbath meal with your family or small group. Intentional inclusion speaks louder than words.",
    sortOrder: 4,
  },
  {
    id: "w4s-23-4-5",
    lessonId: "w4l-23-4",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. How does your church community treat those who are divorced or single? Does the atmosphere communicate grace and belonging, or does it inadvertently communicate judgment? What might need to change?\n2. Paul calls singleness a \"gift\" (1 Corinthians 7:7). Why do you think many churches struggle to affirm singleness as a valid and honoring way of life? What would it look like to truly value single members?\n3. Malachi 4:5-6 promises that God will turn the hearts of parents and children toward each other. Where do you see the need for this kind of heart-turning in your own family or community? What role might you play in that restoration?",
    sortOrder: 5,
  },
  {
    id: "w4s-23-4-6",
    lessonId: "w4l-23-4",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },
];

export const belief23Assessments = [
  { id: "w4a-23-1", lessonId: "w4l-23-1", title: "Marriage in God's Design Assessment", passingScore: 70 },
  { id: "w4a-23-2", lessonId: "w4l-23-2", title: "Covenant Marriage Assessment", passingScore: 70 },
  { id: "w4a-23-3", lessonId: "w4l-23-3", title: "Building a Godly Home Assessment", passingScore: 70 },
  { id: "w4a-23-4", lessonId: "w4l-23-4", title: "Marriage Challenges Assessment", passingScore: 70 },
];

export const belief23Items = [
  {
    id: "w4i-23-1-1",
    assessmentId: "w4a-23-1",
    question: "According to Genesis 2, what was God's stated reason for creating Eve?",
    options: [
      "It is not good that man should be alone",
      "Adam needed someone to serve him",
      "God wanted to create more humans",
      "The animals needed a caretaker"
    ],
    correctIndex: 0,
    explanation: "God said, 'It is not good that man should be alone; I will make him a helper comparable to him' (Genesis 2:18). The creation of Eve addressed Adam's need for partnership and companionship.",
  },
  {
    id: "w4i-23-1-2",
    assessmentId: "w4a-23-1",
    question: "When the Pharisees asked Jesus about divorce, where did He direct them for the standard on marriage?",
    options: [
      "The Mosaic law on certificates of divorce",
      "The prophetic writings of Malachi",
      "The creation account in Genesis",
      "The wisdom literature of Proverbs"
    ],
    correctIndex: 2,
    explanation: "Jesus pointed back to creation: 'Have you not read that He who made them at the beginning made them male and female?' (Matthew 19:4). He used God's original design as the authoritative standard.",
  },
  {
    id: "w4i-23-1-3",
    assessmentId: "w4a-23-1",
    question: "What does the Hebrew word 'ezer' (helper) used for Eve in Genesis 2:18 tell us about her role?",
    options: [
      "It implies a subordinate servant position",
      "It is used elsewhere of God Himself coming to aid His people",
      "It refers exclusively to domestic responsibilities",
      "It means a temporary assistant"
    ],
    correctIndex: 1,
    explanation: "The word 'ezer' is used in Scripture of God Himself as a helper (Psalm 33:20; 70:5). It carries no connotation of inferiority but speaks of essential, vital partnership.",
  },
  {
    id: "w4i-23-1-4",
    assessmentId: "w4a-23-1",
    question: "According to Ephesians 5:31-32, marriage is a living picture of what deeper reality?",
    options: [
      "The relationship between God and the nation of Israel",
      "The relationship between Christ and the church",
      "The hierarchy of authority in the created order",
      "The contractual nature of all human agreements"
    ],
    correctIndex: 1,
    explanation: "Paul reveals that the 'one flesh' union of marriage is a 'great mystery' pointing to the relationship between Christ and the church (Ephesians 5:31-32).",
  },
  {
    id: "w4i-23-1-5",
    assessmentId: "w4a-23-1",
    question: "A couple in your church is preparing for marriage and asks why their wedding vows matter so much. Which response best reflects biblical teaching?",
    options: [
      "Wedding vows are mostly a cultural tradition that can be adjusted to personal preference",
      "Vows are important because they are a legal requirement for the marriage to be recognized",
      "Marriage vows are a covenant before God who stands as witness, reflecting His own faithful love",
      "Vows are symbolic gestures that carry spiritual significance only if both partners are baptized"
    ],
    correctIndex: 2,
    explanation: "Malachi 2:14 describes God as a witness to the marriage covenant. Marriage vows are not merely cultural or legal — they are solemn commitments made before God, reflecting His covenantal faithfulness.",
  },
  {
    id: "w4i-23-2-1",
    assessmentId: "w4a-23-2",
    question: "In Malachi 2:14, how does the prophet describe God's relationship to the marriage commitment?",
    options: [
      "God is an uninvolved observer",
      "God is a distant approver",
      "God has been witness between you and the wife of your youth",
      "God only cares about the spiritual aspects of the relationship"
    ],
    correctIndex: 2,
    explanation: "Malachi 2:14 states, 'The Lord has been witness between you and the wife of your youth.' God personally witnesses and upholds the marriage covenant.",
  },
  {
    id: "w4i-23-2-2",
    assessmentId: "w4a-23-2",
    question: "What is the primary difference between a covenant and a contract as applied to marriage?",
    options: [
      "A contract is religious while a covenant is secular",
      "A covenant is sustained by committed faithfulness witnessed by God, not merely by mutual benefit",
      "A contract requires witnesses while a covenant does not",
      "There is no meaningful difference between the two"
    ],
    correctIndex: 1,
    explanation: "A contract can be dissolved when terms are unmet, but a covenant is a solemn commitment witnessed by God, rooted in faithfulness rather than performance (Malachi 2:14; Mark 10:9).",
  },
  {
    id: "w4i-23-2-3",
    assessmentId: "w4a-23-2",
    question: "What does Paul mean by not being 'unequally yoked' in 2 Corinthians 6:14?",
    options: [
      "Christians should never interact with non-Christians",
      "Believers should seek partners who share their spiritual commitment to Christ",
      "Marriage partners must come from the same cultural background",
      "Only clergy should perform wedding ceremonies"
    ],
    correctIndex: 1,
    explanation: "Being 'equally yoked' refers to shared spiritual commitment, not cultural similarity. A shared foundation in Christ strengthens the marriage covenant and supports mutual faith growth.",
  },
  {
    id: "w4i-23-2-4",
    assessmentId: "w4a-23-2",
    question: "According to Mark 10:9, why should marriage not be dissolved?",
    options: [
      "Because Roman law prohibited divorce",
      "Because divorce was socially unacceptable in Jewish culture",
      "Because what God has joined together, no one should separate",
      "Because remarriage was not legally permitted"
    ],
    correctIndex: 2,
    explanation: "Jesus taught that marriage has a divine dimension: 'What God has joined together, let not man separate' (Mark 10:9). The union carries God's own seal.",
  },
  {
    id: "w4i-23-2-5",
    assessmentId: "w4a-23-2",
    question: "A friend says, 'Marriage is just a piece of paper — what matters is how you feel about each other.' How would you respond biblically?",
    options: [
      "You are right; feelings are the foundation of any relationship",
      "Marriage is more than a document — it is a sacred covenant witnessed by God, sustained by faithfulness, not just feelings",
      "The paper is what makes it official, so that is what matters most",
      "Feelings and legal status are equally important in Scripture"
    ],
    correctIndex: 1,
    explanation: "Scripture presents marriage as a covenant before God (Malachi 2:14), sustained by committed faithfulness that transcends fluctuating emotions. It has a divine dimension beyond any legal document.",
  },
  {
    id: "w4i-23-3-1",
    assessmentId: "w4a-23-3",
    question: "According to Deuteronomy 6:7, when should parents teach God's ways to their children?",
    options: [
      "Only during formal worship services",
      "Once a week during Sabbath School",
      "When sitting, walking, lying down, and rising up — in the ordinary rhythms of daily life",
      "Only when children reach the age of accountability"
    ],
    correctIndex: 2,
    explanation: "Moses instructed, 'You shall teach them diligently to your children, and shall talk of them when you sit in your house, when you walk by the way, when you lie down, and when you rise up' (Deuteronomy 6:7). Faith formation happens continuously in daily life.",
  },
  {
    id: "w4i-23-3-2",
    assessmentId: "w4a-23-3",
    question: "What warning does Paul give to fathers in Ephesians 6:4?",
    options: [
      "Do not allow children to question your authority",
      "Do not provoke your children to wrath, but bring them up in the training and admonition of the Lord",
      "Do not let children participate in church until they are adults",
      "Do not show too much affection to avoid spoiling them"
    ],
    correctIndex: 1,
    explanation: "Paul instructs fathers not to provoke children to anger but to raise them with the Lord's training and gentle correction (Ephesians 6:4). Harsh parenting undermines faith rather than building it.",
  },
  {
    id: "w4i-23-3-3",
    assessmentId: "w4a-23-3",
    question: "How did Timothy's faith develop according to 2 Timothy 1:5?",
    options: [
      "Through formal theological education at a rabbinical school",
      "Through the genuine faith first lived in his grandmother Lois and mother Eunice",
      "Through miraculous signs that he witnessed as a child",
      "Through direct angelic instruction"
    ],
    correctIndex: 1,
    explanation: "Paul recognized that Timothy's 'genuine faith' first dwelt in his grandmother Lois and his mother Eunice (2 Timothy 1:5). Faith was passed down through intergenerational family influence.",
  },
  {
    id: "w4i-23-3-4",
    assessmentId: "w4a-23-3",
    question: "Why do Adventists emphasize family worship as a daily practice?",
    options: [
      "Because church leaders require it for membership",
      "Because it fulfills a legalistic obligation to earn God's favor",
      "Because it reflects the Deuteronomy 6 principle of teaching when you lie down and rise up",
      "Because formal church services are insufficient for salvation"
    ],
    correctIndex: 2,
    explanation: "Daily family worship reflects the biblical model of Deuteronomy 6:7, where faith is woven into the rhythms of each day — consistent, simple devotional practices that build a spiritual foundation.",
  },
  {
    id: "w4i-23-3-5",
    assessmentId: "w4a-23-3",
    question: "A new parent asks you, 'When should I start teaching my child about God?' What is the best biblical response?",
    options: [
      "Wait until they can read the Bible on their own",
      "Start when they are old enough to sit through a sermon",
      "Begin from the earliest days — faith is caught through daily rhythms of love, prayer, and Scripture before it is formally taught",
      "Enroll them in Sabbath School and let the teachers handle it"
    ],
    correctIndex: 2,
    explanation: "Deuteronomy 6:7 envisions faith as woven into every part of daily life from the beginning. Timothy's faith was nurtured from infancy by his grandmother and mother (2 Timothy 3:15). Parents are the primary faith educators.",
  },
  {
    id: "w4i-23-4-1",
    assessmentId: "w4a-23-4",
    question: "According to 1 Corinthians 7:15, what does Paul say when an unbelieving spouse chooses to leave?",
    options: [
      "The believing spouse must prevent the departure at all costs",
      "A brother or sister is not under bondage in such cases",
      "The believing spouse should immediately seek remarriage",
      "The church must discipline the unbelieving spouse"
    ],
    correctIndex: 1,
    explanation: "Paul writes, 'If the unbeliever departs, let him depart; a brother or a sister is not under bondage in such cases. But God has called us to peace' (1 Corinthians 7:15).",
  },
  {
    id: "w4i-23-4-2",
    assessmentId: "w4a-23-4",
    question: "How did Jesus explain the existence of the Mosaic divorce provision in Matthew 19:8?",
    options: [
      "Moses invented it without God's approval",
      "It was given because of the hardness of human hearts, but from the beginning it was not so",
      "Divorce was always part of God's original plan",
      "The provision only applied to Gentile marriages"
    ],
    correctIndex: 1,
    explanation: "Jesus acknowledged that Moses permitted divorce 'because of the hardness of your hearts, but from the beginning it was not so' (Matthew 19:8). Divorce was a concession, not God's design.",
  },
  {
    id: "w4i-23-4-3",
    assessmentId: "w4a-23-4",
    question: "How does Paul describe singleness in 1 Corinthians 7:7?",
    options: [
      "As a punishment for those who cannot find a spouse",
      "As a temporary condition to be endured",
      "As a gift, with its own value and advantages for serving the Lord",
      "As spiritually inferior to marriage"
    ],
    correctIndex: 2,
    explanation: "Paul described his own singleness as a gift from God (1 Corinthians 7:7) and commended it as a state allowing undivided devotion to the Lord (7:35). Singleness is not a lesser calling.",
  },
  {
    id: "w4i-23-4-4",
    assessmentId: "w4a-23-4",
    question: "What does Malachi 4:5-6 promise regarding families?",
    options: [
      "That all families will be perfect in the last days",
      "That divorce will be eliminated before Christ returns",
      "That God will turn the hearts of fathers to children and children to fathers",
      "That only married couples will be part of God's kingdom"
    ],
    correctIndex: 2,
    explanation: "Malachi 4:5-6 promises that God will 'turn the hearts of the fathers to the children, and the hearts of the children to their fathers' — a vision of relational restoration and reconciliation.",
  },
  {
    id: "w4i-23-4-5",
    assessmentId: "w4a-23-4",
    question: "A church member who recently went through a painful divorce tells you they feel unwelcome at church. What response best reflects Adventist pastoral theology?",
    options: [
      "Remind them that God hates divorce and they should feel convicted",
      "Tell them to find another church where people will not judge them",
      "Assure them that while divorce grieves God's heart, His grace is available, and the church is called to be a place of healing and belonging for all",
      "Suggest they wait until the stigma passes before returning to church"
    ],
    correctIndex: 2,
    explanation: "Adventist pastoral theology holds together the high ideal of marriage and the compassionate recognition that sin damages relationships. The church is called to extend grace, support, and community — not judgment or exclusion.",
  },
];

export const belief24Lessons = [
  {
    id: "w4l-24-1",
    moduleId: "bmod-024",
    title: "Biblical Foundations: The Sanctuary in Scripture",
    description: "Tracing the sanctuary theme from the earthly tabernacle through the heavenly reality, and understanding why this teaching matters for every believer.",
    lessonOrder: 1,
    anchorText: "Hebrews 8:1-5; Hebrews 9:11-28; Leviticus 16:1-34",
    anchorBookId: 58,
    anchorChapter: 8,
    anchorVerseStart: 1,
    anchorVerseEnd: 5,
    estimatedMinutes: 35,
  },
  {
    id: "w4l-24-2",
    moduleId: "bmod-024",
    title: "Doctrinal Formulation: Christ's Two-Phase Ministry",
    description: "Understanding the Adventist teaching on Christ's ministry in the heavenly sanctuary, including the transition from intercession to investigative judgment.",
    lessonOrder: 2,
    anchorText: "Daniel 7:9-14; Daniel 8:14; Hebrews 4:14-16",
    anchorBookId: 27,
    anchorChapter: 7,
    anchorVerseStart: 9,
    anchorVerseEnd: 14,
    estimatedMinutes: 30,
  },
  {
    id: "w4l-24-3",
    moduleId: "bmod-024",
    title: "Practical Implications: Confidence Before the Throne",
    description: "Drawing assurance and practical spiritual strength from the reality of Christ's ongoing ministry on our behalf in the heavenly sanctuary.",
    lessonOrder: 3,
    anchorText: "Hebrews 10:19-22; Revelation 14:6-7; 1 John 2:1-2",
    anchorBookId: 58,
    anchorChapter: 10,
    anchorVerseStart: 19,
    anchorVerseEnd: 22,
    estimatedMinutes: 30,
  },
  {
    id: "w4l-24-4",
    moduleId: "bmod-024",
    title: "Misunderstandings & Challenges",
    description: "Addressing common objections and clarifying what the heavenly sanctuary doctrine does and does not teach.",
    lessonOrder: 4,
    anchorText: "Hebrews 6:19-20; Hebrews 9:24-28; Revelation 20:12",
    anchorBookId: 58,
    anchorChapter: 6,
    anchorVerseStart: 19,
    anchorVerseEnd: 20,
    estimatedMinutes: 30,
  },
];

export const belief24Sections = [
  {
    id: "w4s-24-1-1",
    lessonId: "w4l-24-1",
    sectionType: "anchor",
    title: "Anchor Passages",
    content: "Read the following passages carefully, paying attention to the relationship between the earthly sanctuary and its heavenly counterpart, and the purpose of Christ's priestly ministry.\n\n1. **Hebrews 8:1-5** — The author of Hebrews declares that Christ is a minister of the \"true tabernacle\" in heaven. Notice verse 5: the earthly sanctuary was a \"copy and shadow\" of heavenly realities.\n2. **Hebrews 9:11-28** — A detailed comparison between the ministry of the earthly high priest and the ministry of Christ. Observe how Christ entered \"the greater and more perfect tabernacle\" with His own blood.\n3. **Leviticus 16:1-34** — The Day of Atonement ritual. Notice the two phases: the daily ministry throughout the year, and the annual cleansing of the sanctuary. Pay attention to what the high priest does, where he goes, and what the result is.\n4. **Exodus 25:8-9,40** — God's instruction to Moses to build the tabernacle according to the pattern shown on the mountain. The earthly was modeled on a heavenly original.\n5. **Hebrews 4:14-16** — Christ as our great High Priest who sympathizes with our weaknesses. Notice the invitation: \"Let us therefore come boldly to the throne of grace.\"",
    sortOrder: 1,
  },
  {
    id: "w4s-24-1-2",
    lessonId: "w4l-24-1",
    sectionType: "explain",
    title: "Understanding the Sanctuary Theme",
    content: "The sanctuary is one of Scripture's most comprehensive teaching tools. When God instructed Moses, \"Let them make Me a sanctuary, that I may dwell among them\" (Exodus 25:8), He established a visual curriculum for understanding salvation. Every element of the tabernacle — the altar of sacrifice, the laver, the table of showbread, the lampstand, the altar of incense, the veil, the ark of the covenant — pointed forward to some dimension of Christ's saving work. The daily sacrifices illustrated the ongoing availability of forgiveness through the shedding of blood (Hebrews 9:22). The annual Day of Atonement (Leviticus 16) represented a final, comprehensive resolution of sin — a \"cleansing\" of the sanctuary that symbolized the ultimate removal of sin from God's people and His dwelling place.\n\nThe book of Hebrews reveals that the earthly tabernacle was a \"copy and shadow of the heavenly things\" (Hebrews 8:5). The real sanctuary is in heaven, and Christ is its minister. He entered not with the blood of animals but \"with His own blood\" and \"obtained eternal redemption\" (Hebrews 9:12). This is not a metaphor for an abstract spiritual transaction; Hebrews insists that Christ entered \"heaven itself, now to appear in the presence of God for us\" (Hebrews 9:24). His ministry is real, ongoing, and personal. The cross was the sacrifice; the heavenly sanctuary is where the benefits of that sacrifice are applied to believers across history. Christ is both the Lamb who was slain and the Priest who mediates the benefits of His sacrifice.",
    sortOrder: 2,
  },
  {
    id: "w4s-24-1-3",
    lessonId: "w4l-24-1",
    sectionType: "integrate",
    title: "Adventist Theological Integration",
    content: "The sanctuary doctrine holds a central place in Adventist theology because it integrates multiple biblical themes — sacrifice, priesthood, judgment, and restoration — into a coherent picture of God's plan to deal with sin comprehensively. Adventists understand the earthly sanctuary system as a divinely designed teaching model that illuminates Christ's work from the cross through the conclusion of the plan of salvation.\n\nKey Adventist convictions include:\n\n1. **The heavenly sanctuary is real** — Following Hebrews, Adventists affirm that the sanctuary in heaven is not merely symbolic but an actual place where Christ ministers. The earthly was the copy; the heavenly is the original (Hebrews 8:2,5).\n2. **The cross and the sanctuary are complementary, not competing** — Christ's death on the cross accomplished full atonement. His ministry in the heavenly sanctuary applies the benefits of that atonement to believers. These are two phases of one saving work, not two separate salvations.\n3. **The sanctuary reveals God's character** — Every aspect of the sanctuary service points to a God who takes sin seriously, provides for its forgiveness generously, and promises its ultimate eradication completely.\n4. **The sanctuary provides structure for understanding prophecy** — The sanctuary motif runs through Daniel and Revelation, providing the framework for understanding end-time events, including the pre-advent judgment.\n\n**Corrective boundary:** This belief guards against separating the cross from Christ's ongoing ministry. The sacrifice and the priesthood belong together. To emphasize one without the other produces either a truncated gospel (cross without priesthood) or a works-oriented religion (priesthood without cross).\n\nFor further study on the sanctuary theme, visit adventist.org/christs-ministry-in-the-heavenly-sanctuary.",
    sortOrder: 3,
  },
  {
    id: "w4s-24-1-4",
    lessonId: "w4l-24-1",
    sectionType: "practice",
    title: "Putting It Into Practice",
    content: "1. **Articulation exercise:** Write a four-sentence summary explaining what the heavenly sanctuary is and why Christ's ministry there matters. Use at least two Scripture references (e.g., Hebrews 8:1-2 and Hebrews 9:24). Share your summary with a study partner for feedback.\n2. **Study the furniture:** Choose one element of the earthly tabernacle (altar of burnt offering, laver, lampstand, table of showbread, altar of incense, or ark of the covenant). Research its purpose in the sanctuary service and write a short paragraph explaining how it points to Christ.\n3. **Prayer of confidence:** Hebrews 4:16 invites us to \"come boldly to the throne of grace.\" Spend time this week approaching God in prayer with the conscious awareness that Christ is right now interceding for you. Let this reality reshape how you pray.",
    sortOrder: 4,
  },
  {
    id: "w4s-24-1-5",
    lessonId: "w4l-24-1",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. The earthly sanctuary was designed so God could \"dwell among\" His people (Exodus 25:8). What does this tell you about God's deepest desire? How does this shape your understanding of His character?\n2. Hebrews says the earthly sanctuary was a \"copy and shadow\" of heavenly realities (8:5). How does knowing that Christ is ministering in a real heavenly sanctuary affect your confidence in prayer and your assurance of forgiveness?\n3. The sanctuary system taught Israel that sin required a costly sacrifice and a mediating priest. How does this two-fold provision — sacrifice and priesthood — give you a more complete picture of what Christ has done and is doing for you?",
    sortOrder: 5,
  },
  {
    id: "w4s-24-1-6",
    lessonId: "w4l-24-1",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },
  {
    id: "w4s-24-2-1",
    lessonId: "w4l-24-2",
    sectionType: "anchor",
    title: "Anchor Passages",
    content: "Read these passages with attention to the transition in Christ's ministry, the timing of the judgment scene in Daniel, and the assurance provided by Christ's priesthood.\n\n1. **Daniel 7:9-14** — The judgment scene in Daniel's vision. Notice the setting: thrones, the Ancient of Days, books opened, and the Son of Man brought before the Father. This is a courtroom scene in heaven.\n2. **Daniel 8:14** — \"Unto two thousand three hundred days; then the sanctuary shall be cleansed.\" Consider what \"cleansing\" means in the context of the sanctuary's Day of Atonement.\n3. **Hebrews 4:14-16** — Christ as a sympathetic High Priest. Notice that His priesthood is a present reality (\"we have\" a great High Priest), not merely a past event.\n4. **Daniel 8:26-27** — Gabriel tells Daniel the vision concerns \"many days in the future.\" Observe Daniel's response: he was troubled and did not fully understand.\n5. **Revelation 11:19** — The heavenly temple is opened and the ark of the covenant is seen. Notice this occurs in the context of final judgment themes.",
    sortOrder: 1,
  },
  {
    id: "w4s-24-2-2",
    lessonId: "w4l-24-2",
    sectionType: "explain",
    title: "Christ's Two-Phase Ministry",
    content: "The earthly sanctuary operated on two cycles: a daily ministry of intercession and a yearly Day of Atonement. Each day, sacrifices were offered and blood was brought into the Holy Place, symbolizing the continual availability of forgiveness and access to God. Once a year, on the Day of Atonement (Yom Kippur), the high priest entered the Most Holy Place to cleanse the sanctuary of the accumulated record of confessed sins (Leviticus 16). This annual event represented the ultimate resolution of the sin problem — not just forgiveness, but the removal of sin's record from God's dwelling.\n\nAdventists understand Christ's heavenly ministry as following this two-phase pattern. After His ascension, Christ began His intercessory ministry in the heavenly sanctuary, applying the benefits of His sacrifice to all who come to God through Him (Hebrews 7:25). Daniel 7:9-14 describes a judgment scene that takes place before the second coming: the Ancient of Days is seated, the books are opened, and the Son of Man is brought before the Father to receive dominion and a kingdom. Adventists identify this pre-advent judgment as the antitype (the heavenly fulfillment) of the Day of Atonement. Daniel 8:14 provides the prophetic time marker: at the conclusion of the 2,300-day prophecy, \"the sanctuary shall be cleansed.\" Using the day-year principle (Numbers 14:34; Ezekiel 4:6), Adventists calculate this period as beginning in 457 BC (the decree to restore Jerusalem, Daniel 9:25) and concluding in 1844 AD, when Christ's ministry entered its final phase of judgment and vindication.",
    sortOrder: 2,
  },
  {
    id: "w4s-24-2-3",
    lessonId: "w4l-24-2",
    sectionType: "integrate",
    title: "Adventist Theological Integration",
    content: "The pre-advent (investigative) judgment is one of the most distinctive Adventist teachings. It is also one that requires careful, precise articulation. The key theological points are:\n\n1. **The judgment is good news, not a threat** — The judgment vindicates God's people, not condemns them. Daniel 7:22 says judgment was rendered \"in favor of the saints.\" The purpose is to demonstrate before the universe that God's grace has genuinely transformed the lives of those who have trusted in Christ.\n2. **Christ is both Judge and Advocate** — In Daniel 7, the Son of Man stands before the Ancient of Days as representative of His people. In 1 John 2:1, He is our \"Advocate with the Father.\" The judgment is not a cold courtroom where believers face an angry God alone; it is a hearing where Christ Himself stands on their behalf.\n3. **The judgment examines the genuineness of faith** — The books that are opened (Daniel 7:10; Revelation 20:12) record the lives of those who have professed faith. The question is not whether believers have been sinless, but whether they have genuinely trusted Christ and allowed His grace to work in their lives.\n4. **The judgment precedes the second coming** — This is a pre-advent event. Christ comes to earth only after the judgment is complete and He has received the kingdom (Daniel 7:14). This means the verdict is settled before Jesus returns.\n5. **The 2,300-day prophecy provides the timeline** — Using the year-day principle and the connection between Daniel 8:14 and Daniel 9:24-27, Adventists understand 1844 as the beginning of the final phase of Christ's heavenly ministry.\n\n**Corrective boundary:** This belief guards against two errors: (a) the idea that salvation is uncertain or that believers must live in perpetual anxiety about the judgment (the gospel provides assurance — Romans 8:1), and (b) the notion that the judgment is irrelevant because the cross settled everything (the cross provides the basis for salvation; the judgment reveals its fruit).\n\nFor further study, visit adventist.org/christs-ministry-in-the-heavenly-sanctuary.",
    sortOrder: 3,
  },
  {
    id: "w4s-24-2-4",
    lessonId: "w4l-24-2",
    sectionType: "practice",
    title: "Putting It Into Practice",
    content: "1. **Articulation exercise:** Write a brief paragraph explaining the pre-advent judgment to someone unfamiliar with the concept. Focus on three things: what it is (a review of professed believers' lives), who conducts it (Christ as both Advocate and Judge), and why it matters (vindication of God's people and His character). Avoid jargon.\n2. **Scripture comparison:** Read Leviticus 16 alongside Daniel 7:9-14. Make a simple two-column chart comparing the earthly Day of Atonement with the heavenly judgment scene. Note similarities in themes of cleansing, record-keeping, and resolution.\n3. **Assurance prayer:** Read Romans 8:1 (\"There is therefore now no condemnation for those who are in Christ Jesus\") and Hebrews 4:16 (\"Let us come boldly to the throne of grace\"). Spend time in prayer thanking Christ for being your Advocate and asking Him to deepen your confidence in His saving work.",
    sortOrder: 4,
  },
  {
    id: "w4s-24-2-5",
    lessonId: "w4l-24-2",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. The pre-advent judgment reveals that God takes both sin and grace seriously. How does knowing that Christ is your Advocate in this judgment affect your sense of security before God?\n2. Daniel 7:22 says that judgment was rendered \"in favor of the saints.\" How does this change the way you think about divine judgment — from something to fear to something that vindicates?\n3. The 2,300-day prophecy positions us in the final phase of salvation history. How does living in this period shape your sense of purpose, urgency, and hope?",
    sortOrder: 5,
  },
  {
    id: "w4s-24-2-6",
    lessonId: "w4l-24-2",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },
  {
    id: "w4s-24-3-1",
    lessonId: "w4l-24-3",
    sectionType: "anchor",
    title: "Anchor Passages",
    content: "Read these passages looking for the practical confidence and spiritual boldness that flow from Christ's heavenly ministry.\n\n1. **Hebrews 10:19-22** — The invitation to enter God's presence with confidence through Christ's blood. Notice the fourfold description: full assurance, hearts sprinkled, bodies washed, holding fast our confession.\n2. **Revelation 14:6-7** — The first angel's message: \"Fear God and give glory to Him, for the hour of His judgment has come.\" Consider this as an invitation, not a threat.\n3. **1 John 2:1-2** — Christ as our Advocate with the Father. Notice that His advocacy is based on His being the propitiation (atoning sacrifice) for our sins.\n4. **Hebrews 7:25** — Christ \"always lives to make intercession\" for those who come to God through Him. Observe the completeness: He is able to save \"to the uttermost.\"\n5. **Romans 8:33-34** — Paul's rhetorical questions about accusation and condemnation. Notice that Christ's intercession is the final answer to every charge.",
    sortOrder: 1,
  },
  {
    id: "w4s-24-3-2",
    lessonId: "w4l-24-3",
    sectionType: "explain",
    title: "Drawing Confidence from Christ's Ministry",
    content: "The doctrine of Christ's heavenly ministry is not an abstract theological puzzle; it is a source of profound spiritual confidence. The author of Hebrews writes, \"Therefore, brethren, having boldness to enter the Holiest by the blood of Jesus, by a new and living way which He consecrated for us, through the veil, that is, His flesh, and having a High Priest over the house of God, let us draw near with a true heart in full assurance of faith\" (Hebrews 10:19-22). The language is remarkable: boldness, full assurance, a new and living way. Access to God's presence is not restricted to a select priestly class; it is opened to every believer through Christ.\n\nJohn adds another dimension: \"If anyone sins, we have an Advocate with the Father, Jesus Christ the righteous. And He Himself is the propitiation for our sins\" (1 John 2:1-2). The word \"advocate\" (parakletos) means one who is called alongside to help — a defender, an intercessor. When guilt accuses us, Christ speaks for us. His defense is not based on our performance but on His sacrifice. Paul presses this to its logical conclusion: \"Who shall bring a charge against God's elect? It is God who justifies. Who is he who condemns? It is Christ who died, and furthermore is also risen, who is even at the right hand of God, who also makes intercession for us\" (Romans 8:33-34). The entire weight of accusation — from Satan, from conscience, from the law — is met by the interceding Christ.",
    sortOrder: 2,
  },
  {
    id: "w4s-24-3-3",
    lessonId: "w4l-24-3",
    sectionType: "integrate",
    title: "Adventist Theological Integration",
    content: "The Adventist understanding of Christ's heavenly ministry produces not anxiety but assurance. Several practical implications follow:\n\n1. **Confident prayer** — Because Christ is our High Priest who sympathizes with our weaknesses (Hebrews 4:15), believers can approach God's throne with boldness, not timidity. Prayer is not a gamble; it is a conversation with a Father whose Son stands at His right hand on our behalf.\n2. **Assurance of forgiveness** — Christ's intercession means that confessed sin is dealt with completely. \"If we confess our sins, He is faithful and just to forgive us our sins and to cleanse us from all unrighteousness\" (1 John 1:9). The cleansing of the heavenly sanctuary does not undo this promise; it confirms it.\n3. **The judgment message as gospel** — Revelation 14:6-7 announces, \"Fear God and give glory to Him, for the hour of His judgment has come.\" In Adventist theology, this is not a message of terror but of hope. The judgment means that God's justice is active, wrongs will be made right, and those who trust in Christ will be vindicated. The first angel also carries the \"everlasting gospel\" — judgment and gospel are proclaimed together.\n4. **Living with integrity, not perfectionism** — The reality of Christ's ongoing ministry encourages believers to live faithfully without the burden of perfectionism. Our acceptance before God is based on Christ's merits, not our performance. At the same time, genuine faith produces genuine transformation (James 2:17).\n\n**Corrective boundary:** This belief guards against reducing Christianity to a past-tense religion (\"Jesus died for me, and that is all that matters\"). Christ's saving work includes His present ministry of intercession and His future return. The full gospel encompasses cross, priesthood, and kingdom.\n\nFor further reading, visit adventist.org/christs-ministry-in-the-heavenly-sanctuary.",
    sortOrder: 3,
  },
  {
    id: "w4s-24-3-4",
    lessonId: "w4l-24-3",
    sectionType: "practice",
    title: "Putting It Into Practice",
    content: "1. **Articulation exercise:** Write a four-sentence explanation of how Christ's heavenly ministry gives believers confidence before God. Include at least one reference from Hebrews and one from Romans 8 or 1 John 2. Share it with someone who struggles with assurance of salvation.\n2. **Intercessory prayer practice:** Because Christ intercedes for you, practice interceding for others. Choose five people this week and pray specifically for each one by name, trusting that your prayers reach the throne where Christ stands on your behalf.\n3. **Gospel conversation:** The first angel's message combines judgment and gospel (Revelation 14:6-7). This week, practice sharing this combination with someone: \"God's judgment is good news because Christ stands as our Advocate, and those who trust Him have nothing to fear.\"",
    sortOrder: 4,
  },
  {
    id: "w4s-24-3-5",
    lessonId: "w4l-24-3",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. Hebrews 10:19-22 invites you to enter God's presence with \"boldness\" and \"full assurance.\" Do you typically approach God this way, or does guilt or fear hold you back? What would change if you truly believed Christ is interceding for you right now?\n2. Romans 8:33-34 asks, \"Who shall bring a charge against God's elect?\" and answers that Christ's intercession silences every accusation. How does this truth speak to areas of your life where you feel accused or inadequate?\n3. The first angel's message announces both the \"everlasting gospel\" and the \"hour of His judgment\" in the same breath (Revelation 14:6-7). Why do you think judgment and gospel belong together? What happens when they are separated?",
    sortOrder: 5,
  },
  {
    id: "w4s-24-3-6",
    lessonId: "w4l-24-3",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },
  {
    id: "w4s-24-4-1",
    lessonId: "w4l-24-4",
    sectionType: "anchor",
    title: "Anchor Passages",
    content: "Read these passages with attention to the certainty of Christ's priestly ministry, the completeness of His sacrifice, and the relationship between past, present, and future aspects of salvation.\n\n1. **Hebrews 6:19-20** — Our hope as an anchor of the soul, entering behind the veil where Jesus has gone as a forerunner. Notice the imagery: Christ has already entered the Most Holy Place on our behalf.\n2. **Hebrews 9:24-28** — Christ entered heaven itself to appear before God for us. Note verse 28: He will appear \"a second time, apart from sin, for salvation.\" The sequence is sacrifice, intercession, return.\n3. **Revelation 20:12** — The judgment scene with books opened. Notice the basis of judgment: \"according to their works\" as recorded in the books.\n4. **Hebrews 10:11-14** — The contrast between the repeated sacrifices of earthly priests and Christ's one sacrifice. Observe: \"by one offering He has perfected forever those who are being sanctified.\"\n5. **Hebrews 9:27-28** — The parallel between human death and judgment and Christ's sacrificial death and future return.",
    sortOrder: 1,
  },
  {
    id: "w4s-24-4-2",
    lessonId: "w4l-24-4",
    sectionType: "explain",
    title: "Addressing Common Objections",
    content: "The sanctuary doctrine faces several persistent objections. The first and most common is the claim that Christ's work was fully completed at the cross, making any subsequent ministry unnecessary. This objection misunderstands the relationship between sacrifice and priesthood. The cross was indeed the once-for-all sacrifice (Hebrews 10:12), but the author of Hebrews spends multiple chapters explaining that Christ's priestly ministry continues in heaven. A sacrifice without a priest to apply it would be like a payment deposited but never distributed. The cross provides the basis of salvation; Christ's intercession applies it to individual believers across history.\n\nA second objection concerns the pre-advent judgment: does it not undermine the assurance of the gospel? This concern deserves a careful response. The pre-advent judgment does not determine whether Christ's sacrifice is sufficient — that was settled at Calvary. Rather, it examines whether professed believers have genuinely received and responded to that sacrifice. Daniel 7:22 says the judgment was rendered \"in favor of the saints.\" The verdict is good news for those who trust Christ. Romans 8:1 remains true: \"There is therefore now no condemnation for those who are in Christ Jesus.\" A third objection asks whether a heavenly sanctuary is not merely metaphorical. Hebrews answers with striking directness: Christ has entered \"heaven itself\" to appear \"in the presence of God for us\" (Hebrews 9:24). The language of Hebrews treats the heavenly sanctuary as a genuine reality, not a literary device.",
    sortOrder: 2,
  },
  {
    id: "w4s-24-4-3",
    lessonId: "w4l-24-4",
    sectionType: "integrate",
    title: "Adventist Theological Integration",
    content: "Adventists acknowledge that the sanctuary doctrine requires careful study and honest engagement with objections. Several clarifications are essential:\n\n1. **The judgment does not introduce salvation by works** — Works are examined in the judgment (Revelation 20:12), but they are evidence of faith, not the basis of acceptance. Salvation is by grace through faith (Ephesians 2:8-9); works are the fruit that confirms whether faith is genuine (James 2:17-18). The judgment does not weigh good deeds against bad deeds; it examines whether a person has genuinely trusted Christ.\n2. **The 1844 date is based on prophetic interpretation, not arbitrary selection** — The 2,300-day prophecy of Daniel 8:14 is connected to the 70-week prophecy of Daniel 9:24-27 through shared starting points and language. The interpretation follows established principles of prophetic interpretation, including the year-day principle.\n3. **The sanctuary doctrine does not diminish the cross** — Rather, it expands our understanding of Christ's complete saving work. The cross provides the sacrifice; the heavenly ministry applies it; the second coming consummates it. These are three movements in one symphony of salvation.\n4. **Assurance and judgment coexist** — Scripture holds both truths simultaneously. Paul could write \"there is now no condemnation\" (Romans 8:1) and also \"we must all appear before the judgment seat of Christ\" (2 Corinthians 5:10). These are not contradictions; they describe different dimensions of one reality. Believers face judgment not as defendants before an angry judge but as children before a loving Father whose Son has already secured the verdict.\n\n**Corrective boundary:** This belief guards against both dismissing Christ's ongoing ministry (reducing salvation to a single past event) and turning the judgment into a source of spiritual terror (denying the assurance that Christ's intercession provides). The sanctuary doctrine, rightly understood, magnifies both the seriousness of sin and the sufficiency of grace.\n\nFor further study, visit adventist.org/christs-ministry-in-the-heavenly-sanctuary.",
    sortOrder: 3,
  },
  {
    id: "w4s-24-4-4",
    lessonId: "w4l-24-4",
    sectionType: "practice",
    title: "Putting It Into Practice",
    content: "1. **Articulation exercise:** Write a four-sentence response to someone who says, \"If Jesus said 'It is finished' on the cross, why do we need a heavenly sanctuary ministry?\" Distinguish between the sacrifice (finished at the cross) and the application of its benefits (ongoing through Christ's priesthood). Use Hebrews 9:24-28.\n2. **Comparative study:** Read Hebrews 10:11-14 alongside Romans 8:1 and 2 Corinthians 5:10. Write a brief reflection on how these passages hold together the completeness of Christ's sacrifice, the assurance of believers, and the reality of judgment.\n3. **Assurance conversation:** Share the truth of Romans 8:33-34 with a fellow believer who may be struggling with the fear of judgment. Help them see that Christ's intercession is their security, not their threat.",
    sortOrder: 4,
  },
  {
    id: "w4s-24-4-5",
    lessonId: "w4l-24-4",
    sectionType: "reflection",
    title: "Personal Reflection",
    content: "1. How do you personally hold together the assurance of salvation (Romans 8:1) and the reality of judgment (2 Corinthians 5:10)? Does one feel more real to you than the other? Why?\n2. Hebrews 6:19 calls our hope \"an anchor of the soul, both sure and steadfast, and which enters the Presence behind the veil.\" How does picturing your hope as anchored in the heavenly sanctuary — where Christ is right now — affect your spiritual confidence?\n3. Some people find the sanctuary doctrine confusing or anxiety-producing. If you were explaining it to a friend, what would you emphasize first — and what would you save for later? Why?",
    sortOrder: 5,
  },
  {
    id: "w4s-24-4-6",
    lessonId: "w4l-24-4",
    sectionType: "assessment",
    title: "Knowledge Check",
    content: "Test your understanding of this lesson.",
    sortOrder: 6,
  },
];

export const belief24Assessments = [
  { id: "w4a-24-1", lessonId: "w4l-24-1", title: "Sanctuary Foundations Assessment", passingScore: 70 },
  { id: "w4a-24-2", lessonId: "w4l-24-2", title: "Two-Phase Ministry Assessment", passingScore: 70 },
  { id: "w4a-24-3", lessonId: "w4l-24-3", title: "Confidence Before the Throne Assessment", passingScore: 70 },
  { id: "w4a-24-4", lessonId: "w4l-24-4", title: "Sanctuary Challenges Assessment", passingScore: 70 },
];

export const belief24Items = [
  {
    id: "w4i-24-1-1",
    assessmentId: "w4a-24-1",
    question: "According to Hebrews 8:1-5, what is the relationship between the earthly tabernacle and the heavenly sanctuary?",
    options: [
      "The earthly tabernacle replaced the heavenly sanctuary",
      "The earthly tabernacle was a copy and shadow of the heavenly reality",
      "The heavenly sanctuary is a metaphor for the earthly tabernacle",
      "There is no connection between the two"
    ],
    correctIndex: 1,
    explanation: "Hebrews 8:5 states that the earthly priests 'serve the copy and shadow of the heavenly things,' as Moses was instructed to make the tabernacle according to the pattern shown on the mountain.",
  },
  {
    id: "w4i-24-1-2",
    assessmentId: "w4a-24-1",
    question: "With what did Christ enter the heavenly sanctuary according to Hebrews 9:12?",
    options: [
      "With the blood of goats and calves",
      "With gold and precious stones",
      "With His own blood, obtaining eternal redemption",
      "With the prayers of the saints"
    ],
    correctIndex: 2,
    explanation: "Hebrews 9:12 declares that Christ entered the Most Holy Place 'not with the blood of goats and calves, but with His own blood, He obtained eternal redemption.'",
  },
  {
    id: "w4i-24-1-3",
    assessmentId: "w4a-24-1",
    question: "What was the purpose of the annual Day of Atonement in Leviticus 16?",
    options: [
      "To celebrate the anniversary of the tabernacle's construction",
      "To ordain new priests for the coming year",
      "To cleanse the sanctuary of the accumulated record of confessed sins",
      "To collect tithes and offerings from the people"
    ],
    correctIndex: 2,
    explanation: "The Day of Atonement (Yom Kippur) was the annual cleansing of the sanctuary, representing the ultimate removal of sin's record from God's dwelling place (Leviticus 16:30,33).",
  },
  {
    id: "w4i-24-1-4",
    assessmentId: "w4a-24-1",
    question: "How does Hebrews describe the relationship between Christ's sacrifice on the cross and His ministry in the heavenly sanctuary?",
    options: [
      "The cross was incomplete; the sanctuary completes salvation",
      "The cross accomplished the sacrifice; the sanctuary is where its benefits are applied to believers",
      "The sanctuary ministry replaces what happened at the cross",
      "The cross and sanctuary are completely unrelated events"
    ],
    correctIndex: 1,
    explanation: "The cross was the once-for-all sacrifice (Hebrews 10:12), and Christ's heavenly ministry applies the benefits of that sacrifice to believers across history (Hebrews 9:24). They are complementary phases of one saving work.",
  },
  {
    id: "w4i-24-1-5",
    assessmentId: "w4a-24-1",
    question: "A friend asks, 'Why should I care about an ancient tabernacle in the desert?' How would you best explain its relevance?",
    options: [
      "It is mainly a historical curiosity with little relevance to modern faith",
      "The tabernacle is important only for understanding Jewish customs and traditions",
      "Every element of the tabernacle pointed forward to Christ's saving work, and its heavenly counterpart is where Christ ministers for us right now",
      "The tabernacle teaches us about ancient construction techniques"
    ],
    correctIndex: 2,
    explanation: "The sanctuary was God's visual curriculum for understanding salvation (Exodus 25:8-9). Every element pointed to Christ, and Hebrews reveals that its heavenly original is where Christ currently ministers on our behalf (Hebrews 8:1-2).",
  },
  {
    id: "w4i-24-2-1",
    assessmentId: "w4a-24-2",
    question: "In Daniel 7:9-14, what is depicted in the heavenly scene?",
    options: [
      "A coronation ceremony for earthly kings",
      "A judgment scene with thrones, the Ancient of Days, books opened, and the Son of Man receiving dominion",
      "A celebration of the creation of the world",
      "A battle between angelic armies"
    ],
    correctIndex: 1,
    explanation: "Daniel 7:9-14 portrays a heavenly judgment scene: thrones are set, the Ancient of Days takes His seat, books are opened, and the Son of Man is brought before the Father to receive dominion, glory, and a kingdom.",
  },
  {
    id: "w4i-24-2-2",
    assessmentId: "w4a-24-2",
    question: "What does Daniel 8:14 prophesy will happen at the end of the 2,300 days?",
    options: [
      "The earthly temple will be rebuilt",
      "The sanctuary shall be cleansed",
      "Christ will return to earth",
      "A new covenant will be established"
    ],
    correctIndex: 1,
    explanation: "Daniel 8:14 states, 'Unto two thousand three hundred days; then the sanctuary shall be cleansed.' Adventists understand this as referring to the beginning of Christ's final phase of ministry in the heavenly sanctuary.",
  },
  {
    id: "w4i-24-2-3",
    assessmentId: "w4a-24-2",
    question: "According to Daniel 7:22, what was the outcome of the heavenly judgment for the saints?",
    options: [
      "The saints were condemned and punished",
      "Judgment was rendered in favor of the saints",
      "The saints were placed on probation",
      "The judgment was postponed indefinitely"
    ],
    correctIndex: 1,
    explanation: "Daniel 7:22 declares that judgment was rendered 'in favor of the saints of the Most High.' The pre-advent judgment is good news for God's people, vindicating those who have trusted in Christ.",
  },
  {
    id: "w4i-24-2-4",
    assessmentId: "w4a-24-2",
    question: "What interpretive principle do Adventists use to calculate the 2,300-day prophecy?",
    options: [
      "The lunar calendar principle",
      "The day-year principle, supported by Numbers 14:34 and Ezekiel 4:6",
      "The literal-day principle, treating each day as 24 hours",
      "The symbolic-generation principle"
    ],
    correctIndex: 1,
    explanation: "Adventists apply the year-day principle (Numbers 14:34; Ezekiel 4:6) to apocalyptic time prophecies, understanding each prophetic day as representing one literal year, placing the fulfillment of the 2,300 days in 1844 AD.",
  },
  {
    id: "w4i-24-2-5",
    assessmentId: "w4a-24-2",
    question: "A fellow church member says, 'The pre-advent judgment makes me anxious about my salvation.' What is the most biblically accurate response?",
    options: [
      "You should be anxious — the judgment examines every sin you have ever committed",
      "The judgment does not apply to Christians, only to unbelievers",
      "Christ is your Advocate in this judgment, and Daniel 7:22 says the verdict is in favor of the saints — assurance and judgment work together",
      "Just try not to think about the judgment and focus on positive things"
    ],
    correctIndex: 2,
    explanation: "The pre-advent judgment does not undermine assurance. Christ serves as Advocate (1 John 2:1), and the judgment is rendered in favor of the saints (Daniel 7:22). Romans 8:1 still stands: 'There is now no condemnation for those who are in Christ Jesus.'",
  },
  {
    id: "w4i-24-3-1",
    assessmentId: "w4a-24-3",
    question: "According to Hebrews 10:19-22, with what attitude should believers approach God's presence?",
    options: [
      "With fear and trembling, hoping to be accepted",
      "With boldness and full assurance of faith",
      "With uncertainty, since no one can know if they are accepted",
      "With indifference, since the outcome is already determined"
    ],
    correctIndex: 1,
    explanation: "Hebrews 10:19-22 invites believers to enter God's presence with 'boldness' and 'a true heart in full assurance of faith.' Christ's sacrifice and priesthood provide the basis for confident access to God.",
  },
  {
    id: "w4i-24-3-2",
    assessmentId: "w4a-24-3",
    question: "What does 1 John 2:1-2 call Jesus in relation to believers who sin?",
    options: [
      "An impartial Judge who records every failure",
      "An Advocate with the Father and the propitiation for our sins",
      "A distant observer who watches but does not intervene",
      "A harsh disciplinarian who punishes every transgression"
    ],
    correctIndex: 1,
    explanation: "John writes, 'If anyone sins, we have an Advocate with the Father, Jesus Christ the righteous. And He Himself is the propitiation for our sins' (1 John 2:1-2). Christ defends believers based on His own sacrifice.",
  },
  {
    id: "w4i-24-3-3",
    assessmentId: "w4a-24-3",
    question: "In Romans 8:33-34, what silences every accusation against God's people?",
    options: [
      "Their own righteous deeds and good character",
      "The testimony of other believers on their behalf",
      "Christ's death, resurrection, and ongoing intercession at God's right hand",
      "The passage of time, which erases the record of sin"
    ],
    correctIndex: 2,
    explanation: "Paul answers: 'It is Christ who died, and furthermore is also risen, who is even at the right hand of God, who also makes intercession for us' (Romans 8:34). Christ's complete work — death, resurrection, intercession — is the answer to every charge.",
  },
  {
    id: "w4i-24-3-4",
    assessmentId: "w4a-24-3",
    question: "How does the first angel's message in Revelation 14:6-7 combine judgment and gospel?",
    options: [
      "It presents judgment as replacing the gospel in the last days",
      "It announces the everlasting gospel and the hour of judgment together as one unified message",
      "It warns that the gospel period has ended and only judgment remains",
      "It separates judgment and gospel into two different time periods"
    ],
    correctIndex: 1,
    explanation: "Revelation 14:6-7 presents the 'everlasting gospel' and 'the hour of His judgment has come' in the same angelic message. Judgment and gospel are not opposed; they belong together.",
  },
  {
    id: "w4i-24-3-5",
    assessmentId: "w4a-24-3",
    question: "A believer tells you, 'I know Jesus died for me, but I still feel too guilty to pray.' What truth from Christ's heavenly ministry would you share?",
    options: [
      "You should feel guilty — that means the Holy Spirit is convicting you",
      "Stop praying until you feel worthy enough to approach God",
      "Christ is your High Priest right now, interceding for you — Hebrews 4:16 invites you to come boldly to the throne of grace, not because you are worthy but because He is",
      "Guilt is a sign that you have not been forgiven yet"
    ],
    correctIndex: 2,
    explanation: "Hebrews 4:14-16 reveals that Christ is a sympathetic High Priest who invites believers to approach God's throne with confidence. Access to God is based on Christ's worthiness, not ours.",
  },
  {
    id: "w4i-24-4-1",
    assessmentId: "w4a-24-4",
    question: "What is the most common objection to the heavenly sanctuary doctrine?",
    options: [
      "That the earthly tabernacle was never built",
      "That Christ's work was fully completed at the cross, making heavenly ministry unnecessary",
      "That Hebrews does not mention a heavenly sanctuary",
      "That the Day of Atonement was not part of the Levitical system"
    ],
    correctIndex: 1,
    explanation: "The most common objection claims that 'It is finished' (John 19:30) means no further ministry is needed. However, Hebrews extensively teaches that Christ's priestly ministry continues in heaven, applying the benefits of the completed sacrifice.",
  },
  {
    id: "w4i-24-4-2",
    assessmentId: "w4a-24-4",
    question: "How does Hebrews 10:12-14 describe the relationship between Christ's single sacrifice and ongoing sanctification?",
    options: [
      "The sacrifice was incomplete and needs to be repeated",
      "By one offering He has perfected forever those who are being sanctified",
      "The sacrifice only applies to people who lived before the cross",
      "Sanctification happens independently of Christ's sacrifice"
    ],
    correctIndex: 1,
    explanation: "Hebrews 10:14 teaches that 'by one offering He has perfected forever those who are being sanctified.' The single sacrifice is complete; its application to believers' lives (sanctification) is ongoing.",
  },
  {
    id: "w4i-24-4-3",
    assessmentId: "w4a-24-4",
    question: "According to Revelation 20:12, what is the basis of the final judgment?",
    options: [
      "Random selection by God",
      "According to their works as recorded in the books",
      "According to their social status and wealth",
      "According to the denomination they belonged to"
    ],
    correctIndex: 1,
    explanation: "Revelation 20:12 states that 'the dead were judged according to their works, by the things which were written in the books.' Works serve as evidence of genuine faith, not as the basis of earning salvation.",
  },
  {
    id: "w4i-24-4-4",
    assessmentId: "w4a-24-4",
    question: "How do assurance of salvation (Romans 8:1) and the reality of judgment (2 Corinthians 5:10) fit together?",
    options: [
      "They are contradictory — you must choose one or the other",
      "Assurance applies only before the judgment begins, then it is revoked",
      "They describe different dimensions of one reality — no condemnation for those in Christ, yet all appear before Christ's judgment seat",
      "Judgment applies only to unbelievers, so assurance and judgment never overlap"
    ],
    correctIndex: 2,
    explanation: "Scripture holds both truths: no condemnation for those in Christ (Romans 8:1) and all appearing before the judgment seat (2 Corinthians 5:10). Believers face judgment not as condemned defendants but as those whose Advocate has already secured the verdict.",
  },
  {
    id: "w4i-24-4-5",
    assessmentId: "w4a-24-4",
    question: "Someone says, 'The heavenly sanctuary is just a metaphor — there is no literal place in heaven.' How would you respond from Hebrews?",
    options: [
      "You are correct — Hebrews uses only symbolic language",
      "Hebrews 9:24 states that Christ entered heaven itself to appear in the presence of God for us, treating the heavenly sanctuary as a genuine reality",
      "The Bible does not address whether the sanctuary is real or symbolic",
      "Only the earthly tabernacle was real; everything else is figurative"
    ],
    correctIndex: 1,
    explanation: "Hebrews 9:24 directly states that Christ entered 'heaven itself, now to appear in the presence of God for us.' The author of Hebrews treats the heavenly sanctuary not as a metaphor but as the genuine reality of which the earthly was only a copy.",
  },
];
