// Seeded morning-reflection copy for the Home hero. Human-written lines kept in
// the app, not generated when the screen opens. One entry is shown per local
// day, in order. The same line returns after one full pass of the pool.

export interface DailyReflection {
  thought: string;
  reference: string;
}

export const DAILY_REFLECTIONS: DailyReflection[] = [
  { thought: "Grace is not a doctrine to be memorised but a Person to be embraced. Today, let Christ's unmerited favour reshape every anxious thought.", reference: "Ephesians 2:8-9" },
  { thought: "The cross does not merely pardon the past; it empowers the present. Walk today in the strength of the One who conquered death.", reference: "Galatians 2:20" },
  { thought: "Sabbath rest is heaven's rhythm set in time — a weekly reminder that our worth is not in what we produce but in Whose we are.", reference: "Exodus 20:8-11" },
  { thought: "Prayer is not convincing God to act; it is aligning our hearts with the One who is already working all things for good.", reference: "Romans 8:28" },
  { thought: "When we behold Christ, we become like Him — not by straining to imitate, but by gazing until His character becomes our own.", reference: "2 Corinthians 3:18" },
  { thought: "Hope is not wishful thinking. It is the anchor of the soul, fastened to the promise of a God who cannot lie.", reference: "Hebrews 6:19" },
  { thought: "Love your neighbour not because they deserve it, but because you have been loved beyond all deserving. Grace received becomes grace given.", reference: "1 John 4:19" },
  { thought: "The Lord is near to the broken-hearted. Bring Him the weight you cannot name, and let His nearness be enough for this hour.", reference: "Psalm 34:18" },
  { thought: "Faith is taking God at His word when the path is still dark. One step in trust is enough light for today.", reference: "2 Corinthians 5:7" },
  { thought: "The Word is a lamp, not a floodlight. It shows the next step, and that is the mercy.", reference: "Psalm 119:105" },
  { thought: "Do not be afraid, for the Lord your God goes with you. His presence is the promise that outlasts the trouble.", reference: "Deuteronomy 31:8" },
  { thought: "Mercy is new this morning. Yesterday's failure does not get the last word over today's grace.", reference: "Lamentations 3:22-23" },
  { thought: "Seek first the kingdom, and let the rest take its place. What you chase will shape the day.", reference: "Matthew 6:33" },
  { thought: "Be still, and know that He is God. Silence is not emptiness when He is the one who fills it.", reference: "Psalm 46:10" },
  { thought: "Cast your care on Him, because He cares for you. Anxiety was never meant to be carried alone.", reference: "1 Peter 5:7" },
  { thought: "The joy of the Lord is strength for ordinary hours, not only for the days that feel triumphant.", reference: "Nehemiah 8:10" },
  { thought: "Trust in the Lord with all your heart. Your own understanding is a poor map for a God who sees the end.", reference: "Proverbs 3:5-6" },
  { thought: "Christ in you is the hope of glory. The life you need is not borrowed from tomorrow; it is His, given now.", reference: "Colossians 1:27" },
  { thought: "Forgive as you have been forgiven. The mercy you withhold is the mercy you have forgotten.", reference: "Colossians 3:13" },
  { thought: "The Lord is my shepherd. You are not required to be your own guide through the valley.", reference: "Psalm 23:1" },
  { thought: "Let the peace of Christ rule in your heart. Peace is a governor, not a mood you must manufacture.", reference: "Colossians 3:15" },
  { thought: "God is our refuge and strength, a very present help. He is not late to the trouble you are in.", reference: "Psalm 46:1" },
  { thought: "Walk in the light, as He is in the light. Hidden things lose their power when they are brought to Him.", reference: "1 John 1:7" },
  { thought: "The Lord will fight for you; you need only be still. Some battles are won by refusing to panic.", reference: "Exodus 14:14" },
  { thought: "Rejoice in hope, be patient in trouble, and keep praying. These three hold a day together.", reference: "Romans 12:12" },
  { thought: "Jesus is the same yesterday, today, and forever. Your changing feelings do not change His faithfulness.", reference: "Hebrews 13:8" },
  { thought: "Draw near to God, and He will draw near to you. Distance is not His preference.", reference: "James 4:8" },
  { thought: "The Lord bless you and keep you. His face turned toward you is the good you cannot earn.", reference: "Numbers 6:24-26" },
  { thought: "Abide in Me, He says. Fruit is the result of remaining, not of frantic effort.", reference: "John 15:4" },
  { thought: "My grace is sufficient for you. The weakness you resent may be the place His strength is seen.", reference: "2 Corinthians 12:9" },
  { thought: "The name of the Lord is a strong tower. Run into it before you try to outrun the day.", reference: "Proverbs 18:10" },
  { thought: "He who began a good work in you will carry it on. You are unfinished, and that is not failure.", reference: "Philippians 1:6" },
  { thought: "Give thanks in all circumstances. Gratitude does not deny pain; it refuses to let pain be the only voice.", reference: "1 Thessalonians 5:18" },
  { thought: "The Lord is my light and my salvation. Fear loses its claim when He is the one you look to.", reference: "Psalm 27:1" },
  { thought: "Love is patient and kind. Today, let that be more than a reading; let it be how you answer someone.", reference: "1 Corinthians 13:4" },
  { thought: "Come to Me, all who labour. The invitation is for the tired, and it still stands this morning.", reference: "Matthew 11:28-29" },
  { thought: "I can do all things through Christ who strengthens me. The 'all things' is His strength, not your reserve.", reference: "Philippians 4:13" },
  { thought: "Be kind to one another, tender-hearted, forgiving. The church is built of such ordinary mercies.", reference: "Ephesians 4:32" },
  { thought: "In quietness and trust is your strength. Hurry is a poor counsellor.", reference: "Isaiah 30:15" },
  { thought: "He heals the broken-hearted and binds up their wounds. Healing is His work, and He is not careless with yours.", reference: "Psalm 147:3" },
  { thought: "Let your light shine before others. A hidden kindness is still a light someone needed.", reference: "Matthew 5:16" },
  { thought: "The Lord upholds all who fall. Stumbling is not the end of His hold on you.", reference: "Psalm 145:14" },
  { thought: "Do not worry about tomorrow. Today has its own grace, and He has not given you tomorrow's yet.", reference: "Matthew 6:34" },
  { thought: "The Lord is good, a stronghold in the day of trouble. He knows those who take refuge in Him.", reference: "Nahum 1:7" },
  { thought: "Blessed are the peacemakers. Peace-making begins with the words you choose before the conflict grows.", reference: "Matthew 5:9" },
  { thought: "God so loved the world that He gave His Son. Love, in Him, is a gift before it is a demand.", reference: "John 3:16" },
  { thought: "Be strong and courageous. The command comes with a promise: He will not leave you.", reference: "Joshua 1:9" },
  { thought: "Those who wait on the Lord renew their strength. Waiting is not wasting when He is the one you wait for.", reference: "Isaiah 40:31" },
  { thought: "The fruit of the Spirit is love, joy, and peace. These grow where His life is welcomed, not where you strain.", reference: "Galatians 5:22" },
  { thought: "Humble yourselves under the mighty hand of God. Humility is safe because His hand is the one over you.", reference: "1 Peter 5:6" },
  { thought: "I have loved you with an everlasting love. His affection for you did not start when you improved.", reference: "Jeremiah 31:3" },
  { thought: "Let us not grow weary in doing good. The harvest comes in its season, and today is part of the sowing.", reference: "Galatians 6:9" },
  { thought: "Create in me a clean heart. Confession is how a day begins again without pretending.", reference: "Psalm 51:10" },
  { thought: "Jesus said, I am the way, the truth, and the life. Direction, honesty, and life are a Person.", reference: "John 14:6" },
  { thought: "The peace of God will guard your heart and mind. Peace is a sentry, not a feeling you must hold in place.", reference: "Philippians 4:7" },
  { thought: "Taste and see that the Lord is good. Faith deepens when you take Him at His word in something small today.", reference: "Psalm 34:8" },
  { thought: "Bear one another's burdens. Someone near you is carrying more than they have said.", reference: "Galatians 6:2" },
  { thought: "The Lord your God is with you, the Mighty One who saves. He rejoices over you, even on an ordinary day.", reference: "Zephaniah 3:17" },
  { thought: "Ask, and it will be given. Prayer is welcome in the throne room, not an interruption.", reference: "Matthew 7:7" },
  { thought: "He has shown you what is good: to do justly, love mercy, and walk humbly with your God.", reference: "Micah 6:8" },
  { thought: "The Lord is my portion. When other things are thin, He is still the inheritance.", reference: "Lamentations 3:24" },
  { thought: "Encourage one another daily. A true word, spoken in time, can keep a heart from hardening.", reference: "Hebrews 3:13" },
  { thought: "God is light, and in Him is no darkness at all. Bring the day into that light before you edit it.", reference: "1 John 1:5" },
  { thought: "I will never leave you nor forsake you. Absence is not one of His ways with His own.", reference: "Hebrews 13:5" },
  { thought: "The mouth speaks what the heart is full of. Guard the spring, and the words will follow.", reference: "Luke 6:45" },
  { thought: "Commit your work to the Lord, and your plans will be established. Offer the day before you manage it.", reference: "Proverbs 16:3" },
  { thought: "You are God's workmanship, created in Christ Jesus for good works. You were made for more than survival.", reference: "Ephesians 2:10" },
  { thought: "The Lord hears when I call. Prayer is not sent into silence.", reference: "Psalm 4:3" },
  { thought: "The Lord opens the eyes of the blind. Ask Him to show you what you have been walking past.", reference: "Psalm 146:8" },
  { thought: "Rejoice always. Joy is a decision to remember who holds the day, not a denial of what the day holds.", reference: "Philippians 4:4" },
  { thought: "He leads me beside still waters. Rest is on the path, not only at the end of it.", reference: "Psalm 23:2" },
  { thought: "If we confess our sins, He is faithful and just to forgive. Honesty is met with mercy, not with a lecture.", reference: "1 John 1:9" },
  { thought: "The Lord gives strength to His people. Ask for the strength of this hour, not for a lifetime in advance.", reference: "Psalm 29:11" },
  { thought: "Blessed are those who hunger and thirst for righteousness. The appetite itself is a gift from Him.", reference: "Matthew 5:6" },
  { thought: "I am with you always, to the end of the age. The promise covers this morning, not only the last day.", reference: "Matthew 28:20" },
  { thought: "A gentle answer turns away wrath. You can lower the temperature of a room with one unhurried sentence.", reference: "Proverbs 15:1" },
  { thought: "The Lord is close to all who call on Him in truth. Pretending is not required for prayer.", reference: "Psalm 145:18" },
  { thought: "We are more than conquerors through Him who loved us. The victory is His love, not your winning streak.", reference: "Romans 8:37" },
  { thought: "Remember the Sabbath day, to keep it holy. Rest tells the truth that God can hold the world without your labour.", reference: "Exodus 20:8" },
  { thought: "The Spirit helps us in our weakness. When you do not know what to pray, He is not waiting for better words.", reference: "Romans 8:26" },
  { thought: "Fix your eyes on Jesus, the author and finisher of faith. Look up before you look around.", reference: "Hebrews 12:2" },
  { thought: "The Lord will keep your going out and your coming in. Ordinary doors are under His care.", reference: "Psalm 121:8" },
  { thought: "Love your enemies, and pray for those who mistreat you. Prayer is how enmity loses its grip on you.", reference: "Matthew 5:44" },
  { thought: "God is able to do far more than we ask or imagine. Leave room in the day for a goodness you did not plan.", reference: "Ephesians 3:20" },
];
