// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/gtf-light/AccentOptions.tsx": () => import("../components/mockups/gtf-light/AccentOptions.tsx"),
  "./components/mockups/gtf-light/Home.tsx": () => import("../components/mockups/gtf-light/Home.tsx"),
  "./components/mockups/home-layouts/HomeRhythmSpine.tsx": () => import("../components/mockups/home-layouts/HomeRhythmSpine.tsx")
};
