/**
 * Renders docs/legal/*.md into lib/legal/generated.ts and public HTML templates.
 * Markdown stays the single source. Run: npx tsx scripts/render-legal-docs.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import {
  legalDocumentToHtml,
  parseLegalMarkdown,
  stripDraftingNotes,
  type LegalDocument,
} from "../lib/legal/parse-legal-markdown";

const ROOT = path.resolve(process.cwd());
const TERMS_MD = path.join(ROOT, "docs/legal/informed-ministries-terms-of-use.md");
const PRIVACY_MD = path.join(ROOT, "docs/legal/informed-ministries-privacy-policy.md");

function load(docPath: string): { markdown: string; doc: LegalDocument } {
  const raw = readFileSync(docPath, "utf8");
  const markdown = stripDraftingNotes(raw);
  if (/Drafting notes for review/i.test(markdown)) {
    throw new Error(`Drafting notes leaked into rendered markdown: ${docPath}`);
  }
  if (!/Draft for legal review/i.test(markdown)) {
    throw new Error(`Missing draft banner in ${docPath}`);
  }
  return { markdown, doc: parseLegalMarkdown(raw) };
}

function tsLiteral(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

const terms = load(TERMS_MD);
const privacy = load(PRIVACY_MD);

const generated = `/* Generated by scripts/render-legal-docs.ts — do not edit. */
import type { LegalDocument } from "./parse-legal-markdown";

export const LEGAL_TERMS_MARKDOWN = ${tsLiteral(terms.markdown)} as const;

export const LEGAL_PRIVACY_MARKDOWN = ${tsLiteral(privacy.markdown)} as const;

export const LEGAL_TERMS: LegalDocument = ${tsLiteral(terms.doc)} as LegalDocument;

export const LEGAL_PRIVACY: LegalDocument = ${tsLiteral(privacy.doc)} as LegalDocument;
`;

writeFileSync(path.join(ROOT, "lib/legal/generated.ts"), generated, "utf8");

writeFileSync(
  path.join(ROOT, "server/templates/terms.html"),
  legalDocumentToHtml(terms.doc, {
    pageTitle: "Terms of Use — Informed Ministries",
    description:
      "Terms of Use for the Informed Ministries app. Draft for legal review — not yet in force.",
    canonicalPath: "/terms",
    siblingHref: "/privacy",
    siblingLabel: "Privacy Policy",
  }),
  "utf8",
);

writeFileSync(
  path.join(ROOT, "server/templates/privacy.html"),
  legalDocumentToHtml(privacy.doc, {
    pageTitle: "Privacy Policy — Informed Ministries",
    description:
      "Privacy Policy for the Informed Ministries app. Draft for legal review — not yet in force.",
    canonicalPath: "/privacy",
    siblingHref: "/terms",
    siblingLabel: "Terms of Use",
  }),
  "utf8",
);

console.log("[legal] rendered terms + privacy from docs/legal");
