import { db } from "../server/db";
import { sdaChurches } from "../shared/schema";

interface ChurchSeed {
  name: string;
  address: string;
  city: string;
  state: string | null;
  country: string;
  lat: string;
  lng: string;
  serviceTimes: string;
  contactPhone: string | null;
  contactEmail: string | null;
  website: string | null;
  pastorName: string | null;
  membershipSize: string;
}

const GLOBAL_CHURCHES: ChurchSeed[] = [
  // ─── NORTH AMERICA ───────────────────────────────────────────────────
  {
    name: "General Conference of Seventh-day Adventists",
    address: "12501 Old Columbia Pike",
    city: "Silver Spring",
    state: "Maryland",
    country: "United States",
    lat: "39.0458",
    lng: "-76.9605",
    serviceTimes: "Saturday 9:30 AM & 11:00 AM",
    contactPhone: "+1-301-680-6000",
    contactEmail: null,
    website: "https://www.adventist.org",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Oakwood University Church",
    address: "5500 Adventist Blvd NW",
    city: "Huntsville",
    state: "Alabama",
    country: "United States",
    lat: "34.7161",
    lng: "-86.5680",
    serviceTimes: "Saturday 8:30 AM & 11:00 AM",
    contactPhone: "+1-256-726-7000",
    contactEmail: null,
    website: "https://www.oakwood.edu",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Loma Linda University Church",
    address: "11125 Campus St",
    city: "Loma Linda",
    state: "California",
    country: "United States",
    lat: "34.0500",
    lng: "-117.2615",
    serviceTimes: "Saturday 9:00 AM & 11:45 AM",
    contactPhone: "+1-909-558-4570",
    contactEmail: null,
    website: "https://www.lluc.org",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Pioneer Memorial Church",
    address: "8655 University Blvd",
    city: "Berrien Springs",
    state: "Michigan",
    country: "United States",
    lat: "41.9547",
    lng: "-86.3589",
    serviceTimes: "Saturday 9:00 AM & 11:45 AM",
    contactPhone: "+1-269-471-3133",
    contactEmail: null,
    website: "https://www.pmchurch.org",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Collegedale Church of Seventh-day Adventists",
    address: "4829 College Dr E",
    city: "Collegedale",
    state: "Tennessee",
    country: "United States",
    lat: "35.0502",
    lng: "-85.0506",
    serviceTimes: "Saturday 9:15 AM & 11:30 AM",
    contactPhone: "+1-423-396-2134",
    contactEmail: null,
    website: "https://www.collegedalechurch.com",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Kingsway College SDA Church",
    address: "1200 Leland Rd",
    city: "Oshawa",
    state: "Ontario",
    country: "Canada",
    lat: "43.9451",
    lng: "-78.8659",
    serviceTimes: "Saturday 9:30 AM & 11:00 AM",
    contactPhone: "+1-905-433-1144",
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Toronto West SDA Church",
    address: "20 Panorama Ct",
    city: "Toronto",
    state: "Ontario",
    country: "Canada",
    lat: "43.7469",
    lng: "-79.5927",
    serviceTimes: "Saturday 9:30 AM & 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  // ─── CENTRAL & SOUTH AMERICA ─────────────────────────────────────────
  {
    name: "Iglesia Adventista Central de la Ciudad de Mexico",
    address: "Calle Tokio 430, Portales",
    city: "Mexico City",
    state: "CDMX",
    country: "Mexico",
    lat: "19.3705",
    lng: "-99.1445",
    serviceTimes: "Sabado 9:00 AM & 11:30 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Igreja Adventista Central de Sao Paulo",
    address: "R. Funchal 400, Vila Olimpia",
    city: "Sao Paulo",
    state: "SP",
    country: "Brazil",
    lat: "-23.5883",
    lng: "-46.6892",
    serviceTimes: "Sabado 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: "https://www.adventistas.org",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Igreja Adventista do Setimo Dia - Sede Sul-Americana",
    address: "Rodovia SP-127 Km 106",
    city: "Tatui",
    state: "SP",
    country: "Brazil",
    lat: "-23.3503",
    lng: "-47.8568",
    serviceTimes: "Sabado 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: "https://www.adventistas.org",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Iglesia Adventista Central de Lima",
    address: "Jr. Ica 371, Cercado de Lima",
    city: "Lima",
    state: null,
    country: "Peru",
    lat: "-12.0521",
    lng: "-77.0318",
    serviceTimes: "Sabado 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Iglesia Adventista de Montemorelos",
    address: "Universidad de Montemorelos",
    city: "Montemorelos",
    state: "Nuevo Leon",
    country: "Mexico",
    lat: "25.1872",
    lng: "-99.8299",
    serviceTimes: "Sabado 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Iglesia Adventista Central de Buenos Aires",
    address: "Av. Donado 4350, Villa Urquiza",
    city: "Buenos Aires",
    state: null,
    country: "Argentina",
    lat: "-34.5714",
    lng: "-58.4853",
    serviceTimes: "Sabado 9:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Iglesia Adventista Central de Bogota",
    address: "Calle 74A No. 22-31",
    city: "Bogota",
    state: null,
    country: "Colombia",
    lat: "4.6652",
    lng: "-74.0665",
    serviceTimes: "Sabado 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Caribbean Union Conference SDA Church",
    address: "Eastern Main Rd, Maraval",
    city: "Port of Spain",
    state: null,
    country: "Trinidad and Tobago",
    lat: "10.6778",
    lng: "-61.5332",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Kingston Central SDA Church",
    address: "7 West Ave, Kingston 4",
    city: "Kingston",
    state: null,
    country: "Jamaica",
    lat: "18.0132",
    lng: "-76.7928",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "large",
  },
  // ─── AFRICA ──────────────────────────────────────────────────────────
  {
    name: "Nairobi Central SDA Church",
    address: "Milimani Rd",
    city: "Nairobi",
    state: null,
    country: "Kenya",
    lat: "-1.2870",
    lng: "36.8075",
    serviceTimes: "Saturday 8:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "East-Central Africa Division Office Church",
    address: "Milimani Rd, Upperhill",
    city: "Nairobi",
    state: null,
    country: "Kenya",
    lat: "-1.2960",
    lng: "36.8186",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: "https://www.ecd.adventist.org",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Babcock University SDA Church",
    address: "Babcock University Campus",
    city: "Ilishan-Remo",
    state: "Ogun",
    country: "Nigeria",
    lat: "6.8970",
    lng: "3.7112",
    serviceTimes: "Saturday 8:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: "https://www.babcock.edu.ng",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Accra Central SDA Church",
    address: "Castle Rd, Adabraka",
    city: "Accra",
    state: null,
    country: "Ghana",
    lat: "5.5617",
    lng: "-0.2110",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Kampala Central SDA Church",
    address: "Buganda Rd",
    city: "Kampala",
    state: null,
    country: "Uganda",
    lat: "0.3156",
    lng: "32.5832",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Southern Africa-Indian Ocean Division",
    address: "Willowbrook Office Park",
    city: "Johannesburg",
    state: "Gauteng",
    country: "South Africa",
    lat: "-26.0930",
    lng: "28.0183",
    serviceTimes: "Saturday 9:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: "https://sid.adventist.org",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Helderberg College SDA Church",
    address: "Helderberg College Campus",
    city: "Somerset West",
    state: "Western Cape",
    country: "South Africa",
    lat: "-34.0793",
    lng: "18.8758",
    serviceTimes: "Saturday 9:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Dar es Salaam Central SDA Church",
    address: "Kisutu St",
    city: "Dar es Salaam",
    state: null,
    country: "Tanzania",
    lat: "-6.8147",
    lng: "39.2838",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Lusaka Central SDA Church",
    address: "Church Rd, Longacres",
    city: "Lusaka",
    state: null,
    country: "Zambia",
    lat: "-15.4022",
    lng: "28.2878",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Antananarivo Central SDA Church",
    address: "Rue Rainandriamampandry",
    city: "Antananarivo",
    state: null,
    country: "Madagascar",
    lat: "-18.9143",
    lng: "47.5278",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Harare Central SDA Church",
    address: "Corner Second St & Selous Ave",
    city: "Harare",
    state: null,
    country: "Zimbabwe",
    lat: "-17.8277",
    lng: "31.0496",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  // ─── EUROPE ──────────────────────────────────────────────────────────
  {
    name: "Stanborough Park SDA Church",
    address: "609 St Albans Rd",
    city: "Watford",
    state: "Hertfordshire",
    country: "United Kingdom",
    lat: "51.6841",
    lng: "-0.3963",
    serviceTimes: "Saturday 9:30 AM & 11:15 AM",
    contactPhone: "+44-1923-672251",
    contactEmail: null,
    website: "https://www.stanboroughchurch.org",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Advent Centre London",
    address: "39 Brendon St, Marylebone",
    city: "London",
    state: null,
    country: "United Kingdom",
    lat: "51.5165",
    lng: "-0.1683",
    serviceTimes: "Saturday 10:00 AM & 11:30 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Friedensau Adventist University Church",
    address: "An der Ihle 19",
    city: "Friedensau",
    state: "Saxony-Anhalt",
    country: "Germany",
    lat: "52.0819",
    lng: "11.8098",
    serviceTimes: "Samstag 9:30 & 11:00",
    contactPhone: null,
    contactEmail: null,
    website: "https://www.thh-friedensau.de",
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Eglise Adventiste de Paris-Sud",
    address: "130 Bd de l'Hopital",
    city: "Paris",
    state: null,
    country: "France",
    lat: "48.8386",
    lng: "2.3598",
    serviceTimes: "Samedi 9:30 & 11:00",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Adventkirche Zurich",
    address: "Wolframplatz 11",
    city: "Zurich",
    state: null,
    country: "Switzerland",
    lat: "47.3900",
    lng: "8.5188",
    serviceTimes: "Samstag 9:30 & 11:00",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "small",
  },
  {
    name: "Roma Adventist Church",
    address: "Lungotevere Michelangelo 7",
    city: "Rome",
    state: null,
    country: "Italy",
    lat: "41.9115",
    lng: "12.4630",
    serviceTimes: "Sabato 9:30 & 11:00",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "small",
  },
  {
    name: "Adventistkirken Oslo",
    address: "Urtegata 16",
    city: "Oslo",
    state: null,
    country: "Norway",
    lat: "59.9115",
    lng: "10.7655",
    serviceTimes: "Saturday 10:00 AM & 11:30 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "small",
  },
  {
    name: "Bucharest Central SDA Church",
    address: "Str. Popa Tatu 50",
    city: "Bucharest",
    state: null,
    country: "Romania",
    lat: "44.4430",
    lng: "26.0893",
    serviceTimes: "Saturday 9:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "large",
  },
  // ─── ASIA-PACIFIC ────────────────────────────────────────────────────
  {
    name: "Central Philippine Adventist College Church",
    address: "Murcia",
    city: "Bacolod",
    state: "Negros Occidental",
    country: "Philippines",
    lat: "10.5952",
    lng: "122.9751",
    serviceTimes: "Saturday 8:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Manila Central SDA Church",
    address: "953 Gen. Luna St, Ermita",
    city: "Manila",
    state: null,
    country: "Philippines",
    lat: "14.5839",
    lng: "120.9795",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Southern Asia-Pacific Division Office Church",
    address: "Silang",
    city: "Cavite",
    state: null,
    country: "Philippines",
    lat: "14.2189",
    lng: "120.9747",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: "https://ssd.adventist.org",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Seoul SDA Central Church",
    address: "12 Hoehyeon-ro, Jung-gu",
    city: "Seoul",
    state: null,
    country: "South Korea",
    lat: "37.5590",
    lng: "126.9855",
    serviceTimes: "Saturday 9:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Sahmyook University SDA Church",
    address: "815 Hwarang-ro, Nowon-gu",
    city: "Seoul",
    state: null,
    country: "South Korea",
    lat: "37.6420",
    lng: "127.0985",
    serviceTimes: "Saturday 9:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: "https://www.syu.ac.kr",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Avondale Memorial SDA Church",
    address: "582 Freemans Dr",
    city: "Cooranbong",
    state: "New South Wales",
    country: "Australia",
    lat: "-33.0748",
    lng: "151.4566",
    serviceTimes: "Saturday 9:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Wahroonga SDA Church",
    address: "Fox Valley Rd",
    city: "Wahroonga",
    state: "New South Wales",
    country: "Australia",
    lat: "-33.7173",
    lng: "151.1170",
    serviceTimes: "Saturday 9:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Saniku Gakuin SDA Church",
    address: "1500 Aoba-cho",
    city: "Chiba",
    state: "Chiba",
    country: "Japan",
    lat: "35.6290",
    lng: "140.1602",
    serviceTimes: "Saturday 9:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Jakarta Central SDA Church",
    address: "Jl. Kwitang Raya No. 3",
    city: "Jakarta",
    state: null,
    country: "Indonesia",
    lat: "-6.1862",
    lng: "106.8433",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Spicer Adventist University Church",
    address: "Aundh Rd, Ganeshkhind",
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    lat: "18.5569",
    lng: "73.8127",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: "https://www.spicer.edu.in",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Yangon Central SDA Church",
    address: "65 U Wisara Rd",
    city: "Yangon",
    state: null,
    country: "Myanmar",
    lat: "16.8615",
    lng: "96.1535",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Auckland Central SDA Church",
    address: "290 Manukau Rd, Epsom",
    city: "Auckland",
    state: null,
    country: "New Zealand",
    lat: "-36.8871",
    lng: "174.7702",
    serviceTimes: "Saturday 9:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Suva Central SDA Church",
    address: "Amy St, Suva",
    city: "Suva",
    state: null,
    country: "Fiji",
    lat: "-18.1416",
    lng: "178.4419",
    serviceTimes: "Saturday 9:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Papua New Guinea Union Mission Church",
    address: "Lae Mission Compound",
    city: "Lae",
    state: "Morobe",
    country: "Papua New Guinea",
    lat: "-6.7305",
    lng: "147.0040",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "large",
  },
  // ─── MIDDLE EAST ─────────────────────────────────────────────────────
  {
    name: "Middle East and North Africa Union SDA Church",
    address: "Antelias",
    city: "Beirut",
    state: null,
    country: "Lebanon",
    lat: "33.9044",
    lng: "35.5297",
    serviceTimes: "Saturday 10:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "small",
  },
  // ─── INTER-AMERICA ──────────────────────────────────────────────────
  {
    name: "Inter-American Division SDA Church",
    address: "8100 NW 19th St",
    city: "Miami",
    state: "Florida",
    country: "United States",
    lat: "25.8430",
    lng: "-80.2973",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: "https://interamerica.org",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Iglesia Adventista Central de Santo Domingo",
    address: "Av. Romulo Betancourt",
    city: "Santo Domingo",
    state: null,
    country: "Dominican Republic",
    lat: "18.4655",
    lng: "-69.9300",
    serviceTimes: "Sabado 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Eglise Adventiste Centrale de Port-au-Prince",
    address: "Rue Pavee",
    city: "Port-au-Prince",
    state: null,
    country: "Haiti",
    lat: "18.5425",
    lng: "-72.3388",
    serviceTimes: "Samedi 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "large",
  },
  // ─── EAST ASIA ───────────────────────────────────────────────────────
  {
    name: "Hong Kong-Macao Conference SDA Church",
    address: "17 Ventris Rd, Happy Valley",
    city: "Hong Kong",
    state: null,
    country: "Hong Kong",
    lat: "22.2685",
    lng: "114.1835",
    serviceTimes: "Saturday 9:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Taiwan Adventist Hospital Church",
    address: "424 Ba De Rd, Sec 2",
    city: "Taipei",
    state: null,
    country: "Taiwan",
    lat: "25.0487",
    lng: "121.5580",
    serviceTimes: "Saturday 9:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
];

export async function seedGlobalChurches() {
  try {
    const existing = await db.select({ name: sdaChurches.name, country: sdaChurches.country }).from(sdaChurches);
    const existingKeys = new Set(
      existing.map((c) => `${c.name.toLowerCase()}::${c.country.toLowerCase()}`)
    );

    const newChurches = GLOBAL_CHURCHES.filter(
      (c) => !existingKeys.has(`${c.name.toLowerCase()}::${c.country.toLowerCase()}`)
    );

    if (newChurches.length === 0) {
      console.log(`All ${GLOBAL_CHURCHES.length} global churches already present.`);
      return;
    }

    const values = newChurches.map((c) => ({
      name: c.name,
      address: c.address,
      city: c.city,
      state: c.state,
      country: c.country,
      lat: c.lat,
      lng: c.lng,
      serviceTimes: c.serviceTimes,
      contactPhone: c.contactPhone,
      contactEmail: c.contactEmail,
      website: c.website,
      pastorName: c.pastorName,
      membershipSize: c.membershipSize,
    }));

    await db.insert(sdaChurches).values(values);
    console.log(`Seeded ${newChurches.length} new churches (${existing.length + newChurches.length} total).`);
  } catch (err) {
    console.error("Error seeding churches:", err);
  }
}
