import { db } from "../server/db";
import { sdaChurches } from "../shared/schema";
import { eq, and } from "drizzle-orm";

interface ChurchSeed {
  name: string;
  address: string;
  city: string;
  state: string | null;
  country: string;
  lat: string;
  lng: string;
  serviceTimes: string;
  contactPhone: string | null;
  contactEmail: string | null;
  website: string | null;
  pastorName: string | null;
  membershipSize: string;
}

const GLOBAL_CHURCHES: ChurchSeed[] = [
  // ─── NORTH AMERICA ───────────────────────────────────────────────────
  {
    name: "General Conference of Seventh-day Adventists",
    address: "12501 Old Columbia Pike",
    city: "Silver Spring",
    state: "Maryland",
    country: "United States",
    lat: "39.0458",
    lng: "-76.9605",
    serviceTimes: "Saturday 9:30 AM & 11:00 AM",
    contactPhone: "+1-301-680-6000",
    contactEmail: null,
    website: "https://www.adventist.org",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Oakwood University Church",
    address: "5500 Adventist Blvd NW",
    city: "Huntsville",
    state: "Alabama",
    country: "United States",
    lat: "34.7161",
    lng: "-86.5680",
    serviceTimes: "Saturday 8:30 AM & 11:00 AM",
    contactPhone: "+1-256-726-7000",
    contactEmail: null,
    website: "https://www.oakwood.edu",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Loma Linda University Church",
    address: "11125 Campus St",
    city: "Loma Linda",
    state: "California",
    country: "United States",
    lat: "34.0500",
    lng: "-117.2615",
    serviceTimes: "Saturday 9:00 AM & 11:45 AM",
    contactPhone: "+1-909-558-4570",
    contactEmail: null,
    website: "https://www.lluc.org",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Pioneer Memorial Church",
    address: "8655 University Blvd",
    city: "Berrien Springs",
    state: "Michigan",
    country: "United States",
    lat: "41.9547",
    lng: "-86.3589",
    serviceTimes: "Saturday 9:00 AM & 11:45 AM",
    contactPhone: "+1-269-471-3133",
    contactEmail: null,
    website: "https://www.pmchurch.org",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Collegedale Church of Seventh-day Adventists",
    address: "4829 College Dr E",
    city: "Collegedale",
    state: "Tennessee",
    country: "United States",
    lat: "35.0502",
    lng: "-85.0506",
    serviceTimes: "Saturday 9:15 AM & 11:30 AM",
    contactPhone: "+1-423-396-2134",
    contactEmail: null,
    website: "https://www.collegedalechurch.com",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Kingsway College SDA Church",
    address: "1200 Leland Rd",
    city: "Oshawa",
    state: "Ontario",
    country: "Canada",
    lat: "43.9451",
    lng: "-78.8659",
    serviceTimes: "Saturday 9:30 AM & 11:00 AM",
    contactPhone: "+1-905-433-1144",
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Toronto West SDA Church",
    address: "20 Panorama Ct",
    city: "Toronto",
    state: "Ontario",
    country: "Canada",
    lat: "43.7469",
    lng: "-79.5927",
    serviceTimes: "Saturday 9:30 AM & 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  // ─── CENTRAL & SOUTH AMERICA ─────────────────────────────────────────
  {
    name: "Iglesia Adventista Central de la Ciudad de Mexico",
    address: "Calle Tokio 430, Portales",
    city: "Mexico City",
    state: "CDMX",
    country: "Mexico",
    lat: "19.3705",
    lng: "-99.1445",
    serviceTimes: "Sabado 9:00 AM & 11:30 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Igreja Adventista Central de Sao Paulo",
    address: "R. Funchal 400, Vila Olimpia",
    city: "Sao Paulo",
    state: "SP",
    country: "Brazil",
    lat: "-23.5883",
    lng: "-46.6892",
    serviceTimes: "Sabado 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: "https://www.adventistas.org",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Igreja Adventista do Setimo Dia - Sede Sul-Americana",
    address: "Rodovia SP-127 Km 106",
    city: "Tatui",
    state: "SP",
    country: "Brazil",
    lat: "-23.3503",
    lng: "-47.8568",
    serviceTimes: "Sabado 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: "https://www.adventistas.org",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Iglesia Adventista Central de Lima",
    address: "Jr. Ica 371, Cercado de Lima",
    city: "Lima",
    state: null,
    country: "Peru",
    lat: "-12.0521",
    lng: "-77.0318",
    serviceTimes: "Sabado 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Iglesia Adventista de Montemorelos",
    address: "Universidad de Montemorelos",
    city: "Montemorelos",
    state: "Nuevo Leon",
    country: "Mexico",
    lat: "25.1872",
    lng: "-99.8299",
    serviceTimes: "Sabado 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Iglesia Adventista Central de Buenos Aires",
    address: "Av. Donado 4350, Villa Urquiza",
    city: "Buenos Aires",
    state: null,
    country: "Argentina",
    lat: "-34.5714",
    lng: "-58.4853",
    serviceTimes: "Sabado 9:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Iglesia Adventista Central de Bogota",
    address: "Calle 74A No. 22-31",
    city: "Bogota",
    state: null,
    country: "Colombia",
    lat: "4.6652",
    lng: "-74.0665",
    serviceTimes: "Sabado 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Caribbean Union Conference SDA Church",
    address: "Eastern Main Rd, Maraval",
    city: "Port of Spain",
    state: null,
    country: "Trinidad and Tobago",
    lat: "10.6778",
    lng: "-61.5332",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Kingston Central SDA Church",
    address: "7 West Ave, Kingston 4",
    city: "Kingston",
    state: null,
    country: "Jamaica",
    lat: "18.0132",
    lng: "-76.7928",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "large",
  },
  // ─── AFRICA ──────────────────────────────────────────────────────────
  {
    name: "Nairobi Central SDA Church",
    address: "Milimani Rd",
    city: "Nairobi",
    state: null,
    country: "Kenya",
    lat: "-1.2870",
    lng: "36.8075",
    serviceTimes: "Saturday 8:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "East-Central Africa Division Office Church",
    address: "Milimani Rd, Upperhill",
    city: "Nairobi",
    state: null,
    country: "Kenya",
    lat: "-1.2960",
    lng: "36.8186",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: "https://www.ecd.adventist.org",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Babcock University SDA Church",
    address: "Babcock University Campus",
    city: "Ilishan-Remo",
    state: "Ogun",
    country: "Nigeria",
    lat: "6.8970",
    lng: "3.7112",
    serviceTimes: "Saturday 8:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: "https://www.babcock.edu.ng",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Accra Central SDA Church",
    address: "Castle Rd, Adabraka",
    city: "Accra",
    state: null,
    country: "Ghana",
    lat: "5.5617",
    lng: "-0.2110",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Kampala Central SDA Church",
    address: "Buganda Rd",
    city: "Kampala",
    state: null,
    country: "Uganda",
    lat: "0.3156",
    lng: "32.5832",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Southern Africa-Indian Ocean Division",
    address: "Willowbrook Office Park",
    city: "Johannesburg",
    state: "Gauteng",
    country: "South Africa",
    lat: "-26.0930",
    lng: "28.0183",
    serviceTimes: "Saturday 9:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: "https://sid.adventist.org",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Helderberg College SDA Church",
    address: "Helderberg College Campus",
    city: "Somerset West",
    state: "Western Cape",
    country: "South Africa",
    lat: "-34.0793",
    lng: "18.8758",
    serviceTimes: "Saturday 9:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Dar es Salaam Central SDA Church",
    address: "Kisutu St",
    city: "Dar es Salaam",
    state: null,
    country: "Tanzania",
    lat: "-6.8147",
    lng: "39.2838",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Lusaka Central SDA Church",
    address: "Church Rd, Longacres",
    city: "Lusaka",
    state: null,
    country: "Zambia",
    lat: "-15.4022",
    lng: "28.2878",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Antananarivo Central SDA Church",
    address: "Rue Rainandriamampandry",
    city: "Antananarivo",
    state: null,
    country: "Madagascar",
    lat: "-18.9143",
    lng: "47.5278",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Harare Central SDA Church",
    address: "Corner Second St & Selous Ave",
    city: "Harare",
    state: null,
    country: "Zimbabwe",
    lat: "-17.8277",
    lng: "31.0496",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  // ─── EUROPE ──────────────────────────────────────────────────────────
  {
    name: "Stanborough Park SDA Church",
    address: "609 St Albans Rd",
    city: "Watford",
    state: "Hertfordshire",
    country: "United Kingdom",
    lat: "51.6841",
    lng: "-0.3963",
    serviceTimes: "Saturday 9:30 AM & 11:15 AM",
    contactPhone: "+44-1923-672251",
    contactEmail: null,
    website: "https://www.stanboroughchurch.org",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Advent Centre London",
    address: "39 Brendon St, Marylebone",
    city: "London",
    state: null,
    country: "United Kingdom",
    lat: "51.5165",
    lng: "-0.1683",
    serviceTimes: "Saturday 10:00 AM & 11:30 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Friedensau Adventist University Church",
    address: "An der Ihle 19",
    city: "Friedensau",
    state: "Saxony-Anhalt",
    country: "Germany",
    lat: "52.0819",
    lng: "11.8098",
    serviceTimes: "Samstag 9:30 & 11:00",
    contactPhone: null,
    contactEmail: null,
    website: "https://www.thh-friedensau.de",
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Eglise Adventiste de Paris-Sud",
    address: "130 Bd de l'Hopital",
    city: "Paris",
    state: null,
    country: "France",
    lat: "48.8386",
    lng: "2.3598",
    serviceTimes: "Samedi 9:30 & 11:00",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Adventkirche Zurich",
    address: "Wolframplatz 11",
    city: "Zurich",
    state: null,
    country: "Switzerland",
    lat: "47.3900",
    lng: "8.5188",
    serviceTimes: "Samstag 9:30 & 11:00",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "small",
  },
  {
    name: "Roma Adventist Church",
    address: "Lungotevere Michelangelo 7",
    city: "Rome",
    state: null,
    country: "Italy",
    lat: "41.9115",
    lng: "12.4630",
    serviceTimes: "Sabato 9:30 & 11:00",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "small",
  },
  {
    name: "Adventistkirken Oslo",
    address: "Urtegata 16",
    city: "Oslo",
    state: null,
    country: "Norway",
    lat: "59.9115",
    lng: "10.7655",
    serviceTimes: "Saturday 10:00 AM & 11:30 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "small",
  },
  {
    name: "Bucharest Central SDA Church",
    address: "Str. Popa Tatu 50",
    city: "Bucharest",
    state: null,
    country: "Romania",
    lat: "44.4430",
    lng: "26.0893",
    serviceTimes: "Saturday 9:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "large",
  },
  // ─── ASIA-PACIFIC ────────────────────────────────────────────────────
  {
    name: "Central Philippine Adventist College Church",
    address: "Murcia",
    city: "Bacolod",
    state: "Negros Occidental",
    country: "Philippines",
    lat: "10.5952",
    lng: "122.9751",
    serviceTimes: "Saturday 8:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Manila Central SDA Church",
    address: "953 Gen. Luna St, Ermita",
    city: "Manila",
    state: null,
    country: "Philippines",
    lat: "14.5839",
    lng: "120.9795",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Southern Asia-Pacific Division Office Church",
    address: "Silang",
    city: "Cavite",
    state: null,
    country: "Philippines",
    lat: "14.2189",
    lng: "120.9747",
    serviceTimes: "Saturday 9:00 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: "https://ssd.adventist.org",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Seoul SDA Central Church",
    address: "12 Hoehyeon-ro, Jung-gu",
    city: "Seoul",
    state: null,
    country: "South Korea",
    lat: "37.5590",
    lng: "126.9855",
    serviceTimes: "Saturday 9:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Sahmyook University SDA Church",
    address: "815 Hwarang-ro, Nowon-gu",
    city: "Seoul",
    state: null,
    country: "South Korea",
    lat: "37.6420",
    lng: "127.0985",
    serviceTimes: "Saturday 9:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: "https://www.syu.ac.kr",
    pastorName: null,
    membershipSize: "large",
  },
  {
    name: "Avondale Memorial SDA Church",
    address: "582 Freemans Dr",
    city: "Cooranbong",
    state: "New South Wales",
    country: "Australia",
    lat: "-33.0748",
    lng: "151.4566",
    serviceTimes: "Saturday 9:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Wahroonga SDA Church",
    address: "Fox Valley Rd",
    city: "Wahroonga",
    state: "New South Wales",
    country: "Australia",
    lat: "-33.7173",
    lng: "151.1170",
    serviceTimes: "Saturday 9:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  // ─── VICTORIA — MELBOURNE METRO EAST ──────────────────────────────
  {
    name: "The Upper Room Church",
    address: "41-51 Weeden Dr",
    city: "Vermont South",
    state: "Victoria",
    country: "Australia",
    lat: "-37.859",
    lng: "145.167",
    serviceTimes: "Saturday: Bible Study 2:00 PM, Church Service 3:00 PM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Doncaster Hope Fellowship Church",
    address: "901 Doncaster Rd",
    city: "Doncaster East",
    state: "Victoria",
    country: "Australia",
    lat: "-37.784",
    lng: "145.142",
    serviceTimes: "Saturday: Church Service 3:00 PM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Crosswalk Melbourne Church",
    address: "43 York St",
    city: "Surrey Hills",
    state: "Victoria",
    country: "Australia",
    lat: "-37.823",
    lng: "145.104",
    serviceTimes: "Saturday: Church Service 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Western Spanish Church",
    address: "17/19 Surrey Rd W",
    city: "Croydon",
    state: "Victoria",
    country: "Australia",
    lat: "-37.796",
    lng: "145.274",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Romanian Church",
    address: "151 Basin-Olinda Rd",
    city: "The Basin",
    state: "Victoria",
    country: "Australia",
    lat: "-37.856",
    lng: "145.319",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Oakleigh Polish Church",
    address: "2 Willgilson Ct",
    city: "Oakleigh",
    state: "Victoria",
    country: "Australia",
    lat: "-37.901",
    lng: "145.090",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Hughesdale Church",
    address: "165 Poath Rd",
    city: "Murrumbeena",
    state: "Victoria",
    country: "Australia",
    lat: "-37.897",
    lng: "145.069",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Cross-Centred Church",
    address: "6 Tallent St",
    city: "Croydon",
    state: "Victoria",
    country: "Australia",
    lat: "-37.793",
    lng: "145.282",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Zomi-Australian Church",
    address: "18 Lincoln Rd",
    city: "Croydon",
    state: "Victoria",
    country: "Australia",
    lat: "-37.794",
    lng: "145.280",
    serviceTimes: "Saturday: Church Service 10:00 AM, Bible Study 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Wantirna Polish Church",
    address: "753 Boronia Rd",
    city: "Wantirna",
    state: "Victoria",
    country: "Australia",
    lat: "-37.849",
    lng: "145.231",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Yarra Valley Church",
    address: "401 Warburton Hwy",
    city: "Wandin North",
    state: "Victoria",
    country: "Australia",
    lat: "-37.793",
    lng: "145.417",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "The Oasis Church",
    address: "40 Warrandyte Rd",
    city: "Ringwood",
    state: "Victoria",
    country: "Australia",
    lat: "-37.810",
    lng: "145.229",
    serviceTimes: "Saturday: Bible Study 10:30 AM, Church Service 11:45 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Ringwood Church",
    address: "28 Mullum Mullum Rd",
    city: "Ringwood",
    state: "Victoria",
    country: "Australia",
    lat: "-37.815",
    lng: "145.228",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Nunawading Church",
    address: "169 Central Rd",
    city: "Nunawading",
    state: "Victoria",
    country: "Australia",
    lat: "-37.824",
    lng: "145.167",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Gateway East Church",
    address: "38 Exhibition Walk",
    city: "Clayton",
    state: "Victoria",
    country: "Australia",
    lat: "-37.921",
    lng: "145.123",
    serviceTimes: "Saturday: Church Service 10:00 AM, Bible Study 11:30 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Gateway Lighthouse Church",
    address: "37 Taunton St",
    city: "Doncaster East",
    state: "Victoria",
    country: "Australia",
    lat: "-37.775",
    lng: "145.158",
    serviceTimes: "Saturday: Church Service 10:00 AM, Bible Study 11:30 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Wantirna Church",
    address: "119 Mountain Hwy",
    city: "Wantirna",
    state: "Victoria",
    country: "Australia",
    lat: "-37.845",
    lng: "145.221",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Rowville Church",
    address: "82 Bellfield Dr",
    city: "Lysterfield",
    state: "Victoria",
    country: "Australia",
    lat: "-37.871",
    lng: "145.270",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:30 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Mont Albert Church",
    address: "43 York St",
    city: "Surrey Hills",
    state: "Victoria",
    country: "Australia",
    lat: "-37.822",
    lng: "145.104",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Melbourne Asian Church (MASDAC)",
    address: "22 Jellico Dr",
    city: "Scoresby",
    state: "Victoria",
    country: "Australia",
    lat: "-37.877",
    lng: "145.230",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Lilydale Church",
    address: "608 Hull Rd",
    city: "Lilydale",
    state: "Victoria",
    country: "Australia",
    lat: "-37.767",
    lng: "145.355",
    serviceTimes: "Saturday: First Service 9:00 AM, Bible Study 10:15 AM, Second Service 11:30 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Ferntree Gully Church",
    address: "3/5 Railway Ave",
    city: "Upper Ferntree Gully",
    state: "Victoria",
    country: "Australia",
    lat: "-37.882",
    lng: "145.299",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Burwood Community Church",
    address: "162 Highbury Rd",
    city: "Burwood",
    state: "Victoria",
    country: "Australia",
    lat: "-37.856",
    lng: "145.091",
    serviceTimes: "Saturday: Cafe 9:30 AM, Church Service 10:00 AM, Small Groups 11:30 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Melbourne-Ghanaian Church",
    address: "47-53 Tunstall Rd",
    city: "Donvale",
    state: "Victoria",
    country: "Australia",
    lat: "-37.793",
    lng: "145.176",
    serviceTimes: "Saturday: Bible Study 10:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  // ─── VICTORIA — MELBOURNE METRO SOUTH EAST ──────────────────────────────
  {
    name: "Casey Cross Community Church",
    address: "20 Majestic Blvd",
    city: "Cranbourne",
    state: "Victoria",
    country: "Australia",
    lat: "-38.101",
    lng: "145.295",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Clyde Connect Church",
    address: "7-9 Selandra Blvd",
    city: "Clyde North",
    state: "Victoria",
    country: "Australia",
    lat: "-38.108",
    lng: "145.354",
    serviceTimes: "Saturday: Church Service 11:30 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Home of Hope Church",
    address: "710 Baxter-Tooradin Rd",
    city: "Pearcedale",
    state: "Victoria",
    country: "Australia",
    lat: "-38.198",
    lng: "145.237",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Doveton Home Church",
    address: "78 Power Rd",
    city: "Doveton",
    state: "Victoria",
    country: "Australia",
    lat: "-37.993",
    lng: "145.195",
    serviceTimes: "Saturday: Bible Study 9:45 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Cranbourne Church",
    address: "52 Fairhaven Blvd",
    city: "Cranbourne West",
    state: "Victoria",
    country: "Australia",
    lat: "-38.094",
    lng: "145.270",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "The Harvest Church",
    address: "2/6 The Fairway",
    city: "Hampton Park",
    state: "Victoria",
    country: "Australia",
    lat: "-38.035",
    lng: "145.265",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Springvale Sudanese Church",
    address: "46 Balmoral Ave",
    city: "Springvale",
    state: "Victoria",
    country: "Australia",
    lat: "-37.943",
    lng: "145.152",
    serviceTimes: "Saturday: Church Service 2:00 PM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "South East Oromo Church",
    address: "105 High St",
    city: "Berwick",
    state: "Victoria",
    country: "Australia",
    lat: "-38.033",
    lng: "145.354",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Southeast Melbourne Samoan Church",
    address: "25 Boland Dr",
    city: "Lyndhurst",
    state: "Victoria",
    country: "Australia",
    lat: "-38.053",
    lng: "145.254",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Samoan Endeavour Hills Church",
    address: "26 Haverstock Hill Close",
    city: "Endeavour Hills",
    state: "Victoria",
    country: "Australia",
    lat: "-37.982",
    lng: "145.264",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Carrum Downs Samoan Church",
    address: "445 Thompson Rd",
    city: "Bangholme",
    state: "Victoria",
    country: "Australia",
    lat: "-38.063",
    lng: "145.164",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Oromo Church",
    address: "176 Como Parade W",
    city: "Parkdale",
    state: "Victoria",
    country: "Australia",
    lat: "-37.982",
    lng: "145.088",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Mornington Peninsula Fellowship Church",
    address: "359A Point Nepean Rd",
    city: "Dromana",
    state: "Victoria",
    country: "Australia",
    lat: "-38.336",
    lng: "144.964",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Pakenham Lakeside Community Church",
    address: "50 Lakeside Blvd",
    city: "Pakenham",
    state: "Victoria",
    country: "Australia",
    lat: "-38.082",
    lng: "145.492",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Dandenong Polish Church",
    address: "100 James St",
    city: "Dandenong",
    state: "Victoria",
    country: "Australia",
    lat: "-37.987",
    lng: "145.215",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Springvale Spanish Church",
    address: "562/564 Springvale Rd",
    city: "Springvale South",
    state: "Victoria",
    country: "Australia",
    lat: "-37.960",
    lng: "145.152",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Springvale Church",
    address: "46 Balmoral Ave",
    city: "Springvale",
    state: "Victoria",
    country: "Australia",
    lat: "-37.943",
    lng: "145.152",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Frankston Church",
    address: "102 Cranbourne Rd",
    city: "Frankston",
    state: "Victoria",
    country: "Australia",
    lat: "-38.146",
    lng: "145.126",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Filipino-Australian Church",
    address: "26-28 Hutton St",
    city: "Dandenong",
    state: "Victoria",
    country: "Australia",
    lat: "-37.984",
    lng: "145.213",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Casey Church",
    address: "5 Rebound Ct",
    city: "Narre Warren",
    state: "Victoria",
    country: "Australia",
    lat: "-38.017",
    lng: "145.303",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 10:45 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Bayles Church",
    address: "3765 Ballarto Rd",
    city: "Bayles",
    state: "Victoria",
    country: "Australia",
    lat: "-38.187",
    lng: "145.579",
    serviceTimes: "Saturday: Family Worship 10:30 AM, Small Groups 12:00 PM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Longwarry Church",
    address: "16 Princes Ave",
    city: "Longwarry",
    state: "Victoria",
    country: "Australia",
    lat: "-38.107",
    lng: "145.776",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:30 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Berwick Church",
    address: "333 Centre Rd",
    city: "Narre Warren South",
    state: "Victoria",
    country: "Australia",
    lat: "-38.055",
    lng: "145.330",
    serviceTimes: "Saturday: Church Service 10:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Crossroads2421 Church",
    address: "66 Starling Rd",
    city: "Officer",
    state: "Victoria",
    country: "Australia",
    lat: "-38.049",
    lng: "145.415",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Karen Church",
    address: "18 Sullivan St",
    city: "Springvale",
    state: "Victoria",
    country: "Australia",
    lat: "-37.943",
    lng: "145.155",
    serviceTimes: "Saturday: Bible Study 3:00 PM, Church Service 4:00 PM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Carrum Downs Cook Island Church",
    address: "445 Thompson Rd",
    city: "Bangholme",
    state: "Victoria",
    country: "Australia",
    lat: "-38.063",
    lng: "145.164",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  // ─── VICTORIA — MELBOURNE METRO WEST ──────────────────────────────
  {
    name: "Keilor Church",
    address: "Flora Street, Cnr Church St",
    city: "Keilor",
    state: "Victoria",
    country: "Australia",
    lat: "-37.718",
    lng: "144.830",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Werribee Samoan Church",
    address: "80 Lonsdale Cct",
    city: "Hoppers Crossing",
    state: "Victoria",
    country: "Australia",
    lat: "-37.887",
    lng: "144.703",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Agape Gospel Fellowship Church",
    address: "225 Heaths Rd",
    city: "Werribee",
    state: "Victoria",
    country: "Australia",
    lat: "-37.877",
    lng: "144.674",
    serviceTimes: "Saturday: Church Service 4:00 PM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Sunshine Samoan Church",
    address: "50 Station Rd",
    city: "Deer Park",
    state: "Victoria",
    country: "Australia",
    lat: "-37.775",
    lng: "144.782",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Hillside Samoan Church",
    address: "2A Laurel St",
    city: "St Albans",
    state: "Victoria",
    country: "Australia",
    lat: "-37.744",
    lng: "144.809",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Myanmar Melbourne Church",
    address: "159 Taylors Rd",
    city: "St Albans",
    state: "Victoria",
    country: "Australia",
    lat: "-37.743",
    lng: "144.800",
    serviceTimes: "Saturday: Church Service 11:30 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Melton Church",
    address: "19 Claret Ash Blvd",
    city: "Harkness",
    state: "Victoria",
    country: "Australia",
    lat: "-37.666",
    lng: "144.567",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:30 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Melbourne Vietnamese Church",
    address: "3 West Esplanade",
    city: "St Albans",
    state: "Victoria",
    country: "Australia",
    lat: "-37.747",
    lng: "144.795",
    serviceTimes: "Saturday: Bible Study 2:30 PM, Church Service 3:45 PM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Gilson College Community Church",
    address: "450 Taylors Rd",
    city: "Taylors Hill",
    state: "Victoria",
    country: "Australia",
    lat: "-37.712",
    lng: "144.764",
    serviceTimes: "Saturday: Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Gateway West Church",
    address: "43 Paxton Street",
    city: "South Kingsville",
    state: "Victoria",
    country: "Australia",
    lat: "-37.835",
    lng: "144.872",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Fijian Church",
    address: "43 The Parade",
    city: "Ascot Vale",
    state: "Victoria",
    country: "Australia",
    lat: "-37.776",
    lng: "144.919",
    serviceTimes: "Saturday: Church Service 2:30 PM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Westpoint Church",
    address: "2A Roseleigh Blvd",
    city: "Sydenham",
    state: "Victoria",
    country: "Australia",
    lat: "-37.700",
    lng: "144.778",
    serviceTimes: "Saturday: Bible Study 9:45 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Werribee Karen Church",
    address: "47 Derrimut Rd",
    city: "Werribee",
    state: "Victoria",
    country: "Australia",
    lat: "-37.896",
    lng: "144.662",
    serviceTimes: "Saturday: Church Service 4:00 PM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Werribee Church",
    address: "47 Derrimut Rd",
    city: "Werribee",
    state: "Victoria",
    country: "Australia",
    lat: "-37.896",
    lng: "144.662",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Croatian St Albans Church",
    address: "3 West Esplanade",
    city: "St Albans",
    state: "Victoria",
    country: "Australia",
    lat: "-37.747",
    lng: "144.795",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Spotswood Church",
    address: "6 Robert St",
    city: "Spotswood",
    state: "Victoria",
    country: "Australia",
    lat: "-37.832",
    lng: "144.884",
    serviceTimes: "Saturday: Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Seddon Church",
    address: "21 Hotham St",
    city: "Seddon",
    state: "Victoria",
    country: "Australia",
    lat: "-37.806",
    lng: "144.886",
    serviceTimes: "Saturday: Bible Study 9:45 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Macedonian Church",
    address: "252 Gordon St",
    city: "Footscray",
    state: "Victoria",
    country: "Australia",
    lat: "-37.801",
    lng: "144.900",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Emmanuel Community Fellowship Church",
    address: "260-266 Bridge Rd",
    city: "Strathtulloh",
    state: "Victoria",
    country: "Australia",
    lat: "-37.662",
    lng: "144.586",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Living Faith Samoan Church",
    address: "98-100 Coburns Rd",
    city: "Melton South",
    state: "Victoria",
    country: "Australia",
    lat: "-37.704",
    lng: "144.586",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Melton Samoan Church",
    address: "1-5 West Melton Dr",
    city: "Melton West",
    state: "Victoria",
    country: "Australia",
    lat: "-37.679",
    lng: "144.561",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:30 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  // ─── VICTORIA — MELBOURNE METRO NORTH ──────────────────────────────
  {
    name: "Sunbury Vineyard Church",
    address: "27-37 Anderson Rd",
    city: "Sunbury",
    state: "Victoria",
    country: "Australia",
    lat: "-37.568",
    lng: "144.727",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "North Melbourne Samoan Church",
    address: "12/14 National Blvd",
    city: "Campbellfield",
    state: "Victoria",
    country: "Australia",
    lat: "-37.676",
    lng: "144.964",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:30 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Broadford Church",
    address: "156-158 High Street",
    city: "Broadford",
    state: "Victoria",
    country: "Australia",
    lat: "-37.205",
    lng: "145.043",
    serviceTimes: "Saturday: Bible Study 10:30 AM, Church Service 11:30 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Craigieburn Samoan Church",
    address: "15/29 Buchan St",
    city: "Meadow Heights",
    state: "Victoria",
    country: "Australia",
    lat: "-37.651",
    lng: "144.930",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Victorian Wantok Church",
    address: "494 Victoria St",
    city: "Brunswick West",
    state: "Victoria",
    country: "Australia",
    lat: "-37.759",
    lng: "144.945",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Craigieburn Multicultural Church",
    address: "141 Highlander Dr",
    city: "Craigieburn",
    state: "Victoria",
    country: "Australia",
    lat: "-37.605",
    lng: "144.943",
    serviceTimes: "Saturday: Bible Study 9:00 AM, Church Service 10:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Clayton Cook Islands Church",
    address: "378 Haughton Rd",
    city: "Clayton",
    state: "Victoria",
    country: "Australia",
    lat: "-37.925",
    lng: "145.138",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Bundoora Church",
    address: "20 Noorong Ave",
    city: "Bundoora",
    state: "Victoria",
    country: "Australia",
    lat: "-37.696",
    lng: "145.065",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Mernda Hills Community Church",
    address: "370 Bridge Inn Rd",
    city: "Mernda",
    state: "Victoria",
    country: "Australia",
    lat: "-37.604",
    lng: "145.092",
    serviceTimes: "Saturday: Church Service 10:30 AM, Bible Study 11:45 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Preston Church",
    address: "94 David St",
    city: "Preston",
    state: "Victoria",
    country: "Australia",
    lat: "-37.739",
    lng: "145.004",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Plenty Valley Church",
    address: "160 Centenary Dr",
    city: "Mill Park",
    state: "Victoria",
    country: "Australia",
    lat: "-37.660",
    lng: "145.063",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Northpoint Church",
    address: "3 Trade Park Dr",
    city: "Tullamarine",
    state: "Victoria",
    country: "Australia",
    lat: "-37.704",
    lng: "144.883",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Greenvale Church",
    address: "825 Somerton Rd",
    city: "Greenvale",
    state: "Victoria",
    country: "Australia",
    lat: "-37.632",
    lng: "144.882",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  // ─── VICTORIA — MELBOURNE CBD & CENTRAL ──────────────────────────────
  {
    name: "North Fitzroy Church",
    address: "27 Alfred Cres",
    city: "Fitzroy North",
    state: "Victoria",
    country: "Australia",
    lat: "-37.792",
    lng: "144.977",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:30 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Gateway City Church",
    address: "111 Barry St",
    city: "Carlton",
    state: "Victoria",
    country: "Australia",
    lat: "-37.800",
    lng: "144.963",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "The Orchard City Church",
    address: "Level 12, 474 Flinders St",
    city: "Melbourne",
    state: "Victoria",
    country: "Australia",
    lat: "-37.818",
    lng: "144.958",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Melbourne City Church",
    address: "27 Alfred Cres",
    city: "Fitzroy North",
    state: "Victoria",
    country: "Australia",
    lat: "-37.792",
    lng: "144.977",
    serviceTimes: "Saturday: Church Service 3:00 PM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "East Prahran Church",
    address: "8 Wynnstay Rd",
    city: "Prahran",
    state: "Victoria",
    country: "Australia",
    lat: "-37.855",
    lng: "145.002",
    serviceTimes: "Saturday: Bible Study 9:45 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Glen Huntly Church",
    address: "99 Grange Rd",
    city: "Glen Huntly",
    state: "Victoria",
    country: "Australia",
    lat: "-37.884",
    lng: "145.048",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Auburn Church",
    address: "49A Victoria Rd",
    city: "Hawthorn East",
    state: "Victoria",
    country: "Australia",
    lat: "-37.826",
    lng: "145.046",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Ascot Vale Church",
    address: "43 The Parade",
    city: "Ascot Vale",
    state: "Victoria",
    country: "Australia",
    lat: "-37.776",
    lng: "144.919",
    serviceTimes: "Saturday: Bible Study 9:45 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  // ─── VICTORIA — REGIONAL EAST ──────────────────────────────
  {
    name: "Warragul Church",
    address: "43 Mason St",
    city: "Warragul",
    state: "Victoria",
    country: "Australia",
    lat: "-38.159",
    lng: "145.929",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:30 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Traralgon Church",
    address: "50 Stuart St",
    city: "Traralgon",
    state: "Victoria",
    country: "Australia",
    lat: "-38.196",
    lng: "146.540",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:20 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Nhill Church",
    address: "8/7 Belcher St",
    city: "Nhill",
    state: "Victoria",
    country: "Australia",
    lat: "-36.333",
    lng: "141.652",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Sale Church",
    address: "53 Stawell St",
    city: "Sale",
    state: "Victoria",
    country: "Australia",
    lat: "-38.108",
    lng: "147.066",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:25 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Bairnsdale Church",
    address: "455 Princes Hwy",
    city: "Lucknow",
    state: "Victoria",
    country: "Australia",
    lat: "-37.828",
    lng: "147.595",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Tynong Church",
    address: "18 Railway Ave",
    city: "Tynong",
    state: "Victoria",
    country: "Australia",
    lat: "-38.087",
    lng: "145.573",
    serviceTimes: "Saturday: Bible Study 11:00 AM, Church Service 12:00 PM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Moe Church",
    address: "106 Service Rd",
    city: "Moe",
    state: "Victoria",
    country: "Australia",
    lat: "-38.177",
    lng: "146.263",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Leongatha Church",
    address: "18 Sullivan St",
    city: "Leongatha",
    state: "Victoria",
    country: "Australia",
    lat: "-38.477",
    lng: "145.951",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Cann River Church",
    address: "Contact Conference Office",
    city: "Cann River",
    state: "Victoria",
    country: "Australia",
    lat: "-37.567",
    lng: "149.155",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:20 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  // ─── VICTORIA — REGIONAL NORTH EAST ──────────────────────────────
  {
    name: "Mansfield Church",
    address: "Erril Street",
    city: "Mansfield",
    state: "Victoria",
    country: "Australia",
    lat: "-37.063",
    lng: "146.082",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Macedon Ranges Church",
    address: "18 Barringo Rd",
    city: "New Gisborne",
    state: "Victoria",
    country: "Australia",
    lat: "-37.395",
    lng: "144.584",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 10:50 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Warburton Church",
    address: "3490 Warburton Hwy",
    city: "Warburton",
    state: "Victoria",
    country: "Australia",
    lat: "-37.756",
    lng: "145.691",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Wangaratta Church",
    address: "10-12 Phillipson St",
    city: "Wangaratta",
    state: "Victoria",
    country: "Australia",
    lat: "-36.357",
    lng: "146.311",
    serviceTimes: "Saturday: Bible Study 9:50 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Shepparton Church",
    address: "Graham St",
    city: "Shepparton",
    state: "Victoria",
    country: "Australia",
    lat: "-36.376",
    lng: "145.398",
    serviceTimes: "Saturday: Church Service 10:00 AM, Bible Study 11:30 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Alpine Valley Church",
    address: "95 Schmidt Ln",
    city: "Yackandandah",
    state: "Victoria",
    country: "Australia",
    lat: "-36.310",
    lng: "146.843",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Benalla Church",
    address: "44 Smythe St",
    city: "Benalla",
    state: "Victoria",
    country: "Australia",
    lat: "-36.551",
    lng: "145.980",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Healesville Church",
    address: "25 Symons St",
    city: "Healesville",
    state: "Victoria",
    country: "Australia",
    lat: "-37.654",
    lng: "145.523",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  // ─── VICTORIA — REGIONAL NORTH WEST ──────────────────────────────
  {
    name: "Echuca Church",
    address: "31 Mitchell St",
    city: "Echuca",
    state: "Victoria",
    country: "Australia",
    lat: "-36.127",
    lng: "144.750",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Castlemaine Church",
    address: "252 Barker St",
    city: "Castlemaine",
    state: "Victoria",
    country: "Australia",
    lat: "-37.067",
    lng: "144.222",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Bendigo Church",
    address: "396 High St",
    city: "Golden Square",
    state: "Victoria",
    country: "Australia",
    lat: "-36.771",
    lng: "144.244",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Bendigo Karen Church",
    address: "396 High St",
    city: "Golden Square",
    state: "Victoria",
    country: "Australia",
    lat: "-36.771",
    lng: "144.244",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM, Bible Study 4:00 PM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Bendigo Karen Remnant Church",
    address: "High Street",
    city: "Axedale",
    state: "Victoria",
    country: "Australia",
    lat: "-36.775",
    lng: "144.523",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 12:15 PM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Swan Hill Church",
    address: "464 Campbell St",
    city: "Swan Hill",
    state: "Victoria",
    country: "Australia",
    lat: "-35.337",
    lng: "143.555",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Robinvale Church",
    address: "10 Old St",
    city: "Robinvale",
    state: "Victoria",
    country: "Australia",
    lat: "-34.584",
    lng: "142.773",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Mildura Church",
    address: "301 Deakin Ave",
    city: "Mildura",
    state: "Victoria",
    country: "Australia",
    lat: "-34.195",
    lng: "142.132",
    serviceTimes: "Saturday: Bible Study 9:45 AM, Church Service 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Dareton Church",
    address: "15 Hume St",
    city: "Dareton",
    state: "Victoria",
    country: "Australia",
    lat: "-34.096",
    lng: "142.040",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:30 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Maryborough Church",
    address: "35 Raglan St",
    city: "Maryborough",
    state: "Victoria",
    country: "Australia",
    lat: "-37.046",
    lng: "143.736",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  // ─── VICTORIA — REGIONAL SOUTH WEST ──────────────────────────────
  {
    name: "Warrnambool Church",
    address: "101 Lava St",
    city: "Warrnambool",
    state: "Victoria",
    country: "Australia",
    lat: "-38.381",
    lng: "142.483",
    serviceTimes: "Saturday: Church Service 3:00 PM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Portland Church",
    address: "85 Cape Nelson Rd",
    city: "Portland",
    state: "Victoria",
    country: "Australia",
    lat: "-38.350",
    lng: "141.600",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Colac Church",
    address: "53 Manifold St",
    city: "Colac",
    state: "Victoria",
    country: "Australia",
    lat: "-38.340",
    lng: "143.588",
    serviceTimes: "Saturday: Bible Study 9:30 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Camperdown Church",
    address: "48 Walls St",
    city: "Camperdown",
    state: "Victoria",
    country: "Australia",
    lat: "-38.232",
    lng: "143.186",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Hamilton Church",
    address: "71 King St",
    city: "Hamilton",
    state: "Victoria",
    country: "Australia",
    lat: "-37.739",
    lng: "142.023",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Geelong Church",
    address: "10 Little Myers St",
    city: "Geelong",
    state: "Victoria",
    country: "Australia",
    lat: "-38.148",
    lng: "144.357",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Geelong Hungarian Church",
    address: "24 Donnybrook Rd",
    city: "Norlane",
    state: "Victoria",
    country: "Australia",
    lat: "-38.121",
    lng: "144.340",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  // ─── VICTORIA — REGIONAL WEST ──────────────────────────────
  {
    name: "Ararat Church",
    address: "39 Albert St",
    city: "Ararat",
    state: "Victoria",
    country: "Australia",
    lat: "-37.287",
    lng: "142.930",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Stawell Church",
    address: "50 Main St",
    city: "Stawell",
    state: "Victoria",
    country: "Australia",
    lat: "-37.052",
    lng: "142.772",
    serviceTimes: "Saturday: Bible Study 10:00 AM, Church Service 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Horsham Church",
    address: "123a Wilson St",
    city: "Horsham",
    state: "Victoria",
    country: "Australia",
    lat: "-36.709",
    lng: "142.199",
    serviceTimes: "Saturday: Bible Study 9:45 AM, Church Service 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Ballarat Church",
    address: "317-319 Drummond Street",
    city: "South Ballarat",
    state: "Victoria",
    country: "Australia",
    lat: "-37.570",
    lng: "143.854",
    serviceTimes: "Saturday: Small Groups 9:30 AM, Church Service 11:15 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  // ─── EAST ASIA ───────────────────────────────────────────────────────
  {
    name: "Hong Kong-Macao Conference SDA Church",
    address: "17 Ventris Rd, Happy Valley",
    city: "Hong Kong",
    state: null,
    country: "Hong Kong",
    lat: "22.2685",
    lng: "114.1835",
    serviceTimes: "Saturday 9:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
  {
    name: "Taiwan Adventist Hospital Church",
    address: "424 Ba De Rd, Sec 2",
    city: "Taipei",
    state: null,
    country: "Taiwan",
    lat: "25.0487",
    lng: "121.5580",
    serviceTimes: "Saturday 9:30 AM & 11:00 AM",
    contactPhone: null,
    contactEmail: null,
    website: null,
    pastorName: null,
    membershipSize: "medium",
  },
];

export async function seedGlobalChurches() {
  try {
    const vicChurches = GLOBAL_CHURCHES.filter(
      (c) => c.country === "Australia" && c.state === "Victoria"
    );
    if (vicChurches.length > 0) {
      await db.transaction(async (tx) => {
        await tx
          .delete(sdaChurches)
          .where(
            and(
              eq(sdaChurches.country, "Australia"),
              eq(sdaChurches.state, "Victoria")
            )
          );
        const vicValues = vicChurches.map((c) => ({
          name: c.name,
          address: c.address,
          city: c.city,
          state: c.state,
          country: c.country,
          lat: c.lat,
          lng: c.lng,
          serviceTimes: c.serviceTimes,
          contactPhone: c.contactPhone,
          contactEmail: c.contactEmail,
          website: c.website,
          pastorName: c.pastorName,
          membershipSize: c.membershipSize,
        }));
        await tx.insert(sdaChurches).values(vicValues);
      });
      console.log(`Refreshed ${vicChurches.length} Victorian churches with official data.`);
    }

    const existing = await db.select({ name: sdaChurches.name, country: sdaChurches.country }).from(sdaChurches);
    const existingKeys = new Set(
      existing.map((c) => `${c.name.toLowerCase()}::${c.country.toLowerCase()}`)
    );

    const nonVicNew = GLOBAL_CHURCHES.filter(
      (c) => !(c.country === "Australia" && c.state === "Victoria") &&
             !existingKeys.has(`${c.name.toLowerCase()}::${c.country.toLowerCase()}`)
    );

    if (nonVicNew.length > 0) {
      const values = nonVicNew.map((c) => ({
        name: c.name,
        address: c.address,
        city: c.city,
        state: c.state,
        country: c.country,
        lat: c.lat,
        lng: c.lng,
        serviceTimes: c.serviceTimes,
        contactPhone: c.contactPhone,
        contactEmail: c.contactEmail,
        website: c.website,
        pastorName: c.pastorName,
        membershipSize: c.membershipSize,
      }));
      await db.insert(sdaChurches).values(values);
      console.log(`Seeded ${nonVicNew.length} additional churches.`);
    }

    const total = await db.select({ name: sdaChurches.name }).from(sdaChurches);
    console.log(`Church database: ${total.length} total churches.`);
  } catch (err) {
    console.error("Error seeding churches:", err);
  }
}
